### PR TITLE
[SuperTextField] [Android] Fix backspace not working on Android (Resolves #506)

### LINKED ISSUE #506: [SuperTextField] [Android] Backspace not working
# Steps to reproduce
Code:
```
class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        body: Center(
          child: Container(
            color: Colors.black,
            child: const SuperTextField(
              lineHeight: 16,
            ),
          ),
        ),
      ),
    );
  }
}
```
- Run the app
- Tap black rectangle (the text field)
- Type "abc"
- Try to delete using either physical or virtual backspace

# Actual behavior
When pressing backspace, it does not remove any characters

https://user-images.githubusercontent.com/3801761/160953565-3258cb8e-0286-41f7-aa67-5a4791f7f098.mp4

# Expected behavior
Every backspace press should remove a character

# Platform
```
Flutter 2.10.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7e9793dee1 (4 weeks ago) • 2022-03-02 11:23:12 -0600
Engine • revision bd539267b4
Tools • Dart 2.16.1 • DevTools 2.9.2
```

CC @venkatd

### PR DESCRIPTION
**Pull request by angelosilvestre**
Fix backspace not working on Android. Resolves https://github.com/superlistapp/super_editor/issues/506

Some third party keyboards report `backspace` as a key press rather than a deletion delta, so we need to handle this in `onKey`.

I handled `backspace` directly in `_onKeyPressed` because I was not sure if we need to handle multiple keyboard actions like in `SuperDesktopField`

### CODE REVIEW

File: super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart [hunk 1]
```diff
@@ -352,11 +355,48 @@ class SuperAndroidTextFieldState extends State<SuperAndroidTextField>
...
+    _log.finer('_onKeyPressed - keyEvent: ${keyEvent.character}');
+    if (keyEvent is! RawKeyDownEvent) {
+      _log.finer('_onKeyPressed - not a "down" event. Ignoring.');
+      return KeyEventResult.ignored;
+    }
+    if (keyEvent.logicalKey != LogicalKeyboardKey.backspace) {
+      return KeyEventResult.ignored;
+    }
+
+    int deleteEndIndex = -1;
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart:372]: Isn't there a common operation, or a controller behavior that already implements character deletion?

File: super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart [hunk 2]
```diff
@@ -0,0 +1,74 @@
...
+}
+
+Future<void> _pumpTestApp(
+  WidgetTester tester, {
+  required AttributedTextEditingController controller,
+}) async {
+  await tester.pumpWidget(
+    MaterialApp(
+      home: Scaffold(
+        body: SuperTextField(
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart:68]: Make sure to wrap `SuperTextField` with `BoxConstraints` that give a min width, to prevent any surprises with tapping on it. It collapses to zero width without it. I usually pass a width of `300`.

File: super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart [hunk 3]
```diff
@@ -0,0 +1,74 @@
+import 'package:attributed_text/attributed_text.dart';
+import 'package:flutter/material.dart';
+import 'package:flutter/services.dart';
+import 'package:flutter_test/flutter_test.dart';
+import 'package:super_editor/src/infrastructure/super_textfield/super_textfield.dart';
+
+import '../test_tools.dart';
+
+void main() {
+  group('SuperTextField', () {
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart:10]: "SuperTextField" -> "SuperTextField on some bad Android software keyboards"

File: super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+    testWidgetsOnAndroid('BACKSPACE deletes previous character when selection is collapsed (on Android)', (tester) async {
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart:11]: Let's name this test "handles BACKSPACE key event instead of deletion for a collapsed selection"

File: super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+
+      // Press backspace
+      await tester.sendKeyEvent(LogicalKeyboardKey.backspace);
+      await tester.pumpAndSettle();
+
+      // Ensure text is deleted
+      expect(controller.text.text, 'Thi is a text');
+    });
+
+    testWidgetsOnAndroid('BACKSPACE deletes selection when selection is expanded (on Android)', (tester) async {
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart:34]: Let's name this one similar to what I mentioned for the other test.

File: super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+
+import '../test_tools.dart';
+
+void main() {
+  group('SuperTextField', () {
+    testWidgetsOnAndroid('BACKSPACE deletes previous character when selection is collapsed (on Android)', (tester) async {
+      final controller = AttributedTextEditingController(
+        text: AttributedText(text: 'This is a text'),
+      );
+      await _pumpTestApp(tester, controller: controller);
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart:15]: I typically name these methods `_pumpScaffold()`. It's not entirely accurate, but probably better to match the others.

File: super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart [hunk 7]
```diff
@@ -0,0 +1,74 @@
...
+
+      // Focus the text field
+      await tester.tapAt(tester.getCenter(find.byType(SuperTextField)));
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart:18]: Why not use the robot?

File: super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart [hunk 8]
```diff
@@ -0,0 +1,74 @@
...
+      await tester.pump();
+
+      // Place caret at This|. We don't put caret at the end of the text
+      // to ensure we are not deleting always the last character
+      controller.selection = const TextSelection.collapsed(offset: 4);
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart:23]: Why not use the robot?

File: super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart [hunk 9]
```diff
@@ -0,0 +1,74 @@
...
+      await tester.pump();
+
+      // Press backspace
+      await tester.sendKeyEvent(LogicalKeyboardKey.backspace);
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart:27]: Why not use `pressBackspace()`?

File: super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart (hunk 7 above)
Comment (angelosilvestre) [reply super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart:18]: The robot currently doesn't support mobile

File: super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart (hunk 8 above)
Comment (angelosilvestre) [reply super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart:23]: The robot currently doesn't support mobile

File: super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart:372]: All functions that implement character deletion first change the text and then change the selection.

If I try to do this deleting the last character I get an `ArrayIndexOutOfBoundsException` from the java side, because the selection stays is an invalid position.

File: super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart (hunk 7 above)
Comment (matthew-carroll) [reply super_editor/test/super_textfield/super_textfield_mobile_keyboard_test.dart:18]: Let's include TODOs any time that you want to use a robot but can't

File: super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart (hunk 1 above)
Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart:372]: Is there any reason not to update the appropriate function to set the text and selection at the same time, rather than create another implementation of the same thing?

**Review by matthew-carroll — APPROVED** [review]
LGTM - Thanks.
