### PR TITLE
Fix SuperTextField newline not working on mobile and web (Resolves #653)

### LINKED ISSUE #653: [SuperTextField] - Newline not working on web
I have a multi-line `SuperTextField` running in a mobile browser. The software keyboard shows a "newline" button. However, when I press the button, I don't get a newline.

When I press this button, I expect a newline to be inserted into the multi-line text field.

Here's the widget I'm using:
```dart
SuperTextField(
          focusNode: _focusNode,
          textController: widget.controller,
          minLines: 10,
          maxLines: 10,
          lineHeight: 24,
          textStyleBuilder: (_) {
            return const TextStyle(
              color: Colors.white,
              fontSize: 20,
            );
          },
          controlsColor: primaryColorVibrant,
          hintBuilder: widget.hint != null
              ? (_) {
                  return Text(
                    widget.hint!,
                    style: const TextStyle(
                      color: Color(0xFF444444),
                      fontSize: 20,
                    ),
                  );
                }
              : null,
        )
```

### PR DESCRIPTION
**Pull request by angelosilvestre**
Fix SuperTextField newline not working on mobile. Resolves https://github.com/superlistapp/super_editor/issues/653

There were two issues:

* We were not configuring `textInputAction`  to `TextInputAction.newline`  when the textfield was configured for multi-line
* We were not configuring `textInputType` to `TextInputType.multiline` when the textfield was configured for multi-line

I couldn't write an ideal test because we can't simulate the behavior on the tests (on Android and web, clicking the action button will generate an insertion delta of a new line)

### CODE REVIEW

File: super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart [hunk 1]
```diff
@@ -252,6 +254,8 @@ class SuperTextFieldState extends State<SuperTextField> {
         return SuperTextFieldPlatformConfiguration.desktop;
     }
   }
+
+  bool get _isMultiline => widget.minLines != 1 || widget.maxLines != 1;
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart:258]: Let's move this property up above the `build()` method, and then let's move `_configuration` beneath `_isMultiline`

File: super_editor/test/super_textfield/super_textfield_test.dart [hunk 2]
```diff
@@ -104,6 +104,82 @@ void main() {
       });
     });
 
+    group("configures inner textfield textInputAction for newline when it's multiline", () {
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_test.dart:107]: Let's surround these tests with a group called "on mobile" because this doesn't apply to desktop use-cases

File: super_editor/test/super_textfield/super_textfield_test.dart [hunk 3]
```diff
@@ -104,6 +104,82 @@ void main() {
...
+      testWidgetsOnAndroid('on Android', (tester) async {
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_test.dart:108]: We can match the auto-generated style by calling this "(on Android)"

**Review by matthew-carroll — COMMENTED** [review]
Generally looks good. A few stylistic comments.

**Review by matthew-carroll — APPROVED** [review]
LGTM - Thanks
