### PR TITLE
[SuperTextField] [Mobile] Fix viewport height when text changes (Resolves #794)

### LINKED ISSUE #794: [SuperTextField] Attempting to full screen on iOS and Android break the editor
I'm building a syntax highlighting text editor based on `SuperTextField` for a codelab. It works as intended on macOS, and basically works on web (with the expected issue around not being able to background parsing via `compute`), but when I run the code on Android and iOS the displayed text editor doesn't flow through the space that the Widget Inspector says it takes.

Reproduction repo: https://github.com/domesticmouse/super_text_editor_testing

Here it is on macOS:

Screen Shot 2022-09-26 at 10 58 18 pm

Here it is on Android:

Here is the Widget Inspector for the above:

And, of course, iPhone:

For informational purposes: 

```console
$ [✓] Flutter (Channel stable, 3.3.2, on macOS 12.6 21G115 darwin-arm, locale en)
    • Flutter version 3.3.2 on channel stable at /Users/brettmorgan/flutter
    • Upstream repository https://github.com/flutter/flutter
    • Framework revision e3c29ec00c (12 days ago), 2022-09-14 08:46:55 -0500
    • Engine revision a4ff2c53d8
    • Dart version 2.18.1
    • DevTools version 2.15.0

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
    • Android SDK at /Users/brettmorgan/Library/Android/sdk
    • Platform android-33, build-tools 33.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 14.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 14A309
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.12+0-b1504.28-7817840)

[✓] IntelliJ IDEA Community Edition (version 2022.2.2)
    • IntelliJ at /Applications/IntelliJ IDEA CE.app
    • Flutter plugin version 70.0.5
    • Dart plugin version 222.4167.21

[✓] VS Code (version 1.71.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.48.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-arm64   • macOS 12.6 21G115 darwin-arm
    • Chrome (web)    • chrome • web-javascript • Google Chrome 105.0.5195.125

[✓] HTTP Host Availability
    • All required HTTP hosts are available

• No issues found!
```

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperTextField] [Mobile] Fix viewport height when text changes. Resolves #794 

On mobile, changing the text isn't causing the text field to recalculate its viewport height. 

For example:  when adding new lines in a multi-line text field with `maxLines != null`,  the text field maintains the same height calculated for its initial text.

This PR changes the `TextScrollView` used by the mobile text fields to recalculate its viewport height when text changes.

### CODE REVIEW

**Comment by angelosilvestre** [comment]
@domesticmouse Could you please try this PR?

File: super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart [hunk 1]
```diff
@@ -136,6 +138,11 @@ class _TextScrollViewState extends State<TextScrollView>
         ..addListener(_onTextScrollChange);
     }
 
+    if (widget.textEditingController != oldWidget.textEditingController) {
+      oldWidget.textEditingController.removeListener(_onSelectionOrContentChange);
+      widget.textEditingController.addListener(_onSelectionOrContentChange);
+    }
+
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart:145]: Down below is a line that calls `setState()`. I'm pretty sure we aren't allowed to call `setState()` in `didUpdateWidget`. Should we surround that with a post-frame callback?

File: super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart [hunk 2]
```diff
@@ -136,6 +138,11 @@ class _TextScrollViewState extends State<TextScrollView>
         ..addListener(_onTextScrollChange);
     }
 
+    if (widget.textEditingController != oldWidget.textEditingController) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart:141]: If the text controller changed, should we recalculate the viewport size?

File: super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart [hunk 3]
```diff
@@ -385,6 +394,20 @@ class _TextScrollViewState extends State<TextScrollView>
       return didChange;
     }
 
+    if (viewportHeight == null && isMultiline && maxHeight != null && estimatedContentHeight <= maxHeight) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart:397]: I'm curious why this scenario just now came up? This looks like some kind of generic situation, aside from whether or not the content changed text. Do you know why/how we missed this situation before?

File: super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart [hunk 4]
```diff
@@ -385,6 +394,20 @@ class _TextScrollViewState extends State<TextScrollView>
...
+      // We don't have a viewport height, but we're multiline and
+      // our estimated content height fits inside our max height,
+      // so a null viewport height is fine.
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart:400]: A "null viewport" is a proxy for another condition. Rather than say "a null viewport height is fine", how about saying what that condition represents? Does this mean that the viewport should expand to fit the content? Does it mean that the viewport should match the bounds of its parent?

File: super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart [hunk 5]
```diff
@@ -421,6 +444,17 @@ class _TextScrollViewState extends State<TextScrollView>
     return _textLayout.getLineCount();
   }
 
+  void _onSelectionOrContentChange() {
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart:447]: Should this be used to replace the existing `_needViewportHeight` code in `didUpdateWiget`? Also, it looks like some existing code changes `_needViewportHeight` in `setState()`, rather than directly call `_updateViewportHeight()`. Are you sure that you're using that method correctly?

File: super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart:410]: I don't know why we missed this before. I found this during debugging. When I pasted text with more lines than `maxLines` into the text field, the viewport was updated. When I pasted text with fewer lines than `maxLines`, then the viewport wasn't updated.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart:410]: I haven't looked carefully at the conditions above, but I'm skeptical that this condition should exist on it's own. My initial reaction is that one of the above conditions should be adjusted to include this case.

Looking up above I see a condition that says `viewportHeight == null && isMultiline && !isBounded`. I'm not sure what `maxHeight != null` means, but if that means "bounded", then the above condition could be split into two levels:

```dart
if (viewportHeight == null && isMultiline) {
  if (isBounded) { 
    // ^ this is still missing "estimatedContentHeight <= maxHeight". I wasn't sure if
    // this condition might already be met, or if you have to explicitly look for it.

    // your new stuff
  } else {
    // existing stuff
  }
}
```

Or, given that both of those branches are doing the same thing, you might want to set a couple boolean flags. Something like:

```dart
final wantsUnboundedIntrinsicHeight = viewportHeight == null && isMultiline && !isBounded;
final someNameThatMakesSenseForYourSituation = viewportHeight == null && isMultiline && isBounded && estimatedContentHeight <= maxHeight;
if (wantsUnboundedIntrinsicHeight || someNameThatMakesSenseForYourSituation) {
  // keep the existing behavior
}
```

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart]: Updated with the second option.

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Comment by domesticmouse** [comment]
> @domesticmouse Could you please try this PR?

I tried getting my [repro case](https://github.com/domesticmouse/super_text_editor_testing) to work against the head version of `super_text_editor` and I got the following stack trace:

```console
$ flutter run -d macos
Launching lib/main.dart on macOS in debug mode...
--- xcodebuild: WARNING: Using the first of multiple matching destinations:
{ platform:macOS, arch:arm64, id:00006000-001250C00C38801E }
{ platform:macOS, arch:x86_64, id:00006000-001250C00C38801E }
warning: Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase. (in target 'Flutter Assemble' from project 'Runner')
Building macOS application...                                           
Syncing files to device macOS...                                    45ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave application running).
c Clear the screen
q Quit (terminate the application on the device).

💪 Running with sound null safety 💪

An Observatory debugger and profiler on macOS is available at: http://127.0.0.1:52467/R4fNaa5EC3g=/

══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _CastError was thrown building MultiListenableBuilder(dirty, state:
_MultiListenableBuilderState#bd9c1):
type 'Null' is not a subtype of type 'RenderSuperTextLayout' in type cast

The relevant error-causing widget was:
  MultiListenableBuilder
  MultiListenableBuilder:file:///Users/brettmorgan/.pub-cache/git/super_editor-376c0b6856f217b7364ee81cad41140f7132a570/s
  uper_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:297:16

When the exception was thrown, this was the stack:
#0      RenderSuperTextLayout.textLayoutFrom (package:super_text_layout/src/super_text.dart:179:69)
#1      SuperDesktopTextFieldState._getEstimatedLineHeight
(package:super_editor/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:257:46)
#2      SuperDesktopTextFieldState.build.<anonymous closure>
(package:super_editor/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:316:38)
#3      _MultiListenableBuilderState.build (package:super_editor/src/infrastructure/_listenable_builder.dart:66:26)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859:5)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041:11)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (111 frames)
#121    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#122    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#123    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (136 frames)
#259    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#260    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#261    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (175 frames)
#436    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#437    MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#438    MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:6447:32)
...     Normal element mounting (422 frames)
#860    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#861    Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#862    RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1195:16)
#863    RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1164:5)
#864    RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure>
(package:flutter/src/widgets/binding.dart:1111:18)
#865    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2605:19)
#866    RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1110:13)
#867    WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:945:7)
#868    WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:925:7)
(elided 4 frames from class _RawReceivePortImpl, class _Timer, and dart:async-patch)

════════════════════════════════════════════════════════════════════════════════════════════════════

Another exception was thrown: type 'Null' is not a subtype of type 'RenderSuperTextLayout' in type cast
The Flutter DevTools debugger and profiler on macOS is available at:
http://127.0.0.1:9101?uri=http://127.0.0.1:52467/R4fNaa5EC3g=/
Lost connection to device.
```

**Comment by domesticmouse** [comment]
Let me know if you want me to a) open a new bug, and/or b) turn my sample into a test case for your codebase =)

**Comment by matthew-carroll** [comment]
@angelosilvestre can you checkout the linked project and see if you can find out why `SuperTextLayout` is throwing an exception?

**Comment by angelosilvestre** [comment]
@matthew-carroll The fix for this exception was already merged (it was fixed in https://github.com/superlistapp/super_editor/pull/766). We should release a new version of `super_text_layout` to include the fix.

@domesticmouse Meanwhile, you could add this to your `dependency_overrides`: 

```yaml
super_text_layout:
    git: 
      url: https://github.com/superlistapp/super_editor
      path: super_text_layout
```

**Comment by domesticmouse** [comment]
Confirmed this issue is fixed. However, I now have an issue with gratuitous scrolling on character entry on iOS. I've raised https://github.com/superlistapp/super_editor/issues/814 to capture the issue. Thanks!
