### PR TITLE
[SuperTextField] [Desktop] Fix hint text cutting off (Resolves #565)

### LINKED ISSUE #565: [DESKTOP] Hint text cuts off with 1 line input fields on SuperTextField
From the example application, if you go to 

`_interactive_demo.dart` file and change the example as follows: You can see that the text is cut off in the text field. Same happens in our application as well. 

```
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:super_editor/super_editor.dart';

const brandAttribution = NamedAttribution('brand');
const flutterAttribution = NamedAttribution('flutter');

class InteractiveTextFieldDemo extends StatefulWidget {
  @override
  _InteractiveTextFieldDemoState createState() => _InteractiveTextFieldDemoState();
}

class _InteractiveTextFieldDemoState extends State<InteractiveTextFieldDemo> {
  final _textFieldController = AttributedTextEditingController(
    text: AttributedText(
        text: 'Super Editor is an open source text editor for Flutter projects.',
        spans: AttributedSpans(attributions: [
          const SpanMarker(attribution: brandAttribution, offset: 0, markerType: SpanMarkerType.start),
          const SpanMarker(attribution: brandAttribution, offset: 11, markerType: SpanMarkerType.end),
          const SpanMarker(attribution: flutterAttribution, offset: 47, markerType: SpanMarkerType.start),
          const SpanMarker(attribution: flutterAttribution, offset: 53, markerType: SpanMarkerType.end),
        ])),
  );

  OverlayEntry? _popupEntry;
  Offset _popupOffset = Offset.zero;

  FocusNode? _focusNode;

  @override
  void initState() {
    super.initState();
    _focusNode = FocusNode();
  }

  @override
  void dispose() {
    _focusNode!.dispose();
    super.dispose();
  }

  void _onRightClick(
      BuildContext textFieldContext, AttributedTextEditingController textController, Offset localOffset) {
    // Only show menu if some text is selected
    if (textController.selection.isCollapsed) {
      return;
    }

    final overlay = Overlay.of(context)!;
    final overlayBox = overlay.context.findRenderObject() as RenderBox?;
    final textFieldBox = textFieldContext.findRenderObject() as RenderBox;
    _popupOffset = textFieldBox.localToGlobal(localOffset, ancestor: overlayBox);

    if (_popupEntry == null) {
      _popupEntry = OverlayEntry(builder: (context) {
        return GestureDetector(
          behavior: HitTestBehavior.translucent,
          onTapDown: (_) {
            _closePopup();
          },
          child: Container(
            width: double.infinity,
            height: double.infinity,
            color: Colors.transparent,
            child: Stack(
              children: [
                Positioned(
                  left: _popupOffset.dx,
                  top: _popupOffset.dy,
                  child: Container(
                    decoration: BoxDecoration(
                      color: Colors.white,
                      borderRadius: BorderRadius.circular(4),
                      boxShadow: [
                        BoxShadow(
                          color: Colors.black.withOpacity(0.3),
                          blurRadius: 5,
                          offset: const Offset(3, 3),
                        ),
                      ],
                    ),
                    child: Column(
                      children: [
                        TextButton(
                          onPressed: () {
                            Clipboard.setData(ClipboardData(
                              text: textController.selection.textInside(textController.text.text),
                            ));
                            _closePopup();
                          },
                          child: const Text('Copy'),
                        ),
                      ],
                    ),
                  ),
                ),
              ],
            ),
          ),
        );
      });

      overlay.insert(_popupEntry!);
    } else {
      _popupEntry!.markNeedsBuild();
    }
  }

  void _closePopup() {
    if (_popupEntry == null) {
      return;
    }

    _popupEntry!.remove();
    _popupEntry = null;
  }

  @override
  Widget build(BuildContext context) {
    return GestureDetector(
      behavior: HitTestBehavior.opaque,
      onTap: () {
        // Remove focus from text field when the user taps anywhere else.
        _focusNode!.unfocus();
      },
      child: Center(
        child: SizedBox(
          width: 400,
          child: GestureDetector(
            onTap: () {
              // no-op. Prevents unfocus from happening when text field is tapped.
            },
            child: SizedBox(
              width: double.infinity,
              child: SuperDesktopTextField(
                textController: _textFieldController,
                focusNode: _focusNode,
                textStyleBuilder: _textStyleBuilder,
                padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                decorationBuilder: (context, child) {
                  return Container(
                    decoration: BoxDecoration(
                      borderRadius: BorderRadius.circular(4),
                      border: Border.all(
                        color: _focusNode!.hasFocus ? Colors.blue : Colors.grey.shade300,
                        width: 1,
                      ),
                    ),
                    child: child,
                  );
                },
                hintBuilder: (context) {
                  return const Text(
                    'Leave a message',
                    style: TextStyle(
                      color: Colors.grey,
                    ),
                  );
                },
                hintBehavior: HintBehavior.displayHintUntilTextEntered,
                minLines: 1,
                maxLines: 1,
                onRightClick: _onRightClick,
              ),
            ),
          ),
        ),
      ),
    );
  }

  TextStyle _textStyleBuilder(Set<Attribution> attributions) {
    TextStyle textStyle = const TextStyle(
      color: Colors.black,
      fontSize: 14,
    );

    if (attributions.contains(brandAttribution)) {
      textStyle = textStyle.copyWith(
        color: Colors.red,
        fontWeight: FontWeight.bold,
      );
    }
    if (attributions.contains(flutterAttribution)) {
      textStyle = textStyle.copyWith(
        color: Colors.blue,
      );
    }

    return textStyle;
  }
}

``` 

Screen Shot 2022-05-16 at 16 07 12

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperTextField] [Desktop] Fix hint text cutting off. Resolves #565

SuperTextField calculates its viewport height based on an estimated line height. This estimation may differ from the true line height. This difference can cause the hint text to be cut off, because the text field may not have enough room to display it.

The line height is calculated using the text layout `getLineHeightAtPosition` when it's available, so when there is text the field should have the correct height.

This PR changes the line height estimation to be calculated by laying out a `Paragraph` with a single arbitrary character and inspecting its line metrics.

### CODE REVIEW

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart [hunk 1]
```diff
@@ -1676,3 +1680,37 @@ class DefaultSuperTextFieldKeyboardHandlers {
 
   DefaultSuperTextFieldKeyboardHandlers._();
 }
+
+/// Computes the estimated line height of a [TextStyle].
+class _TextMetrics {
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:1685]: The name `TextMetrics` suggests that this object does a lot more than estimate line height. Let's call this `_EstimatedLineHeight` and let's rename the method to `calculate()`.

File: super_editor/test/super_textfield/super_textfield_estimated_line_height_test.dart [hunk 2]
```diff
@@ -0,0 +1,63 @@
...
+
+      // Change the text, this should recompute viewport height.
+      controller.text = AttributedText(text: 'Leave a message');
+      await tester.pumpAndSettle();
+
+      // When the text field has content the line height should be the true line height.
+      final heightWithText = tester.getSize(find.byType(SuperTextField)).height;
+
+      // Ensure the text field has ~ the same height when it's empty and when it has content
+      expect(heightWithEmptyText.truncate(), equals(heightWithText.truncate()));
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_estimated_line_height_test.dart:31]: Is a whole number the closest that we can get? If we can say they're within 1e-1, or 1e-2, that would be better.

File: super_editor/test/super_textfield/super_textfield_estimated_line_height_test.dart [hunk 3]
```diff
@@ -0,0 +1,63 @@
...
+      // is always equal to the true line height.
+      await loadAppFonts();
+
+      // Pump an empty SuperTextField.
+      final controller = AttributedTextEditingController();
+      await _pumpScaffold(tester, controller: controller);
+      await tester.pumpAndSettle();
+
+      // When the text field is empty the line height is estimated.
+      final heightWithEmptyText = tester.getSize(find.byType(SuperTextField)).height;
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_estimated_line_height_test.dart:21]: It's probably worth mentioning that hint text is displayed. Reading this without first reading the full widget tree makes it seem as if we're truly measuring an empty text field. I'd probably change the variable name to reflect this, too. Maybe `heightWithHintText`.

File: super_editor/test/super_textfield/super_textfield_estimated_line_height_test.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/test/super_textfield/super_textfield_estimated_line_height_test.dart:31]: The difference between the two values in the test is approximately 0.2, so I think the closest we can get is 3e-1.

**Review by matthew-carroll — APPROVED** [review]
LGTM
