### PR TITLE
[SuperEditor] Fix crash in release mode (Resolves #1424)

### LINKED ISSUE #1424: [SuperEditor] [SuperReader] Widget is grey in profile and release mode
On Web, macOS, and iOS, in debug mode, the editor looks normal:

Screenshot 2023-09-10 at 1 51 45 PM

In profile or release mode, the editor is covered by a grey box:

Screenshot 2023-09-10 at 1 49 51 PM

**To reproduce**: run the example app in profile or release mode.

This was recently introduced, as I have been working on our Flutter web app for the past few weeks (in both debug and release mode) and didn't notice this issue until today.

cc @matthew-carroll @angelosilvestre

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor] Fix crash in release mode. Resolves #1424.

Running on release mode causes the editor to display only a grey box:

Screenshot 2023-09-10 at 1 49 51 PM

The console shows the following exception:

```console
flutter: LateInitializationError: Local 'result' has not been initialized.
flutter: #0      LateError._throwLocalNotInitialized (dart:_internal-patch/internal_patch.dart:197)
flutter: #1      RenderObject.debugNeedsLayout (package:flutter/src/rendering/object.dart:2156)
flutter: #2      ContentLayerState.build (package:super_editor/src/infrastructure/content_layers.dart:845)
flutter: #3      StatefulElement.build (package:flutter/src/widgets/framework.dart:5572)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5460)
flutter: #5      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5623)
flutter: #6      Element.rebuild (package:flutter/src/widgets/framework.dart:5176)
flutter: #7      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5442)
flutter: #8      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5614)
flutter: #9      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5436)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4315)
flutter: #11     ContentLayersElement.inflateWidget (package:super_editor/src/infrastructure/content_layers.dart:280)
flutter: #12     ContentLayersElement.buildLayers.<anonymous closure> (package:super_editor/src/infrastructure/content_layers.dart:268)
flutter: #13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2824)
flutter: #14     ContentLayersElement.buildLayers (package:super_editor/src/infrastructure/content_layers.dart:251)
flutter: #15     RenderContentLayers.performLayout.<anonymous closure> (package:super_editor/src/infrastructure/content_layers.dart:594)
flutter: #16     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2659)
flutter: #17     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1073)
flutter: #18     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2659)
flutter: #19     RenderContentLayers.performLayout (package:super_editor/src/infrastructure/content_layers.dart:593)
flutter: #20     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #21     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #22     RenderPositionedBox.performLayout (package:flutter/src/rendering/shifted_box.dart:438)
flutter: #23     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #24     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #25     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52)
flutter: #26     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:589)
flutter: #27     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:616)
flutter: #28     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #29     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #30     RenderViewportBoundsReplicator.performLayout (package:super_editor/src/infrastructure/viewport_size_reporting.dart:197)
flutter: #31     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #32     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #33     _RenderSingleChildViewport.performLayout (package:flutter/src/widgets/single_child_scroll_view.dart:494)
flutter: #34     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #35     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #36     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #37     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #38     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #39     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #40     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #41     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #42     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #43     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #44     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #45     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #46     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #47     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #48     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #49     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #50     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #51     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #52     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #53     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #54     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #55     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #56     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #57     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #58     RenderCustomPaint.performLayout (package:flutter/src/rendering/custom_paint.dart:571)
flutter: #59     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #60     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #61     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #62     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #63     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #64     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #65     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #66     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #67     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #68     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #69     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #70     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #71     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #72     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #73     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #74     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #75     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #76     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52)
flutter: #77     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:589)
flutter: #78     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:616)
flutter: #79     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #80     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #81     RenderViewportBoundsReporter.performLayout (package:super_editor/src/infrastructure/viewport_size_reporting.dart:154)
flutter: #82     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #83     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #84     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #85     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #86     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #87     RenderProxyBoxMixin.performLayout (package:flutter/src/rendering/proxy_box.dart:104)
flutter: #88     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #89     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #90     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52)
flutter: #91     RenderFlex._computeSizes (package:flutter/src/rendering/flex.dart:868)
flutter: #92     RenderFlex.performLayout (package:flutter/src/rendering/flex.dart:903)
flutter: #93     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #94     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: #95     ChildLayoutHelper.layoutChild (package:flutter/src/rendering/layout_helper.dart:52)
flutter: #96     RenderStack._computeSize (package:flutter/src/rendering/stack.dart:589)
flutter: #97     RenderStack.performLayout (package:flutter/src/rendering/stack.dart:616)
flutter: #98     RenderObject.layout (package:flutter/src/rendering/object.dart:2548)
flutter: #99     RenderBox.layout (package:flutter/src/rendering/box.dart:2391)
flutter: Another exception was thrown: Instance of 'DiagnosticsProperty<void>'

```

The reason is that, in `ContentLayers` we are checking `debugNeedsLayout`. This getter isn't intended to be called in release mode. Doing so crashes because an uninitialized value:

```dart
/// Whether this render object's layout information is dirty.
  ///
  /// This is only set in debug mode. In general, render objects should not need
  /// to condition their runtime behavior on whether they are dirty or not,
  /// since they should only be marked dirty immediately prior to being laid
  /// out and painted. In release builds, this throws.
  ///
  /// It is intended to be used by tests and asserts.
  bool get debugNeedsLayout {
    late bool result;
    assert(() {
      result = _needsLayout;
      return true;
    }());
    return result; // Crashes here.
  }
```

If we do need to check if layout is needed we have to find another way, as it seems `_needsLayout` is not accessible in any other way.

### CODE REVIEW

**Comment by angelosilvestre** [comment]
@Jethro87 Can you please try this PR ?

**Comment by Jethro87** [comment]
@angelosilvestre It looks like it's been fixed. I had to upgrade to Flutter master to test.

**Comment by matthew-carroll** [comment]
Should we close this, or is there still something we need to do?

**Comment by angelosilvestre** [comment]
@matthew-carroll You can review this PR.

File: super_editor/lib/src/infrastructure/content_layers.dart [hunk 1]
```diff
@@ -841,7 +842,7 @@ abstract class ContentLayerState<WidgetType extends ContentLayerStatefulWidget,
     final contentLayers = (context as Element).findAncestorContentLayers();
     final contentLayout = contentLayers?._content?.findRenderObject();
 
-    if (contentLayers != null && !contentLayers.renderObject._content!.debugNeedsLayout) {
+    if (contentLayers != null && (!kDebugMode || !contentLayers.renderObject._content!.debugNeedsLayout)) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/content_layers.dart:845]: This might fix the crash, but what this has done is bring back the possibility that we compute layout when there is no layout. So this isn't really a fix. We need to find a way to check if layout has run.

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/content_layers.dart:845]: Yes, this only fixes the crash.

It seems we cannot know right now if an arbitrary child render object needs layout or not. Flutter should allow us to query this information.

The only solution that comes to my mind is to force the `ContentLayers`'s content to be a specific type of widget, whose `RenderObject` can "talk" to `ContentLayers` when marked as needing layout.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/content_layers.dart:845]: Do you remember whether requesting layout invalidates all ancestors? Or, if not, where does the layout invalidation stop? Maybe at a repaint boundary?

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/content_layers.dart:845]: It seems it invalidates all ancestors which called layout with `parentUsesSize: true`. From the Flutter docs:


```dart
/// If a render object's parent indicates that it uses the size of one of its
/// render object children when computing its layout information, this
/// function, when called for the child, will also mark the parent as needing
/// layout. In that case, since both the parent and the child need to have
/// their layout recomputed, the pipeline owner is only notified about the
/// parent; when the parent is laid out, it will call the child's [layout]
/// method and thus the child will be laid out as well.
```

As we layout the content by calling `_content!.layout(constraints, parentUsesSize: true);`, `ContentLayers` itself should by marked as needing layout.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/content_layers.dart:845]: Ok. Let's try to check our own render object's layout flag. I'm still worried that it might get out of sync, due to the very unusual stuff we're doing, but we can give it a try.

File: super_editor/lib/src/infrastructure/content_layers.dart [hunk 2]
```diff
@@ -841,7 +873,7 @@ abstract class ContentLayerState<WidgetType extends ContentLayerStatefulWidget,
     final contentLayers = (context as Element).findAncestorContentLayers();
     final contentLayout = contentLayers?._content?.findRenderObject();
 
-    if (contentLayers != null && !contentLayers.renderObject._content!.debugNeedsLayout) {
+    if (contentLayers != null && !contentLayers.renderObject.contentNeedsLayout) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/content_layers.dart:876]: Can all of these changes be replaced by simply accessing `contentLayers.renderObject.hasSize`? Or we could have `bool get contentNeedsLayout => hasSize`

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/content_layers.dart:876]: I tried this but then the test "SuperEditor ContentLayers full rebuild" failed with a NPE.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/content_layers.dart:876]: An NPE when accessing what?

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/content_layers.dart:876]: When  the `textLayout` is accessed:

```console
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _TypeError was thrown building SelectionLeadersDocumentLayer(dirty, state:
_SelectionLeadersDocumentLayerState#b3a90):
Null check operator used on a null value

The relevant error-causing widget was:
  SelectionLeadersDocumentLayer
  SelectionLeadersDocumentLayer:file:///Users/angelosilvestre/dev/super_editor/super_editor/lib/src/default_editor/super_editor.dart:693:12

When the exception was thrown, this was the stack:
#0      SuperTextState.textLayout (package:super_text_layout/src/super_text.dart:70:89)
#1      _SuperTextWithSelectionState.textLayout (package:super_text_layout/src/super_text_layout_with_selection.dart:97:85)
#2      TextComponentState.textLayout (package:super_editor/src/default_editor/text.dart:505:60)
#3      TextComponentState.getOffsetForPosition (package:super_editor/src/default_editor/text.dart:528:12)
#4      TextComponentState.getRectForPosition (package:super_editor/src/default_editor/text.dart:537:20)
#5      _SingleColumnDocumentLayoutState.getRectForPosition (package:super_editor/src/default_editor/layout_single_column/_layout.dart:235:37)
#6      _SelectionLeadersDocumentLayerState.computeLayoutData (package:super_editor/src/infrastructure/selection_leader_document_layer.dart:106:31)
#7      ContentLayerState.build (package:super_editor/src/infrastructure/content_layers.dart:877:21)
many more...
```

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/content_layers.dart:876]: Does this mean that `hasSize` is returning `true` when the content isn't laid out?

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/content_layers.dart:876]: As we are doing some unusual stuff, it seems is possible.

I added the following code in the build method:

```dart
if (contentLayers != null && contentLayers.renderObject.hasSize && contentLayers.renderObject.contentNeedsLayout) {
  print('dirty');
}
```

The failing test caused  the print to execute.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/content_layers.dart:876]: Ok. I guess we'll accept the weird Flutter reporting.

**Review by matthew-carroll — APPROVED** [review]
LGTM
