### PR TITLE
[SuperTextField][Desktop] Implement IME input source (Resolves #892)

### LINKED ISSUE #892: [SuperTextfield] Special characers (ñ è ä ü ö) not working when triggered from US keyboard
Certain special characters can't be entered anymore from US keyboard layouts, for example
ñ
ä
è

If they are a combination of two key inputs (for example Option+n and n to create ñ)

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperTextField][Desktop] Implement IME input source. Resolves #892

Currently, trying to type characters accented characters, like `ã`, `á`, `à`, `â` and `ä` isn't working as expected. On desktop, `SuperTextField` always uses the keyboard as the input source, and Flutter seems to be reporting key events incorrectly. For example, when typing `~` followed by an `a`, I expect Flutter to only report the `ã` character. Instead, it reports a `~` character followed by an `ã` character. I filed https://github.com/flutter/flutter/issues/117294 

This PR implements IME support for the `SuperDesktopTextField`, as it's already implemented for mobile platforms. `SuperDestopTextField` will always use an `ImeAttributedTextEditingController`, as `SuperTextField` does. When using the IME, these characters are handled correctly.

Depending on a given input source, `SuperDestopTextField` will now use either the existing `SuperTextFieldKeyboardInteractor` or a new `SuperTextFieldImeInteractor`. The `SuperTextFieldImeInteractor` implementation is based on the `SuperAndroidTextField's` current implementation.

I needed to change a couple of deletion methods in `AttributedTextEditingController`, because, when using IME, we need to update the text and the selection at the same time. Otherwise, we get an exception when deleting characters at the end of the text.

This PR also renames `super_textfield_mobile_keyboard_test` to `super_textfield_ime_test` and changes the tests to run on all platforms, using IME input source.

### CODE REVIEW

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart [hunk 1]
```diff
@@ -178,6 +194,9 @@ class SuperDesktopTextFieldState extends State<SuperDesktopTextField> implements
   @override
   ProseTextLayout get textLayout => _textKey.currentState!.textLayout;
 
+  @override
+  DeltaTextInputClient get imeClient => _controller;
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:198]: Should this have a "visibleForTesting" annotation, or is `imeClient` meant to be public?

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart [hunk 2]
```diff
@@ -339,6 +355,33 @@ class SuperDesktopTextFieldState extends State<SuperDesktopTextField> implements
     return widget.decorationBuilder != null ? widget.decorationBuilder!(context, child) : child;
   }
 
+  /// Builds the widget tree that applies user input, e.g., key
+  /// presses from a keyboard, or text deltas from the IME.
+  Widget _buildInputSystem({
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:360]: Let's call this `_buildTextInputSystem()` to make sure we don't confuse it with gestures.

I think we can do without a doc comment on this method. The name tell us everything the comment says.

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart [hunk 3]
```diff
@@ -861,6 +904,157 @@ class _SuperTextFieldKeyboardInteractorState extends State<SuperTextFieldKeyboar
   }
 }
 
+/// Governs input that comes from the operating system's
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: "Governs" usually doesn't mean anything, and this doc comment is missing context as to what is done with the IME. 

After a quick overview of the code, I don't see any IME behavior at all. I only see physical keyboard behavior.

File: super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart [hunk 4]
```diff
@@ -65,6 +65,7 @@ class SuperTextField extends StatefulWidget {
     this.lineHeight,
     this.keyboardHandlers = defaultTextFieldKeyboardHandlers,
     this.padding,
+    this.inputSource,
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart:68]: Let's place this property above `keyboardHandler`s. This property sets the most important detail about text input. `keyboardHandlers` sets the second most important detail about text input. So let's keep them near each other, and in that order. This includes the property declaration down below, too.

File: super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart [hunk 5]
```diff
@@ -212,6 +218,26 @@ class SuperTextFieldState extends State<SuperTextField> {
     }
   }
 
+  /// Returns the [SuperTextFieldInputSource] which should be used.
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart:221]: Let's word this first line so it's a bit more clear:

```dart
/// Returns the desired [SuperTextFieldInputSource] for this text field.
```

File: super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart [hunk 6]
```diff
@@ -212,6 +218,26 @@ class SuperTextFieldState extends State<SuperTextField> {
...
+  ///
+  /// If the `inputSource` is configured, it is used. Otherwise,
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart:223]: Let's replace "`inputSource`" with "[widget.inputSource]" so that there's a code reference.

File: super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart [hunk 7]
```diff
@@ -317,3 +344,9 @@ enum SuperTextFieldPlatformConfiguration {
   android,
   iOS,
 }
+
+/// The mode of user text input.
+enum SuperTextFieldInputSource {
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart:349]: I assume that we have this same kind of enum defined for Super Editor. Is that right? If so, should we create a shared definition called `TextInputSource`?

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:198]: It should have a "visibleForTesting". Added.

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:360]: Updated.

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: Dart doc updated. I also added the same comments about the `keyboardHandlers` that the keyboard interactor has.

File: super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart (hunk 4 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart:68]: Updated.

File: super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart (hunk 5 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart:221]: Updated.

File: super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart (hunk 6 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart:223]: Updated.

File: super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart (hunk 7 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart:349]: I renamed the existing `DocumentInputSource` to `TextInputSource`.

File: super_editor/lib/src/core/document_interaction.dart [hunk 8]
```diff
@@ -1,5 +1,5 @@
 /// The mode of user text input.
-enum DocumentInputSource {
+enum TextInputSource {
```
Comment (matthew-carroll) [inline super_editor/lib/src/core/document_interaction.dart:2]: Given that we're now using this for documents and text fields, we should move this into a more appropriate file. How about a `text_input.dart` file in the infrastructure directory?

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart [hunk 9]
```diff
@@ -861,6 +904,162 @@ class _SuperTextFieldKeyboardInteractorState extends State<SuperTextFieldKeyboar
   }
 }
 
+/// Handles the connection with the platform IME through an [ImeAttributedTextEditingController] and dispatches key events.
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: This is still a very generic statement that doesn't really say what this object does. Try reading this from a random developer's perspective. What does it mean to "handle"? Dispatches key events where? For what reason?

The first line should clearly answer the question "should I use this class?" - I don't think that's obvious with this line.

File: super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart [hunk 10]
```diff
@@ -144,6 +146,11 @@ class SuperTextField extends StatefulWidget {
   /// provided and used for all text field height calculations.
   final double? lineHeight;
 
+  /// The `SuperTextField` input source, e.g., keyboard or Input Method Engine.
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/super_textfield.dart:149]: Let's use square brackets "[]" when referencing classes that are available on the existing import paths. By doing that, they should be tied to refactoring tools.

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart (hunk 9 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: How about `/// Connects to the Input Method Engine to receive text input from platform.` ? Then, the key events will be detailed only in the next sentence.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: I think that line describes what a `TextInputClient` does. What does this widget do?

Also, maybe I'm misunderstanding something, but key events don't come from the IME. They come through `FocusNode`s. And they probably originate with a physical keyboard.

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: Basically, it uses `ImeAttributedTextEditingController` to connect/disconnect to the IME when focus changes. 

It uses a `FocusNode` to receive key events. These events are passed to the keyboard handlers, so keyboard actions (like ctrl-c) can work.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: Can you point me to the mobile widget that this is based on?

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: This implementation is based on `SuperAndroidTextField`.

I used the same `_updateSelectionAndImeConnectionOnFocusChange`

https://github.com/superlistapp/super_editor/blob/527f1e165664caa4219c1612352c107c91aa3f98/super_editor/lib/src/infrastructure/super_textfield/android/android_textfield.dart#L294-L321

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: I see that method in `SuperAndroidTextField`, but I don't see any widget in that file that looks like the widget that you added. I thought you copied an existing widget from mobile and then adjusted it for desktop? Is this an entirely new widget?

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: This is almost the same implementation of the `SuperTextFieldKeyboardInteractor`, but with the parts that connect to ime from `SuperAndroidTextField`.

File: super_editor/lib/src/core/document_interaction.dart (hunk 8 above)
Comment (matthew-carroll) [inline super_editor/lib/src/core/document_interaction.dart:2]: Is this resolved? I still see this delta.

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart (hunk 9 above)
Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: Maybe I'm missing something, but if this widget is doing all the same keyboard stuff, and then adding the IME connection on top, wouldn't it make more sense to always include the existing keyboard widget, and then optionally inject a new IME widget as a child of the keyboard widget, when IME is requested?

File: super_editor/lib/src/core/document_interaction.dart (hunk 8 above)
Comment (angelosilvestre) [reply super_editor/lib/src/core/document_interaction.dart]: I forgot to push, sorry.

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart (hunk 9 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: This would work. However, there is a small difference between the keyboard handling of this widget and the existing keyboard widget:

```dart
 KeyEventResult _onKeyPressed(FocusNode focusNode, RawKeyEvent keyEvent) {
    if (keyEvent.character != null) {
      // Character keys are handled as deltas in the text controller.
      return KeyEventResult.ignored;
    }
    ...
 }
```

We ignore character keys, because they are already handled as deltas. If we use the same keyboard widget, we will need some property like `ignoreCharacterKeys`.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: I think the expected solution in that situation is to avoid passing keyboard handlers that do things you shouldn't, right?

If the user doesn't pass character handlers, then it wouldn't double on deltas, would it?

As for default handlers, we can have one list for hardware keyboards, and another list for IME.

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:907]: That makes sense.

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart]: Updated. With this change, it seems we could probably get rid of the `SuperTextFieldImeInteractor` widget.

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart [hunk 11]
```diff
@@ -861,6 +909,97 @@ class _SuperTextFieldKeyboardInteractorState extends State<SuperTextFieldKeyboar
   }
 }
 
+/// Handles the connection with the platform IME when focus changes.
+class SuperTextFieldImeInteractor extends StatefulWidget {
+  const SuperTextFieldImeInteractor({
+    Key? key,
+    required this.focusNode,
+    required this.textController,
+    required this.child,
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:918]: `child` should be last

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart [hunk 12]
```diff
@@ -861,6 +909,97 @@ class _SuperTextFieldKeyboardInteractorState extends State<SuperTextFieldKeyboar
   }
 }
 
+/// Handles the connection with the platform IME when focus changes.
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:912]:
```
/// Opens and closes an IME connection based on changes to focus and selection.
///
/// This widget watches [focusNode] for focus changes, and [textController] for
/// selection changes.
///
/// All IME commands are handled and applied to text field text by the given [textController].
///
/// When [focusNode] gains focus, if the [textController] doesn't have a selection, the caret is
/// placed at the end of the text.
///
/// When [focusNode] loses focus, the [textController]'s selection is cleared.
```

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart [hunk 13]
```diff
@@ -1257,6 +1396,35 @@ const defaultTextFieldKeyboardHandlers = <TextFieldKeyboardHandler>[
   DefaultSuperTextFieldKeyboardHandlers.insertCharacterWhenKeyIsPressed,
 ];
 
+/// The keyboard actions that a [SuperTextField] uses by default when using [TextInputSource.ime].
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:1399]: Let's mention why this list exists. It's like the other one, except it leaves out handlers that input text, because the IME will do that.

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart [hunk 14]
```diff
@@ -339,6 +363,30 @@ class SuperDesktopTextFieldState extends State<SuperDesktopTextField> implements
...
+        child: keyboardChild,
+      );
+    }
+
+    return SuperTextFieldKeyboardInteractor(
+      focusNode: _focusNode,
+      textController: _controller,
+      textKey: _textKey,
+      keyboardActions: widget.keyboardHandlers,
+      child: keyboardChild,
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:386]: We can do this all in one tree:

```dart
child: widget.inputSource == TextInputSource.ime
  ? SuperTextFieldImeInteractor(
        focusNode: _focusNode,
        textController: _controller,
        isMultiline: isMultiline,
        child: child,
      )
  : child,
```

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart [hunk 15]
```diff
@@ -57,8 +58,15 @@ class SuperDesktopTextField extends StatefulWidget {
     this.maxLines = 1,
     this.decorationBuilder,
     this.onRightClick,
-    this.keyboardHandlers = defaultTextFieldKeyboardHandlers,
-  }) : super(key: key);
+    this.inputSource = TextInputSource.keyboard,
+    List<TextFieldKeyboardHandler>? keyboardHandlers,
+  }) : super(key: key) {
+    final defaultKeyboardHandlers = inputSource == TextInputSource.keyboard
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:64]: Is it possible to set this in the initializer list and avoid the `late` keyword?

Something like:
```dart
keyboardHandlers = keyboardHandlers ?? (inputSource == TextInputSource.keyboard ? defaultTextFieldKeyboardHandlers : defaultTextFieldImeKeyboardHandlers)
```

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart [hunk 16]
```diff
@@ -94,21 +102,24 @@ class SuperDesktopTextField extends StatefulWidget {
 
   final RightClickListener? onRightClick;
 
+  /// The `SuperDesktopTextField` input source, e.g., keyboard or Input Method Engine.
+  final TextInputSource inputSource;
+
   /// Priority list of handlers that process all physical keyboard
   /// key presses, for text input, deletion, caret movement, etc.
-  final List<TextFieldKeyboardHandler> keyboardHandlers;
+  late final List<TextFieldKeyboardHandler> keyboardHandlers;
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart:110]: We should probably add a note tot his dart doc that explains the relationship to the `inputSource` and what a developer needs to do to avoid double text entry.

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart (hunk 15 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart]: It's possible. Updated.

File: super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart (hunk 16 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/desktop/desktop_textfield.dart]: Updated.

**Review by matthew-carroll — APPROVED** [review]
LGTM
