### PR TITLE
[SuperEditor][Android] Fix drag handles when selection collapses due to dragging (Resolves #1736)

### LINKED ISSUE #1736: [SuperEditor] [Android] Drag handle is painted at the top-left corner of the editor when selection is collapsed by dragging an handle
**Package Version**
`main` branch with commit hash 5304a3c2294dfa7ae2742539a5e9f2d3e05a3d16.

**To Reproduce**
1. Go to SuperEditor demo
2. Double tap on a word to get an expanded selection
3. Drag the left-handle till the offset of the right handle => selection is collapsed

**Actual behavior**
The Android selection handle is painted on the top-left corner of the editor.

**Expected behavior**
The Android selection handle is painted below the caret.

**Platform**
Android.

**Flutter version**
Flutter master commit e278279a48f0479386c249cf18f26b29c6f9018f.

**Screenshots**

https://github.com/superlistapp/super_editor/assets/31278849/69bf3eab-b2ef-41e5-8b89-ccff68a141c9

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][Android] Fix drag handles when selection collapses due to dragging. Resolves #1736

Dragging an expanded drag handle can cause the selection to collapse. When that happens, the expanded handles are painted in the top left corner:

https://github.com/superlistapp/super_editor/assets/31278849/69bf3eab-b2ef-41e5-8b89-ccff68a141c9

This happens because `AndroidControlsDocumentLayerState` is computing a collapsed handle layout data, while we want to display expanded handles.

This PR changes `AndroidControlsDocumentLayerState` to compute layout data for a expanded handles when the selection is collapsed but we are displaying expanded handles.

After the changes:

[expanded_handles.webm](https://github.com/superlistapp/super_editor/assets/7597082/391d9127-a98b-4382-87b9-adcc266d4f19)

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@angelosilvestre is that video showing the problem or the solution? The user should be able to drag a handle across the boundary to move the other direction.

**Comment by angelosilvestre** [comment]
@matthew-carroll The video is showing the problem. I forgot to upload the video of the solution. Updated the PR description to include the video.

File: super_editor/lib/src/default_editor/document_gestures_touch_android.dart [hunk 1]
```diff
@@ -1444,6 +1444,16 @@ class SuperEditorAndroidControlsOverlayManagerState extends State<SuperEditorAnd
       ..blinkCaret()
       ..hideMagnifier();
 
+    if (widget.selection.value?.isCollapsed == true &&
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_gestures_touch_android.dart:1447]: Do we actually need to care about the handle type here? Regardless of what handle the user stopped dragging, we always want to show the collapsed handle for collapsed and expanded handles for expanded, right?

File: super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart [hunk 2]
```diff
@@ -282,14 +286,24 @@ class AndroidControlsDocumentLayerState
     _caretBlinkController.jumpToOpaque();
   }
 
+  void _onShouldShowCollapsedHandleChange() {
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:289]: The name of this method, and what it's listening to, don't reflect the comment and purpose. For example, whenever the user initially places the caret, this method is probably called, but the commented situation didn't occur.

I'm curious why this layer needs a special update at all for such a situation?

File: super_editor/lib/src/default_editor/document_gestures_touch_android.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_gestures_touch_android.dart:1447]: I added this condition because if the handle type is already `collapsed` we don't need to change anything, because we would already displaying the correct handle.

File: super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:289]: With the changes in this PR, even with a collapsed selection we might have a `DocumentSelectionLayout` which only contains the layout information for the expanded handles. Without this, when we `showCollapsedHandle()` we don't have the `Rect` for the caret and we don't show any drag handles.

File: super_editor/lib/src/default_editor/document_gestures_touch_android.dart (hunk 1 above)
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_gestures_touch_android.dart:1447]: Does that mean the same logic would apply equally well for both expanded and collapsed? If so, I'm wondering why we would want to introduce the extra tracking by passing around the handle type if what we're going to do at the end is the same either way.

File: super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart (hunk 2 above)
Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:289]: > With the changes in this PR, even with a collapsed selection we might have a DocumentSelectionLayout which only contains the layout information for the expanded handles

Why is this the case? Wouldn't this mean that the overlay was already broken in a significant way if it doesn't reflect the latest selection?

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:289]: I'm confused now. Shouldn't we display the expanded handles when the user drags an expanded handle, causing the selection to collapse? If so, we need `DocumentSelectionLayout` to hold layout information for expanded handles.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:289]: > Shouldn't we display the expanded handles when the user drags an expanded handle, causing the selection to collapse? 

Yes, but at the moment I don't know the relationship between that question and the code that I'm commenting on.

My question above was about building this widget when the selection changes. You're saying we need this method so that when the selection changes, we show the right handles. That implies that this widget isn't already rebuilding when the selection changes, right? If this widget isn't rebuilding when the selection changes, then how are the handles ever right? It seems like this UI would be completely broken if this widget wasn't already building when the selection changes. I assume I'm missing something here, but I'm not sure what.

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:289]: Ok, when the selection changes the UI is already rebuilding. This code is to rebuild the user releases the drag handle, so we change from expanded handles to a collapsed handle.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:289]: If we want to react to the user ending a drag, then we should add a listener for when the user ends a drag. Baking that implication into a selection change is something that we'll immediately forget and we'll never be able to remove this method because we don't know why we're actually registering it for selection changes.

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:289]: I didn't add `_onShouldShowCollapsedHandleChange` as a selection listener. It's listening for changes of `SuperEditorAndroidControlsController.shouldShowCollapsedHandle`.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:289]: Was there previously a method registered for selection changes in earlier versions of this PR? Or am I thinking of a different PR?

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:289]: There are already a selection listener in the class that was introduced prior to this PR. That remains unchanged.

File: super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart [hunk 3]
```diff
@@ -282,14 +286,24 @@ class AndroidControlsDocumentLayerState
...
+
   @override
   DocumentSelectionLayout? computeLayoutDataWithDocumentLayout(BuildContext context, DocumentLayout documentLayout) {
     final selection = widget.selection.value;
     if (selection == null) {
       return null;
     }
 
-    if (selection.isCollapsed) {
+    if (selection.isCollapsed && !_controlsController!.shouldShowExpandedHandles.value) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:306]: With regard to the conversation about listening for expanded handles, I'm seeing that the reason you added that listener is because you added the appearance of expanded handles as a condition for computing the layout here.

I think what this issue shows us isn't that we should add another listener, but rather that our assumption that we can conditionally add/remove leaders was wrong. How about we always position all 3 handle types?

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:306]: It seems that are some places that consider the caret to be "visible" if we have the caret rect in the layout data. For example:

```dart
@visibleForTesting
bool get isCaretDisplayed => layoutData?.caret != null;
```

Should we change this to the following?

```dart
@visibleForTesting
bool get isCaretDisplayed => layoutData?.caret != null && widget.selection.value?.isCollapsed == true;
```

We have a `shouldCaretBlink` in the `SuperEditorAndroidControlsController` class, but we don't have a `shouldShowCaret`.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:306]: I can't see the code around those snippets. What's the actual decision process for the code that paints the caret?

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:306]: Currently, it just looks if the caret layout data is non-null. If it is, it paints the caret.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:306]: Ok, I guess we can keep it this way then. Can you please add appropriate comments so that it's clear why we're listening to the expanded handle signal. You can probably use some of my questions here to see where things aren't entirely clear.

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:310]: Updated. Can you let me know if the comment is clear enough?

File: super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart [hunk 4]
```diff
@@ -200,11 +200,18 @@ class AndroidControlsDocumentLayerState
...
       _controlsController!.shouldCaretBlink.removeListener(_onBlinkModeChange);
       _controlsController!.caretJumpToOpaqueSignal.removeListener(_caretJumpToOpaque);
+      _controlsController!.shouldShowCollapsedHandle.removeListener(_onShouldShowCollapsedHandleChange);
     }
 
     _controlsController = SuperEditorAndroidControlsScope.rootOf(context);
     _controlsController!.shouldCaretBlink.addListener(_onBlinkModeChange);
     _controlsController!.caretJumpToOpaqueSignal.addListener(_caretJumpToOpaque);
+
+    // The appearance of the collapsed handle is used to compute the selection layout data.
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:210]: This comment falls into a couple of the recurring issues that we have.

First, as has happened before, the part of the comment that mentions what the code actually does is literally the last line of the comment. Comments should generally be written in a way that the reader might be able to stop reading at any time and move on. But this requires that the most critical information appear first, not last.

Second, while this comment includes a lot of words, and while it might make sense to someone who already knows all the details, it doesn't reveal much of anything to someone who doesn't already know what's going on, and therefore isn't particularly valuable.

Please compare the existing comment to this comment.

```dart
/// Listen for changes about whether we want to show the collapsed handle
/// or whether we want to show expanded handles for a selection. We listen to
/// this because there are some situations where the desired handle type is
/// ambiguous, such as when when the user drags an expanded handle such that
/// the selection collapses. In that case, the selection is collapsed but we want
/// to show the expanded handle. This signal clarifies which one we want.
```

File: super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart [hunk 5]
```diff
@@ -282,14 +290,24 @@ class AndroidControlsDocumentLayerState
     _caretBlinkController.jumpToOpaque();
   }
 
+  void _onShouldShowCollapsedHandleChange() {
+    // When the user drags an expanded handle it might collapse the selection.
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:294]: This comment is better than the comment above, but it's somewhat incorrect. This comment is written from the perspective that we've gone from expanded handles to collapsed handles "Schedule a new layout to recompute the data for the collapsed handle". We're re-running build because we don't know whether we want a collapsed handle or expanded handles. Please ensure that the comment accounts for both possibilities.

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:296]: Updated. Could you take a look and see if it's better?

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:296]: It still looks one sided. Doesn't this method run whenever "should show collapsed handle" goes from `true` to `false` and `false` to `true`?

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:296]: Maybe:

```
// When the user drags an expanded handle it might collapse the selection.
// In this case, we have a collapsed selection, but layout data for the
// expanded handles. Schedule a rebuild whenever the information about
// which handles we want to show changes to recompute the layout data for the selection.
```
?

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart:296]: "In this case, we have a collapsed selection, but layout data for the expanded handles" - this statement sounds like you're saying "this method is running because we have a collapsed selection but we have layout data for the expanded handles". It's unnecessarily ambiguous and can be easily misinterpreted.

```
// The controller went from wanting a collapsed handle to wanting expanded handles,
// or vis-a-versa. This signal is relevant to us because of an ambiguous handle situation.
// The user might drag an expanded handle such  that the selection is collapsed, in which
// case we still want to show an expanded handle. Similarly, if the user then releases that
// expanded handle, we should switch to a collapsed handle for the same selection. This
// method tells us that the desired handle type has changed. Re-run layout and build to
// ensure that we're showing the correct handle.
```

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/platforms/android/android_document_controls.dart]: OK, pushed.

**Review by matthew-carroll — APPROVED** [review]
LGTM
