### PR TITLE
[SuperEditor] Fix typing lag in large documents (Resolves #751)

### LINKED ISSUE #751: Typing lag
When a few hundred nodes (i noticed it with 150 nodes) are created it seems the whole view gets updated and not only the widget tree of the single node making the typing impossibile.

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor] Fix typing lag in large documents. Resolves #751

There is a lag when typing in a document with hundreds of nodes.

This PR is based on the investigation of @jmatth  and @Jei-sKappa.

Some analysis after testing with the Frankenstein document posted by @jmatth  (added as a gist [here](https://gist.github.com/angelosilvestre/cbec8875a67f1b916fcbe09dcbfb06d7)):

* `getNodeIndex` takes some hundred microseconds to complete. It basically walks the entire list of nodes doing a deep comparison. Typing a single letter causes `getNodeIndex` to be called more than 3000 times. This function is called by  `getNodeBefore` , `getNodeAfter` and others.
* `getNodeById` takes some microseconds, but far less than `getNodeIndex`.
* `ParagraphComponentViewModel.==` is broken. Checking `textStyleBuilder == other.textStyleBuilder` always evaluates to `false`. Typing a single letter in a paragraph causes all the components to be considered changed.

This PR changes `MutableDocument`, adding a `Map` to quickly lookup a node index by its id. This `Map` is eagerly updated when the document is created and in each operation which affects the node indices. A `Map` to lookup a node by its id was also added. Because of this `Map's`, I had to change `nodes` to return as an unmodifiable List, to avoid the node list being out of sync with the node maps.

This PR also removes `textStyleBuilder` from the `==` operators of the view models. However, we still need to figure out how to handle the case in which `textStyleBuilder` do change.

After this, I experienced another issue: toggling an attribution wasn't causing the style to be updated immediately. This happens because toggling an attribution just changes `AttributedText` internally. When the viewmodel checks if the text changed, it is the same instance, so it's considered as not changed. This bug was hidden because comparing `textStyleBuilder` always causes the viewmodel to be considered as changed.

This PR changes the attribution commands to create new `AttributedText's`.

After these changes:

https://user-images.githubusercontent.com/7597082/198163767-1941f893-53e5-4da9-a4f5-5059e739e532.mp4

Dragging to select has still some lag:

https://user-images.githubusercontent.com/7597082/198163946-7567f6c3-052a-4564-ba2f-da854be108f0.mp4

Most of the time seems to be spent on `getDocumentSelectionInRegion`, more specifically in a call to `localToGlobal` at:

https://github.com/superlistapp/super_editor/blob/d5e7460956fc6d60abd65991d48ca2c073c1da38/super_editor/lib/src/default_editor/layout_single_column/_layout.dart#L418-L429

When testing with this document I found another bug that is present in the latest main. Typing `1. ` to create a list item it throws this exception: `type 'ListItemNode' is not a subtype of type 'ParagraphNode' of 'element'`. This exception doesn't happen with the default example document.

### CODE REVIEW

**Comment by angelosilvestre** [comment]
I made an attempt to optimize mouse dragging: 

https://user-images.githubusercontent.com/7597082/198168459-9867ddc2-9690-4add-901e-1023b37ebad7.mp4

But it doesn't help when selecting nodes at the end of the document.

File: super_editor/lib/src/core/document_editor.dart [hunk 1]
```diff
@@ -162,7 +168,10 @@ class MutableDocument with ChangeNotifier implements Document {
 
   @override
   int getNodeIndex(DocumentNode node) {
-    return _nodes.indexOf(node);
+    // We always update _nodeIndicesById when the node list changes.
```
Comment (matthew-carroll) [inline super_editor/lib/src/core/document_editor.dart:171]: I think we can do without this comment.

File: super_editor/test/super_editor/supereditor_style_test.dart [hunk 2]
```diff
@@ -0,0 +1,40 @@
...
+import 'package:super_editor/src/default_editor/attributions.dart';
+import 'package:super_editor/super_editor_test.dart';
+import 'package:super_text_layout/super_text_layout.dart';
+
+import '../test_tools.dart';
+import 'document_test_tools.dart';
+
+void main() {
+  group('SuperEditor', () {
+    testWidgetsOnArbitraryDesktop('applies style when toggling attributions', (tester) async {
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_style_test.dart:12]: "applies style when toggling attributions" -> "changes visual text style when attributions change"

**Review by matthew-carroll — COMMENTED** [review]
Generally LGTM. As of this point, what remaining problems do we have?

**Comment by angelosilvestre** [comment]
@matthew-carroll Right now, the only thing I think is missing is a way to detect when `textStyleBuilder` actually changes.

BTW. I replaced `List.unmodifiable` with `UnmodifiableListView` because `List.unmodifiable` copies all elements. With this change, the performance improved a little bit.

**Comment by matthew-carroll** [comment]
@Jei-sKappa @jmatth @Mijawel - Can each of you give this PR a try and verify that it resolves your performance problems?

**Comment by Mijawel** [comment]
Looks good. No obvious lag at 500 nodes/50,000 words. At 1000 nodes/100,000 words there is a decent amount of lag but it is still usable. 

Much better than before. Was getting lag at 50 to 100 nodes.

**Comment by Jei-sKappa** [comment]
For me the performance is good, btw I also notice what @Mijawel said, but it's totally fine unless you type at 200+ wpm.

Unfortunately while testing the editor I noticed a bug when pasting text, I want to make clear that it could be totally unrelated but I wanted to point it out.
Steps to reproduce:
- Run the example app
- Add "some" empty nodes (see the video, it occurred not only with those lines)
- Select all text (in my case with CMD+A)
- Copy it
- Paste it at the bottom



https://user-images.githubusercontent.com/46776108/198833074-3e34dee3-3bfa-49cc-8874-094434eaab72.mov

The error output is:
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following StateError was thrown building TextComponent-[GlobalKey#2a2a8](dirty, state:
TextComponentState#86374):
Bad state: No element

The relevant error-causing widget was:
  TextComponent-[GlobalKey#2a2a8]
  TextComponent:file:///Users/jac/Downloads/super_editor-751_typing_lag/super_editor/lib/src/default_editor/paragraph.dar
  t:91:12

When the exception was thrown, this was the stack:
#0      List.last (dart:core-patch/growable_array.dart:348:5)
#1      AttributedSpans.collapseSpans (package:attributed_text/src/attributed_spans.dart:913:24)
#2      ComputeTextSpan.computeTextSpan (package:super_editor/src/infrastructure/attributed_text_styles.dart:32:34)
#3      TextComponentState.build (package:super_editor/src/default_editor/text.dart:783:31)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4992:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4878:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#8      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:4859:5)
#9      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5041:11)
#10     ComponentElement.mount (package:flutter/src/widgets/framework.dart:4853:5)
...     Normal element mounting (24 frames)
#34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3863:16)
#35     MultiChildRenderObjectElement.inflateWidget (package:flutter/src/widgets/framework.dart:6435:36)
#36     Element.updateChild (package:flutter/src/widgets/framework.dart:3592:18)
#37     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5964:32)
#38     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6460:17)
#39     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#40     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6307:14)
#41     Element.updateChild (package:flutter/src/widgets/framework.dart:3570:15)
#42     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4904:16)
#43     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5050:11)
#44     Element.rebuild (package:flutter/src/widgets/framework.dart:4604:5)
#45     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2667:19)
#46     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#47     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:378:5)
#48     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1175:15)
#49     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1104:9)
#50     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1015:5)
#51     _invoke (dart:ui/hooks.dart:148:13)
#52     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:318:5)
#53     _drawFrame (dart:ui/hooks.dart:115:31)

**Comment by matthew-carroll** [comment]
@Jei-sKappa can you file a new issue for that copy bug?

**Comment by matthew-carroll** [comment]
BTW @Mijawel and @Jei-sKappa - would you two mind telling us a bit about how you're using Super Editor? If you'd like to send that info privately, you're welcome to come over to the Super Editor Slack channel. I'm curious, because the more we know about community use-cases, the better we can focus our roadmap.

**Comment by Jei-sKappa** [comment]
> @Jei-sKappa can you file a new issue for that copy bug?

Issue just created!

> BTW @Mijawel and @Jei-sKappa - would you two mind telling us a bit about how you're using Super Editor? If you'd like to send that info privately, you're welcome to come over to the Super Editor Slack channel. I'm curious, because the more we know about community use-cases, the better we can focus our roadmap.

Of course, I’d be happy to share how I use the editor.
I'll reach you in Slack.

File: super_editor/lib/src/core/document_editor.dart [hunk 3]
```diff
@@ -282,8 +307,12 @@ class MutableDocument with ChangeNotifier implements Document {
       throw Exception('Could not find node with nodeId: $nodeId');
     }
 
-    if (nodes.remove(node)) {
-      nodes.insert(targetIndex, node);
+    if (_nodes.remove(node)) {
+      _nodes.insert(targetIndex, node);
+
+      // The node list changed, we need to update the map to consider the new indices.
```
Comment (matthew-carroll) [inline super_editor/lib/src/core/document_editor.dart:313]: Let's say "// An existing node's index changed. Update our Node ID -> Node Index cache.

File: super_editor/lib/src/core/document_editor.dart [hunk 4]
```diff
@@ -302,6 +331,9 @@ class MutableDocument with ChangeNotifier implements Document {
       newNode.addListener(_forwardNodeChange);
       _nodes.insert(index, newNode);
 
+      // The node list changed, we need to update the map to consider the new indices.
```
Comment (matthew-carroll) [inline super_editor/lib/src/core/document_editor.dart:334]: Let's update this comment, too

File: super_editor/lib/src/core/document_editor.dart [hunk 5]
```diff
@@ -320,19 +352,33 @@ class MutableDocument with ChangeNotifier implements Document {
...
       }
     }
 
     return true;
   }
 
+  /// Updates all the maps which use the node id as the key.
+  ///
+  /// All the maps are cleared and re-populated.
+  void _updateNodeIdMappings() {
```
Comment (matthew-carroll) [inline super_editor/lib/src/core/document_editor.dart:372]: Let's call this `_refreshNodeIdCaches()`

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart [hunk 6]
```diff
@@ -320,7 +317,11 @@ class _SingleColumnDocumentLayoutState extends State<SingleColumnDocumentLayout>
     dynamic bottomNodeBasePosition;
     dynamic bottomNodeExtentPosition;
 
-    for (final componentKey in _topToBottomComponentKeys) {
+    final startOffset = min(baseOffset.dy, extentOffset.dy);
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/layout_single_column/_layout.dart:320]: Let's call this `selectionRegionTopOffset`

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart [hunk 7]
```diff
@@ -320,7 +317,11 @@ class _SingleColumnDocumentLayoutState extends State<SingleColumnDocumentLayout>
...
+    final startIndex = max(_findComponentIndexAtOffset(startOffset), 0);
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/layout_single_column/_layout.dart:321]: Let's call this `componentSearchStartIndex`

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart [hunk 8]
```diff
@@ -320,7 +317,11 @@ class _SingleColumnDocumentLayoutState extends State<SingleColumnDocumentLayout>
...
+
+    for (int i = startIndex; i < _topToBottomComponentKeys.length; i++) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/layout_single_column/_layout.dart:323]: Let's add a comment before this for loop:

```
// Find the top and bottom nodes in the selection region. We do this by finding the component
// at the top of the selection, then we iterate down the document until we find the bottom
// component in the selection region. We obtain the document nodes from the components.
```

Also, given that the 2 variables above this are only used for the loop condition, let's move them directly above the for loop, and let's place this comment above those two lines.

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart [hunk 9]
```diff
@@ -705,6 +719,60 @@ class _SingleColumnDocumentLayoutState extends State<SingleColumnDocumentLayout>
...
+  /// Performs a binary search starting from [minIndex] to [maxIndex] to find
+  /// a component whose bounds contains the offset [dy].
+  ///
+  /// Returns the index of the component, from top to bottom order.
+  int _binarySearchComponentIndexAtOffset(double dy, int minIndex, int maxIndex) {
+    if (minIndex > maxIndex) {
+      return -1;
+    }
+
+    final midleIndex = ((minIndex + maxIndex) / 2).floor();
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/layout_single_column/_layout.dart:739]: "midleIndex" -> "middleIndex"

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart [hunk 10]
```diff
@@ -705,6 +719,60 @@ class _SingleColumnDocumentLayoutState extends State<SingleColumnDocumentLayout>
...
+  /// Returns the index of the component, from top to bottom order.
+  int _findComponentIndexAtOffset(double dy) {
+    return _binarySearchComponentIndexAtOffset(dy, 0, _topToBottomComponentKeys.length);
+  }
+
+  /// Performs a binary search starting from [minIndex] to [maxIndex] to find
+  /// a component whose bounds contains the offset [dy].
+  ///
+  /// Returns the index of the component, from top to bottom order.
+  int _binarySearchComponentIndexAtOffset(double dy, int minIndex, int maxIndex) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/layout_single_column/_layout.dart:734]: To confirm, have you tried selecting in a document with 0, 1, even, and odd node counts? Any of those might blow up a binary search that isn't quite right.

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart [hunk 11]
```diff
@@ -705,6 +719,60 @@ class _SingleColumnDocumentLayoutState extends State<SingleColumnDocumentLayout>
...
+    if (minIndex > maxIndex) {
+      return -1;
+    }
+
+    final midleIndex = ((minIndex + maxIndex) / 2).floor();
+    final componentBounds = _getComponentBoundsByIndex(midleIndex);
+
+    if (dy >= componentBounds.top && dy <= componentBounds.bottom) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/layout_single_column/_layout.dart:742]: FYI - if-statements like this are often easier to read if written like this:

```
componentBounds.top <= dy && dy <= componentBounds.bottom
```

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart [hunk 12]
```diff
@@ -705,6 +719,60 @@ class _SingleColumnDocumentLayoutState extends State<SingleColumnDocumentLayout>
...
+      return midleIndex;
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/layout_single_column/_layout.dart:743]: Let's add a comment:

```
// The component in the middle of the search region is the one we're looking for. Return its index.
```

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart [hunk 13]
```diff
@@ -705,6 +719,60 @@ class _SingleColumnDocumentLayoutState extends State<SingleColumnDocumentLayout>
...
+    }
+
+    if (dy > componentBounds.bottom) {
+      if (midleIndex + 1 < _topToBottomComponentKeys.length) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/layout_single_column/_layout.dart:747]: Let's add a comment:

```
// The component we're looking for is somewhere in the bottom half of the current search region
```

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart [hunk 14]
```diff
@@ -705,6 +719,60 @@ class _SingleColumnDocumentLayoutState extends State<SingleColumnDocumentLayout>
...
+        // Check the gap between two components.
+        final nextComponentBounds = _getComponentBoundsByIndex(midleIndex + 1);
+        if (dy > componentBounds.bottom && dy < nextComponentBounds.top) {
+          return midleIndex;
+        }
+      }
+      return _binarySearchComponentIndexAtOffset(dy, midleIndex + 1, maxIndex);
+    } else {
+      if (midleIndex - 1 >= 0) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/layout_single_column/_layout.dart:756]: Let's add a comment:

```
// The component we're looking for is somewhere in the top half of the current search region
```

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart [hunk 15]
```diff
@@ -705,6 +719,60 @@ class _SingleColumnDocumentLayoutState extends State<SingleColumnDocumentLayout>
...
+
+    if (dy >= componentBounds.top && dy <= componentBounds.bottom) {
+      return midleIndex;
+    }
+
+    if (dy > componentBounds.bottom) {
+      if (midleIndex + 1 < _topToBottomComponentKeys.length) {
+        // Check the gap between two components.
+        final nextComponentBounds = _getComponentBoundsByIndex(midleIndex + 1);
+        if (dy > componentBounds.bottom && dy < nextComponentBounds.top) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/layout_single_column/_layout.dart:750]: Shouldn't we divide these gaps in half? Otherwise, the component that happens to be in the middle of a search receives special treatment with regard to when it's considered selected.

File: super_editor/lib/src/default_editor/text.dart [hunk 16]
```diff
@@ -887,9 +887,19 @@ class AddTextAttributionsCommand implements EditorCommand {
         final node = entry.key;
         final range = entry.value.toSpanRange();
         editorDocLog.info(' - adding attribution: $attribution. Range: $range');
-        node.text.addAttribution(
-          attribution,
-          range,
+
+        // During style phase, we check which components changed, so we only re-style those components.
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/text.dart:891]: Can you file an issue for this? We should probably have a way to compare content.

Also, please add a TODO to each of these comments that references the issue that you file.

File: super_editor/test/src/default_editor/text_test.dart [hunk 17]
```diff
@@ -107,12 +107,13 @@ void main() {
         final editContext = _createEditContext();
 
         // Add a paragraph to the document.
-        (editContext.editor.document as MutableDocument).nodes.add(
-              ParagraphNode(
-                id: 'paragraph',
-                text: AttributedText(text: 'This is some text'),
-              ),
-            );
+        (editContext.editor.document as MutableDocument).insertNodeAt(
```
Comment (matthew-carroll) [inline super_editor/test/src/default_editor/text_test.dart:110]: It looks like the `add()` calls have been replaced by `insertNodeAt()`, which isn't the same behavior. `insertNodeAt()` requires knowledge of how many nodes are in the document. The `add()` method just says "put this at the end, wherever that may be". Can we recover the original behavior without creating a performance problem?

File: super_editor/test/super_editor/supereditor_style_test.dart [hunk 18]
```diff
@@ -0,0 +1,124 @@
...
+          .pump();
+
+      await tester.placeCaretInParagraph(SuperEditorInspector.findDocument()!.nodes.last.id, 0);
+
+      final presenter = tester.state<SuperEditorState>(find.byType(SuperEditor)).presenter;
+      presenter.addChangeListener(SingleColumnLayoutPresenterChangeListener(
+        onViewModelChange: ({required addedComponents, required changedComponents, required removedComponents}) {
+          // The listener is called two times. The first one for the text change,
+          // and the second one for the selection change.
+          componentChangedCount = max(componentChangedCount, changedComponents.length);
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_style_test.dart:76]: It's not obvious to me what this `max()` is trying to accomplish. Can we check the behavior with hard-coded values to make things super clear?

File: super_editor/lib/src/default_editor/text.dart (hunk 16 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/text.dart:891]: Maybe this will change in https://github.com/superlistapp/super_editor/issues/748 ? I will reference this issue then.

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/text.dart:891]: Nevermind, I was confused with another statement.

File: super_editor/test/src/default_editor/text_test.dart (hunk 17 above)
Comment (angelosilvestre) [reply super_editor/test/src/default_editor/text_test.dart:110]: This document created by  `_createEditContext` is an empty one, so, in practice, inserting the node will have the same effect. We can't directly mutate the node list because it will cause the cache to be incorrect, and we currently don't have a method in the document public API to add a node to the end.

File: super_editor/test/super_editor/supereditor_style_test.dart (hunk 18 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_style_test.dart:76]: It's because typing a letter cause 2 calls to `onViewModelChange`, so the selection change overrides the value we care about. I will try to change to make it more obvious.

This might change after https://github.com/superlistapp/super_editor/issues/748 is closed.

File: super_editor/test/src/default_editor/text_test.dart (hunk 17 above)
Comment (matthew-carroll) [reply super_editor/test/src/default_editor/text_test.dart:110]: Then let's go ahead and add that method. I can't think of a good reason to prevent users from doing that.

File: super_editor/test/super_editor/supereditor_style_test.dart (hunk 18 above)
Comment (matthew-carroll) [reply super_editor/test/super_editor/supereditor_style_test.dart:76]: Can you use an if-statement, or some explicit control structure, rather than calculate a max number?

Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_style_test.dart:76]: Updated.

File: super_editor/lib/src/default_editor/text.dart (hunk 16 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/text.dart:891]: We have a way to compare content. The `AttributedText` equality operator is defined as:

```dart
@override
  bool operator ==(Object other) {
    return identical(this, other) ||
        other is AttributedText && runtimeType == other.runtimeType && text == other.text && spans == other.spans;
  }
```

If we just toggle the attributions in the same instance, the first condition will always be true.

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart (hunk 10 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/layout_single_column/_layout.dart:734]: I made a couple of small adjustments.

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart (hunk 15 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/layout_single_column/_layout.dart]: Updated

File: super_editor/lib/src/default_editor/text.dart (hunk 16 above)
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/text.dart:891]: Can you reframe this as an action item? I'm not sure what to do with the above information...

File: super_editor/test/src/default_editor/text_test.dart [hunk 19]
```diff
@@ -107,12 +107,12 @@ void main() {
         final editContext = _createEditContext();
 
         // Add a paragraph to the document.
-        (editContext.editor.document as MutableDocument).nodes.add(
-              ParagraphNode(
-                id: 'paragraph',
-                text: AttributedText(text: 'This is some text'),
-              ),
-            );
+        (editContext.editor.document as MutableDocument).insertNode(
```
Comment (matthew-carroll) [inline super_editor/test/src/default_editor/text_test.dart:110]: This method should be called `add()` - "insert" implies control over the index, or otherwise placing an item between other items.

File: super_editor/lib/src/default_editor/text.dart (hunk 16 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/text.dart:891]: `ParagraphComponentViewModel` compares its `AttributedText` as part of its equality operator (`text == other.text`).

Before the change, we were only modifying the contents of the same `AttributedText` that was referenced in the viewmodel. The contents changed, but as it's referencing the same object, the equality operator returns true, as `identical(this, other)` is `true`.

Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/text.dart:891]: Ok. Let's change the comment to:

```
// Create a new AttributedText with updated attribution spans, so that the presentation system can
// see that we made a change, and re-renders the text in the document.
```

Let's change the implementation to:

```
node.text = AttributedText(
  text: node.text.text,
  spans: node.text.spans.copy()..addAttribution(
    newAttribution: attribution,
    start: range.start,
    end: range.end,
  ),
);
```

**Comment by jmatth** [comment]
This resolves the performance issues for me.

File: super_editor/lib/src/core/document_editor.dart [hunk 20]
```diff
@@ -162,7 +168,7 @@ class MutableDocument with ChangeNotifier implements Document {
 
   @override
   int getNodeIndex(DocumentNode node) {
-    return _nodes.indexOf(node);
+    return _nodeIndicesById[node.id] ?? -1;
```
Comment (jmatth) [inline super_editor/lib/src/core/document_editor.dart:171]: This is changing the behavior of the method slightly. It will now return an index if you pass a node that shares an `id` with one in the document even if they are otherwise unequal. Additionally, if someone implemented custom nodes with overridden `==` behavior, this method may now return `-1` instead of a valid index.

In my implementation I used the cache to quickly look up the node and then performed the comparison to maintain the existing behavior. [Code here][1].

[1]: https://github.com/jmatth/super_editor/blob/79f1032afbff19d7302899ea4e0906a9e48ba708/super_editor/lib/src/core/document_editor.dart#L171-L177

Comment (angelosilvestre) [reply super_editor/lib/src/core/document_editor.dart]: I updated to add the equality check.

File: super_editor/lib/src/core/document_editor.dart [hunk 21]
```diff
@@ -162,7 +168,17 @@ class MutableDocument with ChangeNotifier implements Document {
...
   @override
   int getNodeIndex(DocumentNode node) {
-    return _nodes.indexOf(node);
+    final index = _nodeIndicesById[node.id] ?? -1;
+    if (index < 0) {
+      return -1;
+    }
+
+    if (_nodes[index] != node) {
+      // We found a node by id, but the contents aren't equal.
```
Comment (matthew-carroll) [inline super_editor/lib/src/core/document_editor.dart:177]: I think I would word this a bit differently: `// We found a node by id, but it wasn't the node we expected. Therefore, we couldn't find the requested node`

Comment (angelosilvestre) [reply super_editor/lib/src/core/document_editor.dart]: Updated.

File: super_editor/lib/src/core/document_editor.dart (hunk 20 above)
Comment (matthew-carroll) [reply super_editor/lib/src/core/document_editor.dart]: I thought about this a bit more. Why would there ever be 2 nodes with the same ID and different content? The point of the ID is to uniquely refer to a node within a document...

Comment (matthew-carroll) [reply super_editor/lib/src/core/document_editor.dart]: @jmatth can you let me know when/why this change would be a problem?

Comment (jmatth) [reply super_editor/lib/src/core/document_editor.dart]: I could trivially construct two nodes with the same ID that are otherwise unequal, store one in a `MutableDocument`, then pass the second one to `getNodeIndex` and get a valid index back. I find that result unexpected. Best example I can think of for why this would happen is converting between node types, such as a paragraph to a list item or similar, but I don't actually have any real world examples. If you don't think that's a reasonable use case to accommodate then this method should just be removed entirely, because `getNodeIndexById` also exists, its signature makes it much clearer what the criteria for a match are, and without the equality check the two methods serve the exact same purpose.

Comment (matthew-carroll) [reply super_editor/lib/src/core/document_editor.dart]: @angelosilvestre what do you think about getting rid of this method? Can you take a look at the downstream consequences and see if there's any meaningful reason for us to keep it?

Comment (matthew-carroll) [reply super_editor/lib/src/core/document_editor.dart]: That said, if removal looks acceptable, there's probably no reason to make that breaking change now. We're trying to land a semi-stable release after this PR. So @angelosilvestre if you think removal looks OK, then add a "deprecated" annotation to the method and we'll merge it in as-is.

Comment (angelosilvestre) [reply super_editor/lib/src/core/document_editor.dart]: I will take a look.

Comment (angelosilvestre) [reply super_editor/lib/src/core/document_editor.dart]: @matthew-carroll We are using this method in a number of places, but we could change them to use `getNodeIndexById`. Should I add the deprecated annotation and change the usages?

Comment (matthew-carroll) [reply super_editor/lib/src/core/document_editor.dart]: If you've inspected all of those locations, and you're comfortable that changing them won't be a big deal, then sure, you can go ahead and deprecate this method. Please be sure to include a deprecation message that points to the other method.

Comment (angelosilvestre) [reply super_editor/lib/src/core/document_editor.dart]: I marked `getNodeIndex` as deprecated and changed the places which use this method.

**Review by matthew-carroll — APPROVED** [review]
LGTM
