### PR TITLE
Fixed SuperTextField single-line auto-scroll and scrolling bugs on iOS and Android (Resolves #1673)

### LINKED ISSUE #1673: [SuperTextField][iOS][Android] - Auto-scrolling in single text field is glitchy
**Package Version**
super_editor - main

**To Reproduce**
1. Open Example app with iOS or Android SuperTextField example
2. Run the single-line demo
3. Place the caret somewhere in the text
4. Drag the caret into the auto-scroll gutter

**Actual behavior**
Auto-scrolling starts in the expected direction, but when pulling back, the scroll offset jumps to where it was before the scrolling started. Also, when trying to auto-scroll again after that, the scroll offset rapidly jumps back and forth.

**Expected behavior**
When pulling back after auto-scrolling, the scroll offset should remain wherever the user left it. Also, further auto-scrolling shouldn't jump in a glitchy fashion.

**Platform**
iOS and Android

**Screenshots**

https://github.com/superlistapp/super_editor/assets/7259036/92a24ea5-2573-4aee-9dac-57d1c02bd439

https://github.com/superlistapp/super_editor/assets/7259036/d7825078-7b43-44e5-95d9-e57ae4780b6b

### PR DESCRIPTION
**Pull request by matthew-carroll**
Fixed SuperTextField single-line auto-scroll and scrolling bugs on iOS and Android (Resolves #1673)

There were a number of problems with iOS and Android single-line `SuperTextField`s:

- When dragging to the edge to auto-scroll, when the user let go, the selection would jump somewhere else.
- On Android, auto-scrolling to the right would almost immediately jump to the end of the text.
- Pressing and dragging anywhere would place and drag the caret - the caret should only drag when the user presses near it.

To test these behaviors, I added a number of test tools for `SuperTextField`.

The root issue was mostly about the timing of certain behaviors. Adjusting when certain things happen was able to resolve these glitches. There were also a few logical errors in the code - for example, when we were checking if the caret was beyond the right side of the viewport, we weren't accounting for the scroll offset.

### CODE REVIEW

File: super_editor/test/super_textfield/ios/super_textfield_ios_scrolling_test.dart [hunk 1]
```diff
@@ -0,0 +1,267 @@
...
+        // This width is important because it determines how far we need to drag the caret
+        // to the right to enter the auto-scroll region.
+        maxWidth: 200,
+      );
+
+      await tester.placeCaretInSuperTextField(0);
+      expect(controller.selection.extentOffset, 0);
+
+      // Drag caret from left side of text field to right side of text field, into the
+      // right auto-scroll regin.
```
Comment (angelosilvestre) [inline super_editor/test/super_textfield/ios/super_textfield_ios_scrolling_test.dart:56]: "regin" -> "region"

File: super_editor/test/super_textfield/ios/super_textfield_ios_scrolling_test.dart [hunk 2]
```diff
@@ -0,0 +1,267 @@
...
+        minLines: 1,
+        maxLines: 1,
+        // This width is important because it determines how far we need to drag the caret
+        // to the right to enter the auto-scroll region.
+        maxWidth: 200,
+      );
+
+      // Begin with the caret at the end of the text, scrolled all the way to the right.
+      expect(controller.selection.extentOffset, startCaretPosition);
+      // expect(SuperTextFieldInspector.isScrolledToEnd(), isTrue);
```
Comment (angelosilvestre) [inline super_editor/test/super_textfield/ios/super_textfield_ios_scrolling_test.dart:116]: Please remove the commented line

File: super_editor/test/super_textfield/ios/super_textfield_ios_scrolling_test.dart [hunk 3]
```diff
@@ -0,0 +1,267 @@
...
+
+      // Tap on the text field to give it focus, so that the caret appears.
+      await tester.placeCaretInSuperTextField(startCaretPosition);
+
+      // Drag caret from right side of text field to left side of text field, into the
+      // left auto-scroll regin.
```
Comment (angelosilvestre) [inline super_editor/test/super_textfield/ios/super_textfield_ios_scrolling_test.dart:122]: regin -> region

File: super_editor/test/super_textfield/ios/super_textfield_ios_scrolling_test.dart [hunk 4]
```diff
@@ -0,0 +1,267 @@
...
+
+      // Drag from right to left.
+      await tester.drag(find.byType(SuperTextField), const Offset(-100, 0));
+
+      // Ensure the scroll offset didn't change and there's still no selection or focus.
+      expect(SuperTextFieldInspector.findScrollOffset()!, 0);
+      expect(SuperTextFieldInspector.findSelection()!.isValid, isFalse);
+      expect(SuperTextFieldInspector.hasFocus(), isFalse);
+
+      await tester.pump(kTapTimeout);
```
Comment (angelosilvestre) [inline super_editor/test/super_textfield/ios/super_textfield_ios_scrolling_test.dart:190]: Why do we need this pump ?

File: super_editor/test/super_textfield/ios/super_textfield_ios_scrolling_test.dart [hunk 5]
```diff
@@ -0,0 +1,267 @@
...
+      // Place a caret in the field.
+      await tester.placeCaretInSuperTextField(0);
+
+      // Ensure there's a selection with focus
+      expect(SuperTextFieldInspector.findSelection()!.isValid, isTrue);
+      expect(SuperTextFieldInspector.hasFocus(), isTrue);
+
+      // Drag from right to left, far away from the caret.
+      final selectionBeforeDrag = SuperTextFieldInspector.findSelection();
+      await tester.drag(find.byType(SuperTextField), const Offset(100, 0));
```
Comment (angelosilvestre) [inline super_editor/test/super_textfield/ios/super_textfield_ios_scrolling_test.dart:222]: We are dragging from left to right here.

File: super_editor/test/super_textfield/super_textfield_gestures_test.dart [hunk 6]
```diff
@@ -519,13 +519,36 @@ a scrollbar
...
+        // Ensure the caret didn't move.
+        expect(SuperTextFieldInspector.findSelection()!.extent.offset, 3);
+      });
+
+      testWidgetsOnMobile("tap up in focused field moves the caret", (tester) async {
+        await _pumpTestApp(tester);
+
+        // Tap in empty space to place the caret at the end of the text.
+        await tester.tapAt(tester.getBottomRight(find.byType(SuperTextField)) - const Offset(10, 10));
+        // Without this 'delay' onTapDown is not called the second time
```
Comment (angelosilvestre) [inline super_editor/test/super_textfield/super_textfield_gestures_test.dart:531]: Please end the comment with a dot.

**Review by angelosilvestre — APPROVED** [review]
LGTM with some minor comments.

File: super_editor/test/super_textfield/android/super_textfield_android_scrolling_test.dart [hunk 7]
```diff
@@ -0,0 +1,332 @@
...
+
+      // Drag from right to left.
+      await tester.drag(find.byType(SuperTextField), const Offset(-100, 0));
+
+      // Ensure the scroll offset didn't change and there's still no selection or focus.
+      expect(SuperTextFieldInspector.findScrollOffset()!, 0);
+      expect(SuperTextFieldInspector.findSelection()!.isValid, isFalse);
+      expect(SuperTextFieldInspector.hasFocus(), isFalse);
+
+      await tester.pump(kTapTimeout);
```
[the remark this answers is not in the document]
Comment (matthew-carroll) [reply super_editor/test/super_textfield/android/super_textfield_android_scrolling_test.dart:255]: Added a comment - it's to avoid blowing up due to an active timer in tap recognizer.
