### PR TITLE
[SuperEditor][Android] Fix caret not blinking with autofocus (Resolves #1723)

### LINKED ISSUE #1723: [SuperEditor] Android carat doesn't blink when editor autoFocus set to true
**Package Version**
super_editor stable

**Platform**
Android

**Flutter version**
Flutter stable 3.16.5

@matthew-carroll This seems to be the same issue that was originally raised for iOS: https://github.com/superlistapp/super_editor/issues/1566

In that issue, two bugs were reported:
1. The carat doesn't blink when autoFocus in the editor is set to true
2. This issue (carat not blinking) also occurs when initializing an editor and attempting to set selection to the last selectable position

both of which are happening on Android. Here is the PR that fixed this on iOS: https://github.com/superlistapp/super_editor/pull/1575.

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][Android] Fix caret not blinking with autofocus. Resolves #1723

When the editor has autofocus, the caret is display, but it doesn't blink. We had a similar issue on iOS, which was fixed in https://github.com/superlistapp/super_editor/pull/1575

This PR applies the same solution.

### CODE REVIEW

File: super_editor/lib/src/default_editor/document_gestures_touch_android.dart [hunk 1]
```diff
@@ -133,7 +133,7 @@ class SuperEditorAndroidControlsController {
 
   /// Whether the caret should blink right now.
   ValueListenable<bool> get shouldCaretBlink => _shouldCaretBlink;
-  final _shouldCaretBlink = ValueNotifier<bool>(false);
+  final _shouldCaretBlink = ValueNotifier<bool>(true);
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_gestures_touch_android.dart:136]: Should we have a test for this?

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_gestures_touch_android.dart:136]: Added tests

File: super_editor/lib/src/default_editor/document_caret_overlay.dart [hunk 2]
```diff
@@ -46,22 +46,24 @@ class CaretDocumentOverlay extends DocumentLayoutLayerStatefulWidget {
...
+  DocumentLayoutLayerState<CaretDocumentOverlay, Rect?> createState() => CaretDocumentOverlayState();
 }
 
-class _CaretDocumentOverlayState extends DocumentLayoutLayerState<CaretDocumentOverlay, Rect?>
+@visibleForTesting
+class CaretDocumentOverlayState extends DocumentLayoutLayerState<CaretDocumentOverlay, Rect?>
     with SingleTickerProviderStateMixin {
-  late final BlinkController _blinkController;
+  @visibleForTesting
+  late final BlinkController blinkController;
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_caret_overlay.dart:56]: Let's not make the controller public, let's just add a visible-for-testing method that reports whether the caret is currently visible.

File: super_editor/test/super_editor/supereditor_caret_test.dart [hunk 3]
```diff
@@ -326,6 +328,81 @@ void main() {
         });
       });
     });
+
+    group('blinks caret at rest', () {
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_caret_test.dart:332]: What does "rest" mean? Is this group about `SuperEditor` initialization?

I've been thinking that we should have a test suite specifically for `SuperEditor` initialization where we check all the ways it might initialize. Do you want to move these two tests into a new suite called `supereditor_initialization_test.dart`?

We could have a group called "SuperEditor > initialization >"

File: super_editor/test/super_editor/supereditor_caret_test.dart [hunk 4]
```diff
@@ -409,3 +486,21 @@ Future<void> _resizeWindow({
     await tester.pumpAndSettle();
   }
 }
+
+bool _isCaretVisible(WidgetTester tester) {
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_caret_test.dart:490]: This looks like it should be an inspector method.

File: super_editor/test/super_editor/supereditor_caret_test.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_caret_test.dart:332]: > What does "rest" mean? Is this group about SuperEditor initialization?

Here, rest just means that the user isn't typing. The first test is about `SuperEditor` initialization, but the second isn't.

I added a `supereditor_initialization_test.dart` and moved the first test.

File: super_editor/test/super_editor/supereditor_initialization_test.dart [hunk 5]
```diff
@@ -0,0 +1,52 @@
...
+import 'package:super_editor/src/core/document_selection.dart';
+import 'package:super_editor/src/default_editor/text.dart';
+import 'package:super_editor/src/test/super_editor_test/supereditor_inspector.dart';
+import 'package:super_text_layout/super_text_layout.dart';
+
+import 'supereditor_test_tools.dart';
+
+void main() {
+  group('SuperEditor > initialization >', () {
+    testWidgetsOnAllPlatforms('blinks caret when autofocus is true', (tester) async {
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_initialization_test.dart:13]: Let's call this test 'immediately shows and blinks the caret when autofocus is true'

File: super_editor/test/super_editor/supereditor_caret_test.dart [hunk 6]
```diff
@@ -326,6 +327,43 @@ void main() {
         });
       });
     });
+
+    testWidgetsOnAllPlatforms('blinks caret when focused by tap', (tester) async {
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_caret_test.dart:331]: Let's call this test 'blinks the caret when the user places the caret with a single tap'

File: super_editor/test/super_editor/supereditor_caret_test.dart [hunk 7]
```diff
@@ -326,6 +327,43 @@ void main() {
...
+      // Configure BlinkController to animate, otherwise it won't blink.
+      BlinkController.indeterminateAnimationsEnabled = true;
+      addTearDown(() => BlinkController.indeterminateAnimationsEnabled = false);
+
+      // Duration to switch between visible and invisible.
+      const flashPeriod = Duration(milliseconds: 500);
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_caret_test.dart:337]: Can we expose this from the caret system in a way that allows us to create a `SuperEditorInspector` to query it?

File: super_editor/test/super_editor/supereditor_caret_test.dart [hunk 8]
```diff
@@ -3,6 +3,7 @@ import 'package:flutter_test/flutter_test.dart';
 import 'package:flutter_test_runners/flutter_test_runners.dart';
 import 'package:super_editor/super_editor.dart';
 import 'package:super_editor/super_editor_test.dart';
+import 'package:super_text_layout/super_text_layout.dart';
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_caret_test.dart:6]: Do we need this import?

Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_caret_test.dart:6]: The `BlinkController` seems to be exposed only by `super_text_layout.dart`. Should we expose it somewhere else?

File: super_editor/test/super_editor/supereditor_caret_test.dart (hunk 7 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_caret_test.dart]: Added a `SuperEditorInspector.caretFlashPeriod` method.

File: super_editor/test/super_editor/supereditor_caret_test.dart (hunk 8 above)
Comment (matthew-carroll) [reply super_editor/test/super_editor/supereditor_caret_test.dart:6]: We can leave it as-is

**Review by matthew-carroll — APPROVED** [review]
LGTM
