### PR TITLE
[SuperTextField] Fix new line duplication (Resolves #1468)

### LINKED ISSUE #1468: [SuperTextField] SHIFT+ENTER adds 2 new lines
Steps to reproduce:
* Run interactive SuperTextField demo 
* Place the selection somewhere in the content
* Press SHIFT+ENTER

**Expected:** a single new line is added
**Actual:** 2 new lines are added

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperTextField] Fix new line duplication. Resolves #1468

On macOS, pressing ENTER or SHIFT + ENTER is inserting two lines. This is caused because pressing ENTER generates both an `onPerformAction` call and a `\n` insertion.

On Windows this issue doesn't happen because we are using key event handlers to insert new lines. If we remove the key handler that inserts new lines, the issue happens on Windows as well. This issue was introduced when the selector handlers were implemented.

This PR changes `_onPerformAction` to avoid inserting new lines.

### CODE REVIEW

File: super_editor/test/super_editor/supereditor_test_tools.dart [hunk 1]
```diff
@@ -738,3 +739,21 @@ class FakeSuperEditorScroller implements DocumentScroller {
   @override
   void detach() => throw UnimplementedError();
 }
+
+/// The platform to be used when simulating a keyboard event with `sendKeyEvent`,
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_test_tools.dart:743]: Why would this platform be different than the `defaultTargetPlatform`? Also, where is this being used?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 2]
```diff
@@ -1288,7 +1288,13 @@ class _SuperTextFieldImeInteractorState extends State<SuperTextFieldImeInteracto
   void _onPerformAction(TextInputAction action) {
     switch (action) {
       case TextInputAction.newline:
-        widget.textController.insertNewline();
+        // On mac desktop, we don't insert new lines via keyboard events.
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1291]: This says "On mac desktop" but I don't see any platform inspection nearby....

File: super_editor/test/super_textfield/super_textfield_ime_test.dart [hunk 3]
```diff
@@ -683,6 +621,38 @@ void main() {
   });
 }
 
+Future<void> _pressEnterOnSuperTextField(WidgetTester tester) async {
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_ime_test.dart:624]: Is this actually specific to `SuperTextField`? Why doesn't this apply to `SuperEditor`, too? Also, does this belong in the testing robots package for general use?

File: super_editor/test/super_textfield/super_textfield_ime_test.dart [hunk 4]
```diff
@@ -683,6 +621,38 @@ void main() {
...
+  final handled = await tester.sendKeyEvent(LogicalKeyboardKey.enter, platform: testKeyEventPlatform);
+  if (handled) {
+    // The textfield handled the key event.
+    // It won't bubble up to the OS to generate text deltas or input actions.
+    return;
+  }
+
+  // The ENTER key event wasn't handled by the textfield.
+  // The OS generates both a "\n" insertion and a new line action.
+  await tester.ime.typeText('\n', getter: imeClientGetter);
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_ime_test.dart:634]: Should we be checking for an open connection instead of assuming that there is one?

File: super_editor/test/super_editor/supereditor_test_tools.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_test_tools.dart:743]: It's used in `_pressEnterOnSuperTextField`. I extracted this from `pressEnter`.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1291]: I'm not inspecting the platform because for other desktop platforms, the new line is inserted via keyboard handlers. Because of that, the IME doesn't reports input actions nor insertion deltas.

If, at some point, we remove the ENTER keyboard handler, we would be in the same situation as on mac...

Should I just update the comment?

File: super_editor/test/super_textfield/super_textfield_ime_test.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor/test/super_textfield/super_textfield_ime_test.dart:624]: We could add this to the test robots. Should I open a PR for this?

File: super_editor/test/super_textfield/super_textfield_ime_test.dart (hunk 4 above)
Comment (angelosilvestre) [reply super_editor/test/super_textfield/super_textfield_ime_test.dart:639]: Updated

File: super_editor/test/super_editor/supereditor_test_tools.dart (hunk 1 above)
Comment (matthew-carroll) [reply super_editor/test/super_editor/supereditor_test_tools.dart:743]: Why did you extract it instead of use it? And also I'd still like to know why it doesn't use `defaultTargetPlatform`. I don't remember what we did for `pressEnter` originally, or why.

File: super_editor/test/super_textfield/super_textfield_ime_test.dart (hunk 3 above)
Comment (matthew-carroll) [reply super_editor/test/super_textfield/super_textfield_ime_test.dart:624]: Yeah you can open a PR for that. What about the first two questions?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 2 above)
Comment (matthew-carroll) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1291]: Is the purpose of this code comment to explain why we're not doing anything when we get a newline?

If so, does the following comment better capture the situation?

```dart
// Do nothing for IME newline actions
//
// Mac: Key presses flow, unhandled, to the OS and turn into IME selectors. We handle newlines there.
// Windows/Linux: Newlines are inserted by Super Editor key handlers, instead of IME actions, because Flutter doesn't dispatch newline IME actions for these platforms.
// Android/iOS: This text field implementation is only for desktop, mobile is handled elsewhere.
```

Also, can you remind me why we're using key handlers for Windows/Linux and not using the IME actions? Is that because Flutter doesn't send us IME actions for those?

File: super_editor/test/super_editor/supereditor_test_tools.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_test_tools.dart:743]: I didn't use `pressEnter` because I had to check whether or not the key was handled in order to generate the input action and the insertion delta.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1291]: Previously, we used key handlers to insert new line on all desktop platforms. After the `performSelection` implementation, we stopped doing that on mac.

We could probably could do the same on the other desktop platforms. I tested on Windows and we also receive the input actions and insertion deltas if we don't handle the ENTER key.

File: super_editor/test/super_textfield/super_textfield_ime_test.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor/test/super_textfield/super_textfield_ime_test.dart:624]: This will apply for `SuperEditor` also. I was looking into implementing it on testing robots `pressEnter`, but then we will need to add an optional `imeClientGetter` parameter. 

To generate deltas, we need to access `DeltaTextInputClient` in order to obtain the current editing value.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 2 above)
Comment (matthew-carroll) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart]: Ok. Let's try removing the ENTER handler from the IME handler list for Windows and Linux.

File: super_editor/test/super_textfield/super_textfield_ime_test.dart (hunk 3 above)
Comment (matthew-carroll) [reply super_editor/test/super_textfield/super_textfield_ime_test.dart]: Can we introduce a `pressEnterOnIme()` to the robots package?

Comment (angelosilvestre) [reply super_editor/test/super_textfield/super_textfield_ime_test.dart]: Opened https://github.com/Flutter-Bounty-Hunters/flutter_test_robots/pull/20

Comment (matthew-carroll) [reply super_editor/test/super_textfield/super_textfield_ime_test.dart]: I just released v0.0.22

**Comment by matthew-carroll** [comment]
@angelosilvestre is this ready for review? Or still doing work?

**Comment by matthew-carroll** [comment]
Also, looks like tests are failing, FYI.

**Comment by angelosilvestre** [comment]
@matthew-carroll This is ready for another review now.

**Comment by matthew-carroll** [comment]
Looks like this PR has a merge conflict.

**Comment by angelosilvestre** [comment]
@matthew-carroll Rebased.

File: super_editor/test/super_editor/supereditor_test_tools.dart [hunk 5]
```diff
@@ -1,6 +1,7 @@
 import 'dart:math';
 import 'dart:ui' as ui;
 
+import 'package:flutter/foundation.dart';
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_test_tools.dart:4]: Do you need this import?

**Review by matthew-carroll — APPROVED** [review]
LGTM with removal of one superfluous import

File: super_editor/test/super_editor/supereditor_test_tools.dart (hunk 5 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_test_tools.dart]: Nope. Removed.

**Comment by matthew-carroll** [comment]
FYI @angelosilvestre CI is going to automatically create a PR when we merge, but you'll have to explicitly close and re-open the PR to get other CI checks to run.

**Comment by angelosilvestre** [comment]
@matthew-carroll I didn't find any PR created for after the merge

**Comment by matthew-carroll** [comment]
Ugh - CI is failing for some reason....complaining that GitHub bot doesn't have permission, which doesn't make sense given that this has worked previously.

https://github.com/superlistapp/super_editor/actions/runs/6552954869/job/17799413806
