### PR TITLE
[SuperEditor][SuperTextField][macOS] Fix crash when attaching to the IME. (Resolves #2696)

### LINKED ISSUE #2696: [BUG] - MacOS crash on Flutter 3.32.0 ("unrecognized selector sent to instance")
TL;DR a small update is required to prevent crashing on MacOS in Flutter 3.32.0.

**Package Version**
super_editor: 0.3.0-dev.24 (updated)

**To Reproduce**
1. Upgrade to Flutter 3.32.0
2. Use a SuperEditor
3. Crash: `Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull longLongValue]: unrecognized selector sent to instance 0x1f5b0cd18'`

**Actual behavior**

```
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull longLongValue]: unrecognized selector sent to instance 0x1f5b0cd18'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000018674eca0 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x0000000186212b90 objc_exception_throw + 88
	2   CoreFoundation                      0x000000018680bb90 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00000001866bcddc ___forwarding___ + 1500
	4   CoreFoundation                      0x00000001866bc740 _CF_forwarding_prep_0 + 96
	5   FlutterMacOS                        0x0000000104c61e34 -[FlutterTextInputPlugin handleMethodCall:result:] + 2324
	6   FlutterMacOS                        0x00000001059174b4 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 180
	7   FlutterMacOS                        0x0000000104c4a748 -[FlutterEngine engineCallbackOnPlatformMessage:] + 416
	8   FlutterMacOS                        0x000000010551b024 _ZNSt3_fl10__function6__funcIZ23FlutterEngineInitializeE3$_3NS_9allocatorIS2_EEFvNS_10unique_ptrIN7flutter15PlatformMessageENS_14default_deleteIS7_EEEEEEclEOSA_ + 128
	9   FlutterMacOS                        0x000000010552e7f4 _ZN7flutter20PlatformViewEmbedder21HandlePlatformMessageENSt3_fl10unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE + 76
	10  FlutterMacOS                        0x000000010552f384 _ZNSt3_fl10__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter20PlatformViewEmbedder30EmbedderPlatformMessageHandler21HandlePlatformMessageENS_10unique_ptrINS5_15PlatformMessageENS_14defa	11  FlutterMacOS                        0x000000010552b3c4 _ZN7flutter18EmbedderTaskRunner8PostTaskEy + 652
	12  FlutterMacOS                        0x000000010551f95c _ZN7flutter14EmbedderEngine7RunTaskEPK11FlutterTask + 56
	13  FlutterMacOS                        0x0000000105512890 FlutterEngineRunTask + 68
	14  FlutterMacOS                        0x0000000104c4daa8 __60-[FlutterEngine postMainThreadTask:targetTimeInNanoseconds:]_block_invoke + 72
	15  FlutterMacOS                        0x0000000104c5d734 -[FlutterRunLoop performExpiredTasks] + 524
	16  CoreFoundation                      0x00000001866ddcd4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
	17  CoreFoundation                      0x00000001866ddc68 __CFRunLoopDoSource0 + 172
	18  CoreFoundation                      0x00000001866dd9d4 __CFRunLoopDoSources0 + 232
	19  CoreFoundation                      0x00000001866dc628 __CFRunLoopRun + 840
	20  CoreFoundation                      0x00000001866dbc58 CFRunLoopRunSpecific + 572
	21  HIToolbox                           0x000000019217027c RunCurrentEventLoopInMode + 324
	22  HIToolbox                           0x00000001921734e8 ReceiveNextEventCommon + 676
	23  HIToolbox                           0x00000001922fe484 _BlockUntilNextEventMatchingListInModeWithFilter + 76
	24  AppKit                              0x000000018a603ab4 _DPSNextEvent + 684
	25  AppKit                              0x000000018afa25b0 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
	26  AppKit                              0x000000018a5f6c64 -[NSApplication run] + 480
	27  AppKit                              0x000000018a5cd35c NSApplicationMain + 880
	28  Plot.debug.dylib                    0x000000010080ab70 $sSo21NSApplicationDelegateP6AppKitE4mainyyFZ + 40
	29  Plot.debug.dylib                    0x000000010080ab38 $s4Plot11AppDelegateC5$mainyyFZ + 44
	30  Plot.debug.dylib                    0x000000010080abd8 __debug_main_executable_dylib_entry_point + 28
	31  dyld                                0x0000000186252b98 start + 6076
)
```

**Platform**
MacOS

**Flutter version**
Flutter 3.32.0

**Additional context**

- [Known Flutter issue](https://github.com/flutter/flutter/issues/169204) -- the workaround requires an update to libraries use `TextInput.attach`.
- [An example update in another library](https://github.com/AppFlowy-IO/appflowy-editor/pull/1109)

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][SuperTextField][macOS] Fix crash when attaching to the IME. (Resolves #2696)

When running on Flutter 3.32, both `SuperEditor` and `SuperTextField` crash when attaching to the IME with the following exception:

```console
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull longLongValue]: unrecognized selector sent to instance 0x1f5b0cd18'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000018674eca0 __exceptionPreprocess + 176
	1   libobjc.A.dylib                     0x0000000186212b90 objc_exception_throw + 88
	2   CoreFoundation                      0x000000018680bb90 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00000001866bcddc ___forwarding___ + 1500
	4   CoreFoundation                      0x00000001866bc740 _CF_forwarding_prep_0 + 96
	5   FlutterMacOS                        0x0000000104c61e34 -[FlutterTextInputPlugin handleMethodCall:result:] + 2324
	6   FlutterMacOS                        0x00000001059174b4 __45-[FlutterMethodChannel setMethodCallHandler:]_block_invoke + 180
	7   FlutterMacOS                        0x0000000104c4a748 -[FlutterEngine engineCallbackOnPlatformMessage:] + 416
	8   FlutterMacOS                        0x000000010551b024 _ZNSt3_fl10__function6__funcIZ23FlutterEngineInitializeE3$_3NS_9allocatorIS2_EEFvNS_10unique_ptrIN7flutter15PlatformMessageENS_14default_deleteIS7_EEEEEEclEOSA_ + 128
	9   FlutterMacOS                        0x000000010552e7f4 _ZN7flutter20PlatformViewEmbedder21HandlePlatformMessageENSt3_fl10unique_ptrINS_15PlatformMessageENS1_14default_deleteIS3_EEEE + 76
	10  FlutterMacOS                        0x000000010552f384 _ZNSt3_fl10__function6__funcIN3fml8internal14CopyableLambdaIZN7flutter20PlatformViewEmbedder30EmbedderPlatformMessageHandler21HandlePlatformMessageENS_10unique_ptrINS5_15PlatformMessageENS_14defa	11  FlutterMacOS                        0x000000010552b3c4 _ZN7flutter18EmbedderTaskRunner8PostTaskEy + 652
	12  FlutterMacOS                        0x000000010551f95c _ZN7flutter14EmbedderEngine7RunTaskEPK11FlutterTask + 56
	13  FlutterMacOS                        0x0000000105512890 FlutterEngineRunTask + 68
	14  FlutterMacOS                        0x0000000104c4daa8 __60-[FlutterEngine postMainThreadTask:targetTimeInNanoseconds:]_block_invoke + 72
	15  FlutterMacOS                        0x0000000104c5d734 -[FlutterRunLoop performExpiredTasks] + 524
	16  CoreFoundation                      0x00000001866ddcd4 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
	17  CoreFoundation                      0x00000001866ddc68 __CFRunLoopDoSource0 + 172
	18  CoreFoundation                      0x00000001866dd9d4 __CFRunLoopDoSources0 + 232
	19  CoreFoundation                      0x00000001866dc628 __CFRunLoopRun + 840
	20  CoreFoundation                      0x00000001866dbc58 CFRunLoopRunSpecific + 572
	21  HIToolbox                           0x000000019217027c RunCurrentEventLoopInMode + 324
	22  HIToolbox                           0x00000001921734e8 ReceiveNextEventCommon + 676
	23  HIToolbox                           0x00000001922fe484 _BlockUntilNextEventMatchingListInModeWithFilter + 76
	24  AppKit                              0x000000018a603ab4 _DPSNextEvent + 684
	25  AppKit                              0x000000018afa25b0 -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 688
	26  AppKit                              0x000000018a5f6c64 -[NSApplication run] + 480
	27  AppKit                              0x000000018a5cd35c NSApplicationMain + 880
	28  Plot.debug.dylib                    0x000000010080ab70 $sSo21NSApplicationDelegateP6AppKitE4mainyyFZ + 40
	29  Plot.debug.dylib                    0x000000010080ab38 $s4Plot11AppDelegateC5$mainyyFZ + 44
	30  Plot.debug.dylib                    0x000000010080abd8 __debug_main_executable_dylib_entry_point + 28
	31  dyld                                0x0000000186252b98 start + 6076
)
```

The issue is that, due to the multi-window work, we need to provide the view ID in the `TextInputConfiguration`.

This PR adds a required `viewId` parameter to the `SuperEditorImeConfiguration.toTextInputConfiguration`. We could instead add a `viewId` property to `SuperEditorImeConfiguration` itself, but doing so would require that we have access to the `BuildContext` in all places where we instantiate the `SuperEditorImeConfiguration`.  By adding it to `toTextInputConfiguration`, the `BuildContext` is only required when we try to attach to the IME

It was also needed to modify the `SoftwareKeyboardController` and the `SoftwareKeyboardControllerDelegate` to require the view ID.

Although only macOS requires it at this time, I think that it's better to make it required, because otherwise it would make it easy to forget to provide it. So, I think it's better to break the build than risking a crash at runtime.

This is a breaking change for people using `SoftwareKeyboardController`, but it would be a simple fix:

Before:

```dart
controller.open();
```

After:

```dart
controller.open(viewId: View.of(context).viewId);
```

We could also required a `BuildContext` instead of the viewId, but I'm worried that passing the `BuildContext` would be too much.

### CODE REVIEW

File: super_editor/test/super_editor/supereditor_keyboard_test.dart [hunk 1]
```diff
@@ -948,6 +948,15 @@ DocumentSelection _selectionInParagraph(
   );
 }
 
+/// Finds the viewId of the [SuperEditor] widget.
+///
+/// {@macro supereditor_finder}
+int _findSuperEditorViewId([Finder? finder]) {
+  finder ??= find.byType(SuperEditor);
+  final context = (finder.evaluate().first as BuildContext);
+  return View.of(context).viewId;
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_keyboard_test.dart:957]: What is this value during a test? Do we set it? If so, can we just hard-code a literal value in tests, the same way we do with paragraph IDs in most cases?
