### PR TITLE
[SuperEditor] Fix crashing when deleting all content which contains a non-deletable node at an edge (Resolves #2393)

### LINKED ISSUE #2393: [SuperEditor] - Exceptions when deleting all content with a non-deletable node at start or end of the document
When all content in the document is selected using CMD+A and then pressing delete or backspace, it will throw exceptions if there is a non-deletable node at the start and/or end of the document. Here are 2 tests that reproduce this issue, one for each case:

**Non-deletable node at the end of the document**
<details>
  <summary>test that reproduces issue</summary>

  ```dart
      testWidgetsOnApple(
        'selects all when CMD+A is pressed with a two-node document',
        (tester) async {
          await tester //
              .createDocument()
              .withCustomContent(
                MutableDocument(
                  nodes: [
                    ParagraphNode(
                      id: '1',
                      text: AttributedText('This is some text'),
                    ),
                    HorizontalRuleNode(id: '2'),
                  ],
                ),
              )
              .pump();

          await tester.placeCaretInParagraph("1", 0);

          // Select all content
          await tester.pressCmdA();

          // Ensure everything is selected.
          expect(
            SuperEditorInspector.findDocumentSelection(),
            const DocumentSelection(
              base: DocumentPosition(
                nodeId: '1',
                nodePosition: TextNodePosition(offset: 0),
              ),
              extent: DocumentPosition(
                nodeId: '2',
                nodePosition: UpstreamDownstreamNodePosition.downstream(),
              ),
            ),
          );

          await tester.pressDelete();
        },
      );
  ```
</details>

<details>
  <summary>exception</summary>

  ```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following _TypeError was thrown while dispatching notifications for
PausableValueNotifier<DocumentSelection?>:
Null check operator used on a null value

When the exception was thrown, this was the stack:
#0      InspectDocumentSelection.selectUpstreamPosition (package:super_editor/src/core/document_selection.dart:387:62)
#1      InspectDocumentSelection.getNodesInContentOrder (package:super_editor/src/core/document_selection.dart:378:30)
#2      DocumentImeSerializer._serialize (package:super_editor/src/default_editor/document_ime/document_serialization.dart:69:31)
#3      new DocumentImeSerializer (package:super_editor/src/default_editor/document_ime/document_serialization.dart:34:5)
#4      DocumentImeInputClient._sendDocumentToIme (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:265:30)
#5      DocumentImeInputClient._onContentChange (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:87:5)
#6      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:437:24)
#7      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:559:5)
#8      PausableValueNotifier.resumeNotifications (package:super_editor/src/infrastructure/pausable_value_notifier.dart:49:11)
#9      MutableDocumentComposer.onTransactionEnd (package:super_editor/src/core/document_composer.dart:155:24)
#10     Editor._onTransactionEnd (package:super_editor/src/core/editor.dart:331:16)
#11     Editor.endTransaction (package:super_editor/src/core/editor.dart:231:5)
#12     Editor.execute (package:super_editor/src/core/editor.dart:283:7)
#13     CommonEditorOperations._deleteExpandedSelection (package:super_editor/src/default_editor/common_editor_operations.dart:1352:12)
#14     CommonEditorOperations.deleteDownstream (package:super_editor/src/default_editor/common_editor_operations.dart:868:7)
#15     deleteDownstreamContentWithDelete (package:super_editor/src/default_editor/text.dart:2378:43)
#16     _SuperEditorHardwareKeyHandlerState._onKeyPressed (package:super_editor/src/default_editor/document_hardware_keyboard/document_physical_keyboard.dart:84:50)
#17     _HighlightModeManager.handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:2116:29)
#18     KeyEventManager._dispatchKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1104:34)
#19     KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1176:17)
#20     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
#21     TestDefaultBinaryMessenger.handlePlatformMessage (package:flutter_test/src/test_default_binary_messenger.dart:99:42)
#22     KeyEventSimulator._simulateKeyEventByRawEvent.<anonymous closure> (package:flutter_test/src/event_simulation.dart:655:79)
#25     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:74:41)
#26     KeyEventSimulator._simulateKeyEventByRawEvent (package:flutter_test/src/event_simulation.dart:653:27)
#27     KeyEventSimulator.simulateKeyDownEvent.simulateByRawEvent (package:flutter_test/src/event_simulation.dart:740:14)
#28     KeyEventSimulator.simulateKeyDownEvent (package:flutter_test/src/event_simulation.dart:760:23)
#29     simulateKeyDownEvent (package:flutter_test/src/event_simulation.dart:883:48)
#30     WidgetController.sendKeyEvent (package:flutter_test/src/controller.dart:1998:32)
#31     KeyboardInput.pressDelete (package:flutter_test_robots/src/keyboard.dart:278:11)
#32     main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/miguel/Documents/GitHub/super_editor/super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart:2004:24)
<asynchronous suspension>
#33     testWidgetsOnMac.<anonymous closure> (package:flutter_test_runners/src/platform_runners.dart:96:7)
<asynchronous suspension>
#34     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#35     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)

The PausableValueNotifier<DocumentSelection?> sending notification was:
  PausableValueNotifier<DocumentSelection?>#99818([Selection] - 1: 0)
════════════════════════════════════════════════════════════════════════════════════════════════════ 
 ```
</details>

**Non-deletable node at the start of the document**
<details>
  <summary>test that reproduces issue</summary>

  ```dart
        testWidgetsOnApple(
        'selects all when CMD+A is pressed with a two-node document',
        (tester) async {
          await tester //
              .createDocument()
              .withCustomContent(
                MutableDocument(
                  nodes: [
                    HorizontalRuleNode(id: '1'),
                    ParagraphNode(
                      id: '2',
                      text: AttributedText('This is some text'),
                    ),
                  ],
                ),
              )
              .pump();

          await tester.placeCaretInParagraph("2", 0);

          // Select all content
          await tester.pressCmdA();

          // Ensure everything is selected.
          expect(
            SuperEditorInspector.findDocumentSelection(),
            const DocumentSelection(
              base: DocumentPosition(
                nodeId: '1',
                nodePosition: UpstreamDownstreamNodePosition.upstream(),
              ),
              extent: DocumentPosition(
                nodeId: '2',
                nodePosition: TextNodePosition(offset: 17),
              ),
            ),
          );

          await tester.pressDelete();
        },
      );
  ```
</details>

<details>
  <summary>exception</summary>

 ```
══╡ EXCEPTION CAUGHT BY FOUNDATION LIBRARY ╞════════════════════════════════════════════════════════
The following _Exception was thrown while dispatching notifications for
PausableValueNotifier<DocumentSelection?>:
Exception: Expected a UpstreamDownstreamNodePosition for position1 but received a TextNodePosition

When the exception was thrown, this was the stack:
#0      BlockNode.selectUpstreamPosition (package:super_editor/src/default_editor/box_component.dart:32:7)
#1      InspectDocumentSelection.selectUpstreamPosition (package:super_editor/src/core/document_selection.dart:401:20)
#2      InspectDocumentSelection.getNodesInContentOrder (package:super_editor/src/core/document_selection.dart:378:30)
#3      DocumentImeSerializer._serialize (package:super_editor/src/default_editor/document_ime/document_serialization.dart:69:31)
#4      new DocumentImeSerializer (package:super_editor/src/default_editor/document_ime/document_serialization.dart:34:5)
#5      DocumentImeInputClient._sendDocumentToIme (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:265:30)
#6      DocumentImeInputClient._onContentChange (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:87:5)
#7      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:437:24)
#8      ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:559:5)
#9      PausableValueNotifier.resumeNotifications (package:super_editor/src/infrastructure/pausable_value_notifier.dart:49:11)
#10     MutableDocumentComposer.onTransactionEnd (package:super_editor/src/core/document_composer.dart:155:24)
#11     Editor._onTransactionEnd (package:super_editor/src/core/editor.dart:331:16)
#12     Editor.endTransaction (package:super_editor/src/core/editor.dart:231:5)
#13     Editor.execute (package:super_editor/src/core/editor.dart:283:7)
#14     CommonEditorOperations._deleteExpandedSelection (package:super_editor/src/default_editor/common_editor_operations.dart:1352:12)
#15     CommonEditorOperations.deleteDownstream (package:super_editor/src/default_editor/common_editor_operations.dart:868:7)
#16     deleteDownstreamContentWithDelete (package:super_editor/src/default_editor/text.dart:2378:43)
#17     _SuperEditorHardwareKeyHandlerState._onKeyPressed (package:super_editor/src/default_editor/document_hardware_keyboard/document_physical_keyboard.dart:84:50)
#18     _HighlightModeManager.handleKeyMessage (package:flutter/src/widgets/focus_manager.dart:2116:29)
#19     KeyEventManager._dispatchKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1104:34)
#20     KeyEventManager.handleRawKeyMessage (package:flutter/src/services/hardware_keyboard.dart:1176:17)
#21     BasicMessageChannel.setMessageHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:235:49)
#22     TestDefaultBinaryMessenger.handlePlatformMessage (package:flutter_test/src/test_default_binary_messenger.dart:99:42)
#23     KeyEventSimulator._simulateKeyEventByRawEvent.<anonymous closure> (package:flutter_test/src/event_simulation.dart:655:79)
#26     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:74:41)
#27     KeyEventSimulator._simulateKeyEventByRawEvent (package:flutter_test/src/event_simulation.dart:653:27)
#28     KeyEventSimulator.simulateKeyDownEvent.simulateByRawEvent (package:flutter_test/src/event_simulation.dart:740:14)
#29     KeyEventSimulator.simulateKeyDownEvent (package:flutter_test/src/event_simulation.dart:760:23)
#30     simulateKeyDownEvent (package:flutter_test/src/event_simulation.dart:883:48)
#31     WidgetController.sendKeyEvent (package:flutter_test/src/controller.dart:1998:32)
#32     KeyboardInput.pressDelete (package:flutter_test_robots/src/keyboard.dart:278:11)
#33     main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/miguel/Documents/GitHub/super_editor/super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart:2004:24)
<asynchronous suspension>
#34     testWidgetsOnMac.<anonymous closure> (package:flutter_test_runners/src/platform_runners.dart:96:7)
<asynchronous suspension>
#35     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#36     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 3 frames from dart:async and package:stack_trace)

The PausableValueNotifier<DocumentSelection?> sending notification was:
  PausableValueNotifier<DocumentSelection?>#4b7a2([Selection] - 1: 0)
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _Exception was thrown building SelectionLeadersDocumentLayer(state:
_SelectionLeadersDocumentLayerState#304d9):
Exception: Expected nodePosition of type UpstreamDownstreamNodePosition but received:
TextPosition(offset: 0, affinity: TextAffinity.downstream)

The relevant error-causing widget was:
  SelectionLeadersDocumentLayer
  SelectionLeadersDocumentLayer:file:///Users/miguel/Documents/GitHub/super_editor/super_editor/lib/src/default_editor/super_editor.dart:1064:12

When the exception was thrown, this was the stack:
#0      _BoxComponentState.getRectForPosition (package:super_editor/src/default_editor/box_component.dart:214:7)
#1      _SingleColumnDocumentLayoutState.getRectForPosition (package:super_editor/src/default_editor/layout_single_column/_layout.dart:255:37)
#2      _SelectionLeadersDocumentLayerState.computeLayoutDataWithDocumentLayout (package:super_editor/src/infrastructure/documents/selection_leader_document_layer.dart:102:31)
#3      DocumentLayoutLayerState.computeLayoutData (package:super_editor/src/infrastructure/documents/document_layers.dart:50:12)
#4      ContentLayerState.build (package:super_editor/src/infrastructure/content_layers.dart:963:21)
#5      StatefulElement.build (package:flutter/src/widgets/framework.dart:5749:27)
#6      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5637:15)
#7      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5800:11)
#8      Element.rebuild (package:flutter/src/widgets/framework.dart:5353:7)
#9      StatefulElement.update (package:flutter/src/widgets/framework.dart:5823:5)
#10     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#11     ContentLayersElement.buildLayers.<anonymous closure> (package:super_editor/src/infrastructure/content_layers.dart:288:25)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3046:19)
#13     ContentLayersElement.buildLayers (package:super_editor/src/infrastructure/content_layers.dart:269:12)
#14     RenderContentLayers.performLayout.<anonymous closure> (package:super_editor/src/infrastructure/content_layers.dart:618:17)
#15     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2738:59)
#16     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1108:15)
#17     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2738:14)
#18     RenderContentLayers.performLayout (package:super_editor/src/infrastructure/content_layers.dart:617:5)
#19     RenderObject.layout (package:flutter/src/rendering/object.dart:2627:7)
#20     _RenderSliverHybridStack.performLayout (package:super_editor/src/infrastructure/sliver_hybrid_stack.dart:58:12)
#21     RenderObject.layout (package:flutter/src/rendering/object.dart:2627:7)
#22     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:609:13)
#23     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1524:12)
#24     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1435:20)
#25     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2465:7)
#26     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1062:18)
#27     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1075:15)
#28     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1435:27)
#29     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:475:5)
#30     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#31     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#32     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1288:9)
#35     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:74:41)
#36     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1275:27)
#37     WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:726:23)
#40     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:74:41)
#41     WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:719:27)
#42     KeyboardInput.pressDelete (package:flutter_test_robots/src/keyboard.dart:279:11)
<asynchronous suspension>
#43     main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/miguel/Documents/GitHub/super_editor/super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart:2004:11)
<asynchronous suspension>
#44     testWidgetsOnMac.<anonymous closure> (package:flutter_test_runners/src/platform_runners.dart:96:7)
<asynchronous suspension>
#45     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#46     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
The following _Exception was thrown building CaretDocumentOverlay(state:
CaretDocumentOverlayState#964c0(ticker inactive)):
Exception: Expected nodePosition of type UpstreamDownstreamNodePosition but received:
TextPosition(offset: 0, affinity: TextAffinity.downstream)

The relevant error-causing widget was:
  CaretDocumentOverlay
  CaretDocumentOverlay:file:///Users/miguel/Documents/GitHub/super_editor/super_editor/lib/src/default_editor/super_editor.dart:1227:12

When the exception was thrown, this was the stack:
#0      _BoxComponentState.getRectForPosition (package:super_editor/src/default_editor/box_component.dart:214:7)
#1      _BoxComponentState.getEdgeForPosition (package:super_editor/src/default_editor/box_component.dart:197:25)
#2      _SingleColumnDocumentLayoutState.getEdgeForPosition (package:super_editor/src/default_editor/layout_single_column/_layout.dart:239:37)
#3      CaretDocumentOverlayState.computeLayoutDataWithDocumentLayout (package:super_editor/src/default_editor/document_caret_overlay.dart:169:24)
#4      DocumentLayoutLayerState.computeLayoutData (package:super_editor/src/infrastructure/documents/document_layers.dart:50:12)
#5      ContentLayerState.build (package:super_editor/src/infrastructure/content_layers.dart:963:21)
#6      StatefulElement.build (package:flutter/src/widgets/framework.dart:5749:27)
#7      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5637:15)
#8      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5800:11)
#9      Element.rebuild (package:flutter/src/widgets/framework.dart:5353:7)
#10     StatefulElement.update (package:flutter/src/widgets/framework.dart:5823:5)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3949:15)
#12     ContentLayersElement.buildLayers.<anonymous closure> (package:super_editor/src/infrastructure/content_layers.dart:288:25)
#13     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:3046:19)
#14     ContentLayersElement.buildLayers (package:super_editor/src/infrastructure/content_layers.dart:269:12)
#15     RenderContentLayers.performLayout.<anonymous closure> (package:super_editor/src/infrastructure/content_layers.dart:618:17)
#16     RenderObject.invokeLayoutCallback.<anonymous closure> (package:flutter/src/rendering/object.dart:2738:59)
#17     PipelineOwner._enableMutationsToDirtySubtrees (package:flutter/src/rendering/object.dart:1108:15)
#18     RenderObject.invokeLayoutCallback (package:flutter/src/rendering/object.dart:2738:14)
#19     RenderContentLayers.performLayout (package:super_editor/src/infrastructure/content_layers.dart:617:5)
#20     RenderObject.layout (package:flutter/src/rendering/object.dart:2627:7)
#21     _RenderSliverHybridStack.performLayout (package:super_editor/src/infrastructure/sliver_hybrid_stack.dart:58:12)
#22     RenderObject.layout (package:flutter/src/rendering/object.dart:2627:7)
#23     RenderViewportBase.layoutChildSequence (package:flutter/src/rendering/viewport.dart:609:13)
#24     RenderViewport._attemptLayout (package:flutter/src/rendering/viewport.dart:1524:12)
#25     RenderViewport.performLayout (package:flutter/src/rendering/viewport.dart:1435:20)
#26     RenderObject._layoutWithoutResize (package:flutter/src/rendering/object.dart:2465:7)
#27     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1062:18)
#28     PipelineOwner.flushLayout (package:flutter/src/rendering/object.dart:1075:15)
#29     AutomatedTestWidgetsFlutterBinding.drawFrame (package:flutter_test/src/binding.dart:1435:27)
#30     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:475:5)
#31     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#32     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1318:9)
#33     AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1288:9)
#36     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:74:41)
#37     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1275:27)
#38     WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:726:23)
#41     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:74:41)
#42     WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:719:27)
#43     KeyboardInput.pressDelete (package:flutter_test_robots/src/keyboard.dart:279:11)
<asynchronous suspension>
#44     main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/miguel/Documents/GitHub/super_editor/super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart:2004:11)
<asynchronous suspension>
#45     testWidgetsOnMac.<anonymous closure> (package:flutter_test_runners/src/platform_runners.dart:96:7)
<asynchronous suspension>
#46     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#47     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)

════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY SCHEDULER LIBRARY ╞═════════════════════════════════════════════════════════
The following _Exception was thrown during a scheduler callback:
Exception: Expected nodePosition of type UpstreamDownstreamNodePosition but received:
TextPosition(offset: 0, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack:
#0      _BoxComponentState.getRectForPosition (package:super_editor/src/default_editor/box_component.dart:214:7)
#1      _SingleColumnDocumentLayoutState.getRectForPosition (package:super_editor/src/default_editor/layout_single_column/_layout.dart:255:37)
#2      SuperEditorImeInteractorState._computeCaretRectInViewportSpace (package:super_editor/src/default_editor/document_ime/supereditor_ime_interactor.dart:420:44)
#3      SuperEditorImeInteractorState._reportCaretRectToIme (package:super_editor/src/default_editor/document_ime/supereditor_ime_interactor.dart:348:23)
#4      SuperEditorImeInteractorState._reportVisualInformationToIme (package:super_editor/src/default_editor/document_ime/supereditor_ime_interactor.dart:300:7)
#5      SuperEditorImeInteractorState._reportVisualInformationToIme.<anonymous closure> (package:super_editor/src/default_editor/document_ime/supereditor_ime_interactor.dart:309:24)
#6      Frames.onNextFrame.<anonymous closure> (package:super_editor/src/infrastructure/flutter/flutter_scheduler.dart:72:11)
#7      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1397:15)
#8      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1331:11)
#9      AutomatedTestWidgetsFlutterBinding.pump.<anonymous closure> (package:flutter_test/src/binding.dart:1288:9)
#12     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:74:41)
#13     AutomatedTestWidgetsFlutterBinding.pump (package:flutter_test/src/binding.dart:1275:27)
#14     WidgetTester.pumpAndSettle.<anonymous closure> (package:flutter_test/src/widget_tester.dart:726:23)
#17     TestAsyncUtils.guard (package:flutter_test/src/test_async_utils.dart:74:41)
#18     WidgetTester.pumpAndSettle (package:flutter_test/src/widget_tester.dart:719:27)
#19     KeyboardInput.pressDelete (package:flutter_test_robots/src/keyboard.dart:279:11)
<asynchronous suspension>
#20     main.<anonymous closure>.<anonymous closure>.<anonymous closure> (file:///Users/miguel/Documents/GitHub/super_editor/super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart:2004:11)
<asynchronous suspension>
#21     testWidgetsOnMac.<anonymous closure> (package:flutter_test_runners/src/platform_runners.dart:96:7)
<asynchronous suspension>
#22     testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:189:15)
<asynchronous suspension>
#23     TestWidgetsFlutterBinding._runTestBody (package:flutter_test/src/binding.dart:1032:5)
<asynchronous suspension>
<asynchronous suspension>
(elided 5 frames from dart:async and package:stack_trace)
════════════════════════════════════════════════════════════════════════════════════════════════════
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following message was thrown:
Multiple exceptions (4) were detected during the running of the current test, and at least one was
unexpected.
════════════════════════════════════════════════════════════════════════════════════════════════════
 ```

</details>

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor] Fix crashing when deleting all content which contains a non-deletable node at an edge. Resolves #2393

When all content in the document is selected using CMD+A and then pressing delete or backspace, it will throw exceptions if there is a non-deletable node at the start and/or end of the document.

When the user attempts to delete all content, `SuperEditor` inserts a new empty paragraph at the first deleted node's index and with the first deleted node's id, and places the caret on it. 

When a non-deletable node is at the beginning or end of the selection, it was breaking this logic. We were not inserting a new empty paragraph and we were trying to place a text selection for a block node.

This PR fixes this issue by also inserting a new empty paragraph when all deletable nodes were deleted and choosing the id of the existing `TextNode` to place the selection.

### CODE REVIEW

File: super_editor/lib/src/default_editor/multi_node_editing.dart [hunk 1]
```diff
@@ -786,19 +786,34 @@ class DeleteContentCommand extends EditCommand {
       );
     }
 
+    final wereAllNodesDeleted = document.getNodeById(startNode.id) == null && document.getNodeById(endNode.id) == null;
+    final wereAllDeletableNodesDeleted = document.every(
+      (e) => e is BlockNode && !e.isDeletable,
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/multi_node_editing.dart:791]: Why do the remaining nodes have to be block nodes?

File: super_editor/lib/src/default_editor/multi_node_editing.dart [hunk 2]
```diff
@@ -786,19 +786,34 @@ class DeleteContentCommand extends EditCommand {
...
+    );
+
     // If all selected nodes were deleted, e.g., the user selected from
     // the beginning of the first node to the end of the last node, then
     // we need insert an empty paragraph node so that there's a place
     // to position the caret.
-    if (document.getNodeById(startNode.id) == null && document.getNodeById(endNode.id) == null) {
-      final insertIndex = min(startNodeIndex, endNodeIndex);
+    if (wereAllNodesDeleted || wereAllDeletableNodesDeleted) {
+      // When we have non-deletable nodes and all deletable nodes were deleted,
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/multi_node_editing.dart:799]: This comment says "When we have non-deletable nodes..." but I don't see that condition evaluated. I just see `wereAllDeletableNodesDeleted` but that doesn't imply the existence of of non-deletable nodes, does it? If it does, I think it has the wrong name. All deletable nodes can be deleted regardless of whether we have non-deletable nodes, or not.

File: super_editor/lib/src/default_editor/multi_node_editing.dart [hunk 3]
```diff
@@ -786,19 +786,34 @@ class DeleteContentCommand extends EditCommand {
...
+      // insert the new node at the end of the document.
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/multi_node_editing.dart:800]: Please include in the comment what we're doing when the first statement isn't true. For example, I don't immediately see why `min(startNodeIndex, endNodeIndex)` is there...

File: super_editor/lib/src/default_editor/multi_node_editing.dart [hunk 4]
```diff
@@ -786,19 +786,34 @@ class DeleteContentCommand extends EditCommand {
...
+      final insertIndex = wereAllDeletableNodesDeleted //
+          ? document.nodeCount
+          : min(startNodeIndex, endNodeIndex);
+
+      // Pick the deletable node id as the id for the new paragraph.
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/multi_node_editing.dart:805]: Rather than say we're picking an ID, which is fairly obvious, please describe what policy you're implementing to select the ID. I see that this policy involves block nodes vs non-block nodes, deletable vs non-deletable, and selects the start vs the end. It's unclear what any of these details mean in terms of your intent.

File: super_editor/lib/src/default_editor/multi_node_editing.dart [hunk 5]
```diff
@@ -786,19 +786,34 @@ class DeleteContentCommand extends EditCommand {
...
+      final newId = (startNode is BlockNode && !startNode.isDeletable) //
+          ? endNode.id
+          : startNode.id;
+
       document.insertNodeAt(
         insertIndex,
-        ParagraphNode(id: startNode.id, text: AttributedText()),
+        ParagraphNode(id: newId, text: AttributedText()),
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/multi_node_editing.dart:812]: Maybe we should call it `emptyParagraphId` instead of `newId` to be clear why we created it.

File: super_editor/test/super_editor/supereditor_undeletable_content_test.dart [hunk 6]
```diff
@@ -695,6 +696,140 @@ void main() {
...
+            DocumentSelection.collapsed(
+              position: DocumentPosition(
+                nodeId: document.last.id,
+                nodePosition: const TextNodePosition(offset: 0),
+              ),
+            ),
+          );
+        });
+
+        testWidgetsOnDesktop('when the whole document is selected and ends with a non-deletable node', (tester) async {
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_undeletable_content_test.dart:768]: What about when the document begins AND ends with non-deletable nodes?

What about when the document ONLY contains non-deletable nodes?

File: super_editor/test/super_editor/supereditor_undeletable_content_test.dart [hunk 7]
```diff
@@ -1610,6 +1879,162 @@ void main() {
...
+                    ),
+                  ],
+                ),
+              )
+              .pump();
+
+          // Place the caret at the beginning of the paragraph.
+          await tester.placeCaretInParagraph("2", 0);
+
+          // Select the whole content.
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_undeletable_content_test.dart:1904]: Can we trigger select all using a shortcut instead of running a direct manipulation?

Maybe this selection change is related to the purpose of the test? I'm not sure what this test is verifying that isn't already verified by the other two similar tests..

File: super_editor/lib/src/default_editor/multi_node_editing.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/multi_node_editing.dart]: Updated.

File: super_editor/lib/src/default_editor/multi_node_editing.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/multi_node_editing.dart]: The `min(startNodeIndex, endNodeIndex)` was there before, but it's unnecessary because the range is normalized. Updated.

File: super_editor/lib/src/default_editor/multi_node_editing.dart (hunk 4 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/multi_node_editing.dart]: Updated.

File: super_editor/lib/src/default_editor/common_editor_operations.dart [hunk 8]
```diff
@@ -1381,13 +1382,15 @@ class CommonEditorOperations {
   /// Returns the [DocumentPosition] where the caret should sit after deleting
   /// the given [selection] from the given [document].
   ///
+  /// Returns `null` if there are no deletable nodes the [selection].
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/common_editor_operations.dart:1385]: "no deletable nodes the [selection]" -> "no deletable nodes within the [selection]".

File: super_editor/lib/src/default_editor/multi_node_editing.dart [hunk 9]
```diff
@@ -786,19 +789,42 @@ class DeleteContentCommand extends EditCommand {
       );
     }
 
+    final wereAllNodesInRangeDeleted =
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/multi_node_editing.dart:792]: I'm not sure how this name matches the check. You're checking if the first and last were deleted - but why does that mean that a node in between those two was also deleted?

File: super_editor/lib/src/default_editor/multi_node_editing.dart [hunk 10]
```diff
@@ -786,19 +789,42 @@ class DeleteContentCommand extends EditCommand {
...
+        document.getNodeById(startNode.id) == null && document.getNodeById(endNode.id) == null;
+    final wereAllDeletableNodesDeleted = nodes.every(
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/multi_node_editing.dart:794]: Lets' call this `wereAllDeletableNodesInRangeDeleted` so that it's not confused with document-wide statements.

File: super_editor/lib/src/default_editor/multi_node_editing.dart [hunk 11]
```diff
@@ -786,19 +789,42 @@ class DeleteContentCommand extends EditCommand {
...
+      (node) => document.getNodeById(node.id) == null || !node.isDeletable,
+    );
+    final hasNonDeletableNodes = nodes.any((node) => !node.isDeletable);
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/multi_node_editing.dart:797]: Let's call this `hasNonDeletableNodesInRange`.

File: super_editor/lib/src/default_editor/multi_node_editing.dart [hunk 12]
```diff
@@ -1144,12 +1170,12 @@ class DeleteSelectionCommand extends EditCommand {
       }
     }
 
-    final newSelectionPosition = CommonEditorOperations.getDocumentPositionAfterExpandedDeletion(
-      document: document,
-      selection: selection,
-    );
-
     final nodes = document.getNodesInside(selection.start, selection.end);
+    if (nodes.every((node) => !node.isDeletable)) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/multi_node_editing.dart:1174]: Don't we already have this condition stored in a variable from above? Or is this outside the earlier scope?

File: super_editor/lib/src/default_editor/multi_node_editing.dart (hunk 9 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/multi_node_editing.dart:792]: Looking at this again, we probably just need `wereAllNodesInRangeDeleted`.

File: super_editor/lib/src/default_editor/multi_node_editing.dart (hunk 12 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/multi_node_editing.dart:1172]: This is another command.

**Review by matthew-carroll — APPROVED** [review]
LGTM
