### PR TITLE
[SuperEditor] Fix markdown sublist deserialization (Resolves #1821) (Resolves #1822)

### LINKED ISSUE #1821: Markdown list parsing (using `deserializeMarkdownDocument`) is not working as expected with multiple-level lists
**Package Version**
I am on the stable branch. I also just checked to be using the last commit (`c69abd`)

**To Reproduce**
1. Copy this string: 
```
final string_test = """
To create an outline using multiple levels of lists for the uploaded document, it appears we have the introductory sections of a chapter on quantum mechanics, specifically the following main points can be outlined:

1. Introduction to quantum mechanics
   - Study of physics at small length scales
   - Quantum vs. classical mechanics
   - Schrodinger equation and wave properties of particles
   - Application of quantum mechanics and philosophical questions

2. Chapter outline
   - Section 10.1: Brief history of quantum mechanics
   - Section 10.2: Schrodinger wave equation
   - Section 10.3: Examples with analogies to earlier systems
   - Section 10.4: Uncertainty principle

3. 10.1 A brief history
   - 1900: Planck's introduction of energy quantization
   - 1905: Einstein's photon hypothesis and work on photoelectric effect
   - 1913: Bohr's model of the atom with electron wave properties
   - 1924: de Broglie's wave-particle duality proposal
   - 1925: Heisenberg's matrix mechanics
   - 1926: Schrodinger's wave mechanics

Each point corresponds to a section or a significant idea presented in the text so far. Shall I continue scrolling to expand on this outline?
""";
```

(here is the string printed using `jsonEncode`, might be useful):

```
To create an outline using multiple levels of lists for the uploaded document, it appears we have the introductory sections of a chapter on quantum mechanics, specifically the following main points can be outlined:\n\n1. Introduction to quantum mechanics\n   - Study of physics at small length scales\n   - Quantum vs. classical mechanics\n   - Schrodinger equation and wave properties of particles\n   - Application of quantum mechanics and philosophical questions\n\n2. Chapter outline\n   - Section 10.1: Brief history of quantum mechanics\n   - Section 10.2: Schrodinger wave equation\n   - Section 10.3: Examples with analogies to earlier systems\n   - Section 10.4: Uncertainty principle\n\n3. 10.1 A brief history\n   - 1900: Planck's introduction of energy quantization\n   - 1905: Einstein's photon hypothesis and work on photoelectric effect\n   - 1913: Bohr's model of the atom with electron wave properties\n   - 1924: de Broglie's wave-particle duality proposal\n   - 1925: Heisenberg's matrix mechanics\n   - 1926: Schrodinger's wave mechanics\n\nEach point corresponds to a section or a significant idea presented in the text so far. Shall I continue scrolling to expand on this outline?
```

2. Parse the string using `deserializeMarkdownToDocument`:

```
final doc = deserializeMarkdownToDocument(string_test)
```

4. See the parsing issues

**Actual behavior**
The resulting document looks like this:
image

There are a couple problems that happen when parsing strings with multiple levels:

- [ ] The numbered lists are not correctly numbered.
- [ ] Some texts are repeated
- [ ] Some nodes that should be bullet points, are copied as text nodes

These issues might be related to #1711 

**Expected behavior**
The text should look like this:

---

To create an outline using multiple levels of lists for the uploaded document, it appears we have the introductory sections of a chapter on quantum mechanics, specifically the following main points can be outlined:

1. Introduction to quantum mechanics
   - Study of physics at small length scales
   - Quantum vs. classical mechanics
   - Schrodinger equation and wave properties of particles
   - Application of quantum mechanics and philosophical questions

2. Chapter outline
   - Section 10.1: Brief history of quantum mechanics
   - Section 10.2: Schrodinger wave equation
   - Section 10.3: Examples with analogies to earlier systems
   - Section 10.4: Uncertainty principle

3. 10.1 A brief history
   - 1900: Planck's introduction of energy quantization
   - 1905: Einstein's photon hypothesis and work on photoelectric effect
   - 1913: Bohr's model of the atom with electron wave properties
   - 1924: de Broglie's wave-particle duality proposal
   - 1925: Heisenberg's matrix mechanics
   - 1926: Schrodinger's wave mechanics

Each point corresponds to a section or a significant idea presented in the text so far. Shall I continue scrolling to expand on this outline?

---

**Platform**
I am on flutter web, on a MacOS. I am using Chrome.

**Flutter version**
```
Flutter 3.16.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2e9cb0aa71 (6 weeks ago) • 2023-12-11 14:35:13 -0700
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
```

### LINKED ISSUE #1822: When parsing an empty sublist, `deserializeMarkdownToDocument` makes everything crash (probably because of an infinite loop)
**Package Version**
I am on the stable branch. I also just checked to be using the last commit (c69abd)

**To Reproduce**
1. Copy this string:

```
final test_string = """- hey there friend
    - """;
```

2. Run `deserializeMarkdownToDocument(test_string)`
3. Armageddon 💥

**Actual behavior**
The whole flutter app crashes. Probably due to an infinite loop

**Expected behavior**
The string should be parsed as this: (just without the dot on the sub list)

---

- hey there friend
     - .

---

**Platform**
I am on flutter web, on a MacOS. I am using Chrome.

**Flutter version**
```
Flutter 3.16.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2e9cb0aa71 (6 weeks ago) • 2023-12-11 14:35:13 -0700
Engine • revision 54a7145303
Tools • Dart 3.2.3 • DevTools 2.28.4
```

**Additional context**
- #1711 and #1821 might be related

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor] Fix markdown sublist deserialization. Resolves #1821, Resolves #1822 

We still have some issues with our list item markdown parsing:

1. The following  input causes an infinite loop:

```
- hey there friend
    - 
```

2. Parsing list with sublist still produces incorrect results. Parsing the following input produces the document of the screenshot:
 
```

final string_test = """
To create an outline using multiple levels of lists for the uploaded document, it appears we have the introductory sections of a chapter on quantum mechanics, specifically the following main points can be outlined:

1. Introduction to quantum mechanics
   - Study of physics at small length scales
   - Quantum vs. classical mechanics
   - Schrodinger equation and wave properties of particles
   - Application of quantum mechanics and philosophical questions

2. Chapter outline
   - Section 10.1: Brief history of quantum mechanics
   - Section 10.2: Schrodinger wave equation
   - Section 10.3: Examples with analogies to earlier systems
   - Section 10.4: Uncertainty principle

3. 10.1 A brief history
   - 1900: Planck's introduction of energy quantization
   - 1905: Einstein's photon hypothesis and work on photoelectric effect
   - 1913: Bohr's model of the atom with electron wave properties
   - 1924: de Broglie's wave-particle duality proposal
   - 1925: Heisenberg's matrix mechanics
   - 1926: Schrodinger's wave mechanics

Each point corresponds to a section or a significant idea presented in the text so far. Shall I continue scrolling to expand on this outline?

```

image

Also, when an ordered list has an unordered sublist, each item of the ordered list resets is number to 1.

- The infinite loop is caused by our `_EmptyLinePreservingParagraphSyntax`. It always returns `true` when there isn't a block parser that can parse the current input. However, there is situations were it returns `true`, but when its `parse` method is called it returns `null`. For example, when the current input is empty. This is the cause of the infinity loop, we are saying we can parse the input, but it turns out we can't. The infinite loop happens inside the markdown package code. This PR fixes that.

- The sublist issue happens because it seems we are still not handling the list item's children correctly. The list item might have child elements that we need to visit before adding the list node to the document. This PR changes the list item handling to avoid directly adding the list item to the document the moment we visit it, if it has child elements. Instead, we keep track that we are visiting a list item and add the list to the document when we visit the list item's child.

- The list numbering issue happens because we compute the list item number, we stop if we find an unordered list. This PR changes that to continue counting.

### CODE REVIEW

File: super_editor/test/super_editor/components/list_items_test.dart [hunk 1]
```diff
@@ -427,6 +427,98 @@ void main() {
...
+        expect(context.document.nodes[3], isA<ListItemNode>());
+        expect((context.document.nodes[3] as ListItemNode).type, ListItemType.ordered);
+
+        expect(context.document.nodes[4], isA<ListItemNode>());
+        expect((context.document.nodes[4] as ListItemNode).type, ListItemType.unordered);
+
+        expect(context.document.nodes[5], isA<ListItemNode>());
+        expect((context.document.nodes[5] as ListItemNode).type, ListItemType.unordered);
+
+        // Ensure the sequence was kept.
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/components/list_items_test.dart:464]: Can't you check sequencing and indent through the document nodes rather than involving the UI?

File: super_editor_markdown/lib/src/markdown_to_document_parsing.dart [hunk 2]
```diff
@@ -85,6 +85,17 @@ class _MarkdownToDocument implements md.NodeVisitor {
 
   final _listItemTypeStack = <ListItemType>[];
 
+  /// The count of the list items currently being visited.
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown_to_document_parsing.dart:88]: I think we need a better comment here. I can't provide a suggestion because the phrasing of this comment requires enough implicit knowledge of the parsing process that I don't really know what it's trying to describe.

File: super_editor_markdown/lib/src/markdown_to_document_parsing.dart [hunk 3]
```diff
@@ -590,7 +617,26 @@ class _EmptyLinePreservingParagraphSyntax extends md.BlockSyntax {
...
+    }
+
+    if (parser.current.isEmpty) {
+      // We consider this input to be a separator between blocks because
+      // it started with an empty line. We want to parse this input.
+      return true;
+    }
+
+    if (_isAtParagraphEnd(parser, ignoreEmptyBlocks: _endsWithHardLineBreak(parser.current))) {
+      // Ths input is at the end of a paragraph. Let other parsers run.
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown_to_document_parsing.dart:633]: Please specify why the end of a paragraph is some kind of special case. it isn't obvious why the end of a paragraph would be different from the end of anything else. It's also not clear what "end of a paragraph" means in a block parser.

File: super_editor_markdown/test/super_editor_markdown_test.dart [hunk 4]
```diff
@@ -1130,6 +1130,68 @@ This is some code
         expect((document.nodes.first as ListItemNode).text.text, isEmpty);
       });
 
+      test('unordered list followd by empty list item', () {
+        const markdown = """- list item 1
+    - """;
+
+        final document = deserializeMarkdownToDocument(markdown);
+
+        expect(document.nodes.length, 1);
```
Comment (matthew-carroll) [inline super_editor_markdown/test/super_editor_markdown_test.dart:1139]: Is this the correct expectation? Why don't we have a second, empty list item?

File: super_editor_markdown/test/super_editor_markdown_test.dart [hunk 5]
```diff
@@ -1130,6 +1130,68 @@ This is some code
...
+
+        expect(document.nodes[0], isA<ListItemNode>());
+        expect((document.nodes[0] as ListItemNode).type, ListItemType.unordered);
+        expect((document.nodes[0] as ListItemNode).text.text, 'list item 1');
+      });
+
+      test('parses mixed unordered and ordered items', () {
```
Comment (matthew-carroll) [inline super_editor_markdown/test/super_editor_markdown_test.dart:1146]: Isn't this already tested in the other test suite?

File: super_editor/test/super_editor/components/list_items_test.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/components/list_items_test.dart:464]: We can check the indent through the document node, but the sequencing is only resolved at the UI level...

File: super_editor_markdown/lib/src/markdown_to_document_parsing.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown_to_document_parsing.dart:633]: Basically it means that another parser wants to parse this input. We have a dart doc for `_isAtParagraphEnd` that says:

```dart
/// Checks if the current line ends a paragraph by verifying if another
/// block syntax can parse the current input.
///
/// An empty line ends the paragraph, unless [ignoreEmptyBlocks] is `true`.
```

File: super_editor_markdown/lib/src/markdown_to_document_parsing.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown_to_document_parsing.dart:88]: I tried to improve it a little bit.

File: super_editor_markdown/test/super_editor_markdown_test.dart (hunk 4 above)
Comment (angelosilvestre) [reply super_editor_markdown/test/super_editor_markdown_test.dart:1139]: Most parsers I tried consider the second `-` as a syntax to apply the "header 2" style to the list node. Currently, we set "listItem" as the block type  in the list item metadata, so we can't currently apply this to the node. That's why I'm just ignoring the second `-`.

File: super_editor_markdown/test/super_editor_markdown_test.dart (hunk 5 above)
Comment (angelosilvestre) [reply super_editor_markdown/test/super_editor_markdown_test.dart:1146]: We have a test that checks multiple levels of lists with this input:

```

- Level 1
   1. Level 2
      1. Level 3
         - Sublevel 1         
         - Sublevel 2
      2. Level 3 again
   2. Level 2 returning
2. Level 1 once more
   - Bullet list
     - Another bullet
- Main bullet list
   - Sub bullet list
      - Subsub bullet list
```

The new test has a single level of ordered and unordered lists. I think we probably should keep it.

File: super_editor/test/super_editor/components/list_items_test.dart (hunk 1 above)
Comment (matthew-carroll) [reply super_editor/test/super_editor/components/list_items_test.dart:464]: What do you mean by sequencing?

File: super_editor_markdown/lib/src/markdown_to_document_parsing.dart (hunk 3 above)
Comment (matthew-carroll) [reply super_editor_markdown/lib/src/markdown_to_document_parsing.dart]: Unfortunately, that other comment isn't clear at all either. I still don't know what the phrase means.

"Checks if the current line ends a paragraph" - meaning what? Is this referring to the possibility that someone inserted a single newline in Markdown, which is supposed to be interpreted as part of paragraph above it? That comment is missing an explanation of surrounding context to help frame what it's stating...

For `_isAtParagraphEnd` - does it mean that we're pulling pieces of text out of a block and we've reached the end of block text? I don't get it...

File: super_editor_markdown/test/super_editor_markdown_test.dart (hunk 4 above)
Comment (matthew-carroll) [reply super_editor_markdown/test/super_editor_markdown_test.dart:1139]: Why would a trailing `-` be considered a "header 2" style that applies to the list item above it? That doesn't seem to make sense.

File: super_editor_markdown/test/super_editor_markdown_test.dart (hunk 5 above)
Comment (matthew-carroll) [reply super_editor_markdown/test/super_editor_markdown_test.dart:1146]: Please be specific - I don't know which test is "we have a test" and which is "the new test". There's another test in this PR that seemed to verify a very similar structure. It would seem that both tests are "new tests" so I don't know what exactly you're referencing here. Did you not already create a multi level list structure in another test in this PR?

File: super_editor_markdown/test/super_editor_markdown_test.dart (hunk 4 above)
Comment (angelosilvestre) [reply super_editor_markdown/test/super_editor_markdown_test.dart:1139]: I agree it doesn't seem to make sense, but this is how the markdown package parse it:

If you paste the following input the markdown package will interpret a header:

```
- list item 1
   - 
```

Captura de Tela 2024-02-07 às 20 36 46

Looking at the markdown spec, the trailing `-` seems to be considered a setext heading: 


> A [setext heading underline](https://spec.commonmark.org/0.31.2/#setext-heading-underline) is a sequence of = characters or a sequence of - characters, with no more than 3 spaces of indentation and any number of trailing spaces or tabs.
> 
> The heading is a level 1 heading if = characters are used in the [setext heading underline](https://spec.commonmark.org/0.31.2/#setext-heading-underline), and a level 2 heading if - characters are used. The contents of the heading are the result of parsing the preceding lines of text as CommonMark inline content.

Source: https://spec.commonmark.org/0.31.2/#setext-headings

We should probably mention the setext heading in that text description.

File: super_editor/test/super_editor/components/list_items_test.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/components/list_items_test.dart:464]: I mean the ordinal value of each list item. When we parse a ordered list like the following:

```
1. First
2. Second
3. Third
```

We don't store the list item number in the document node (maybe we should). We resolve it when build the viewModel by walking backwards counting the number of ordered list items before the current node.

File: super_editor_markdown/lib/src/markdown_to_document_parsing.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown_to_document_parsing.dart]: Currently, that are three possibilities to end a paragraph:

1. We are at the end of the input.
2. Another block syntax is able to parse the current input.
3. The current line is an empty line, except if the previous line ends with a hard line break (ends with two or more spaces).

That's what we are checking.

File: super_editor_markdown/test/super_editor_markdown_test.dart (hunk 5 above)
Comment (angelosilvestre) [reply super_editor_markdown/test/super_editor_markdown_test.dart:1146]: The existing test parses the input I posted on the previous comment on this thread. This PR adds a new test that parses the following input:

```
1. Ordered 1
   - Unordered 1
   - Unordered 2

2. Ordered 2
   - Unordered 1
   - Unordered 2

3. Ordered 3
   - Unordered 1
   - Unordered 2
 ```

This input wasn't being handled correctly with our current parsing implementation.

File: super_editor_markdown/lib/src/markdown_to_document_parsing.dart (hunk 3 above)
Comment (matthew-carroll) [reply super_editor_markdown/lib/src/markdown_to_document_parsing.dart]: What's "input"?

File: super_editor_markdown/test/super_editor_markdown_test.dart (hunk 5 above)
Comment (matthew-carroll) [reply super_editor_markdown/test/super_editor_markdown_test.dart:1146]: Like I said in the comment above, I don't know what "the existing test" is, nor am I asking about an existing test. This PR includes a number of NEW tests. A couple of them look very similar, so the question is whether or not they need to be separate tests or if one test is sufficient.

Here is one of those new tests: super_editor/test/super_editor/components/list_items_test.dart

Here is another new test: super_editor_markdown/test/super_editor_markdown_test.dart

I see two tests that are parsing a multi-level mixed list. Those test are fairly long. Do we need both tests? Or would one test suffice equally well for both cases?

Comment (angelosilvestre) [reply super_editor_markdown/test/super_editor_markdown_test.dart:1146]: After looking into this again, the test in `super_editor_markdown_test.dart` is a dart test and the one in `list_items_test.dart` is a Flutter test, because we need to look into the document component to query the list item ordinal.

Although both tests parse a document from markdown, the `list_items_test.dart` isn't testing any markdown parsing logic. I think both tests should be kept.

File: super_editor_markdown/lib/src/markdown_to_document_parsing.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown_to_document_parsing.dart]: > What's "input"?

The markdown that we are parsing.

**Review by matthew-carroll — APPROVED** [review]
LGTM
