### PR TITLE
[SuperEditor] Fix caret misplaced when indenting a list item (Resolves #777)

### LINKED ISSUE #777: Caret misplaced when the indentation of a list item (ordered or unordered) changes
Steps to reproduce:
* Create a list item node (unordered or ordered)
* Press TAB

Expected: List item node gets indented and caret moves to the new start position of the node
Actual: List item node gets indented but the caret remains in the old position

https://user-images.githubusercontent.com/31278849/189396028-a9233274-6be3-47a5-ad53-4bd587d3768e.mov

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor] Fix caret misplaced when indenting a list item. Resolves #777

When indenting or unindenting a list item via keyboard (pressing tab/backspace) the node gets indented but the caret remains in the old position, as seen in the video: 

https://user-images.githubusercontent.com/31278849/189396028-a9233274-6be3-47a5-ad53-4bd587d3768e.mov

The issue happens because `CaretDocumentOverlay` isn't being notified that something changed, as it only listens for selection changes.

This PR changes `CaretDocumentOverlay` to update the caret on all document changes.

### CODE REVIEW

File: super_editor/test/src/default_editor/list_items_test.dart [hunk 1]
```diff
@@ -233,6 +237,142 @@ void main() {
...
+        );
+
+        // Ensure the list indentation was actually performed.
+        expect(computedOffsetAfterIndent.dx, greaterThan(caretOffsetBeforeIndent.dx));
+
+        // Find the offset at which the caret is currently being displayed.
+        final caretOffsetAfterIndent = SuperEditorInspector.findCaretOffsetInDocument();
+
+        // Ensure the caret is being displayed at the correct position.
+        expect(caretOffsetAfterIndent, offsetMoreOrLessEquals(computedOffsetAfterIndent));
```
Comment (matthew-carroll) [inline super_editor/test/src/default_editor/list_items_test.dart:271]: Doesn't this 2nd expectation make the first expectation redundant? Also, it doesn't look like you need to place the caret offset in a variable. You can just call `SuperEditorInspector.findCaretOffsetInDocument()` where you need it.

File: super_editor/test/src/default_editor/list_items_test.dart [hunk 2]
```diff
@@ -233,6 +237,142 @@ void main() {
...
+        );
+
+        // Ensure the list indentation was actually performed.
+        expect(computedOffsetAfterUnindent.dx, lessThan(caretOffsetBeforeUnindent.dx));
+
+        // Find the offset at which the caret is currently being displayed.
+        final caretOffsetAfterUnindent = SuperEditorInspector.findCaretOffsetInDocument();
+
+        // Ensure the caret is being displayed at the correct position.
+        expect(caretOffsetAfterUnindent, offsetMoreOrLessEquals(computedOffsetAfterUnindent));
```
Comment (matthew-carroll) [inline super_editor/test/src/default_editor/list_items_test.dart:306]: Same comments here, and possibly elsewhere, as mentioned in the first test.

File: super_editor/lib/src/default_editor/document_caret_overlay.dart [hunk 3]
```diff
@@ -35,6 +41,7 @@ class _CaretDocumentOverlayState extends State<CaretDocumentOverlay> with Single
   void initState() {
     super.initState();
     widget.composer.selectionNotifier.addListener(_onSelectionChange);
+    widget.document.addListener(_onSelectionChange);
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_caret_overlay.dart:44]: We shouldn't call a method called `_onSelectionChange` when the document changes. A document change is not a selection change. Please rename the method accordingly.

File: super_editor/lib/src/default_editor/document_caret_overlay.dart [hunk 4]
```diff
@@ -19,6 +22,9 @@ class CaretDocumentOverlay extends StatefulWidget {
   /// that the current selection can be mapped to an (x,y) offset and a height.
   final DocumentLayout Function() documentLayoutResolver;
 
+  /// The editor's [Document].
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_caret_overlay.dart:25]: Please add an explanation about why we need to listen to document changes. It's not obvious why a `Document` is needed.

File: super_editor/test/src/default_editor/list_items_test.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/test/src/default_editor/list_items_test.dart:271]: The first expectation is to ensure that pressing tab actually indented the list. Without this expectation, if for some reason pressing tab didn't indent the list, the test will still pass.

File: super_editor/lib/src/default_editor/document_caret_overlay.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_caret_overlay.dart:44]: Method renamed.

File: super_editor/lib/src/default_editor/document_caret_overlay.dart (hunk 4 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_caret_overlay.dart:25]: Added a dart doc.

**Review by matthew-carroll — APPROVED** [review]
LGTM
