### PR TITLE
[SuperEditor][Web] Fix crash when merging paragraphs (Resolves #1921)

### LINKED ISSUE #1921: Crash when removing the line on chrome
**Package Version**
super_editor, GitHub, stable branch

**To Reproduce**
1. Run the demo app on chrome
2. Position the caret before 'Ready-made solutions'
3. Click backspace to merge the text with pervious text block. First click removes the styling, second moves the caret to previous line but does not merge the blocks
5. See error
6. From now on editor is unresponsive to input and crashes on selection

**Actual behavior**
It's not possible to remove a line when placing a caret in front of the line

**Expected behavior**
It should be possible to remove the line and join it with the line above.

**Platform**
Running Web on Chrome 123.0.6312.106

**Flutter version**
Flutter 3.19.1 • channel stable
Dart 3.3.0 

**Comments**
On Mac app and iOS app it behaves correctly

**Screenshots**

https://github.com/superlistapp/super_editor/assets/13262745/7ebac03a-bef9-4457-ad94-36fb9f93b7a7

**Logs**

```
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════


The following TypeErrorImpl was thrown during method call


TextInputClient.updateEditingStateWithDeltas:


Unexpected null value.





When the exception was thrown, this was the stack:


dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3                  throw_


dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 806:18             nullCheck


packages/super_editor/src/default_editor/document_ime/document_serialization.dart 259:71     [_imeToDocumentPosition]


packages/super_editor/src/default_editor/document_ime/document_serialization.dart 218:14     imeToDocumentRange


packages/super_editor/src/default_editor/document_ime/document_delta_editing.dart 639:29     [_calculateNewComposingRegion]


packages/super_editor/src/default_editor/document_ime/document_delta_editing.dart 102:41     applyDeltas


packages/super_editor/src/default_editor/document_ime/document_ime_communication.dart 219:5  updateEditingValueWithDeltas


packages/super_editor/src/default_editor/document_ime/ime_decoration.dart 124:14             updateEditingValueWithDeltas


packages/flutter/src/services/text_input.dart 1876:10                                        _handleTextInputInvocation


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                           runBody


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                           _async


packages/flutter/src/services/text_input.dart 1780:45                                        [_handleTextInputInvocation]


packages/flutter/src/services/text_input.dart 1765:20                                        _loudlyHandleTextInputInvocation


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                           runBody


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                           _async


packages/flutter/src/services/text_input.dart 1763:51                                        [_loudlyHandleTextInputInvocation]


packages/flutter/src/services/platform_channel.dart 571:55                                   _handleAsMethodCall


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                           runBody

dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                           _async


packages/flutter/src/services/platform_channel.dart 568:40                                   [_handleAsMethodCall]


packages/flutter/src/services/platform_channel.dart 564:34                                   <fn>


packages/flutter/src/services/binding.dart 603:35                                            <fn>


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                           runBody


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                           _async


packages/flutter/src/services/binding.dart 600:98                                            <fn>


lib/_engine/engine/platform_dispatcher.dart 1377:5                                           invoke2


lib/ui/channel_buffers.dart 25:12                                                            invoke


lib/ui/channel_buffers.dart 65:7                                                             push


lib/ui/channel_buffers.dart 131:16                                                           push


lib/_engine/engine/platform_dispatcher.dart 421:10                                           invokeOnPlatformMessage


lib/_engine/engine/text_editing/text_editing.dart 2206:30                                    updateEditingStateWithDelta


lib/_engine/engine/text_editing/text_editing.dart 2313:11                                    <fn>


lib/_engine/engine/text_editing/text_editing.dart 1400:7                                     handleChange


dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37             _checkAndCall


dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39             dcall





call:


  MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{oldText: . Now, you're off


  to the races! SuperEditor renders your document, and lets you select, insert, and delete content.,


  deltaText: , deltaStart: 1, deltaEnd: 2, selectionBase: 1, selectionExtent: 1, composingBase: -1,


  composingExtent: -1}]}])


════════════════════════════════════════════════════════════════════════════════════════════════════


Another exception was thrown: Unexpected null value.


Error: Exception: No such position in document: [DocumentPosition] - node: "01d0caa8-3a69-4346-9c5a-d7d7da999166", position: (TextNodePosition(offset: 0, affinity: TextAffinity.downstream))


dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 297:3                        throw_


packages/super_editor/src/core/editor.dart 593:7                                                   getNodesInside


packages/super_editor/src/default_editor/layout_single_column/_styler_composing_region.dart 77:48  [_applyComposingRegion]


packages/super_editor/src/default_editor/layout_single_column/_styler_composing_region.dart 53:11  <fn>


packages/super_editor/src/default_editor/layout_single_column/_styler_composing_region.dart 53:82  style


packages/super_editor/src/default_editor/layout_single_column/_presenter.dart 190:33               [_createNewViewModel]


packages/super_editor/src/default_editor/layout_single_column/_presenter.dart 148:18               updateViewModel


packages/super_editor/src/default_editor/layout_single_column/_layout.dart 111:12                  _onPresenterMarkedDirty


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                 runBody


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                                 _async


packages/super_editor/src/default_editor/layout_single_column/_layout.dart 109:39                  [_onPresenterMarkedDirty]


packages/super_editor/src/default_editor/layout_single_column/_presenter.dart 339:30               onPresenterMarkedDirty


packages/super_editor/src/default_editor/layout_single_column/_presenter.dart 97:17                [_onDocumentChange]


packages/super_editor/src/core/editor.dart 747:7                                                   onTransactionEnd


packages/super_editor/src/core/editor.dart 168:19                                                  execute


packages/super_editor/src/default_editor/document_ime/document_delta_editing.dart 405:7            delete


packages/super_editor/src/default_editor/document_ime/document_delta_editing.dart 251:5            [_applyDeletion]


packages/super_editor/src/default_editor/document_ime/document_delta_editing.dart 85:9             applyDeltas


packages/super_editor/src/default_editor/document_ime/document_ime_communication.dart 219:5        updateEditingValueWithDeltas


packages/super_editor/src/default_editor/document_ime/ime_decoration.dart 124:14                   updateEditingValueWithDeltas


packages/flutter/src/services/text_input.dart 1876:10                                              _handleTextInputInvocation


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                 runBody


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                                 _async


packages/flutter/src/services/text_input.dart 1780:45                                              [_handleTextInputInvocation]


packages/flutter/src/services/text_input.dart 1765:20                                              _loudlyHandleTextInputInvocation


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                 runBody


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                                 _async


packages/flutter/src/services/text_input.dart 1763:51                                              [_loudlyHandleTextInputInvocation]


packages/flutter/src/services/platform_channel.dart 571:55                                         _handleAsMethodCall


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                 runBody


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                                 _async


packages/flutter/src/services/platform_channel.dart 568:40                                         [_handleAsMethodCall]


packages/flutter/src/services/platform_channel.dart 564:34                                         <fn>


packages/flutter/src/services/binding.dart 603:35                                                  <fn>


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                                 runBody


dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                                 _async


packages/flutter/src/services/binding.dart 600:98                                                  <fn>


lib/_engine/engine/platform_dispatcher.dart 1377:5                                                 invoke2


lib/ui/channel_buffers.dart 25:12                                                                  invoke


lib/ui/channel_buffers.dart 65:7                                                                   push


lib/ui/channel_buffers.dart 131:16                                                                 push


lib/_engine/engine/platform_dispatcher.dart 421:10                                                 invokeOnPlatformMessage


lib/_engine/engine/text_editing/text_editing.dart 2206:30                                          updateEditingStateWithDelta


lib/_engine/engine/text_editing/text_editing.dart 2313:11                                          <fn>


lib/_engine/engine/text_editing/text_editing.dart 1400:7                                           handleChange


dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 550:37                   _checkAndCall


dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 555:39                   dcall


Another exception was thrown: Exception: No such document position in the IME content: [DocumentPosition] - node: "01d0caa8-3a69-4346-9c5a-d7d7da999166", position: (TextNodePosition(offset: 0, affinity: TextAffinity.downstream))


```

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][Web] Fix crash when merging paragraphs. Resolves #1921 

When pressing BACKSPACE at the beginning of a paragraph to merge it with the previous paragraph, the following crash happens:

```console
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════


The following TypeErrorImpl was thrown during method call


TextInputClient.updateEditingStateWithDeltas:


Unexpected null value.

```

The issue was introduced in https://github.com/superlistapp/super_editor/pull/1860, where we changed our IME code to adjust the composing region if it was reported on the invisible range.

The root cause is that the `isPositionInsidePlaceholder` method doesn't account for invalid position ( offset of `-1`).

This PR changes `isPositionInsidePlaceholder` to return false for a `-1` offset.

### CODE REVIEW

**Comment by matthew-carroll** [comment]
> The root cause is that the isPositionInsidePlaceholder method doesn't account for invalid position ( offset of -1).

Why are we getting an invalid position?

**Comment by angelosilvestre** [comment]
> Why are we getting an invalid position?

When there is no composing region, `-1` is reported as the offset.

File: super_editor/lib/src/default_editor/document_ime/document_serialization.dart [hunk 1]
```diff
@@ -236,6 +236,12 @@ class DocumentImeSerializer {
       return false;
     }
 
+    if (imePosition.offset <= -1) {
+      // This isn't a valid text position. For example, when a composing region is reported
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/document_serialization.dart:240]: Based on your comment in the conversation, let's be crystal clear with this comment.

```
// The given imePosition might be a selection or a composing region.
// The IME composing position always has a value. When the IME wants
// to describe the absence of a composing region, the offset is set to -1.
// Therefore, this position refers to the absence of a composing region, so
// this position isn't sitting in the placeholder.
```

**Review by matthew-carroll — APPROVED** [review]
LGTM - PS - was this a web-specific issue? If so, why?

**Comment by angelosilvestre** [comment]
This is a web specific issue. The browser IME handles the CMD + LEFT combo to move the caret to the beginning of the line, which caused the problem fixed in https://github.com/superlistapp/super_editor/pull/1860. 

The fix caused the issue fixed by this PR. Because the changes introduced in https://github.com/superlistapp/super_editor/pull/1860 only run on web, only web is affected by this issue.

File: super_editor/lib/src/default_editor/document_ime/document_serialization.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/document_serialization.dart]: Updated.
