### PR TITLE
Make Android IME work when newlines are in deltas list (Resolves #1081)

### LINKED ISSUE #1081: IME Error after insert: Couldn't map an IME position to a document position
We are running into this new issue on the latest stable SE and Flutter.

Repro steps:

1. Enter some text into a new document (a sentence or so)
2. Insert text into the document via `CommonEditorOperations.insertPlainText`
3. Tap and place cursor just before the inserted text, press enter (new line) once
4. Tap and place cursor just after the inserted text (now on a new line), press enter (go to next line) once
5. Attempt to enter additional text into the document, throws with aforementioned error

Logs:

══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. IME position: TextPosition(offset:
80, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack:
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:271:5)
#1      DocumentImeSerializer.imeToDocumentSelection (package:super_editor/src/default_editor/document_ime/document_serialization.dart:164:18)
#2      TextDeltasDocumentEditor._applyNonTextChange (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:180:7)
#3      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:58:9)
#4      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:213:30)
#5      DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:119:14)
#6      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1867:63)
#7      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1753:20)
#8      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:555:55)
#9      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:548:34)
#10     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393:35)
#11     _invoke2.<anonymous closure> (dart:ui/hooks.dart:186:15)
#15     _invoke2 (dart:ui/hooks.dart:185:10)
#16     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#17     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#18     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#19     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
#20     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
(elided 3 frames from dart:async)

call:
  MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{oldText: It works. Now I
  add one prompt and a new line and it breaksWho was your first true friend?
  , deltaText:
  , deltaStart: 79, deltaEnd: 79, selectionBase: 80, selectionExtent: 80, composingBase: -1,
  composingExtent: -1}, {oldText: It works. Now I add one prompt and a new line and it breaks
  Who was your first true friend?
  , deltaText: , deltaStart: -1, deltaEnd: -1, selectionBase: 80, selectionExtent: 80,
  composingBase: -1, composingExtent: -1}, {oldText: It works. Now I add one prompt and a new line and it breaks
  Who was your first true friend?
  , deltaText: , deltaStart: -1, deltaEnd: -1, selectionBase: 80, selectionExtent: 80,
  composingBase: 80, composingExtent: 83}]}])
════════════════════════════════════════════════════════════════════════════════════════════════════
I/TRuntime.CctTransportBackend(24996): Making request to: https://firebaselogging-pa.googleapis.com/v1/firelog/legacy/batchlog
I/TRuntime.CctTransportBackend(24996): Status Code: 200
D/InputMethodManager(24996): showSoftInput() view=io.flutter.embedding.android.FlutterView{6d84cc8 VFED..... .F...... 0,0-1080,2287 #2 aid=1073741824} flags=0 reason=SHOW_SOFT_INPUT
D/InsetsController(24996): show(ime(), fromIme=true)

Another exception was thrown: Exception: Couldn't map an IME position to a document position. IME position: TextPosition(offset: 81, affinity: TextAffinity.downstream)

### PR DESCRIPTION
**Pull request by matthew-carroll**
Make Android IME work when newlines are in deltas list (Resolves #1081)

Our existing IME delta implementation assumes that the overall structure of a `Document` stays consistent through a given list of deltas. In some cases, such as an Android device inserting a newline through deltas (instead of a hardware ENTER button), the structure of the document changes in the middle of the deltas, e.g., a single paragraph becomes two paragraphs.

This PR reworks the IME delta application process so that our internal mapping from `TextEditingValue` ranges, to `Document` ranges, updates itself with each delta, if needed.

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@transcendr can you please try this PR branch on your relevant Android devices and see if the problem has been resolved?

Also, please keep an eye out for any new problems that this PR creates. I had rework a lot of stuff to get to the root of the Android newline issue.

**Comment by transcendr** [comment]
@matthew-carroll incredible, I will run it through its paces and report back.  thanks, so much!

**Comment by matthew-carroll** [comment]
@transcendr thanks for checking. We'll get this in as a hot fix for the existing release on Pub.

File: super_editor/example/lib/main.dart [hunk 1]
```diff
@@ -39,7 +39,7 @@ Future<void> main() async {
   initLoggers(Level.FINEST, {
     // editorScrollingLog,
     // editorGesturesLog,
-    // editorImeLog,
+    editorImeLog,
```
Comment (angelosilvestre) [inline super_editor/example/lib/main.dart:42]: Did you intend to leave this uncommented?

File: super_editor/test/src/default_editor/document_input_ime_test.dart [hunk 2]
```diff
@@ -416,6 +419,158 @@ void main() {
       });
     });
 
+    // Note: Some Android devices report ENTER and BACKSPACE as hardware keys. Other Android
+    //       devices report "\n" insertion and deletion IME deltas, instead.
+    group('on Xiaomi Redmi tablet (Android 12 SP1A)', () {
```
Comment (angelosilvestre) [inline super_editor/test/src/default_editor/document_input_ime_test.dart:424]: Does this device uses GBoard or is it a Xiaomi keyboard? 

Different software keyboards report operations differently. For example, GBoard reports backspaces as deletion deltas while Samsung reports them as hardware keys.

Maybe the keyboard name is more useful than device...

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 3]
```diff
@@ -1,64 +1,85 @@
...
       if (delta is TextEditingDeltaInsertion) {
-        _applyInsertion(delta, serializedDocBeforeDelta);
+        _applyInsertion(delta);
       } else if (delta is TextEditingDeltaReplacement) {
-        _applyReplacement(delta, serializedDocBeforeDelta);
+        _applyReplacement(delta);
       } else if (delta is TextEditingDeltaDeletion) {
-        _applyDeletion(delta, serializedDocBeforeDelta);
+        _applyDeletion(delta);
+        print("Selection after _applyDeletion()\n${selection.value}");
```
Comment (angelosilvestre) [inline super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:76]: We should remove this print statement

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 4]
```diff
@@ -96,36 +111,56 @@ class TextDeltasDocumentEditor {
       if (defaultTargetPlatform == TargetPlatform.android || kIsWeb) {
         editorImeLog.fine("Received a newline insertion on Android. Forwarding to newline input action.");
         onPerformAction(TextInputAction.newline);
+        return;
       } else {
         editorImeLog.fine("Skipping insertion delta because its a newline");
       }
+
+      // Update the local IME value that changes with each delta
```
Comment (angelosilvestre) [inline super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:119]: We have some comments that don't end with a `.`

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 5]
```diff
@@ -173,17 +214,28 @@ class TextDeltasDocumentEditor {
...
+    print("");
+    print("Non-text change:");
+    print("IME selection: \n${delta.selection}\n");
+    print("Existing composer selection: \n${selection.value}\n");
+
+    // final docSelection = DocumentImeSerializer(
+    //   editor.document,
+    //   selection.value!,
+    //   null,
+    // ).imeToDocumentSelection(delta.selection);
```
Comment (angelosilvestre) [inline super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:226]: Please remove the commented lines.

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 6]
```diff
@@ -194,8 +246,12 @@ class TextDeltasDocumentEditor {
     selection.value = insertionSelection;
 
     editorImeLog.fine("Inserting the text at the Document Composer's selection");
-    final didInsert = commonOps.insertPlainText(textInserted);
+    final didInsert = _insertPlainText(
+      insertionSelection.extent,
+      textInserted,
+    );
     editorImeLog.fine("Insertion successful? $didInsert");
+    print("Insertion successful? $didInsert");
```
Comment (angelosilvestre) [inline super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:254]: There are some other print statements we should remove.

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 7]
```diff
@@ -252,18 +345,233 @@ class TextDeltasDocumentEditor {
...
+        // the user is trying to delete upstream.
+        //  * If the node above is an empty paragraph, delete it.
+        //  * If the node above is non-selectable, delete it.
+        //  * Otherwise, move the caret up to the node above.
+        final nodeBefore = editor.document.getNodeBefore(node);
+        if (nodeBefore == null) {
+          return false;
+        }
+
+        final componentBefore = documentLayoutResolver().getComponentByNodeId(nodeBefore.id)!;
```
Comment (angelosilvestre) [inline super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:403]: I think we should move this line just above `if (!componentBefore.isVisualSelectionSupported()) {`

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 8]
```diff
@@ -252,18 +345,233 @@ class TextDeltasDocumentEditor {
...
+    if (deletionPosition.nodePosition is TextNodePosition) {
+      final textPosition = deletionPosition.nodePosition as TextNodePosition;
+      print("Deleting upstream from a TextNodePosition: $textPosition");
+      if (textPosition.offset == 0) {
+        final nodeBefore = editor.document.getNodeBefore(node);
+        if (nodeBefore == null) {
+          return false;
+        }
+
+        print("YOLO");
```
Comment (angelosilvestre) [inline super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:431]: =D

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 9]
```diff
@@ -252,18 +345,233 @@ class TextDeltasDocumentEditor {
...
+          replicateExistingMetadata: currentExtentPosition.offset != endOfParagraph.offset,
+        ),
+      );
+
+      final newTextNode = editor.document.getNodeById(newNodeId)!;
+      selection.value = DocumentSelection.collapsed(
+          position: DocumentPosition(
+        nodeId: newTextNode.id,
+        nodePosition: newTextNode.beginningPosition,
+      ));
```
Comment (angelosilvestre) [inline super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:506]: The formatting here seems a bit weird.

**Review by angelosilvestre — COMMENTED** [review]
I left a few comments. 

There are a number of `print` statements that we should remove before merging.

File: super_editor/test/src/default_editor/document_input_ime_test.dart (hunk 2 above)
Comment (matthew-carroll) [reply super_editor/test/src/default_editor/document_input_ime_test.dart:424]: The reason for naming it after the device and OS version is so that we have the best possible chance of reproducing the issue, if needed. I don't know what kind of keyboard it's using, but I also don't know for sure if this problem would truly be limited to the type of keyboard. We want to give ourselves the best chance to locate the problem again in the future. We can always look up what kind of keyboard is on that tablet, but if we only write down the keyboard, we can't look up the original device where we found the issue.

**Comment by matthew-carroll** [comment]
@angelosilvestre I applied your comments. Do you wanna do one more pass and see if anything looks wrong or overly confusing?

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 10]
```diff
@@ -96,36 +106,56 @@ class TextDeltasDocumentEditor {
       if (defaultTargetPlatform == TargetPlatform.android || kIsWeb) {
         editorImeLog.fine("Received a newline insertion on Android. Forwarding to newline input action.");
         onPerformAction(TextInputAction.newline);
+        return;
```
Comment (angelosilvestre) [inline super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:109]: Don't we need to update `_previousImeValue` here?

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 11]
```diff
@@ -263,7 +337,204 @@ class TextDeltasDocumentEditor {
...
+    if (deletionPosition.nodePosition is UpstreamDownstreamNodePosition) {
+      final nodePosition = deletionPosition.nodePosition as UpstreamDownstreamNodePosition;
+      if (nodePosition.affinity == TextAffinity.downstream) {
+        // The caret is sitting on the downstream edge of block-level content. Delete the
+        // whole block by replacing it with an empty paragraph.
+        commonOps.replaceBlockNodeWithEmptyParagraphAndCollapsedSelection(deletionPosition.nodeId);
+
+        return true;
+      } else {
+        // The caret is sitting on the upstream edge of block-level content and
```
Comment (angelosilvestre) [inline super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:365]: As we are returning in the `if` branch, we could add the write the following block without the `else`.

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 12]
```diff
@@ -263,7 +337,204 @@ class TextDeltasDocumentEditor {
...
+          return false;
+        }
+
+        final componentBefore = documentLayoutResolver().getComponentByNodeId(nodeBefore.id)!;
+
+        if (nodeBefore is TextNode) {
+          // The caret is at the beginning of one TextNode and is preceded by
+          // another TextNode. Merge the two TextNodes.
+          return commonOps.mergeTextNodeWithUpstreamTextNode();
+        } else if (!componentBefore.isVisualSelectionSupported()) {
```
Comment (angelosilvestre) [inline super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:407]: Same here about using the `else` branch. If we remove it, we could declare `componentBefore` right before it's used.

**Review by angelosilvestre — APPROVED** [review]
LGTM with a few comments.

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart (hunk 10 above)
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:109]: I'm not entirely sure, but I removed that `return` statement and all the tests still pass, so we can go with that.

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart (hunk 11 above)
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:365]: I'm not sure there's any value in doing that in this case. This method is filled with conditional branches. Removing one of those `else` branches might be more likely to hurt readability in this method, as help it.

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart (hunk 12 above)
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:407]: Ok, I refactored these branches to be a series of individual guards.

**Comment by transcendr** [comment]
@matthew-carroll  we had this fix rolled out to beta for a little while now with no reported issues or crash reports associated with it, but then suddenly yesterday got a couple of crash reports (no user report yet).  This is a very low incidence rate, and I'm just wondering if from an excerpt of the relevant logs you can tell if this is related (if not I'll investigate more and open a proper issue), and if it is, can tell me if this is a critical issue (as in the editor would stop working for the user during the session) or not.  I appreciate that perhaps it's impossible to tell from the logs, but I thought I would ask.  Many thanks.

DocumentImeSerializer._imeToDocumentPosition
io.flutter.plugins.firebase.crashlytics.FlutterError - Exception: Couldn't map an IME position to a document position. 
package:super_editor/src/default_editor/document_ime/document_serialization.dart:271

Logs:

```
1
12:59:03.842 PM
Instance of 'DiagnosticsProperty<MethodCall>'
2
12:59:03.839 PM
!!![editor.ime] [SHOUT]  - IME range: TextRange(start: 0, end: 648) -> Text node: 1a07942f-46ee-4b4a-a888-89396accfaca
3
12:59:03.839 PM
!!![editor.ime] [SHOUT] -----------------------------------------------------------
4
12:59:03.839 PM
!!![editor.ime] [SHOUT]     ^ node content: '[REDACTED]'
5
12:59:03.839 PM
!!![editor.ime] [SHOUT] IME Ranges to text nodes:
6
12:59:03.839 PM
!!![editor.ime] [SHOUT] Document composing region: [DocumentRange] - from: ([DocumentPosition] - node: "1a07942f-46ee-4b4a-a888-89396accfaca", position: (TextPosition(offset: 615, affinity: TextAffinity.downstream))), to: ([DocumentPosition] - node: "1a07942f-46ee-4b4a-a888-89396accfaca", position: (TextPosition(offset: 648, affinity: TextAffinity.downstream)))
7
12:59:03.839 PM
!!![editor.ime] [SHOUT]
8
12:59:03.839 PM
!!![editor.ime] [SHOUT] Document selection: [DocumentSelection] -    base: ([DocumentPosition] - node: "1a07942f-46ee-4b4a-a888-89396accfaca", position: (TextPosition(offset: 648, affinity: TextAffinity.downstream))),   extent: ([DocumentPosition] - node: "1a07942f-46ee-4b4a-a888-89396accfaca", position: (TextPosition(offset: 648, affinity: TextAffinity.downstream)))
9
12:59:03.839 PM
!!![editor.ime] [SHOUT]
10
12:59:03.839 PM
!!![editor.ime] [SHOUT] IME prepended placeholder: ''
11
12:59:03.839 PM
!!![editor.ime] [SHOUT]
12
12:59:03.839 PM
!!![editor.ime] [SHOUT] IME text: '[REDACTED]'
13
12:59:03.839 PM
!!![editor.ime] [SHOUT] Desired IME position: 'TextPosition(offset: 652, affinity: TextAffinity.downstream)'
14
12:59:03.838 PM
!!![editor.ime] [SHOUT] Couldn't map an IME position to a document position.
15
12:59:03.838 PM
!!![editor.ime] [SHOUT] ---------------DocumentImeSerializer----------------------
16
12:59:03.838 PM
[editor.ime] [INFO] ---------------------------------------------------
17
12:59:03.836 PM
[editor.layout] [INFO] Done calculating new document layout view model
18
12:59:03.835 PM
[editor.style] [INFO] (Re)calculating selection view model for document layout
```

**Comment by matthew-carroll** [comment]
@transcendr based on that log, that error would probably at least force the user to close the keyboard connection and re-open it. I don't think we have nearly enough information from that log to try to address it. I think you'll need to figure out how to reproduce the error.

Can you ship any additional logs with your app that show you what the user was doing just before the error appeared?

**Comment by transcendr** [comment]
@matthew-carroll appreciate the feedback. There are additional logs. I just wanted to show those relevant to SuperEditor. 
 I have been digging through the logs and they all seem to have one thing in common which is the user is selecting text just before the crash event.  That probably doesn't help much but I found it interesting.  

We're getting in contact with the beta testers who were tagged to see how they were affected, if at all.  The good or bad news is, depending how you look at it, is it's not a specific device, whereas previously we had a majority of Samsung devices reporting.

I am attempting to repro now, and will open a proper issue for this one when I am able to.  Since the error is the same as this most recent issue ("Couldn't map an IME position to a document position"), just spitballing here but perhaps it was something similar that is triggered specifically while the user is selecting text?

**Comment by matthew-carroll** [comment]
@transcendr that's certainly possible. There are a lot of moving parts when it comes to altering the content of a document. It's difficult to say what the cause might be without a reproduction.

**Comment by transcendr** [comment]
@matthew-carroll hey, after some additional feedback, I've created a new issue which is a start. I will be adding details, additional repro, etc to it as I learn more: https://github.com/superlistapp/super_editor/issues/1217
