### PR TITLE
[SuperEditor] Fix selection when tapping beyond end of content (Resolves #744)

### LINKED ISSUE #744: [super_editor] - Tapping beyond end of content should place caret at end of document
**Expected behavior:**
When there's empty space after (or below) the content in a `SuperEditor`, if the user taps the empty space, the caret should be placed at the end of the document's content. In other words, when the user taps at a location beyond the end of the document, the caret should always be placed at the end of the document, regardless of the x-position of the mouse cursor.

**Actual behavior:**
When the user taps in the empty space, the caret is placed in the last line of content, but it's placed at the same horizontal position as the user's tap.

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor] Fix selection when tapping beyond end of content. Resolves #744

Tapping at the empty space after the content in `SuperEditor` is placing the caret at the horizontal position where the tap happened.

This PR changes `SuperEditor` to place the caret at the end of the document when a tap happens beyond the end of the content.

### CODE REVIEW

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart [hunk 1]
```diff
@@ -136,6 +136,15 @@ class _SingleColumnDocumentLayoutState extends State<SingleColumnDocumentLayout>
     );
     editorLayoutLog.info('Getting document position near offset: $documentOffset');
 
+    if (_isBeyondDocumentEnd(documentOffset)) {
+      // The given offset is beyond the end of the content.
+      // Return the position at the end of the last node.
+      final lastPosition = _findLastPosition();
+      if (lastPosition != null) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/layout_single_column/_layout.dart:143]: What happens if this condition isn't triggered?

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart [hunk 2]
```diff
@@ -136,6 +136,15 @@ class _SingleColumnDocumentLayoutState extends State<SingleColumnDocumentLayout>
     );
     editorLayoutLog.info('Getting document position near offset: $documentOffset');
 
+    if (_isBeyondDocumentEnd(documentOffset)) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/layout_single_column/_layout.dart:139]: If our problem is in the layout offset lookup, should we also handle the case when we're above the document start?

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart [hunk 3]
```diff
@@ -456,6 +479,21 @@ class _SingleColumnDocumentLayoutState extends State<SingleColumnDocumentLayout>
     return nearestComponentKey;
   }
 
+  /// Returns the [DocumentPosition] at the end of the last node or `null` if the document is empty.
+  DocumentPosition? _findLastPosition() {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/layout_single_column/_layout.dart:483]: Don't we already have a method somewhere that finds the last position in the document?

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/layout_single_column/_layout.dart:483]: We have a method to find the last selectable position. This method always returns the last position, even if the component is not selectable.

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/layout_single_column/_layout.dart:143]: `_findLastPosition` only returns null if the document doesn't have any node. So in this case there will be no selection.

File: super_editor/lib/src/default_editor/layout_single_column/_layout.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/layout_single_column/_layout.dart:148]: Tap above start implemented.

**Review by matthew-carroll — APPROVED** [review]
LGTM
