### PR TITLE
[SuperEditor][Web] Fix selection change with CMD + RIGHT (Resolves #2304)

### LINKED ISSUE #2304: [BUG] [MacOS + Web] - CMD+Left/Right arrow does not move selection correctly
**Package Version**
super_editor, main branch, flutter master.

**User Info**
Superlist

**To Reproduce**
1. On a Mac
2. Update to latest version
3. Run the example app with Chrome
4. Place cursor on the beginning of the line "To get started with your own editing experience, take the following steps:"
5. Press CMD+Right arrow
6. **Expected:** Cursor is placed at the end of the line, **Actual:** Cursor is placed at the beginning of the word "steps"
7. Press CMD+Left arrow
8. **Expected:**, Cursor at beginning of line **Actual:** Cursor at beginning of line (all good!)
9. Press CMD+Left arrow again 
10. **Expected:** Cursor still at beginning of line, **Actual:** Cursor moved to previous line

**Minimal Reproduction Code**
None needed. Example app of super_editor repo.

**Platform**
MacOS + Web

**Flutter version**
Flutter 3.24.0-1.0.pre.565 • channel master • https://github.com/superlistapp/flutter.git

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][Web] Fix selection change with CMD + RIGHT. Resolves #2304

Steps to reproduce: 

1. Run the example app with Chrome 
2. Place cursor on the beginning of the line "To get started with your own editing experience, take the following steps:"
3. Press CMD+Right arrow

Expected: Cursor is placed at the end of the line, Actual: Cursor is placed at the beginning of the word "steps"

This wrong offset is being reported by the selection change delta. On web, Flutter relies on html inputs to handle text input. When the user presses CMD + RIGHT, the browser moves the selection to where it thinks the end of the line is, and the Flutter code generates text deltas for us.

I haven't dug deep into this, but this seems our text layout and the browser text layout are different. For example, in the repro text, the browser thinks the line ends before "steps".

We started handling deltas for moving the caret with the arrow keys in https://github.com/superlistapp/super_editor/pull/1269. I think I failed to document why we need to let the IME generate non-text deltas for this. However, I tested the issues reported in the original ticket (https://github.com/superlistapp/super_editor/issues/1224) and I wasn't able to reproduce any of them.

This PR changes `doNothingWithLeftRightArrowKeysAtMiddleOfTextOnWeb` to avoid sending the key event back to the OS if CMD is pressed.

The ideal solution would be to investigate why our line breaks are different from the browser line breaks, but this will require a deeper investigation.

As a reference, in our "Regular Flutter TextField Demo", if we limit the width of the Flutter TextField to 400px, we can also see the caret moving to the wrong position.

### CODE REVIEW

**Comment by angelosilvestre** [comment]
Playing around a bit with the css flutter generates, it seems that the html input does end the line before "steps" (red is the html input text):

image

**Comment by matthew-carroll** [comment]
This probably shouldn't be too surprising that this happens given that Flutter uses a different text layout implementation than the browser. 

Can you file an issue with Flutter?

Also, did you test jumping by word to see if that's broken in a similar way?

File: super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart [hunk 1]
```diff
@@ -635,6 +635,20 @@ ExecutionInstruction doNothingWithLeftRightArrowKeysAtMiddleOfTextOnWeb({
     return ExecutionInstruction.continueExecution;
   }
 
+  if ((CurrentPlatform.isApple && HardwareKeyboard.instance.isMetaPressed) ||
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:638]: Rather than have this blocking handler know about certain key combo exceptions, can you just move or replicate the relevant key combo above this one in the priority list, along with a comment about why?

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:638]: Do you mean to have a `moveToStartOrEndOfLineWithArrowKeysOnWeb` ?

**Comment by angelosilvestre** [comment]
> Can you file an issue with Flutter?

I'll try to make a repo.

>  Also, did you test jumping by word to see if that's broken in a similar way?

Jumping by word looks fine.

File: super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart (hunk 1 above)
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:638]: I'm not sure about the specifics, because I don't know which handlers this one is currently blocking, but the name you mentioned seems to make sense. If we had such a handler higher up in priority, instead of blocking logic, would it still fix the issue?

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart]: Added a new handler for that.

File: super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart [hunk 2]
```diff
@@ -671,6 +671,63 @@ ExecutionInstruction doNothingWithLeftRightArrowKeysAtMiddleOfTextOnWeb({
...
+  }
+
+  const arrowKeys = [
+    LogicalKeyboardKey.arrowLeft,
+    LogicalKeyboardKey.arrowRight,
+  ];
+  if (!arrowKeys.contains(keyEvent.logicalKey)) {
+    return ExecutionInstruction.continueExecution;
+  }
+
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:693]: Should we check for any other control keys, like Option? A quick check of cmd+option+arrow shows that something else happens in my browser. It doesn't move my cursor. Instead, it seems to switch browser tabs...

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:693]: I tried in chrome and pressing cmd + option + arrow doesn't hit this handler. Maybe the browser is handling the shortcut before us and prevent the event?

**Comment by angelosilvestre** [comment]
Updated the PR to prevent moving between nodes with CMD + LEFT/RIGHT arrow as discussed in the original ticket.

File: super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart [hunk 3]
```diff
@@ -1616,6 +1616,58 @@ This is a paragraph
           ),
         );
       });
+
+      testWidgetsOnApple('with CMD + LEFT ARROW at the beginning of a paragraph', (tester) async {
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart:1620]: These tests verify that CMD + LEFT ARROW do nothing "at the beginning of the paragraph" and the right arrow does nothing "at the end of the paragraph". 

I'm confused by this.

CMD + LEFT/RIGHT ARROW should do nothing on Linux *ever*. Not just at the beginning and end of lines.

It's on a Mac that they should do nothing at the beginning/end of lines.

Also, isn't this ticket about web? If so, shouldn't the new tests simulate web, and reference web?

Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart:1620]: > CMD + LEFT/RIGHT ARROW should do nothing on Linux ever. Not just at the beginning and end of lines.

But we are not running on Linux, we are running on Apple Devices. I create a `testWidgetsOnMacDesktopAndWeb` that might be more appropriate here.

> Also, isn't this ticket about web? If so, shouldn't the new tests simulate web, and reference web?

Yes, but in [this comment](https://github.com/superlistapp/super_editor/issues/2304#issuecomment-2391048168) Brian agreed that we should keep this behavior consistent for web and desktop.

Comment (matthew-carroll) [reply super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart:1620]: Aren't these tests declared inside of a "Linux" group?

Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart]: I didn't notice that. Moved to "Mac and iOS >" group.

**Review by matthew-carroll — APPROVED** [review]
LGTM
