### PR TITLE
[SuperEditor][SuperTextField][Web] Fix IME panels positioning (Resolves #1356)

### LINKED ISSUE #1356: [Web] Japenese & Emoji IME popovers in wrong position
**Reproduction**

  1. Launch Super Editor Example on super_editor main branch / flutter master branch as a MacOS Desktop App
  3. Run main demo or super text field demo
  4. On MacOS, Open emoji popover. Popover appears in correct position
  5. On MacOS, enable Japanese Romanji Keyboard.
  6. From the Keyboard Selection menu, choose "Hiragana - Romanji"
  7. Type the letters "sa"
  8. Japanese IME popver should appear in correct position
  9. Launch example app as a Chrome Web App
  10. Repeat Steps 4-8.
  11. Emoji & Japanese IME popovers appear in the wrong part of the screen.

**macOS (working)**

https://github.com/superlistapp/super_editor/assets/90610075/4fbf6ea0-477e-47ca-ae2d-6e3228bf9ad4

**Chrome (not working)**

https://github.com/superlistapp/super_editor/assets/90610075/b1cfcef6-ea80-4cd6-8cff-bc8618c5789f

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][SuperTextField][Web] Fix IME panels positioning. Resolves #1356

On web, IME panels like the emoji picker, accent panel or japanese input panel aren't displayed at the correct position.

The root cause is that calling `setCaretRect` does nothing on web. To work around that, we need two changes:

- Report the current text style to the IME
- Change `SuperEditor`'s size and transform reporting to report only the bounds of the selected node's visual component instead of the bounds of the whole editor

This PR changes the IME interactors so that, on web, we avoid calling `setCaretRect` and send the the selected component size and transform to the IME. 

This PR introduces a `TextInputComponent` interface to provide methods and properties to query the required information that we need to send to the IME. I'd prefer to avoid declaring this interface and just adding those methods to `TextComponentState`, but it wouldn't work for the task component as it doesn't bind the component key to the inner `TextComponent`. If we can change that, this new interface can be removed.

https://github.com/superlistapp/super_editor/assets/7597082/1801c9d2-d11d-4da3-a6f6-715ac1839677

https://github.com/superlistapp/super_editor/assets/7597082/96bdf4d2-35db-4afe-90b6-2a503ac4a3d3

https://github.com/superlistapp/super_editor/assets/7597082/f04839c0-ddb3-4fdf-8683-940bfac8fa3d

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@angelosilvestre you said that the task component doesn't link to its inner text component, but it does. The Task state object exposes both a `childDocumentComponentKey` and `childTextComposable`.

File: super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart [hunk 1]
```diff
@@ -517,6 +517,14 @@ ExecutionInstruction moveUpAndDownWithArrowKeys({
     return ExecutionInstruction.continueExecution;
   }
 
+  if (isWeb && (editContext.hasPrimaryFocus.value) && (editContext.composer.composingRegion.value != null)) {
+    // We are composing a character on web. It's possible that a native element is being displayed,
+    // like an emoji picker or a character selection panel.
+    // We need to let the OS handle the key so the user can navigate
+    // on the list of possible characters.
+    return ExecutionInstruction.blocked;
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:525]: Please include links to any associated Flutter issue ticket related to this and mention that ideally we wouldn't have to run this check.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 2]
```diff
@@ -231,11 +242,18 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
-      _configureImeClientDecorators();
-      _documentImeConnection.value = _documentImeClient;
-      _reportVisualInformationToIme();
+      return;
+    }
+
+    _configureImeClientDecorators();
+    _documentImeConnection.value = _documentImeClient;
+
+    if (!_imeConnection.value!.attached) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:251]: What does it mean to not be attached here? Why would this happen?

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 3]
```diff
@@ -257,13 +275,8 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
 
-    final renderBox = context.findRenderObject() as RenderBox;
-    _imeConnection.value!.setEditableSizeAndTransform(renderBox.size, renderBox.getTransformTo(null));
-
-    final caretRect = _computeCaretRectInViewportSpace();
-    if (caretRect != null) {
-      _imeConnection.value!.setCaretRect(caretRect);
-    }
+    _reportSizeAndTransformToIme();
+    _reportCaretRectToIme();
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:279]: Is there a reason that we don't report the style information here, too? Isn't the style info also "visual information" that the IME needs?

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 4]
```diff
@@ -273,6 +286,104 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
     onNextFrame((_) => _reportVisualInformationToIme());
   }
 
+  /// Report our size and transform to the root node coordinates to the IME.
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:289]: This first line phrasing is confusing.

"Report the global size and transform of the editor to the IME"

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 5]
```diff
@@ -273,6 +286,104 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
+  ///
+  /// This is needed to display the OS emoji & symbols panel at the editor selected position.
+  void _reportSizeAndTransformToIme() {
+    //print('reporting size and transform');
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:293]: Please remove `print`

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 6]
```diff
@@ -273,6 +286,104 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
+    late Size size;
+    late Matrix4 transform;
+
+    if (isWeb) {
+      // On web, we can't set the caret rect.
+      // To display the IME panels at the correct position,
+      // instead of reporting the whole editor size and transform,
+      // we report only the information about the selected node.
+      final sizeAndTransform = _computeSizeAndTransformOfSelectNode();
+      if (sizeAndTransform == null) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:303]: Why might this happen?

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 7]
```diff
@@ -273,6 +286,104 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
+        return;
+      }
+
+      size = sizeAndTransform.$1;
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:307]: Please always name properties. I don't know why Dart thought that referring to things as `$1` and `$2` was an acceptable UX decision, but it's awful.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 8]
```diff
@@ -273,6 +286,104 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
+      size = renderBox.size;
+      transform = renderBox.getTransformTo(null);
+    }
+
+    _imeConnection.value!.setEditableSizeAndTransform(size, transform);
+  }
+
+  void _reportCaretRectToIme() {
+    if (isWeb) {
+      // On web, setting the caret rect isn't supported.
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:321]: Rather than say that something isn't supported, please tell the reader what conclusion to draw. For example, does this comment mean that all popovers are misaligned on web because "setting the caret rect isn't supported"?

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 9]
```diff
@@ -273,6 +286,104 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
+      return;
+    }
+
+    final caretRect = _computeCaretRectInViewportSpace();
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:325]: I see that we do this in viewport space. Can you check what happens when SuperEditor isn't aligned to the top-left of the window? Do we still report the correct offset?

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 10]
```diff
@@ -273,6 +286,104 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
+      _imeConnection.value!.setCaretRect(caretRect);
+    }
+  }
+
+  /// Report our text style to the IME.
+  ///
+  /// This is used on web to set the text style of the hidden native input,
+  /// to try to match the text size on the browser with our text size.
+  ///
+  /// As our content can have multiple styles, the sizes won't be 100% in sync.
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:336]: Please include link to Flutter issue where we're trying to get this to work for our multi-style editor experience

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 11]
```diff
@@ -273,6 +286,104 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
+
+    final nodePosition = selection.extent.nodePosition;
+    if (nodePosition is! TextNodePosition) {
+      // The selected component doesn't contain text.
+      return;
+    }
+
+    final docLayout = widget.editContext.documentLayout;
+    final selectedComponent = docLayout.getComponentByNodeId(selection.extent.nodeId);
+    if (selectedComponent == null) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:357]: Why might this happen?

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 12]
```diff
@@ -273,6 +286,104 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
+    _imeConnection.value!.setStyle(
+      fontFamily: style.fontFamily,
+      fontSize: style.fontSize,
+      fontWeight: style.fontWeight,
+      textDirection: textInputComponent.textDirection ?? TextDirection.ltr,
+      textAlign: textInputComponent.textAlign ?? TextAlign.left,
+    );
+  }
+
+  void _onSelectionChanged() {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:377]: Please put this above all these reporting methods.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 13]
```diff
@@ -273,6 +286,104 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
+    if (!isWeb) {
+      return;
+    }
+
+    // Selection has changed.
+    // Report the text style of the current selection to the IME.
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:383]: Please mention why this needs to happen on the next frame.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 14]
```diff
@@ -302,6 +413,32 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
     return caretOffset & rectInDocLayoutSpace.size;
   }
 
+  /// Compute the size and transform of the selected node's visual component
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:416]: There's probably no need to ever talk about "root node coordinates". I think what you're talking about are "global coordinates".

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 15]
```diff
@@ -302,6 +413,32 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
+  /// to the root node coordinates.
+  (Size size, Matrix4 transform)? _computeSizeAndTransformOfSelectNode() {
+    final selection = widget.editContext.composer.selection;
+    if (selection == null) {
+      return null;
+    }
+
+    final docLayout = widget.editContext.documentLayout;
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:424]: Let's call this `documentLayout`, matching the thing you're accessing.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 16]
```diff
@@ -302,6 +413,32 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
+    final selectedComponent = docLayout.getComponentByNodeId(selection.extent.nodeId);
+    if (selectedComponent == null) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:426]: Why might this happen?

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 17]
```diff
@@ -302,6 +413,32 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
...
+      return null;
+    }
+
+    if (selectedComponent is! TextInputComponent) {
+      // The selected doesn't report text bounds.
+      return null;
+    }
+
+    final rect = (selectedComponent as TextInputComponent).getTextBounds();
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:435]: Is there a reason that the text component doesn't report its global transform? I know we talked briefly about transforms, but I thought render objects could find their global transform?

File: super_editor/lib/src/default_editor/tasks.dart [hunk 18]
```diff
@@ -230,6 +232,38 @@ class _TaskComponentState extends State<TaskComponent> with ProxyDocumentCompone
...
+    return _computeStyles(attributions);
+  }
+
+  @override
+  TextAlign? get textAlign => TextAlign.left;
+
+  @override
+  TextDirection? get textDirection => Directionality.of(context);
+
+  TextStyle _computeStyles(Set<Attribution> attributions) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/tasks.dart:255]: Please add Dart Doc so it's clear which portion of text these styles apply to, or how it's expected to be used.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 19]
```diff
@@ -1016,6 +1022,8 @@ class SuperTextFieldImeInteractor extends StatefulWidget {
   /// the [ProseTextLayout] widget that paints the text for this text field.
   final GlobalKey<ProseTextState> textKey;
 
+  final AttributionStyleBuilder textStyleBuilder;
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1025]: Please add all appropriate Dart Docs

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 20]
```diff
@@ -997,9 +1000,12 @@ class SuperTextFieldImeInteractor extends StatefulWidget {
     required this.focusNode,
     required this.textController,
     required this.isMultiline,
+    required this.textStyleBuilder,
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1003]: Let's put this down with the other text style properties

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 21]
```diff
@@ -1128,6 +1143,15 @@ class _SuperTextFieldImeInteractorState extends State<SuperTextFieldImeInteracto
     }
   }
 
+  void _onImeConnectionChanged() {
+    if (!widget.textController.isAttachedToIme) {
+      return;
+    }
+
+    _reportTextStyleToIme();
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1151]: Here again, is there a reason that these two reportings are separated?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 22]
```diff
@@ -1157,6 +1175,58 @@ class _SuperTextFieldImeInteractorState extends State<SuperTextFieldImeInteracto
     onNextFrame((_) => _reportVisualInformationToIme());
   }
 
+  void _reportSizeAndTransformToIme() {
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1178]: Please add Dart Doc

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 23]
```diff
@@ -1157,6 +1175,58 @@ class _SuperTextFieldImeInteractorState extends State<SuperTextFieldImeInteracto
...
+
+    final selection = widget.textController.selection;
+    if (selection.isValid) {
+      // We have a selection, compute the style based on the attributions present
+      // at the selection extent.
+      final text = widget.textController.text;
+      final attributions = text.getAllAttributionsAt(selection.extentOffset);
+      textStyle = widget.textStyleBuilder(attributions);
+    } else {
+      // We don't have a selection, use the default style.
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1217]: If we don't have a selection, should we be reporting anything?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 24]
```diff
@@ -1789,6 +1859,15 @@ class DefaultSuperTextFieldKeyboardHandlers {
     if (!arrowKeys.contains(keyEvent.logicalKey)) {
       return TextFieldKeyboardHandlerResult.notHandled;
     }
+
+    if (isWeb && (controller.composingRegion.isValid)) {
+      // We are composing a character on web. It's possible that a native element is being displayed,
+      // like an emoji picker or a character selection panel.
+      // We need to let the OS handle the key so the user can navigate
+      // on the list of possible characters.
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1867]: Same comment here as super editor, please reference a Flutter issue and explain that we'd like to get rid of this.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:251]: `_onImeConnectionChange` is also called when the we detach from the IME, so we shouldn't try to report this information.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:279]: Updated.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 8 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:321]: Updated.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 21 above)
Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1151]: Updated.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 23 above)
Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1217]: Probably not. updated.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 6 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:303]: Added a dart doc to `_computeSizeAndTransformOfSelectNode` explaining why it might return null.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 11 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:357]: As `getComponentByNodeId` can return null, I added this guard clause. Should I just use a null assertion? 

```dart
final selectedComponent = docLayout.getComponentByNodeId(selection.extent.nodeId)!;
```

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 16 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:426]: Same as before.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 9 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:325]: I tested the sliver demo and it seems we are reporting the correct offset.

**Comment by angelosilvestre** [comment]
@matthew-carroll 

> The Task state object exposes both a childDocumentComponentKey and childTextComposable

The `childDocumentComponentKey` can be bound to an arbitrary component, not just a text component. It's true that in the majority of cases it will be a text component though. If we want to use `childDocumentComponentKey` then we need to check for a `ProxyDocumentComponent` and hard cast its child component to a `TextComponent`.

Please let me know what do you think.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 17 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:420]: I will come back for this comment after we discuss https://github.com/superlistapp/super_editor/pull/1418#issuecomment-1714731423

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 2 above)
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:241]: Ok. In general when I ask about why a condition might happen, it means that the code should clarify why it can happen. Please let the reader the know why we might not be attached to the IME at that point.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 9 above)
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:315]: Can you try using a non-sliver SuperEditor in a location that isn't aligned with the top left? Slivers might do all sorts of weird things when it comes to geometry reporting.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 11 above)
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:349]: At a minimum we should add a warning log in the if-statement that explains what went wrong. An if-statement like this, without a comment, and without a log, suggests that such a situation is expected and acceptable.

**Comment by matthew-carroll** [comment]
For the case of a proxy component, how about we check if we're dealing with a proxy component. If we are, get the wrapped component, and then check if it's a text component, and then everything else continues as before.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:241]: Updated.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 11 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:349]: Updated.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 9 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:315]: I tested and it seems everything is correct.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 2 above)
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:241]: This comment is still confusing. Why would the IME connection be closed and yet `_imeConnection.value` is non-null?

File: super_editor/lib/src/default_editor/text.dart [hunk 25]
```diff
@@ -834,6 +834,17 @@ class TextComponentState extends State<TextComponent> with DocumentComponent imp
     );
   }
 
+  /// Return the [TextStyle] for the character at [offset].
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/text.dart:837]: Please also describe what this returns when the caret is at the beginning of the text, the end of the text, or when there is no text.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 26]
```diff
@@ -1000,6 +1003,9 @@ class SuperTextFieldImeInteractor extends StatefulWidget {
     required this.selectorHandlers,
     this.textInputAction,
     this.imeConfiguration,
+    this.textAlign,
+    this.textDirection,
+    required this.textStyleBuilder,
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1008]: Let's place this above `textAlign`

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 27]
```diff
@@ -1016,6 +1022,10 @@ class SuperTextFieldImeInteractor extends StatefulWidget {
   /// the [ProseTextLayout] widget that paints the text for this text field.
   final GlobalKey<ProseTextState> textKey;
 
+  /// Text style factory that creates styles for the content in
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1025]: I'm not sure this Dart Doc covers relevant information....

The actual text styling is done somewhere else right? We have this IME interactor, which otherwise shouldn't know anything about text styling, and yet we have these properties. A user is going to be confused by that, right? Also, I assume that we expect the user to pass us the exact same styler that's used elsewhere? If so, these are the kinds of details that we need to capture.

Similar to some other recent Dart Docs in PRs, putting yourself in the shoes of a user, what do you need to know about this property to use it correctly? It doesn't seem to me that we've captured that.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:241]: I checked the places where we close the IME connection and we always set `_imeConnection.value` to `null`, so it seems we don't need this if statement.

File: super_editor/lib/src/default_editor/text.dart (hunk 25 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/text.dart:837]: Updated. I also adjusted the case where the selection is at the end of the text.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 27 above)
Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1025]: Updated.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 11 above)
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:352]: Won't this if-statement be triggered if the user selects a proxy component that doesn't include text? If so, should that really result in a warning?

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 28]
```diff
@@ -302,6 +398,35 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
     return caretOffset & rectInDocLayoutSpace.size;
   }
 
+  /// Compute the size and transform of the selected node's visual component
+  /// to the global coordinates.
+  ///
+  /// Returns `null` if the we don't have a selection, or if the selected
+  /// component can't report its inner text bounds.
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:405]: Why wouldn't it be able to report its inner text bounds?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 29]
```diff
@@ -1028,6 +1046,10 @@ class SuperTextFieldImeInteractor extends StatefulWidget {
   /// Preferences for how the platform IME should look and behave during editing.
   final TextInputConfiguration? imeConfiguration;
 
+  final TextAlign? textAlign;
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1049]: Please ensure that the order of properties matches the order of named parameters in the constructor.

Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1049]: Updated.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 28 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:405]: Updated.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 11 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:352]: No, it will only trigger if `selectedComponent.childDocumentComponentKey.currentState` returns `null`. It doesn't matter if it has text or not.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 20 above)
Comment (matthew-carroll) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1003]: Looks like this is still an issue?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 29 above)
Comment (matthew-carroll) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1049]: I was expecting that you'd move the style builder down here above the related text style proeprties, rather than alter the constructor to separate the properties. Please keep highly related properties together.

Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1049]: I misunderstood the comment. Sorry.

Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1049]: Updated.

**Review by matthew-carroll — APPROVED** [review]
LGTM
