### PR TITLE
[SuperEditor][Web] Fix cmd + left to move selection (Resolves #1852)

### LINKED ISSUE #1852: [SuperEditor] [Web] CMD+Left-arrow does not move
**Package Version**
`main` branch with commit hash 94d8fec5fabbc8ae3a8023769fb98d80a4a2606e

**To Reproduce**
1. On web, go to SuperEditor demo app
2. Place the selection in the middle of a text node
3. Press CMD-left-arrow

**Actual behavior**
Nothing happens, i.e. the selection remains the same.

**Expected behavior**
Selection moves to the start of the node.

**Platform**
Web

**Flutter version**
Flutter master commit e278279a48f0479386c249cf18f26b29c6f9018f.

**Screenshots**

https://github.com/superlistapp/super_editor/assets/31278849/adca2187-f45e-4a7a-ab2b-e4ea23006571

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][Web] Fix cmd + left to move selection (Resolves #1852)

On web, pressing CMD + LEFT ARROW isn't changing the selection. The selection movement on web is done using the non-text deltas that the IME generates instead of handling key presses. This causes an issue when the user tries to move the selection to the first character, because the first character the IME sees sits in the invisible region. For example, for the paragraph with the content "This is the first line", the IME content looks like this:

```
. This is the first line
```

So, when the IME moves the selection to the beginning of the line, the selection sits before the `.`. Because of that, we can't map the IME position to a document position and the selection remains unchanged.

This PR changes how we handle non-text deltas on web when the a collapsed selection or composing region sits in the invisible area. Now, in those cases we move the selection/composing region to the first visible character.

### CODE REVIEW

**Comment by angelosilvestre** [comment]
@matthew-carroll  We should merge https://github.com/superlistapp/super_editor/pull/1859 first because of the updated goldens.

**Comment by matthew-carroll** [comment]
@angelosilvestre are you saying that our keyboard handler doesn't run on web for CMD+LEFT? If not, how about any other such command, like CMD+RIGHT, SHIFT+ALT+RIGHT? Is Flutter not reporting those key presses on web?

**Comment by angelosilvestre** [comment]
@matthew-carroll 

> are you saying that our keyboard handler doesn't run on web for CMD+LEFT? 

Yes, most of the caret movement key handlers don't run on web. Flutter reports them, but we ignore the key presses and handle the non-text deltas. This change was made in a previous PR, because caret movement doesn't work reliably on web if we handle those key presses.

The only affected handlers are those that move the caret to the beginning of the text. As all of them will generate the same deltas, they are all covered by this PR.

**Comment by matthew-carroll** [comment]
@angelosilvestre is this ready for review?

**Comment by angelosilvestre** [comment]
@matthew-carroll Yeah, it's ready for review.

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 1]
```diff
@@ -97,9 +98,29 @@ class TextDeltasDocumentEditor {
     // the IME composing region.
     editorImeLog.fine("After applying all deltas, converting the final composing region to a document range.");
     editorImeLog.fine("Raw IME delta composing region: ${textEditingDeltas.last.composing}");
+
+    final lastDelta = textEditingDeltas.last;
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:102]: There are two maintenance and readability concerns here. First, we're dumping a bunch of nuanced lines of a code in the middle of the high level processing function. Notice how the existing code around this is all higher level and more abstract. When reading a loop that applies deltas, it's difficult to come down here and have any context for what this bundle of code means.

Second, it seems that this exact code, or very similar code, is replicated down below. That creates an opportunity to change one version and not the other, leading to a bug.

Please extract this behavior into a method called:

```
DocumentRange? _calculateNewComposingRegion(List<TextEditingDelta> deltas) {}
```

File: super_editor/lib/src/default_editor/document_ime/document_serialization.dart [hunk 2]
```diff
@@ -243,15 +243,26 @@ class DocumentImeSerializer {
     return true;
   }
 
+  /// Returns the first visible position in the IME content.
+  ///
+  /// If a placeholder is prepended, returns the first position after the placeholder,
+  /// otherwise, returns the first position.
+  TextPosition firstVisiblePosition() {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/document_serialization.dart:250]: Should this be a getter?

File: super_editor/lib/src/default_editor/document_ime/document_serialization.dart [hunk 3]
```diff
@@ -243,15 +243,26 @@ class DocumentImeSerializer {
...
+    return didPrependPlaceholder //
+        ? TextPosition(offset: _prependedPlaceholder.length)
+        : const TextPosition(offset: 0);
+  }
+
   DocumentPosition _imeToDocumentPosition(TextPosition imePosition, {required bool isUpstream}) {
+    final affinity = isUpstream ? TextAffinity.upstream : TextAffinity.downstream;
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/document_serialization.dart:257]: Why was this needed? If it's needed, why wasn't the absence of this breaking any tests?

File: super_editor/test/super_editor/supereditor_keyboard_test.dart [hunk 4]
```diff
@@ -284,6 +284,42 @@ void main() {
       });
     });
 
+    group('on web', () {
+      group('moves caret', () {
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_keyboard_test.dart:288]: Is there a reason this group is here?

File: super_editor/lib/src/default_editor/document_ime/document_serialization.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/document_serialization.dart:250]: It can be.  Updated.

File: super_editor/test/super_editor/supereditor_keyboard_test.dart (hunk 4 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_keyboard_test.dart:288]: Ungrouped. If we need other related tests in the future we can re-group.

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:102]: Updated. Also extracted the `DocumentSelection` calculation to be consistent with the composing region calculation.

File: super_editor/lib/src/default_editor/document_ime/document_serialization.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/document_serialization.dart]: I can't remember if I needed this for something. Removed and nothing seems to break...

**Review by matthew-carroll — APPROVED** [review]
LGTM
