### PR TITLE
[SuperEditor][Mobile] Fix crash on long press over non-text node (Resolves #2126)

### LINKED ISSUE #2126: [BUG] - Crash occurs when trying to long press (scroll) on a non-text node on Android/iOS.
**Package Version**
super_editor, GitHub, stable branch

**User Info**
Knips (https://knips.io) - We are working on replacing our Block Text Editor with the Super Editor (not released yet). The editor will be used to create posts on our platform.

**To Reproduce**
1. Build the demo app on Android/iOS.
2. Add a non-text node, such as an image or divider.
3. Long press on the node (this could happen when a user is trying to scroll).
4. The app crashes.

**Minimal Reproduction Code**
The bug is present in the demo app.

**Actual behavior**
Crash

```
The following _TypeError was thrown while handling a gesture:
Null check operator used on a null value

When the exception was thrown, this was the stack: 
#0      AndroidDocumentLongPressSelectionStrategy.onLongPressDragUpdate (package:super_editor/src/infrastructure/platforms/android/long_press_selection.dart:221:74)
#1      _AndroidDocumentTouchInteractorState._onLongPressPanUpdate (package:super_editor/src/default_editor/document_gestures_touch_android.dart:1072:25)
#2      _AndroidDocumentTouchInteractorState._onPanUpdate (package:super_editor/src/default_editor/document_gestures_touch_android.dart:1050:7)
#3      DragGestureRecognizer._checkUpdate.<anonymous closure> (package:flutter/src/gestures/monodrag.dart:806:55)
#4      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
#5      DragGestureRecognizer._checkUpdate (package:flutter/src/gestures/monodrag.dart:806:7)
#6      DragGestureRecognizer.handleEvent (package:flutter/src/gestures/monodrag.dart:652:11)
#7      PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:98:12)
#8      PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:143:9)
#9      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:633:13)
#10     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:141:18)
#11     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:127:7)
#12     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:495:19)
#13     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#14     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425:11)
#15     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#16     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#17     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#18     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#19     _invoke1 (dart:ui/hooks.dart:328:13)
#20     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#21     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
Handler: "onUpdate"
Recognizer: VerticalDragGestureRecognizer#7209a
  start behavior: down
```

**Expected behavior**
No crash, user is able to scroll/long-press without any issue

**Platform**
Android/iOS

**Flutter version**
[3.22.2](https://github.com/flutter/flutter/releases/tag/3.22.2)

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][Mobile] Fix crash on long press over non-text node. Resolves #2126.

Long-pressing on a non-text node, such as an image or a horizontal rule causes the editor to crash, and prevents the selection with the following exception:

```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
#0      IosLongPressSelectionStrategy.onLongPressStart (package:super_editor/src/infrastructure/platforms/ios/long_press_selection.dart:48:39)
#1      _IosDocumentTouchInteractorState._onLongPressDown (package:super_editor/src/default_editor/document_gestures_touch_ios.dart:610:60)
#2      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#3      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#4      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#5      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

A similar crash also happens on Android.

The issue is that we are assuming that the long-press selection always starts at a text node, which isn't the case.

This PR changes the long-press selection strategy to handle the case where the selection starts at a non-text node.

[android_long_press.webm](https://github.com/superlistapp/super_editor/assets/7597082/c23f1113-7bfe-4612-9de6-33a5aec3b7a7)

### CODE REVIEW

File: super_editor/lib/src/infrastructure/platforms/android/long_press_selection.dart [hunk 1]
```diff
@@ -203,10 +222,12 @@ class AndroidDocumentLongPressSelectionStrategy {
 
     final isOverNonTextNode = fingerDocumentPosition.nodePosition is! TextNodePosition;
     if (isOverNonTextNode) {
-      // The user is dragging over content that isn't text, therefore it doesn't have
-      // a concept of "words". Select the whole node.
-      longPressSelectionLog.finer("Dragging over non-text node. Selecting the whole node.");
-      _select(_longPressInitialSelection!.expandTo(fingerDocumentPosition));
+      if (fingerDocumentPosition.nodeId != _longPressInitialSelection!.base.nodeId) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/platforms/android/long_press_selection.dart:225]: Can you comment what this if-statement is checking? It's not clear to me upon reading it.

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/platforms/android/long_press_selection.dart:228]: Updated.

**Review by matthew-carroll — APPROVED** [review]
LGTM
