### PR TITLE
[SuperEditor][SuperReader][Android] Add TapRegion groupId (Resolves #1692)

### LINKED ISSUE #1692: [SuperEditor] [Android] Editor loses focus when dragging selection handles when using TapRegion to unfocus the editor when tapped outside
**Package Version**
Using 0a58e704469ccaffe5ab14620a56afe75bee6574 in `main`.

**To Reproduce**
The pre-condition is to have a `TapRegion` above `SuperEditor` that unfocuses the editor when tapped outside. See the code snippet below.

1. Go to the altered SuperEditor demo
2. Double-tap on a word
3. Drag one of the selection handles to extend the seleciton

**Minimal Reproduction Code**

In `example_editor.dart`, wrap `SuperEditor` with `TapRegion`:

<details>
  <summary>Minimal, Runnable Code Sample</summary>

  ```dart
  TapRegion(
    onTapOutside: (_) {
      _editorFocusNode.unfocus();
    },
    child: SuperEditor(...),
  ),
  ```
</details>

**Actual behavior**
Document loses focus.

**Expected behavior**
Selection changes as the handle is dragged.

**Platform**
Android.

**Flutter version**
Flutter `master` commit e278279a48f0479386c249cf18f26b29c6f9018f.

**Screenshots**

https://github.com/superlistapp/super_editor/assets/31278849/6459944d-251a-48cf-8697-87b02720ec32

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][SuperReader][Android] Add TapRegion groupId. Resolves #1692

When placed inside a `TapRegion`, tapping on the drag handle is causing `onTapOutside` to be called. It might be related to the fact that the drag handle is displayed, but on iOS this issue isn't happening. Wrapping the overlay with a `TapRegion` and giving it the same `groupId` as the `TapRegion` surrounding the editor solves the problem.

This PR adds a `tapRegionGroupId` property to both `SuperEditor` and `SuperReader`, so they can be used inside a `TapRegion`.

### CODE REVIEW

File: super_editor/lib/src/default_editor/super_editor.dart [hunk 1]
```diff
@@ -227,6 +228,14 @@ class SuperEditor extends StatefulWidget {
   /// when a user taps on a link.
   final SuperEditorContentTapDelegateFactory? contentTapDelegateFactory;
 
+  /// {@template super_editor_tap_region_group_id}
+  /// A group ID for a tap region that surrounds the editor
+  /// and also surrounds any related widgets, such as drag handles and a toolbar.
+  ///
+  /// A [tapRegionGroupId] must be provided when the editor is inside a [TapRegion].
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/super_editor.dart:235]: This statement doesn't tell the reader why this "must" be done, nor how a developer should figure out what the value should be. Please ensure that the developer is educated as to the relevance of this property.

File: super_editor/lib/src/default_editor/super_editor.dart [hunk 2]
```diff
@@ -738,6 +747,7 @@ class SuperEditorState extends State<SuperEditor> {
           ]),
           scrollChangeSignal: _scrollChangeSignal,
           dragHandleAutoScroller: _dragHandleAutoScroller,
+          tapRegionGroupId: widget.tapRegionGroupId,
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/super_editor.dart:750]: Why is this is only being applied when running on Android?

File: super_editor/lib/src/test/super_reader_test/super_reader_robot.dart [hunk 3]
```diff
@@ -192,6 +193,19 @@ extension SuperReaderRobot on WidgetTester {
     await pumpAndSettle();
   }
 
+  Future<TestGesture> pressDownOnDownstreamMobileHandle() async {
```
Comment (matthew-carroll) [inline super_editor/lib/src/test/super_reader_test/super_reader_robot.dart:196]: Do we have a corresponding method for pressing down on an upstream handle? If not, why not?

File: super_editor/lib/src/test/super_reader_test/super_reader_robot.dart [hunk 4]
```diff
@@ -192,6 +193,19 @@ extension SuperReaderRobot on WidgetTester {
...
+    final handleElement = find
+        .byWidgetPredicate((widget) => widget is AndroidSelectionHandle && widget.handleType == HandleType.downstream)
+        .evaluate()
+        .firstOrNull;
+    assert(handleElement != null, "Tried to press down on upstream handle but no handle was found.");
```
Comment (matthew-carroll) [inline super_editor/lib/src/test/super_reader_test/super_reader_robot.dart:201]: This assertion says "upstream handle" - shouldn't it be "downstream"?

File: super_editor/test/super_editor/mobile/super_editor_android_selection_test.dart [hunk 5]
```diff
@@ -430,6 +433,113 @@ void main() {
           await tester.pump();
         });
       });
+
+      testWidgetsOnAndroid("changes selection when dragging the collapsed handle", (tester) async {
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/mobile/super_editor_android_selection_test.dart:437]: Are you actually trying to test handle selection control? Or are you trying to test something related to tap regions?

File: super_editor/lib/src/default_editor/super_editor.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/super_editor.dart:235]: Updated.

File: super_editor/lib/src/default_editor/super_editor.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/super_editor.dart:750]: During tests, the issue only happened on Android. Should we also apply it to iOS ?

File: super_editor/test/super_editor/mobile/super_editor_android_selection_test.dart (hunk 5 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/mobile/super_editor_android_selection_test.dart:437]: We are testing if we can drag the handle to change the selection when the editor is inside a `TapRegion`. 

Should the test have a different description? Should I write a different test?

File: super_editor/lib/src/default_editor/super_editor.dart (hunk 2 above)
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/super_editor.dart:753]: Unless tap regions are something that will only be used on Android, we should treat this work as applying to all platforms.

File: super_editor/test/super_editor/mobile/super_editor_android_selection_test.dart (hunk 5 above)
Comment (matthew-carroll) [reply super_editor/test/super_editor/mobile/super_editor_android_selection_test.dart:437]: At a minimum it seems that the tests are conflating what they're testing with how they're testing. Isn't this PR really about playing nice with `TapRegion`s? Dragging a handle might be one way to test that goal, but dragging a handle isn't the direct goal of this work, is it?

File: super_editor/lib/src/default_editor/super_editor.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/super_editor.dart:753]: Updated.

File: super_editor/test/super_editor/mobile/super_editor_android_selection_test.dart (hunk 5 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/mobile/super_editor_android_selection_test.dart:437]: Do you think we should only add a "when inside a TapRegion" to the test description, or change the test to only ensure that `onTapOutSide` wasn't called?

Comment (angelosilvestre) [reply super_editor/test/super_editor/mobile/super_editor_android_selection_test.dart]: Updated.

File: super_editor/test/super_editor/supereditor_test_tools.dart [hunk 6]
```diff
@@ -525,6 +533,7 @@ class _TestSuperEditorState extends State<_TestSuperEditor> {
       autofocus: widget.testConfiguration.autoFocus,
       scrollController: widget.testConfiguration.scrollController,
       plugins: widget.testConfiguration.plugins,
+      tapRegionGroupId: widget.testConfiguration.tapRegionGroupId,
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_test_tools.dart:536]: Please move this up beneath `focusNode` so that it's with other Flutter framework stuff. Also, we don't want to simply tack new properties at the bottom. Generally speaking, `plugins` should be the last item in the list because plugins are the part that's most removed from `SuperEditor`.

Please make a similar change to the property order, too.

File: super_editor/test/super_reader/mobile/super_reader_android_selection_test.dart [hunk 7]
```diff
@@ -2,9 +2,9 @@ import 'package:flutter_test/flutter_test.dart';
 import 'package:flutter_test_runners/flutter_test_runners.dart';
 import 'package:super_editor/src/infrastructure/platforms/android/magnifier.dart';
 import 'package:super_editor/src/infrastructure/platforms/android/selection_handles.dart';
-import 'package:super_editor/src/test/super_reader_test/super_reader_inspector.dart';
 import 'package:super_editor/super_editor.dart';
 import 'package:super_editor/super_editor_test.dart';
+import 'package:super_editor/super_reader_test.dart';
```
Comment (matthew-carroll) [inline super_editor/test/super_reader/mobile/super_reader_android_selection_test.dart:7]: Should this import be here?

File: super_editor/test/super_editor/supereditor_test_tools.dart (hunk 6 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_test_tools.dart]: I also moved `autofocus` close to `FocusNode`. I think it makes sense to keep these properties together.

File: super_editor/test/super_reader/super_reader_tapregion_test.dart [hunk 8]
```diff
@@ -0,0 +1,74 @@
...
+import 'package:super_editor/src/infrastructure/multi_tap_gesture.dart';
+import 'package:super_editor/src/test/super_reader_test/super_reader_inspector.dart';
+import 'package:super_editor/src/test/super_reader_test/super_reader_robot.dart';
+
+import '../test_tools.dart';
+import 'reader_test_tools.dart';
+
+void main() {
+  group('SuperReader inside a TapRegion', () {
+    testWidgetsOnMobile("changes selection when dragging expanded handle", (tester) async {
```
Comment (matthew-carroll) [inline super_editor/test/super_reader/super_reader_tapregion_test.dart:16]: I think we still have an issue with test naming. We're not testing selection changes, we're testing tap regions and shared focus. A more appropriate name would be "does not report a tap outside when the user touches overlay controls"

File: super_editor/test/super_reader/reader_test_tools.dart [hunk 9]
```diff
@@ -274,6 +283,7 @@ class TestDocumentConfigurator {
             autofocus: _autoFocus,
             scrollController: _scrollController,
             androidToolbarBuilder: _androidToolbarBuilder,
+            tapRegionGroupId: _tapRegionGroupId,
```
Comment (matthew-carroll) [inline super_editor/test/super_reader/reader_test_tools.dart:286]: Should this move up below `focusNode`?

File: super_editor/test/super_reader/reader_test_tools.dart [hunk 10]
```diff
@@ -96,6 +96,7 @@ class TestDocumentConfigurator {
   DocumentSelection? _selection;
   WidgetBuilder? _androidToolbarBuilder;
   DocumentFloatingToolbarBuilder? _iOSToolbarBuilder;
+  String? _tapRegionGroupId;
```
Comment (matthew-carroll) [inline super_editor/test/super_reader/reader_test_tools.dart:99]: Should the focus things be grouped together in this list?

File: super_editor/lib/src/default_editor/super_editor.dart [hunk 11]
```diff
@@ -143,6 +144,17 @@ class SuperEditor extends StatefulWidget {
...
   final bool autofocus;
 
+  /// {@template super_editor_tap_region_group_id}
+  /// A group ID for a tap region that surrounds the editor
+  /// and also surrounds any related widgets, such as drag handles and a toolbar.
+  ///
+  /// When the editor is inside a [TapRegion], tapping at a drag handle causes
+  /// [TapRegion.onTapOutside] to be called. To prevent that, provide a
+  /// [tapRegionGroupId] with the same value as the ancestor [TapRegion] groupId.
+
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/super_editor.dart:154]: It looks like there's an extra blank line here.

File: super_editor/lib/src/default_editor/super_editor.dart (hunk 2 above)
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/super_editor.dart:754]: Should this property be moved to teh top?

File: super_editor/test/super_editor/supereditor_test_tools.dart [hunk 12]
```diff
@@ -559,6 +568,7 @@ class SuperEditorTestConfiguration {
   final addedComponents = <ComponentBuilder>[];
   DocumentFloatingToolbarBuilder? androidToolbarBuilder;
   DocumentFloatingToolbarBuilder? iOSToolbarBuilder;
+  String? tapRegionGroupId;
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_test_tools.dart:571]: Should this be moved up?

File: super_editor/test/super_reader/super_reader_tapregion_test.dart (hunk 8 above)
Comment (matthew-carroll) [reply super_editor/test/super_reader/super_reader_tapregion_test.dart:16]: Did this change not get pushed? I see the same name.

Comment (angelosilvestre) [reply super_editor/test/super_reader/super_reader_tapregion_test.dart]: That's weird. Updated again.

**Review by matthew-carroll — APPROVED** [review]
LGTM
