### PR TITLE
Fix crash in linkification reaction, also add linkification to inline markdown parsing (Resolves #2074)

### LINKED ISSUE #2074: [SuperEditor] Editor crashes when user types [google](www.google.com)
**Package Version**
main

**To Reproduce**
1. Go to SuperEditor demo
2. On a paragraph write `[google](www.google.com)`

**Actual behavior**
Throws an exception:
```
The following FormatException was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Missing end `]` to match `[` in host (at character 9)
https://[google](www.goggle.com)
        ^

When the exception was thrown, this was the stack: 
#0      _Uri._fail (dart:core/uri.dart:1737:5)
#1      _Uri._makeHost (dart:core/uri.dart:2068:9)
#2      new _Uri.notSimple (dart:core/uri.dart:1612:14)
#3      Uri.parse (dart:core/uri.dart:1138:17)
#4      parseLink (package:super_editor/src/default_editor/default_document_editor_reactions.dart:848:13)
#5      LinkifyReaction._extractUpstreamWordAndLinkify (package:super_editor/src/default_editor/default_document_editor_reactions.dart:667:19)
#6      LinkifyReaction.react (package:super_editor/src/default_editor/default_document_editor_reactions.dart:610:9)
#7      Editor._reactToChanges (package:super_editor/src/core/editor.dart:218:16)
#8      Editor.execute (package:super_editor/src/core/editor.dart:161:9)
#9      TextDeltasDocumentEditor._insertPlainText (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:333:12)
#10     TextDeltasDocumentEditor.insert (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:285:23)
#11     TextDeltasDocumentEditor._applyInsertion (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:175:5)
#12     TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:81:9)
#13     DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:232:30)
#14     DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
#15     TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1903:63)
#16     TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1794:20)
#17     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571:55)
#18     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564:34)
#19     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:576:35)
#20     _invoke2 (dart:ui/hooks.dart:344:13)
#21     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
#22     _Channel.push (dart:ui/channel_buffers.dart:135:31)
#23     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
#24     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
#25     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 27, oldText: . [google](www.goggle.com), selectionAffinity: TextAffinity.downstream, deltaEnd: 26, deltaText:  , deltaStart: 26, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 27, composingBase: -1}]}])
```

**Expected behavior**
Ideally it should linkify the word "google". 
The very least, it should not crash the browser.

**Platform**
All.

**Flutter version**
Flutter master

### PR DESCRIPTION
**Pull request by matthew-carroll**
Fix crash in linkification reaction, also add linkification to inline markdown parsing (Resolves #2074)

Repro: Type `[google](www.google.com)`.

Result: Crash due to the (non-Markdown) linkification reaction.

This PR does two things:

1. Don't crash in the non-Markdown linkification reaction.
2. Linkify the Markdown syntax.

Previously, I didn't include Markdown linkification in the upstream Markdown parser reaction. That's because the link syntax is a lot more complicated to parse character by character.

In this PR, I carved out the link syntax as a special case within the parser reaction. In that carve-out I use a `RegExp` to find the link. So now that parser also parses link syntax.

### CODE REVIEW

**Comment by miguelcmedeiros** [comment]
@matthew-carroll, tested the change and found a problem with the selection after the conversion:

https://github.com/superlistapp/super_editor/assets/31278849/274c4ad4-b056-49e8-96fb-996b08b7eac0

In this case I typed the letter "d" which triggered the conversion, but the selection remains at the end of the link.

**Comment by matthew-carroll** [comment]
@miguelcmedeiros I changed the reaction to only linkify when a space is inserted after the link. Please try again.

**Review by angelosilvestre — APPROVED** [review]
LGTM

**Comment by miguelcmedeiros** [comment]
@matthew-carroll the selection is still off by -1 when using a space. When the conversion happens, the caret stays at the end of the link and there's a space on the right side.

Also, I noticed that if I copy/paste `[google](www.google.com)`, it throws:
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: FormatException: Missing end `]` to match `[` in host (at character 9)
https://[google](www.google.com)
        ^

#0      _Uri._fail (dart:core/uri.dart:1737:5)
#1      _Uri._makeHost (dart:core/uri.dart:2068:9)
#2      new _Uri.notSimple (dart:core/uri.dart:1612:14)
#3      Uri.parse (dart:core/uri.dart:1138:17)
#4      parseLink (package:super_editor/src/default_editor/default_document_editor_reactions.dart:862:13)
#5      PasteEditorCommand._findUrlSpansInText (package:super_editor/src/default_editor/common_editor_operations.dart:2397:21)
#6      PasteEditorCommand._inferAttributionsForLinesOfPastedText (package:super_editor/src/default_editor/common_editor_operations.dart:2370:11)
#7      PasteEditorCommand.execute (package:super_editor/src/default_editor/common_editor_operations.dart:2279:29)
#8      _DocumentEditorCommandExecutor.executeCommand (package:super_editor/src/core/editor.dart:252:15)
#9      Editor._executeCommand (package:super_editor/src/core/editor.dart:195:22)
#10     Editor.execute (package:super_editor/src/core/editor.dart:148:30)
#11     CommonEditorOperations._paste (package:super_editor/src/default_editor/common_editor_operations.dart:2232:12)
```

**Comment by matthew-carroll** [comment]
@miguelcmedeiros I corrected the caret placement when linkifying Markdown while you type - I added that condition to the associated test.

I prevented crashing in the standard non-Markdown pasting behavior. I also found that we weren't positioning the caret at the end of pasted text, so I added a selection change there, too. I updated the paste test to also check selection placement.

Please let me know if you find any other weird behaviors.

**Review by miguelcmedeiros — APPROVED** [review]
LGTM

**Comment by matthew-carroll** [comment]
@angelosilvestre  do you wanna take another review pass on this?

File: super_editor_markdown/lib/src/markdown_inline_upstream_plugin.dart [hunk 1]
```diff
@@ -295,6 +304,66 @@ class _UpstreamInlineMarkdownParser {
...
+      // isn't a link. Short-circuit return.
+      return null;
+    }
+
+    final markdownLinkRegex = RegExp(r'\[([\w\s\d]+)]\(((?:|https?://)[\w\d./?=#]+)\)');
+    final matches = markdownLinkRegex.allMatches(attributedText.text);
+    if (matches.isEmpty) {
+      // Didn't find any links.
+      return null;
+    }
```
Comment (angelosilvestre) [inline super_editor_markdown/lib/src/markdown_inline_upstream_plugin.dart:331]: Would it make sense to run the regex only on the portion after the latest space character? For example, if the paragraph text is `Parse the following link: [mylink](https://www.google.com) `.

We could extract `[mylink](https://www.google.com)` based on the spaces before and after it, them we just try to parse that substring. That way we could avoid running the regex over the whole paragraph. We would also make sure that the parsed link is immediately upstream.

Comment (matthew-carroll) [reply super_editor_markdown/lib/src/markdown_inline_upstream_plugin.dart:331]: I thought about that, but I don't actually have a good rule to extract the link. For example, what if the link starts like this " [this is my link](...)"?

Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown_inline_upstream_plugin.dart:331]: Understood. 

Maybe we could walk backwards, when we find an empty space:

* If we didn't find any `]` while walking backwards, extract the substring.
* If we found a `]` while walking backwards, keep walking backwards until we find a matching `[`.

Do you think this it would worth the effort?

Comment (matthew-carroll) [reply super_editor_markdown/lib/src/markdown_inline_upstream_plugin.dart:331]: Probably not worth it at this point. I think we can adjust the behavior later if this ends up being too costly. This check should only be running on at most a single paragraph at a time, and only when the user just typed a space.

Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown_inline_upstream_plugin.dart:331]: Ok then.

Comment (matthew-carroll) [reply super_editor_markdown/lib/src/markdown_inline_upstream_plugin.dart:331]: Please let me know if you have anything else for the review.

**Review by angelosilvestre — APPROVED** [review]
LGTM
