### PR TITLE
[SuperEditor][SuperTextField] Avoid handling non-text deltas in the same frame we set the editing state (Resolves #930, #971, #970)

### LINKED ISSUE #930: [SuperEditor] - Non-fatal error in example app
Repro: Launch the Mac desktop version of the example app. Immediately tap near the top of the window to drag the window around.

Result: an error appears in the logs.

```
======== Exception caught by services library ======================================================
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: Couldn't map an IME position to a document position. IME position: TextPosition(offset: 122, affinity: TextAffinity.downstream)

When the exception was thrown, this was the stack: 
#0      DocumentImeSerializer._imeToDocumentPosition (package:super_editor/src/default_editor/document_ime/document_serialization.dart:252:5)
#1      DocumentImeSerializer.imeToDocumentSelection (package:super_editor/src/default_editor/document_ime/document_serialization.dart:161:13)
#2      TextDeltasDocumentEditor._applyNonTextChange (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:167:7)
#3      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:46:9)
#4      DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:336:30)
#5      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1867:63)
#6      TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1753:20)
#7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:555:55)
#8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:548:34)
#9      _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:393:35)
#10     _invoke2 (dart:ui/hooks.dart:183:13)
#11     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:40:5)
#12     _Channel.push (dart:ui/channel_buffers.dart:130:31)
#13     ChannelBuffers.push (dart:ui/channel_buffers.dart:326:17)
#14     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:664:22)
#15     _dispatchPlatformMessage (dart:ui/hooks.dart:86:31)
call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{selectionBase: 122, oldText: We hope you enjoy using Super Editor. Let us know what you're building, and please file issues for any bugs that you find., selectionAffinity: TextAffinity.downstream, deltaEnd: 0, deltaText: , deltaStart: 0, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 122, composingBase: -1}]}])
====================================================================================================

```

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][SuperTextField] Avoid handling non-text deltas in the same frame we set the editing state. Resolves #930,  #971, #970.

In some platforms, like macOS, whenever we call `setEditingState`, the engine sends us back a `TextEditingDeltaNonTextUpdate` to sync its state. We are always handling `TextEditingDeltaNonTextUpdate`s to change our selection, so this behavior causes various problems related to the selection, including some infinite loops.

We have no way to know if the `TextEditingDeltaNonTextUpdate` means that the selection/composing region changed, or if it means that the engine is trying to sync its state. I filed https://github.com/flutter/flutter/issues/118759 to track this.

This PR changes the IME code of both SuperEditor and SuperTextField to avoid handling `TextEditingDeltaNonTextUpdate` in the same frame we call `setEditingState`. By doing this we avoid selection bugs and the software keyboard gestures (swipe keyboard to change the selection, etc...) still work.

I also found a bug in `_updatePlatformImeValueWithDeltas` which caused the issue mentioned in #970

### CODE REVIEW

**Comment by raulmabe-labhouse** [comment]
I tested your fix on `_updatePlatformImeValueWithDeltas` and it also resolves #969 😄

**Comment by angelosilvestre** [comment]
@raulmabe-labhouse Great! Thanks for letting us know.

File: super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart [hunk 1]
```diff
@@ -185,16 +188,23 @@ class DocumentImeInputClient extends TextInputConnectionDecorator with TextInput
       editorImeLog.fine("$delta");
     }
 
+    final allowedDeltas = _allowNonTextDeltas
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart:191]: Let's definitely comment what we're doing here and why. Future developers would drive themselves nuts trying to figure out why we're throwing away some deltas.

File: super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart [hunk 2]
```diff
@@ -223,6 +233,21 @@ class DocumentImeInputClient extends TextInputConnectionDecorator with TextInput
       return;
     }
 
+    // In some platforms, like macOS, whenever we call setEditing state, the engine send us back a
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart:236]: "setEditing state" -> "`setEditingState()`"

File: super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart [hunk 3]
```diff
@@ -223,6 +233,21 @@ class DocumentImeInputClient extends TextInputConnectionDecorator with TextInput
...
+    //
+    // We have no way to know if the delta means that the selection/composing region changed,
+    // or if it means that the engine is syncing its state.
+    //
+    // If we always handle the non-text deltas, we might end up in an endless loop of deltas.
+    // To avoid this, we don't handle any non-text deltas until the next frame, after we call setEditingState.
+    //
+    // Remove this as soon as https://github.com/flutter/flutter/issues/118759 is resolved.
+    _allowNonTextDeltas = false;
+    WidgetsBinding.instance.addPostFrameCallback((timeStamp) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart:247]: It's not immediately clear to me how this frame scheduling helps. Initially, I would have expected the call to `setEditingState()` to be moved to the next frame. Instead, we're just altering a variable. What effect does that have?

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart:247]: When we call `setEditingState`, `updateEditingValueWithDeltas` is called on the same frame with the "confirmation" delta. So we change `_allowNonTextDeltas` to `false` to avoid handling non-text deltas on the current frame.

At the end of the current frame, we set `_allowNonTextDeltas` to `true` to allow handling "real" non-text deltas.

File: super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart:197]: Comment added.

**Comment by angelosilvestre** [comment]
This PR also fixed https://github.com/superlistapp/super_editor/issues/979.

**Review by matthew-carroll — APPROVED** [review]
LGTM
