### PR TITLE
fixes shift+tab exception for non ListItemNode

### LINKED ISSUE #364: [bug] shift + tab throws an Exception when pressed outside in non-ListItemNode
To reproduce:
- put the selection on a paragraph
- press shift + tab

```
The following _CastError was thrown while processing the key message handler:
type 'ParagraphNode' is not a subtype of type 'ListItemNode' in type cast
```

Expected Behavior:
The key event should be ignored for non-ListItemNode and propagate to the rest of the keyboardActions/app.

### PR DESCRIPTION
**Pull request by osaxma**
fixes #364 

I added a condition for `unindentListItem` to skip `shift + tab` if the node isn't a `ListItemNode`

### CODE REVIEW

File: super_editor/lib/src/default_editor/common_editor_operations.dart [hunk 1]
```diff
@@ -1807,7 +1807,7 @@ class CommonEditorOperations {
 
     final baseNode = editor.document.getNodeById(composer.selection!.base.nodeId);
     final extentNode = editor.document.getNodeById(composer.selection!.extent.nodeId);
-    if (baseNode!.id != extentNode!.id) {
+    if (baseNode!.id != extentNode!.id || baseNode is! ListItemNode) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/common_editor_operations.dart:1810]: Thanks for the fix. Can you do me a favor and make these 2 different if-statements? Throughout the code like this, you'll see that I generally keep independent conditions in independent if-statements. I think this makes it much easier for developers to quickly audit the various conditions that reject a behavior, rather than requiring very careful reading of unrelated conditions in a single if-statement.

Comment (osaxma) [reply super_editor/lib/src/default_editor/common_editor_operations.dart]: Makes sense. The statement is split now.

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Comment by osaxma** [comment]
Hi @matthew-carroll 

Just in case you're waiting for me to merge this, I can't do that btw. 

Screen Shot 2021-12-30 at 6 26 28 AM

**Comment by matthew-carroll** [comment]
Sorry, I thought GitHub allowed that with an appropriate admin approval. I'll merge this in.
