### PR TITLE
[attributed_text] Fix exception in hasAttributionsWithin (Resolves #1201)

### LINKED ISSUE #1201: [attributed_text] AttributedSpans.hasAttributionsWithin incorrectly throws as it incorrectly iterates over a Set of attributes
The method AttributedSpans.hasAttributionsWithin iterates over a Set of attributes it want's to check and removes removes entries from this Set while iterating. This throws an exception (ConcurrentModificationError) as the iterator cannot be used after removing entries from the underlying it. This is a simple algorithmic bug / invalid usage of a set and it's iterator.

Here is the fix for this issue: https://github.com/superlistapp/super_editor/pull/1202
(previous pull request without a unit test was: https://github.com/superlistapp/super_editor/pull/1188)

### PR DESCRIPTION
**Pull request by angelosilvestre**
[attributed_text] Fix exception in hasAttributionsWithin. Resolves #1201.

This PR is built on top of https://github.com/superlistapp/super_editor/pull/1202

`hasAttributionsWithin` incorrectly removes attributions while iterating over a `Set`. This causes an exception when looking for multiple attributions at the same time.

This PR changes the method to only remove the attributions after iterating.

### CODE REVIEW

File: attributed_text/lib/src/attributed_spans.dart [hunk 1]
```diff
@@ -65,15 +65,19 @@ class AttributedSpans {
...
     for (int i = start; i <= end; ++i) {
+      final foundAttributions = <Attribution>{};
       for (final attribution in attributionsToFind) {
         if (hasAttributionAt(i, attribution: attribution)) {
-          attributionsToFind.remove(attribution);
-        }
-
-        if (attributionsToFind.isEmpty) {
-          return true;
+          // Add the attribution to be removed later.
```
Comment (matthew-carroll) [inline attributed_text/lib/src/attributed_spans.dart:71]: This comment doesn't make much sense to me. Can we get a better explanation?

File: attributed_text/test/attributed_spans_test.dart [hunk 2]
```diff
@@ -157,6 +157,52 @@ void main() {
...
+            true);
+
+        expect(
+          spans.hasAttributionsWithin(attributions: {
+            ExpectedSpans.bold,
+            ExpectedSpans.strikethrough,
+          }, start: 0, end: 4),
+          false,
+        );
+      });
```
Comment (matthew-carroll) [inline attributed_text/test/attributed_spans_test.dart:205]: Please add a blank line after the test.

File: attributed_text/lib/src/attributed_spans.dart (hunk 1 above)
Comment (angelosilvestre) [reply attributed_text/lib/src/attributed_spans.dart]: Updated. Please take a look if it's more clear now.

**Review by matthew-carroll — APPROVED** [review]
LGTM
