### PR TITLE
Bugfix: caret no longer gets stuck in middle of emojis when moving left/right (Resolves #391)

### LINKED ISSUE #391: Exception thrown when cursor when placing the caret before an emoji
Steps to reproduce:
* Paste an emoji into a document (e.g. ❤️)
* Place the caret before the emoji
* Press left-arrow key

Then the following exception is thrown:

```
======== Exception caught by widgets library =======================================================
The following StateError was thrown building BlinkingTextCaret(dirty, state: _BlinkingTextCaretState#a81f5):
Bad state: No element

When the exception was thrown, this was the stack: 
#0      List.first (dart:core-patch/growable_array.dart:339:5)
#1      SuperSelectableTextState.getCharacterBox (package:super_editor/src/infrastructure/super_selectable_text.dart:292:10)
#2      SuperSelectableTextState.getLineHeightAtPosition (package:super_editor/src/infrastructure/super_selectable_text.dart:224:12)
#3      _BlinkingTextCaretState.build (package:super_editor/src/infrastructure/caret.dart:40:42)
#4      StatefulElement.build (package:flutter/src/widgets/framework.dart:4716:27)
#5      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4599:15)
#6      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4774:11)
#7      Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#8      StatefulElement.update (package:flutter/src/widgets/framework.dart:4806:5)
#9      Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#10     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6141:14)
#11     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#12     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5637:32)
#13     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6295:17)
#14     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#15     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6141:14)
#16     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#17     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6141:14)
#18     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#19     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#20     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4774:11)
#21     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#22     StatefulElement.update (package:flutter/src/widgets/framework.dart:4806:5)
#23     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#24     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#25     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4774:11)
#26     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#27     StatefulElement.update (package:flutter/src/widgets/framework.dart:4806:5)
#28     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#29     RenderObjectElement.updateChildren (package:flutter/src/widgets/framework.dart:5637:32)
#30     MultiChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6295:17)
#31     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#32     SingleChildRenderObjectElement.update (package:flutter/src/widgets/framework.dart:6141:14)
#33     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#34     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#35     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4774:11)
#36     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#37     StatefulElement.update (package:flutter/src/widgets/framework.dart:4806:5)
#38     Element.updateChild (package:flutter/src/widgets/framework.dart:3381:15)
#39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4624:16)
#40     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4774:11)
#41     Element.rebuild (package:flutter/src/widgets/framework.dart:4322:5)
#42     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2589:33)
#43     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:882:21)
#44     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:363:5)
#45     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1145:15)
#46     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1082:9)
#47     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:996:5)
#51     _invoke (dart:ui/hooks.dart:151:10)
#52     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:308:5)
#53     _drawFrame (dart:ui/hooks.dart:115:31)
(elided 3 frames from dart:async)
====================================================================================================
```

### PR DESCRIPTION
**Pull request by matthew-carroll**
Bugfix: caret no longer gets stuck in middle of emojis when moving left/right (Resolves #391)

#391 said errors were being thrown. I wasn't able to reproduce any errors by selecting emojis on desktop in the example app. However, the caret was getting stuck in the middle of emojis because we were moving by code point rather than by character. This PR adds machinery to all `String`s to move by character, and updates the keyboard handler to use the new behavior.

@miguelcmedeiros please let me know if you're still seeing any errors or related problems with emojis.

### CODE REVIEW

File: super_editor/lib/src/infrastructure/strings.dart [hunk 1]
```diff
@@ -0,0 +1,174 @@
...
+  /// one word upstream from the given [textOffset] code point index.
+  ///
+  /// Examples:
+  ///   |word up -> `null`
+  ///   wo|rd up -> `0`
+  ///   word| up -> `0`
+  ///   word |up -> `4`
+  ///   word up| -> `6`
+  int? moveOffsetUpstreamByWord(int textOffset, {int characterCount = 1}) {
+    if (textOffset < 0 || textOffset > length) {
```
Comment (miguelcmedeiros) [inline super_editor/lib/src/infrastructure/strings.dart:14]: Shouldn't we throw if `textOffset` is equal to `length`?
(same comment for the other 3 methods)

**Review by miguelcmedeiros — APPROVED** [review]
Code looks great (1 small comment).

While testing, I noticed weird behaviour with the caret height:
ezgif com-gif-maker-4
The caret height on the left side of the emoji is larger than on the right side and the remaining of the paragraph. 
I'm opening a new issue for this, but just wanted to bring this up.

LGTM

File: super_editor/lib/src/infrastructure/strings.dart (hunk 1 above)
Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/strings.dart:14]: I don't think so. A `textOffset` that equals the length represents a caret at the very end of the text. If we throw an exception then we'll need to add special handling to any code whose caret is sitting at the end. This is the same reason that we return`null` at the beginning of the text, instead of throwing an exception.
