### PR TITLE
Fix BlinkController not notifying its listeners when it stops blinking (Resolves #523)

### LINKED ISSUE #523: Potential bug in the `CaretBlinkController` implementation
I am reviewing the `super_editor` repo to get familiar with it, and I have found a couple of potential issues with the `CaretBlinkController` in the following places:

- https://github.com/superlistapp/super_editor/blob/main/super_text/lib/src/caret.dart#L299-L302
  Where a `notifyListeners` call is missing after setting `_isVisible` to `true`.

  ```dart
  void stopBlinking() {
    _isVisible = true; // If we're not blinking then we need to be visible
    _stopTimer();
  }
  ```

- https://github.com/superlistapp/super_editor/blob/main/super_text/lib/src/caret.dart#L311-L326
  Where a `notifyListeners` call is also missing after setting `_isVisible` to `true`.

  ```dart
  /// Clients should call this method whenever the caret moves within
  /// the content so that the caret is made fully opaque and the blink
  /// timer restarts.
  void onCaretMoved() {
    // Immediately make the caret visible whenever the position
    // changes, e.g., when the user adds/removes a character.
    _isVisible = true;

    _timer?.cancel();

    if (!_isBlinkingEnabled) {
      return;
    }

    _startTimer();
  }
  ```

### PR DESCRIPTION
**Pull request by angelosilvestre**
`BlinkController` was not calling `notifyListeners` when `stopBlinking` was called. Resolves https://github.com/superlistapp/super_editor/issues/523

As `_CaretPainter` uses its blinkController as a repaint `Listenable`, it's necessary to call `notifyListeners` to cause `_CaretPainter` to repaint.

I added tests to ensure both `stopBlinking` and `startBlinking` cause the listeners to be notified

### CODE REVIEW

File: super_text_layout/test/blink_controller_test.dart [hunk 1]
```diff
@@ -0,0 +1,73 @@
+import 'package:flutter/src/scheduler/ticker.dart';
+import 'package:flutter_test/flutter_test.dart';
+import 'package:super_text_layout/src/infrastructure/blink_controller.dart';
+
+void main() {
+  group("BlinkController", () {
+    testWidgets("should notify its listeners when it stops blinking", (tester) async {
```
Comment (matthew-carroll) [inline super_text_layout/test/blink_controller_test.dart:7]: A minor nitpick about wording: when possible, prefer statements about what something does, rather than what it should do -> `notifies listeners when it stops blinking`.

File: super_text_layout/test/blink_controller_test.dart [hunk 2]
```diff
@@ -0,0 +1,73 @@
...
+    testWidgets("should notify its listeners when it starts blinking", (tester) async {
+      // duration to switch between visible and invisible
+      const flashPeriod = Duration(milliseconds: 500);
+
+      bool hasNotifiedItsListeners = false;      
+      
+      // Create a fake ticker provider to be able to manually trigger a tick
+      final tickerProvider = _TestSingleTickerProvider();          
+      final blinkController = BlinkController(
+        tickerProvider: tickerProvider,
```
Comment (matthew-carroll) [inline super_text_layout/test/blink_controller_test.dart:30]: Can you pass the `WidgetTester` as the `TickerProvider` and then use `pump(Duration(...))`?

File: super_text_layout/test/blink_controller_test.dart [hunk 3]
```diff
@@ -0,0 +1,73 @@
...
+        hasNotifiedItsListener = true;
+      });      
+      
+      blinkController.stopBlinking();
+      
+      // Ensure that the callback was called
+      expect(hasNotifiedItsListener, true);
+    });
+
+    testWidgets("should notify its listeners when it starts blinking", (tester) async {
```
Comment (matthew-carroll) [inline super_text_layout/test/blink_controller_test.dart:21]: I think this test is really verifying that `notifies listeners every time it blinks`, which I think is different than `notifies listeners when it starts blinking`. Both of those deserve tests, so this test shouldn't be removed, but I think testing the `starts blinking` case requires first stopping the controller, then starting it again. I think we want/expect the controller to immediately notify listeners when it starts again, even before the first blink.

**Review by matthew-carroll — COMMENTED** [review]
Thanks for the explanation of the problem in the PR writeup. I have a few comments for the tests, and I think we may need to add one more notification to the implementation.

**Review by matthew-carroll — APPROVED** [review]
LGTM, thanks.
