### PR TITLE
[SuperEditor][Android] Fix IME mappings on text replacements (Resolves #1217)

### LINKED ISSUE #1217: [Android] (DocumentImeSerializer._imeToDocumentPosition) Couldn't map an IME position to a document position - Editor Freezes
We started to get feedback from our first major rollout of SE to android (we've been in production ios/mac os for upwards of a year now with no issues, something we are extremely grateful for, really incredible work).  This error is associated with the crash event, and it is the same base error reported in #1081.

There is common behavior reported throughout every user we have been able to individually contact tagged on this event: the editor stops taking input and it must be closed and then reopened in order to continue editing the document (in our case referred to as an "entry").

This is the average report:

> After a short period, text will fail to appear as I'm typing. Fixed by coming out of the editor and going back in. But the problem will repeat resulting in having to go in and out several times to complete the entry.

So far, there doesn't seem to be any one specific action / repro that triggers the crash, but rather a myriad of various common editing actions:

**- adding a bulleted list**

The user adds a bullet list item and can no longer advance to the next line:

https://github.com/superlistapp/super_editor/assets/37011672/f6415536-b2b0-40c6-9baf-da56b45750f5

**- in some cases, adding a new line**

The user types "Happy", applies rich-text formatting (header), and then moves to the next line:

https://github.com/superlistapp/super_editor/assets/37011672/35526d0c-718f-401b-8f74-0023444e47fa

**- special characters associated with non-English languages**

>  Today I noticed a pattern. The editor freezed after writing "ão" (common in Portuguese words) It happened 2 times and in each of them I had to checkmark, close and open again to continue writing.

**- after autocorrection of a typo**

The user misspells "waves" (~1:17) and the word is auto-corrected, then the editor freezes.

https://github.com/superlistapp/super_editor/assets/37011672/db03b42c-df0e-41bc-ba1a-a021a4334d70

**- manually accepting keyboard text suggestions**

The user accepts text suggestion of the word "anonymous"

https://github.com/superlistapp/super_editor/assets/37011672/f7a572aa-8000-4d34-a61b-05fff5bde8ee

The user accepts text suggestion of the word "issues" (~:25)

https://github.com/superlistapp/super_editor/assets/37011672/c13e7a4a-c159-4b28-9ac4-e340772ab565

Below are logs of six separate variants of the same error in order of most to least common:

Variant 1
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
Exception: Couldn't map an IME position to a document position. TextEditingValue: '[redacted]' IME position: TextPosition(offset: 251, affinity: TextAffinity.downstream). Error thrown Instance of 'ErrorDescription'.
DocumentImeSerializer._imeToDocumentPosition (document_serialization.dart:271)
DocumentImeSerializer.imeToDocumentSelection (document_serialization.dart:164)
TextDeltasDocumentEditor._applyInsertion (document_delta_editing.dart:133)
TextDeltasDocumentEditor.applyDeltas (document_delta_editing.dart:69)
DocumentImeInputClient.updateEditingValueWithDeltas (document_ime_communication.dart:215)
DeltaTextInputClientDecorator.updateEditingValueWithDeltas (ime_decoration.dart:119)
TextInput._handleTextInputInvocation (text_input.dart:1867)
TextInput._loudlyHandleTextInputInvocation (text_input.dart:1753)
MethodChannel._handleAsMethodCall (platform_channel.dart:555)
MethodChannel.setMethodCallHandler.<fn> (platform_channel.dart:548)
_DefaultBinaryMessenger.setMessageHandler.<fn> (binding.dart:393)
```

Variant 2
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError
Exception: Couldn't map an IME position to a document position. TextEditingValue: '[redacted]' IME position: TextPosition(offset: 129, affinity: TextAffinity.downstream). Error thrown Instance of 'ErrorDescription'.
DocumentImeSerializer._imeToDocumentPosition (document_serialization.dart:271)
DocumentImeSerializer.imeToDocumentSelection (document_serialization.dart:164)
TextDeltasDocumentEditor._applyInsertion (document_delta_editing.dart:133)
TextDeltasDocumentEditor.applyDeltas (document_delta_editing.dart:69)
DocumentImeInputClient.updateEditingValueWithDeltas (document_ime_communication.dart:215)
DeltaTextInputClientDecorator.updateEditingValueWithDeltas (ime_decoration.dart:119)
TextInput._handleTextInputInvocation (text_input.dart:1867)
TextInput._loudlyHandleTextInputInvocation (text_input.dart:1753)
MethodChannel._handleAsMethodCall (platform_channel.dart:555)
MethodChannel.setMethodCallHandler.<fn> (platform_channel.dart:548)
_DefaultBinaryMessenger.setMessageHandler.<fn> (binding.dart:393)
```

Variant 3
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Exception: Couldn't map an IME position to a document position. 
TextEditingValue: '[redacted] '
IME position: TextPosition(offset: 132, affinity: TextAffinity.downstream). Error thrown Instance of 'ErrorDescription'.
       at DocumentImeSerializer._imeToDocumentPosition(document_serialization.dart:271)
       at DocumentImeSerializer.imeToDocumentSelection(document_serialization.dart:164)
       at TextDeltasDocumentEditor._applyNonTextChange(document_delta_editing.dart:211)
       at TextDeltasDocumentEditor.applyDeltas(document_delta_editing.dart:75)
       at DocumentImeInputClient.updateEditingValueWithDeltas(document_ime_communication.dart:215)
       at DeltaTextInputClientDecorator.updateEditingValueWithDeltas(ime_decoration.dart:119)
       at TextInput._handleTextInputInvocation(text_input.dart:1867)
       at TextInput._loudlyHandleTextInputInvocation(text_input.dart:1753)
       at MethodChannel._handleAsMethodCall(platform_channel.dart:555)
       at MethodChannel.setMethodCallHandler.<fn>(platform_channel.dart:548)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(binding.dart:393)
```

Variant 4
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Exception: Couldn't map an IME position to a document position. 
TextEditingValue: '[redacted] '
IME position: TextPosition(offset: 128, affinity: TextAffinity.downstream). Error thrown Instance of 'ErrorDescription'.
       at DocumentImeSerializer._imeToDocumentPosition(document_serialization.dart:271)
       at DocumentImeSerializer.imeToDocumentSelection(document_serialization.dart:164)
       at TextDeltasDocumentEditor.delete(document_delta_editing.dart:311)
       at TextDeltasDocumentEditor._applyDeletion(document_delta_editing.dart:198)
       at TextDeltasDocumentEditor.applyDeltas(document_delta_editing.dart:73)
       at DocumentImeInputClient.updateEditingValueWithDeltas(document_ime_communication.dart:215)
       at DeltaTextInputClientDecorator.updateEditingValueWithDeltas(ime_decoration.dart:119)
       at TextInput._handleTextInputInvocation(text_input.dart:1867)
       at TextInput._loudlyHandleTextInputInvocation(text_input.dart:1753)
       at MethodChannel._handleAsMethodCall(platform_channel.dart:555)
       at MethodChannel.setMethodCallHandler.<fn>(platform_channel.dart:548)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(binding.dart:393)
```

Variant 5
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Exception: Couldn't map an IME position to a document position. 
TextEditingValue: '[redacted]'
IME position: TextPosition(offset: 4, affinity: TextAffinity.downstream). Error thrown Instance of 'ErrorDescription'.
       at DocumentImeSerializer._imeToDocumentPosition(document_serialization.dart:271)
       at DocumentImeSerializer.imeToDocumentRange(document_serialization.dart:220)
       at TextDeltasDocumentEditor.applyDeltas(document_delta_editing.dart:89)
       at DocumentImeInputClient.updateEditingValueWithDeltas(document_ime_communication.dart:215)
       at DeltaTextInputClientDecorator.updateEditingValueWithDeltas(ime_decoration.dart:119)
       at TextInput._handleTextInputInvocation(text_input.dart:1867)
       at TextInput._loudlyHandleTextInputInvocation(text_input.dart:1753)
       at MethodChannel._handleAsMethodCall(platform_channel.dart:555)
       at MethodChannel.setMethodCallHandler.<fn>(platform_channel.dart:548)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(binding.dart:393)
```

Variant 6
```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Exception: Couldn't map an IME position to a document position. 
TextEditingValue: '[redacted]'
IME position: TextPosition(offset: 316, affinity: TextAffinity.downstream). Error thrown Instance of 'ErrorDescription'.
       at DocumentImeSerializer._imeToDocumentPosition(document_serialization.dart:271)
       at DocumentImeSerializer.imeToDocumentSelection(document_serialization.dart:164)
       at TextDeltasDocumentEditor.replace(document_delta_editing.dart:283)
       at TextDeltasDocumentEditor._applyReplacement(document_delta_editing.dart:184)
       at TextDeltasDocumentEditor.applyDeltas(document_delta_editing.dart:71)
       at DocumentImeInputClient.updateEditingValueWithDeltas(document_ime_communication.dart:215)
       at DeltaTextInputClientDecorator.updateEditingValueWithDeltas(ime_decoration.dart:119)
       at TextInput._handleTextInputInvocation(text_input.dart:1867)
       at TextInput._loudlyHandleTextInputInvocation(text_input.dart:1753)
       at MethodChannel._handleAsMethodCall(platform_channel.dart:555)
       at MethodChannel.setMethodCallHandler.<fn>(platform_channel.dart:548)
       at _DefaultBinaryMessenger.setMessageHandler.<fn>(binding.dart:393)
```

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][Android] Fix IME mappings on text replacements. Resolves #1217

There are different issues in the ticket:

1. On Android, accepting keyboard text suggestions sometimes causes the editor to crash due to an IME mapping failure. Most of the examples listed in the ticket seem to be caused by the same problem.

This seems to happen when the IME sends a replacement text bigger than the replaced text and an insertion in the same list. This is causing us to fail to map the position for the insertion. I noticed that this happens only when using the Samsung keyboard. When using GBoard, the IME generates a deletion followed by an insertion instead of a replacement.

This PR changes our replacement handling to reset `_serializedDoc` the same way we do when handling insertions.

2. Pressing the ENTER key in a list item has no effect:

This seems to be the same issue as https://github.com/superlistapp/super_editor/issues/1157, which has an open PR https://github.com/superlistapp/super_editor/pull/1184.

3. "The user types "Happy", applies rich-text formatting (header), and then moves to the next line":

I wasn't able to reproduce this issue.

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@angelosilvestre can you please post example of the deltas that you described? It's important that we keep historical records of real-world deltas that we run into.

File: super_editor/test/src/default_editor/document_input_ime_test.dart [hunk 1]
```diff
@@ -573,6 +573,57 @@ Paragraph two
       });
     });
 
+    group('on Samsung M51 (Android 12 SP1A)', () {
+      testWidgetsOnAndroid('applies replacements followed by insertions in the same delta list', (tester) async {
```
Comment (matthew-carroll) [inline super_editor/test/src/default_editor/document_input_ime_test.dart:577]: I'm not sure this name helps us much. What's the situation that's happening when these deltas are sent?

File: super_editor/test/src/default_editor/document_input_ime_test.dart [hunk 2]
```diff
@@ -573,6 +573,57 @@ Paragraph two
...
+            composing: TextRange(start: -1, end: -1),
+          )
+        ], getter: imeClientGetter);
+
+        expect(
+          SuperEditorInspector.findTextInParagraph('1').text,
+          'Anonymous ',
+        );
+      });
+    });
```
Comment (matthew-carroll) [inline super_editor/test/src/default_editor/document_input_ime_test.dart:625]: Wasn't there a GBoard situation related to this, too? Shouldn't we have a test with those deltas, too?

**Comment by angelosilvestre** [comment]
@matthew-carroll Typing "Testing the uss" and accepting a suggestion to replace "uss" with "issue":

Typing the last "s" in the original sentence:

```dart
[
  TextEditingDeltaInsertion(
      oldText: 'Testing the us',
      textInserted: 's',
      insertionOffset: 14,
      selection: TextSelection.collapsed(offset: 15, affinity: TextAffinity.downstream),
      composing: TextRange(start: 12, end: 15),
    ),
]
```

Accepting the suggestions (deltas received in a single call to `updateEditingValueWithDeltas`:

```dart
[
   TextEditingDeltaReplacement(
      oldText: 'Testing the uss',      
      replacementText: 'issue',
      replacedRange: TextRange(start: 12, end: 15),
      selection: TextSelection.collapsed(offset: 17, affinity: TextAffinity.downstream),
      composing: TextRange(start: -1, end: -1),
    ),
    TextEditingDeltaInsertion(
      oldText: 'Testing the issue',
      textInserted: ' ',
      insertionOffset: 17,
      selection: TextSelection.collapsed(
        offset: 18,
        affinity: TextAffinity.downstream,
      ),
      composing: TextRange(start: -1, end: -1),
    ),
]
```

File: super_editor/test/src/default_editor/document_input_ime_test.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/test/src/default_editor/document_input_ime_test.dart]: Updated.

File: super_editor/test/src/default_editor/document_input_ime_test.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/test/src/default_editor/document_input_ime_test.dart:625]: Added a test simulating GBoard behavior.

**Review by matthew-carroll — APPROVED** [review]
LGTM
