### PR TITLE
[Quill] - Fix exceptions when parsing ambiguous custom block formats (Resolves #2286)

### LINKED ISSUE #2286: [Quill] - Bug: block deserialization formats blow up if assumptions not met
When deserializing block formats, we make certain assumptions that can blow up under certain reasonable circumstances.

Example: Consider a custom block format with an embedded list property:

```
{
  "list": {
    "list": "ordered"
  }
}
```

Compare the custom block format to the standard Delta list item format:

```
{
  "list": "ordered"
}
```

Both of these are allowed. Yet, if we send the custom delta through the default block formats, we get an exception because the list item delta parser expects the value of "list" to be a `String`.

### PR DESCRIPTION
**Pull request by matthew-carroll**
[Quill] - Fix exceptions when parsing ambiguous custom block formats (Resolves #2286)

When implementing a custom Delta format that happens to have the same key as a standard format, e.g., "list", we were blowing up with an exception because the standard format assumed the wrong value type for the given key.

### CODE REVIEW

File: super_editor_quill/test/parsing_test.dart [hunk 1]
```diff
@@ -565,5 +565,114 @@ void main() {
...
+                "align": "left",
+              },
+            },
+            "insert": "\n"
+          },
+          {"insert": "Paragraph six\n"},
+        ]);
+
+        // If we get here without an exception, the test passes. This means that
+        // the standard
```
Comment (angelosilvestre) [inline super_editor_quill/test/parsing_test.dart:633]: It seems this sentence is incomplete.

**Review by angelosilvestre — COMMENTED** [review]
LGTM with a minor comment.
