### PR TITLE
[SuperEditor][Android] Hide expanded drag handles after deleting the selected text (Resolves #1936)

### LINKED ISSUE #1936: Exception thrown when dragging Android handles after `cut` or regular delete
**Package Version**
`main`

**To Reproduce**
The behavior can be reproduced in the example application.

1. Run example application on an Android device
2. Select text
3. Select cut from editing toobar
4. See non-collapsed text selection handles
5. Attempt to drag one
7. Observe `Exception: Tried to drag an expanded Android handle but the selection is collapsed.` followed by `Exception: Tried to pan an Android drag handle but the focal point is null. The focal point is set when the drag begins. This shouldn't be possible.`

The same behavior can be observed if the selected text is removed via backspace not just cut.

Additionally, when text is cut or deleted and you type something, the text selection handlers continue to indicate an uncollapsed selection even though it is actually collapsed.

**Actual behavior**
The selection handlers indicate a non-collapsed document selection and it seems other parts of super_editor don't expect this.

**Expected behavior**
After cut or deletion, the selection handlers should probably be removed or collapsed.

**Platform**
Android

**Flutter version**
```
Flutter 3.19.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 300451adae (3 weeks ago) • 2024-03-27 21:54:07 -0500
Engine • revision e76c956498
Tools • Dart 3.3.3 • DevTools 2.31.1
```

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][Android] Hide expanded drag handles after deleting the selected text. Resolves #1936

On Android with an expanded selection, performing any action that causes text to be deleted, such as cutting, deleting, pasting or typing to replace the text, keeps the expanded handles visible. Trying to drag those handles throws an exception:

```console
════════ Exception caught by gesture ═══════════════════════════════════════════
The following _Exception was thrown while handling a gesture:
Exception: Tried to drag an expanded Android handle but the selection is collapsed.
```

The expanded handles are kept visible because of https://github.com/superlistapp/super_editor/pull/1754, where we changed the expanded handles to be allowed to be visible even with a collapsed selection. However, this should happen when the user is dragging the handles, not when the selection collapses due to a deletion.

Looking at other Android apps, it seems that the expected behavior is that no handle should be visible after deleting the selected text, not even the collapsed drag handle.

This PR changes the Android touch interactor to hide the expanded handles and any other controls when text is deleted, causing the selection to collapse. 

We could also implement this by adding a listener directly to the editor and then listening for selection change events. If a better solution would be to find a way to make `shouldShowExpandedHandles` to be `false` if the user is not dragging then I can dig into that.

On iOS this issue doesn't happen, because the expanded handles are never visible when the selection is collapsed. I added the same test I added for android.

### CODE REVIEW

File: super_editor/lib/src/default_editor/document_gestures_touch_android.dart [hunk 1]
```diff
@@ -655,7 +656,38 @@ class _AndroidDocumentTouchInteractorState extends State<AndroidDocumentTouchInt
     widget.dragHandleAutoScroller.value!.ensureOffsetIsVisible(extentOffsetInViewport);
   }
 
-  void _onDocumentChange(_) {
+  void _onDocumentChange(DocumentChangeLog changeLog) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_gestures_touch_android.dart:659]: My initial thought is that this a backwards place to recognize such a situation. We have various Android-specific widgets and configurations for the UI. The UI is where the user's interaction originates. Is there not a much simpler location in the Android-specific UI where we can recognize this situation, rather than try to reconstruct our knowledge of it after the fact?

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_gestures_touch_android.dart:659]: I don't think so, even though we can hide the controls in the `cut` handler, for the cases where the user presses the backspace button, or type when the selection is expanded, the IME will generate deltas that will modify the document, without any user interaction with the app. The user interaction in this case is only with the software keyboard.

Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_gestures_touch_android.dart:659]: When the handles rebuild for the new collapsed selection, doesn't the Android interactor know that the user isn't currently dragging a handle, and therefore knows that we should collapse the handles?

**Comment by matthew-carroll** [comment]
@angelosilvestre are you waiting for me on this? It looks like I had an open question.

File: super_editor/lib/src/default_editor/document_gestures_touch_android.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_gestures_touch_android.dart:659]: I'm not sure if I understood where you are suggesting to write this code...

Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_gestures_touch_android.dart:659]: @angelosilvestre can you please frame that as a question? Where are you getting confused?

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_gestures_touch_android.dart:659]: @matthew-carroll I'll take a look at the existing code to frame a question.

**Comment by angelosilvestre** [comment]
@matthew-carroll I modified the implementation as you suggested.

File: super_editor/lib/src/default_editor/document_gestures_touch_android.dart [hunk 2]
```diff
@@ -1363,6 +1370,23 @@ class SuperEditorAndroidControlsOverlayManagerState extends State<SuperEditorAnd
   @visibleForTesting
   bool get wantsToDisplayMagnifier => _controlsController!.shouldShowMagnifier.value;
 
+  void _onDocumentChange(_) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_gestures_touch_android.dart:1373]: It looks like this only moved the problem I identified before. The problem is that you're trying to identify a user interaction through a document change. My original question, which is still my question, is why can't you identify the user interaction when the user interaction happens, instead of after the fact?

This issue says its about "deleting the selected text". I assume that involves an expanded selection, then some kind of keyboard interaction, then a collapsed selection.

Doesn't this widget already know when the selection is expanded, and when the selection is collapsed? Why can't the widget recognize that the selection has collapsed and then hide the expanded handles, without worrying about document changes at all?

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_gestures_touch_android.dart]: Updated.

**Review by matthew-carroll — APPROVED** [review]
LGTM
