### PR TITLE
Changed linkification on paste to match URL parsing within the linkification reaction (Resolves #2031)

### LINKED ISSUE #2031: Inconsistent linkifying behaviour
**Package Version**
commit: 8592c1f6b4cbd77b4b89986a6070939aaa12b336

**To Reproduce**
1. Add a link without http, for example www.google.com by typing it in and click return
2. Paste in the text with the same link inside for example "My link www.google.com pasted in"

**Minimal Reproduction Code**
Reproducible in demo 

**Actual behavior**
First link is linkified but the second is not. When pasting in link is required to start with http, but when typing the link by hand it gets changed even without http.

**Expected behavior**
Behaviour should be consistent 

**Platform**
web, android, iOS

**Flutter version**
3.22

**Screenshots**
Example result

### PR DESCRIPTION
**Pull request by matthew-carroll**
Changed linkification on paste to match URL parsing within the linkification reaction (Resolves #2031)

Linkification when pasting content wasn't recognizing URLs without www and https. This is because we have two different linkification paths. One for pasting, which happens at the moment the text is pasted. Another for reacting to user input.

This PR alters the existing pasting behavior to match the link extraction of the linkification reaction.

I'd like to move linkification entirely into the reaction, but it's not completely clear how to determine whether or not the user pasted the content vs got it some other way. I filed a proposal to add such details to all changes: https://github.com/superlistapp/super_editor/issues/2044

This PR solves the problem without doing a much larger refactor as described in that proposal.

### CODE REVIEW

File: super_editor/test/super_editor/text_entry/links_test.dart [hunk 1]
```diff
@@ -1173,25 +1170,134 @@ void main() {
       // Place the caret at the beginning of the empty document.
       await tester.placeCaretInParagraph("1", 0);
 
-      // Type a URL. It shouldn't linkify until we add a space.
-      await tester.typeImeText("www.google.com");
+      // Type text with two URLs
+      await tester.typeImeText("https://www.google.com and https://flutter.dev ");
```
Comment (angelosilvestre) [inline super_editor/test/super_editor/text_entry/links_test.dart:1174]: Please end the comment with a dot.

File: super_editor/test/super_editor/text_entry/links_test.dart [hunk 2]
```diff
@@ -1173,25 +1170,134 @@ void main() {
...
+      await tester //
+          .createDocument()
+          .withSingleEmptyParagraph()
+          .withInputSource(TextInputSource.ime)
+          .pump();
+
+      // Place the caret at the beginning of the empty document.
+      await tester.placeCaretInParagraph("1", 0);
+
+      // Paste text with a URL
```
Comment (angelosilvestre) [inline super_editor/test/super_editor/text_entry/links_test.dart:1207]: Please end the comment with a dot.

File: super_editor/test/super_editor/text_entry/links_test.dart [hunk 3]
```diff
@@ -1173,25 +1170,134 @@ void main() {
...
+      tester.simulateClipboard();
+      await tester.setSimulatedClipboardContent("Hello https://www.google.com world");
+      // TODO: create and use something like tester.pressPasteAdaptive()
+      if (debugDefaultTargetPlatformOverride == TargetPlatform.macOS) {
+        await tester.pressCmdV();
+      } else {
+        await tester.pressCtlV();
+      }
+
+      // Ensure the URL is linkified
```
Comment (angelosilvestre) [inline super_editor/test/super_editor/text_entry/links_test.dart:1217]: Please end the comment with a dot.

File: super_editor/test/super_editor/text_entry/links_test.dart [hunk 4]
```diff
@@ -1173,25 +1170,134 @@ void main() {
...
+      await tester //
+          .createDocument()
+          .withSingleEmptyParagraph()
+          .withInputSource(TextInputSource.ime)
+          .pump();
+
+      // Place the caret at the beginning of the empty document.
+      await tester.placeCaretInParagraph("1", 0);
+
+      // Paste text with a URL
```
Comment (angelosilvestre) [inline super_editor/test/super_editor/text_entry/links_test.dart:1279]: Please end the comment with a dot.

File: super_editor/test/super_editor/text_entry/links_test.dart [hunk 5]
```diff
@@ -1173,25 +1170,134 @@ void main() {
...
+      tester.simulateClipboard();
+      await tester.setSimulatedClipboardContent("Hello google.com world");
+      // TODO: create and use something like tester.pressPasteAdaptive()
+      if (debugDefaultTargetPlatformOverride == TargetPlatform.macOS) {
+        await tester.pressCmdV();
+      } else {
+        await tester.pressCtlV();
+      }
+
+      // Ensure the URL is linkified
```
Comment (angelosilvestre) [inline super_editor/test/super_editor/text_entry/links_test.dart:1289]: Please end the comment with a dot.

**Review by angelosilvestre — APPROVED** [review]
LGTM
