### PR TITLE
[SuperEditor] Limit tag expansion to caret position (Resolves #2240, #2241, #2242)

### LINKED ISSUE #2240: [BUG] - Exception when deleting composing action tag, then starting new one
**Package Version**
super_editor, GitHub, main branch

**User Info**
coneno, QuikFlow

**To Reproduce**
1. Go to the "Action Tags" section of the example app
2. Type some text
3. Place the cursor in the middle of the text
4. Type "/"
5. Press backspace
6. Type "/" again
7. See exception

**Actual behavior**
```
════════ Exception caught by services library ══════════════════════════════════
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: removeAttribution() did not satisfy start < 0 and start > end, start: 6, end: 5

When the exception was thrown, this was the stack:
#0      AttributedSpans.removeAttribution (package:attributed_text/src/attributed_spans.dart:514:7)
attributed_spans.dart:514
#1      RemoveTextAttributionsCommand.execute (package:super_editor/src/default_editor/text.dart:1444:15)
text.dart:1444
#2      _DocumentEditorCommandExecutor.executeCommand (package:super_editor/src/core/editor.dart:701:15)
editor.dart:701
#3      Editor._executeCommand (package:super_editor/src/core/editor.dart:304:22)
editor.dart:304
#4      Editor.execute (package:super_editor/src/core/editor.dart:266:30)
editor.dart:266
#5      ActionTagComposingReaction._healCancelledTags (package:super_editor/src/default_editor/text_tokenizing/action_tags.dart:364:23)
action_tags.dart:364
#6      ActionTagComposingReaction.react (package:super_editor/src/default_editor/text_tokenizing/action_tags.dart:286:5)
action_tags.dart:286
#7      Editor._reactToChanges (package:super_editor/src/core/editor.dart:357:16)
editor.dart:357
#8      Editor.endTransaction (package:super_editor/src/core/editor.dart:222:5)
editor.dart:222
#9      TextDeltasDocumentEditor.applyDeltas (package:super_editor/src/default_editor/document_ime/document_delta_editing.dart:118:12)
document_delta_editing.dart:118
#10     DocumentImeInputClient.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/document_ime_communication.dart:232:30)
document_ime_communication.dart:232
#11     DeltaTextInputClientDecorator.updateEditingValueWithDeltas (package:super_editor/src/default_editor/document_ime/ime_decoration.dart:129:14)
ime_decoration.dart:129
#12     TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1906:63)
text_input.dart:1906
#13     TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1794:20)
text_input.dart:1794
#14     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:571:55)
platform_channel.dart:571
#15     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:564:34)
platform_channel.dart:564
#16     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:581:35)
binding.dart:581
#17     _invoke2 (dart:ui/hooks.dart:344:13)
hooks.dart:344
#18     _ChannelCallbackRecord.invoke (dart:ui/channel_buffers.dart:45:5)
channel_buffers.dart:45
#19     _Channel.push (dart:ui/channel_buffers.dart:135:31)
channel_buffers.dart:135
#20     ChannelBuffers.push (dart:ui/channel_buffers.dart:343:17)
channel_buffers.dart:343
#21     PlatformDispatcher._dispatchPlatformMessage (dart:ui/platform_dispatcher.dart:750:22)
platform_dispatcher.dart:750
#22     _dispatchPlatformMessage (dart:ui/hooks.dart:257:31)
hooks.dart:257

call: MethodCall(TextInputClient.updateEditingStateWithDeltas, [7, {deltas: [{selectionBase: 8, oldText: . asdfasdf, selectionAffinity: TextAffinity.downstream, deltaEnd: 7, deltaText: /, deltaStart: 7, composingExtent: -1, selectionIsDirectional: false, selectionExtent: 8, composingBase: -1}]}])
════════════════════════════════════════════════════════════════════════════════
```

**Expected behavior**
A new action tag is being composed.

**Platform**
macOS

**Flutter version**
Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (4 weeks ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3

**Screenshots**
Screenshot 2024-08-14 at 13 05 15

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor] Limit tag expansion to caret position. Resolves #2240, #2241, #2242

Steps to reproduce:

1. Go to the "Action Tags" section of the example app
2. Type some text
3. Place the cursor in the middle of the text
4. Type "/"
5. Press backspace
6. Type "/" again

The editor crashes with the following exception:

```console
════════ Exception caught by services library ══════════════════════════════════
The following _Exception was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Exception: removeAttribution() did not satisfy start < 0 and start > end, start: 6, end: 5

When the exception was thrown, this was the stack:
#0      AttributedSpans.removeAttribution (package:attributed_text/src/attributed_spans.dart:514:7)
attributed_spans.dart:514
#1      RemoveTextAttributionsCommand.execute (package:super_editor/src/default_editor/text.dart:1439:15)
text.dart:1439
#2      _DocumentEditorCommandExecutor.executeCommand (package:super_editor/src/core/editor.dart:701:15)
editor.dart:701
#3      Editor._executeCommand (package:super_editor/src/core/editor.dart:304:22)
editor.dart:304
#4      Editor.execute (package:super_editor/src/core/editor.dart:266:30)
editor.dart:266
#5      ActionTagComposingReaction._healCancelledTags (package:super_editor/src/default_editor/text_tokenizing/action_tags.dart:364:23)
action_tags.dart:364
#6      ActionTagComposingReaction.react (package:super_editor/src/default_editor/text_tokenizing/action_tags.dart:286:5)
action_tags.dart:286
#7      Editor._reactToChanges (package:super_editor/src/core/editor.dart:357:16)
editor.dart:357
#8      Editor.endTransaction (package:super_editor/src/core/editor.dart:222:5)
editor.dart:222
... many more
```

While investigating this, I noticed that typing "/" at the middle of the word causes all the text that comes after the "/" to be part of the action tag:

https://github.com/user-attachments/assets/a7e3a359-ad31-494f-8593-ea75c91de951

This doesn't look like is expected.

This PR changes this behavior. Now, the tag is expanded only until the caret position:

https://github.com/user-attachments/assets/f3f79c33-04ca-4f08-bf90-fcd39a74224f

Changing this seems to already fix the issue, and also https://github.com/superlistapp/super_editor/issues/2241 and https://github.com/superlistapp/super_editor/issues/2242

### CODE REVIEW

**Comment by angelosilvestre** [comment]
@alterhuman @KevinBrendel  Would you mind trying this PR?

**Comment by angelosilvestre** [comment]
@alterhuman I fixed the first issue you mentioned. For the second issue, I'm not sure I followed. It doesn't seem to be related to any of the existing issues.

**Comment by angelosilvestre** [comment]
@alterhuman Is this happening on latest main? It doesn't look like it's related to the changes of this PR. If so, can you file a separate issue for this?

File: super_editor/lib/src/default_editor/text_tokenizing/tags.dart [hunk 1]
```diff
@@ -10,11 +10,15 @@ import 'package:super_editor/src/default_editor/text.dart';
 class TagFinder {
   /// Finds a tag that touches the given [expansionPosition] and returns that tag,
   /// indexed within the document, along with the [expansionPosition].
+  ///
+  /// If [endPosition] is provided, the search will be limited to the range between
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/text_tokenizing/tags.dart:14]: I don't understand this description of `endPosition`. This method was intended to only look for tags that touch `expansionPosition`, which is a singular position. There shouldn't be a range involved. So the idea of an `endPosition` doesn't make sense to me.

Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/text_tokenizing/tags.dart:14]: My point was that I don't know what you're trying to do here because it doesn't seem to make sense. I can't answer that question until I first understand what exactly you were trying to do.

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/text_tokenizing/tags.dart:14]: What I'm trying to do is to prevent the tag to expand beyond the caret position. For example, if we have the string "helloworld" and the user types a "/" at the middle, changing it to "hello/world", the string "world" shouldn't be attributed as a tag. The user can input a tag in the middle of a word, but the tag shouldn't expand beyond the caret position.

Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/text_tokenizing/tags.dart:14]: I understand the feature goal. What I don't understand is the code that I commented on. I don't understand how/why achieving the feature goal that you described requires a caller to pass some thing called an "end position". Can you explain what this approach is doing and why it makes sense for the feature goal?

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/text_tokenizing/tags.dart:14]: `TagFinder.findTagAroundPosition` always returns the range from the trigger character to the end of the word. In this example, typing "/" in the middle of the word results in the following:

```
hello/world
     |      caret
     ^^^^^^ tag attribution
```

With the changes in this PR, the text will be attributed only from the trigger char until the caret position, so it would be:

```
hello/world
     |      caret
     ^      tag attribution
```

As the user types, the attribution expands until the caret position:

```
hello/otherworld
           |      caret
     ^^^^^^       tag attribution
```

So, the goal for `endPosition` is to restrict the tag range, not letting it go until the end of the word.

Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/text_tokenizing/tags.dart:14]: Based on this description, the name of the method no longer seems to apply. You're not "finding a tag" - you're maybe finding a trigger, or perhaps creating a tag. So I'm guessing that the changes to this method could break other types of tags, no? Even if the tests pass, this seems to be making a substantive change in behavior which no longer matches the original intention of the method.

For example, if I start with `flutter` and then place the caret `|flutter` and then insert `#|flutter`, I actually want the whole word to be a tag. I don't want to restrict to the caret position. For an `@` tag, I'm not entirely sure which is expected, but I think on X, for example, you could do the exact same thing I just mentioned with `@` and it'll apply to whatever text follows.

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/text_tokenizing/tags.dart:14]: @matthew-carroll  Another option is to keep the method as it was prior to this PR and modify the reaction adding a configuration to the  `TagRule` to determine if a tag can go beyond the caret or if it should be allowed only until the caret position.

If the `TagRule` is configured to restrict the position, we would adjust the tag bounds. What do you think?

Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/text_tokenizing/tags.dart:14]: The API docs for `TagRule` says:

```
/// A rule for matching a text token to a tag.
///
/// A tag begins with a [trigger] character, and is then followed by one or more
/// non-whitespace characters, except for [excludedCharacters].
```

What you've described doesn't sound like "matching a text token to a tag".

Is there any reason that we shouldn't just stop using the shared tag finder implementation within the action tag reaction and instead code the action tag reaction to just do whatever specific thing it wants? Is there any actual "tag finding" going on here?

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/text_tokenizing/tags.dart]: Hi @alterhuman. I'm resuming the work on this PR.

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/text_tokenizing/tags.dart]: @alterhuman Can you try this PR again?

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Comment by matthew-carroll** [comment]
@angelosilvestre can you please file a follow up issue?

**Comment by angelosilvestre** [comment]
@matthew-carroll Filed https://github.com/superlistapp/super_editor/issues/2479
