### PR TITLE
[SuperTextField][Android] Fix drag handle jumping when adding text at the end (Resolves #1114)

### LINKED ISSUE #1114: [SuperTextField][Android] - Cursor Jumps
When I touch middle of the text cursor comes there(with extra pointer), then I touch end of sentence cursor goes there(with extra pointer). Then I'm typing some characters and cursor jumps very fast into middle of the sentence, then end and put the character without a problem. But it feels that something jumpy and not stable. @matthew-carroll @angelosilvestre 

I mean (with extra pointer):
Screenshot 2023-05-04 at 13 58 18

- Cursor actually at end, I touch a character
Screenshot 2023-05-04 at 14 04 17
- Then extra pointer jumps to old position very fast
Screenshot 2023-05-04 at 14 04 07
- Then put my inserted character
Screenshot 2023-05-04 at 14 04 32

<details>
  <summary>Logs Fine</summary>
<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-f3244cb0-7fff-0863-eef4-3a53beae20f1"><div dir="ltr" style="margin-left:0pt;" align="left">

I  (40.162) textfield.android > INFO: Attaching TextInputClient to TextInput
I  (40.163) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy├, selection: TextSelection.collapsed(offset: 16, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (40.164) textfield.ime > FINE: Is attached to input client? true
I  (42.535) textfield.android > FINE: User tapped down
I  (42.536) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy├, selection: TextSelection.collapsed(offset: 8, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (42.590) textfield.android > FINE: User released a tap
I  (42.592) textfield.android > FINE: _onPanCancel()
I  (42.592) textfield.android > FINE: _onHandleDragEnd()
I  (42.899) textfield.android > FINE: Intercepting single tap
I  (47.602) textfield.android > FINE: User tapped down
I  (47.603) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guy├, selection: TextSelection.collapsed(offset: 16, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (47.664) textfield.android > FINE: User released a tap
I  (47.666) textfield.android > FINE: _onPanCancel()
I  (47.666) textfield.android > FINE: _onHandleDragEnd()
I  (47.966) textfield.android > FINE: Intercepting single tap
I  (48.535) textfield.ime > FINE: Received text editing deltas from platform...
I  (48.535) textfield.ime > FINE: Processing insertion: TextEditingDeltaInsertion#06e62(oldText: Good morning guy, textInserted: h, insertionOffset: 16, selection: TextSelection.collapsed(offset: 17, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (48.537) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guyh├, selection: TextSelection.collapsed(offset: 17, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (49.167) textfield.ime > FINE: Received text editing deltas from platform...
I  (49.168) textfield.ime > FINE: Processing insertion: TextEditingDeltaInsertion#bba8f(oldText: Good morning guyh, textInserted: g, insertionOffset: 17, selection: TextSelection.collapsed(offset: 18, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (49.169) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guyhg├, selection: TextSelection.collapsed(offset: 18, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (51.801) textfield.ime > FINE: Received text editing deltas from platform...
I  (51.801) textfield.ime > FINE: Processing insertion: TextEditingDeltaInsertion#9d4b4(oldText: Good morning guyhg, textInserted: b, insertionOffset: 18, selection: TextSelection.collapsed(offset: 19, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
I  (51.803) textfield.ime > FINE: Sending TextEditingValue to platform: TextEditingValue(text: ┤Good morning guyhgb├, selection: TextSelection.collapsed(offset: 19, affinity: TextAffinity.downstream, isDirectional: false), composing: TextRange(start: -1, end: -1))
</div><br /></b>
</details>

https://user-images.githubusercontent.com/2773578/236185769-4744ab91-a7eb-49a8-91a4-2c7989eaf530.mp4

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperTextField][Android] Fix drag handle jumping when adding text at the end. Resolves #1114

When the text field is center-aligned, typing at the end of the text field causes the drag handle to "flash" at the center of the text field before being displayed at the correct position:

https://github.com/superlistapp/super_editor/assets/7597082/7ffae77a-f018-44fe-b8a1-e5ee0380a20d

The cause seems to be a timing issue. We are computing the drag handle offset during build and it seems we are requesting the caret offset while the text layout isn't updated with the new text.

This PR changes the `AndroidEditingOverlayControls` to compute and cache the caret offset in a post-frame callback after the text/selection changes.

After the changes:

https://github.com/superlistapp/super_editor/assets/7597082/6b97475e-ccd9-423c-9452-e1b094361be0

Unfortunately, I couldn't write a test for it. We don't seem to have the same timing issues in the widget tests.

### CODE REVIEW

File: super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart [hunk 1]
```diff
@@ -110,13 +110,29 @@ class _AndroidEditingOverlayControlsState extends State<AndroidEditingOverlayCon
   // line of text.
   Offset? _touchHandleOffsetFromLineOfText;
 
+  bool get _shouldShowCollapsedHandle =>
+      widget.editingController.textController.selection.isCollapsed && !_isDraggingBase && !_isDraggingExtent;
+
+  /// Holds the offset in text layout space where the collapsed drag handle is displayed.
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart:116]: Did you test to see if any similar positioning issues occur with expanded handles?

File: super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart [hunk 2]
```diff
@@ -367,6 +395,76 @@ class _AndroidEditingOverlayControlsState extends State<AndroidEditingOverlayCon
...
+      return;
+    }
+
+    _collapsedHandleOffset = offset;
+  }
+
+  /// Update the offset for the collapsed handle and call `setState`.
+  ///
+  /// Re-schedules the update if we can't compute compute the offset at the current frame.
+  void _updateOffsetForCollapsedHandleAndRebuild() {
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart:419]: This looks nearly identical to the other method.

File: super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart:116]: I didn't notice issues like this with expanded handles.

File: super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart:419]: Yeah, this is nearly identical. The only difference is that one method directly assignes the value because it is called in the build phase and the other calls setState.

Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart:419]: So we should de-duplicate it.

Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart]: After reviewing and testing again, it seems we don't need two methods. We aren't calling this from the build phase.
Updated.

**Review by matthew-carroll — APPROVED** [review]
LGTM
