### PR TITLE
[SuperEditor] Fix serialization/deserialization of empty paragraphs (Resolves #710)

### LINKED ISSUE #710: The getter 'estimatedLineHeight' isn't defined for the class 'ProseTextLayout'
When trying use the main branch of the code from GitHub we're seeing the following error when trying to build the app:

````
  super_editor:
    dependency: "direct main"
    description:
      path: super_editor
      ref: HEAD
      resolved-ref: "23b6a079fdb21f9f733f05862fbff024d91348fe"
      url: "https://github.com/superlistapp/super_editor.git"
    source: git
    version: "0.2.0"
````

```
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart(191,87): error GD65BB2B6: The getter 'estimatedLineHeight' isn't defined for the class 'ProseTextLayout'. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart(204,37): warning GBC99161D: Operand of null-aware operation '?.' has type 'TextBox' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart(206,12): warning GBC99161D: Operand of null-aware operation '?.' has type 'TextBox' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart(206,48): error GD65BB2B6: The getter 'estimatedLineHeight' isn't defined for the class 'ProseTextLayout'. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart(251,24): warning GBC99161D: Operand of null-aware operation '?.' has type 'TextBox' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart(251,98): error GD65BB2B6: The getter 'estimatedLineHeight' isn't defined for the class 'ProseTextLayout'. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart(299,22): warning GBC99161D: Operand of null-aware operation '?.' has type 'TextBox' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart(299,86): error GD65BB2B6: The getter 'estimatedLineHeight' isn't defined for the class 'ProseTextLayout'. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/infrastructure/text_scrollview.dart(338,71): error GD65BB2B6: The getter 'estimatedLineHeight' isn't defined for the class 'ProseTextLayout'. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/flutter_slidable-1.2.0/lib/src/auto_close_behavior.dart(391,24): warning GBC99161D: Operand of null-aware operation '!' has type 'SchedulerBinding' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/cached_network_image-3.0.0/lib/src/image_provider/_image_provider_io.dart(128,25): warning GBC99161D: Operand of null-aware operation '?.' has type 'PaintingBinding' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart(357,41): warning GBC99161D: Operand of null-aware operation '?.' has type 'TextBox' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart(357,98): error GD65BB2B6: The getter 'estimatedLineHeight' isn't defined for the class 'ProseTextLayout'. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart(519,21): warning GBC99161D: Operand of null-aware operation '?.' has type 'TextBox' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart(519,89): error GD65BB2B6: The getter 'estimatedLineHeight' isn't defined for the class 'ProseTextLayout'. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart(563,21): warning GBC99161D: Operand of null-aware operation '?.' has type 'TextBox' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart(563,91): error GD65BB2B6: The getter 'estimatedLineHeight' isn't defined for the class 'ProseTextLayout'. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart(570,21): warning GBC99161D: Operand of null-aware operation '?.' has type 'TextBox' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/android/_editing_controls.dart(570,93): error GD65BB2B6: The getter 'estimatedLineHeight' isn't defined for the class 'ProseTextLayout'. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/android/_user_interaction.dart(460,21): warning GBC99161D: Operand of null-aware operation '?.' has type 'TextBox' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/android/_user_interaction.dart(460,85): error GD65BB2B6: The getter 'estimatedLineHeight' isn't defined for the class 'ProseTextLayout'. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/ios/_editing_controls.dart(418,21): warning GBC99161D: Operand of null-aware operation '?.' has type 'TextBox' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/ios/_editing_controls.dart(418,91): error GD65BB2B6: The getter 'estimatedLineHeight' isn't defined for the class 'ProseTextLayout'. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/ios/_editing_controls.dart(425,21): warning GBC99161D: Operand of null-aware operation '?.' has type 'TextBox' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/ios/_editing_controls.dart(425,93): error GD65BB2B6: The getter 'estimatedLineHeight' isn't defined for the class 'ProseTextLayout'. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
../../AppData/Roaming/Pub/Cache/git/super_editor-23b6a079fdb21f9f733f05862fbff024d91348fe/super_editor/lib/src/infrastructure/super_textfield/ios/_caret.dart(125,37): warning GBC99161D: Operand of null-aware operation '?.' has type 'TextBox' which excludes null. [C:\Users\hillel\Documents\invoiceninja_client\build\windows\flutter\flutter_assemble.vcxproj]
Exception: Build process failed.
Exited (sigterm)
```

Note: if I change to the `typing-fade-prototype` branch the error goes away. 

Thanks for your help, let me know if you need any more details.

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor] Fix serialization/deserialization of empty paragraphs. Resolves #710

The markdown spec doesn't describe how to represent empty paragraphs, so multiple blank lines between paragraphs are ignored. However, we don't want to delete empty paragraphs when serializing/deserializing.

This PR changes the deserialization logic so that when we get two consecutive blank lines, the second one is considered an empty paragraph.

Also, SuperEditor doesn't add blank lines after paragraphs. This causes problems when deserializing some blocks.  For example:

A document containing one paragraph and one horizontal rule is serialized as
```
Paragraph
---
```

When this markdown is deserialized, it's interpreted as a setext-style header and we lose the horizontal rule.

This PR changes the paragraph serialization to add a blank line after a paragraph, except when it's the last node in the document.

The example above will now produce:

```
Paragraph

---
```

One thing that's still missing is the deserialization of paragraphs that aren't empty, but contain blank lines. The blank lines are serialized, but during serialization, they might be interpreted as empty paragraphs. 

One possible solution is to use hard line breaks as described in the markdown spec, where we would add two spaces before the line break. That way, the line break and the next line would be considered part of the previous paragraph.

### CODE REVIEW

**Comment by matthew-carroll** [comment]
@angelosilvestre can you describe more about the remaining problem that you mentioned at the end of your description? If we're going to refactor this code, I'd like to solve all the related problems.

**Comment by angelosilvestre** [comment]
@matthew-carroll Currently we are not handling paragraphs that contain empty lines. For example:

```dart
final doc = MutableDocument(nodes: [
   ParagraphNode(
     id: '1',
     text: AttributedText(
       text: 'First Paragraph.\n'
     ),
   ),
   ParagraphNode(
     id: '2',
     text: AttributedText(
       text: 'Second Paragraph',
     ),
   ),
 ]);
```
The serialization will produce this markdown:

```
First Paragraph.


Second Paragraph
```

The deserialization of this markdown will result in a document with three paragraphs:
First Paragraph
(Empty Paragraph)
Second Paragraph

We are losing the information that the first empty line belongs to the first paragraph.

The markdown spec defines that if the line ending is preceded by two spaces, then it's considered a "hard line break". We could serialize empty lines inside paragraphs this way. During deserialization, we could then handle this case to consider the empty lines as part of the previous paragraph.

**Comment by matthew-carroll** [comment]
@angelosilvestre let's try the change you suggested so that we solve the blank-line-in-paragraph problem, too.

**Comment by angelosilvestre** [comment]
@matthew-carroll I implemented the blank-line-in-paragraph handling

File: super_editor_markdown/lib/src/markdown.dart [hunk 1]
```diff
@@ -20,6 +20,7 @@ MutableDocument deserializeMarkdownToDocument(
   final markdownDoc = md.Document(
     blockSyntaxes: [
       if (syntax == MarkdownSyntax.superEditor) _ParagraphWithAlignmentSyntax(),
+      _EmptyLinePreservingParagraphSyntax(),
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:23]: On the line above, can you add a "//" comment to break the line in two

File: super_editor_markdown/lib/src/markdown.dart [hunk 2]
```diff
@@ -105,6 +106,13 @@ String serializeDocumentToMarkdown(
         }
         buffer.write(node.text.toMarkdown());
       }
+
+      // Separates paragraphs with blank lines.
+      // If we are at the last node we don't add a trailing
+      // blank line.
+      if (i != doc.nodes.length - 1) {
+        buffer.writeln();
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:114]: Replace the comment up above with the following comment before the `buffer` line:

```
// We're not at the end of the document yet. Add a blank line after the
// paragraph so that we can tell the difference between separate
// paragraphs vs. newlines within a single paragraph.
```

File: super_editor_markdown/lib/src/markdown.dart [hunk 3]
```diff
@@ -545,7 +553,21 @@ class AttributedTextMarkdownSerializer extends AttributionVisitor {
   void onVisitEnd() {
     // When the last span has no attributions, we still have text that wasn't added to the buffer yet.
     if (_bufferCursor <= _fullText.length - 1) {
-      _buffer.write(_fullText.substring(_bufferCursor));
+      _writeTextToBuffer(_fullText.substring(_bufferCursor));
+    }
+  }
+
+  void _writeTextToBuffer(String text) {
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:560]: Please add a Dart Doc

File: super_editor_markdown/lib/src/markdown.dart [hunk 4]
```diff
@@ -545,7 +553,21 @@ class AttributedTextMarkdownSerializer extends AttributionVisitor {
...
+    final lines = text.split('\n');
+    for (int i = 0; i < lines.length; i++) {
+      // Adds two spaces before line breaks,
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:563]: Please mention something about the Markdown specification. Otherwise, the reader has no idea why we care about two spaces instead of one.

File: super_editor_markdown/lib/src/markdown.dart [hunk 5]
```diff
@@ -687,6 +700,116 @@ class _ParagraphWithAlignmentSyntax extends md.ParagraphSyntax {
...
+  bool canEndBlock(md.BlockParser parser) => false;
+
+  @override
+  bool canParse(md.BlockParser parser) => !_standardNonParagraphBlockSyntaxes.any((e) => e.canParse(parser));
+
+  @override
+  md.Node? parse(md.BlockParser parser) {
+    final childLines = <String>[];
+    final startsWithEmptyLine = parser.current.isEmpty;
+    // Indicates wether or not the following line might be interpreted
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:722]: Why does this situation "indicate" that conclusion?

File: super_editor_markdown/lib/src/markdown.dart [hunk 6]
```diff
@@ -687,6 +700,116 @@ class _ParagraphWithAlignmentSyntax extends md.ParagraphSyntax {
...
+    // as part of the same paragraph.
+    bool hasHardLineBreak = parser.current.endsWith('  ');
+
+    if (startsWithEmptyLine) {
+      // The parser started at an empty line.
+      // Consume the line as an separator between blocks.
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:728]: "an" -> "a"

File: super_editor_markdown/lib/src/markdown.dart [hunk 7]
```diff
@@ -687,6 +700,116 @@ class _ParagraphWithAlignmentSyntax extends md.ParagraphSyntax {
...
+      parser.advance();
+
+      // The document ended with an empty line.
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:731]: When your comment describes the situation within the if-statement, please place the comment within the if-statement. Otherwise, it reads like "The document ended" regardless of the if-statement, which is confusing.

Comment (matthew-carroll) [reply super_editor_markdown/lib/src/markdown.dart:731]: Also, why are we treating the end of the parser like a blank paragraph? What's the implication of doing that?

File: super_editor_markdown/lib/src/markdown.dart [hunk 8]
```diff
@@ -687,6 +700,116 @@ class _ParagraphWithAlignmentSyntax extends md.ParagraphSyntax {
...
+      // Treat it as an empty paragraph.
+      if (parser.isDone) {
+        return md.Element('p', []);
+      }
+
+      // We found an empty line, but the following line isn't blank.
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:737]: Here again, the comment should go within the if-statement.

Also, rather then imply what some other part of the system is going to do in the future, you should just describe why returning `null` is the appropriate thing for this object to do right now - WRT: "the remaining of the input is parsed by another syntax"

File: super_editor_markdown/lib/src/markdown.dart [hunk 9]
```diff
@@ -687,6 +700,116 @@ class _ParagraphWithAlignmentSyntax extends md.ParagraphSyntax {
...
+      // Therefore, the first empty line is consumed as a separator between blocks and
+      // the remaining of the input is parsed by another syntax.
+      if (!_blankLinePattern.hasMatch(parser.current)) {
+        return null;
+      }
+
+      // We found an empty line followed by a line that is either empty,
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:744]: I'm not sure that this comment is helpful. The comment appears before a line of code that adds a blank line, but the comment doesn't explain why "looking at a paragraph that starts with a blank line" should lead to `childLines.add('')`.

If I'm understanding the code correctly, then it sounds like what you want is:
```
// We found a paragraph, and the first line of that paragraph is empty. Add a
// corresponding empty line to the parsed version of the paragraph.
```

File: super_editor_markdown/lib/src/markdown.dart [hunk 10]
```diff
@@ -687,6 +700,116 @@ class _ParagraphWithAlignmentSyntax extends md.ParagraphSyntax {
...
+      // or consisting of whitespace only.
+      // Therefore, we are looking at paragraph that starts with a blank line.
+      childLines.add('');
+
+      // After the first line, we can still add more lines to the paragraph,
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:749]: I don't see how this comment connects to the code. This comment talks about something that might be true. What is the actual situation here? What are we doing? Why are we doing it?

File: super_editor_markdown/lib/src/markdown.dart [hunk 11]
```diff
@@ -687,6 +700,116 @@ class _ParagraphWithAlignmentSyntax extends md.ParagraphSyntax {
...
+      // if the current line ends with at least two spaces.
+      hasHardLineBreak = parser.current.endsWith('  ');
+      parser.advance();
+    }
+
+    // Consume everything until another block element is found.
+    // A line break will cause the parser to stop, unless the preceding line
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:756]: Why does "two spaces" matter?

File: super_editor_markdown/lib/src/markdown.dart [hunk 12]
```diff
@@ -687,6 +700,116 @@ class _ParagraphWithAlignmentSyntax extends md.ParagraphSyntax {
...
+      parser.advance();
+    }
+
+    // We already started looking at a different block element.
+    // Let another syntax parse it.
+    if (childLines.isEmpty) {
+      return null;
+    }
+
+    var contents = md.UnparsedContent(childLines.map((e) => _removeTrailingSpaces(e)).join('\n'));
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:773]: Should this be `final`?

Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:773]: Also, please describe what's happening here.

File: super_editor_markdown/lib/src/markdown.dart [hunk 13]
```diff
@@ -687,6 +700,116 @@ class _ParagraphWithAlignmentSyntax extends md.ParagraphSyntax {
...
+    return _LineBreakSeparatedElement('p', [contents]);
+  }
+
+  /// Checks if another block syntax can parse the current input.
+  ///
+  /// If [ignoreEmptyBlocks] is `true`, empty blocks don't end the paragraph.
+  bool _isAtParagraphEnd(md.BlockParser parser, {required bool ignoreEmptyBlocks}) {
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:780]: Either the name of this method should be changed, or the comment should be changed. I would not expect a method called "isAtParagraphEnd" to be described as "Checks if another block syntax can parse the current input"

File: super_editor_markdown/lib/src/markdown.dart [hunk 14]
```diff
@@ -687,6 +700,116 @@ class _ParagraphWithAlignmentSyntax extends md.ParagraphSyntax {
...
+      return null;
+    }
+
+    var contents = md.UnparsedContent(childLines.map((e) => _removeTrailingSpaces(e)).join('\n'));
+    return _LineBreakSeparatedElement('p', [contents]);
+  }
+
+  /// Checks if another block syntax can parse the current input.
+  ///
+  /// If [ignoreEmptyBlocks] is `true`, empty blocks don't end the paragraph.
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:779]: This comment is too passive. Please describe how this property impacts the *behavior* of this method.

File: super_editor_markdown/lib/src/markdown.dart [hunk 15]
```diff
@@ -687,6 +700,116 @@ class _ParagraphWithAlignmentSyntax extends md.ParagraphSyntax {
...
+  bool _isAtParagraphEnd(md.BlockParser parser, {required bool ignoreEmptyBlocks}) {
+    if (parser.isDone) return true;
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:781]: Please use braces in all if-statements, regardless of line count.

File: super_editor_markdown/lib/src/markdown.dart [hunk 16]
```diff
@@ -687,6 +700,116 @@ class _ParagraphWithAlignmentSyntax extends md.ParagraphSyntax {
...
+      if (!(syntax is md.EmptyBlockSyntax && ignoreEmptyBlocks) &&
+          syntax.canParse(parser) &&
+          syntax.canEndBlock(parser)) {
+        return true;
+      }
+    }
+    return false;
+  }
+
+  /// Removes whitespace at the end of a line.
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:792]: This description leaves the door open for confusion. Do you mean the following?

```
/// Removes all whitespace characters except `"\n"`.
```

File: super_editor_markdown/lib/src/markdown.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown.dart:560]: Dart Doc added.

File: super_editor_markdown/lib/src/markdown.dart (hunk 4 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown.dart:563]: Comment updated.

File: super_editor_markdown/lib/src/markdown.dart (hunk 5 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown.dart:722]: Comment updated.

File: super_editor_markdown/lib/src/markdown.dart (hunk 12 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown.dart:773]: Comment added.

File: super_editor_markdown/lib/src/markdown.dart (hunk 13 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown.dart:780]: Comment updated.

File: super_editor_markdown/lib/src/markdown.dart (hunk 14 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown.dart:779]: Comment updated.

File: super_editor_markdown/lib/src/markdown.dart (hunk 10 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown.dart:749]: Comment updated. I extracted the check for a hard line break into a method, so we can add a Dart Doc explaining what is a hard line break.

File: super_editor_markdown/lib/src/markdown.dart (hunk 11 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown.dart:756]: Comment updated.

File: super_editor_markdown/lib/src/markdown.dart (hunk 7 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown.dart:731]: After analyzing again, I think the correct behavior is to return `null`. I added a comment explaining why.

File: super_editor_markdown/lib/src/markdown.dart (hunk 8 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown.dart:737]: Comment updated.

File: super_editor_markdown/lib/src/markdown.dart [hunk 17]
```diff
@@ -545,7 +554,27 @@ class AttributedTextMarkdownSerializer extends AttributionVisitor {
...
     // When the last span has no attributions, we still have text that wasn't added to the buffer yet.
     if (_bufferCursor <= _fullText.length - 1) {
-      _buffer.write(_fullText.substring(_bufferCursor));
+      _writeTextToBuffer(_fullText.substring(_bufferCursor));
+    }
+  }
+
+  /// Writes the given [text] to [_buffer].
+  ///
+  /// Separates multiple lines in a single paragraph according to
```
Comment (matthew-carroll) [inline super_editor_markdown/lib/src/markdown.dart:563]: You can mention the spec, but don't make the reader go find the spec. Please include what this method is actually doing.

**Review by matthew-carroll — APPROVED** [review]
LGTM - with one more dart doc improvement

File: super_editor_markdown/lib/src/markdown.dart (hunk 17 above)
Comment (angelosilvestre) [reply super_editor_markdown/lib/src/markdown.dart]: Dart Doc updated.
