### PR TITLE
Don't extend links to new, empty paragraphs (Resolves #1276)

### LINKED ISSUE #1276: [SuperEditor] Pressing ENTER at end of LinkAttribution adds it to newly created node
Steps to reproduce:
* Run the empty document demo
* Type or paste a link (e.g. www.google.com)
* Remove any space at the end of the node 
* Press ENTER

**Expected:** new paragraph node is added without any attribution
**Actual:** new paragraph node is added with the same `LinkAttribution` as the previous node

The document after pressing ENTER looks like this:
```
[TextNode] - text: [AttributedText] - "google.com"
[AttributedSpans] (1 spans):
 - [SpanMarker] - attribution: [LinkAttribution]: https://google.com, offset: 0, type: SpanMarkerType.start
 - [SpanMarker] - attribution: [LinkAttribution]: https://google.com, offset: 9, type: SpanMarkerType.end, metadata: {blockType: [NamedAttribution]: paragraph}
[TextNode] - text: [AttributedText] - ""
[AttributedSpans] (1 spans):
 - [SpanMarker] - attribution: [LinkAttribution]: https://google.com, offset: 0, type: SpanMarkerType.start
 - [SpanMarker] - attribution: [LinkAttribution]: https://google.com, offset: 0, type: SpanMarkerType.end, metadata: {blockType: [NamedAttribution]: paragraph}
```

### PR DESCRIPTION
**Pull request by matthew-carroll**
Don't extend links to new, empty paragraphs (Resolves #1276)

The problem: When the user places the caret at the end of a link, at the end of a paragraph, and the user presses ENTER, the newly created paragraph initially contains the same link attribution. This attribution is immediately removed when the user starts typing, but the attribution should not exist at all in the new empty paragraph.

The longer term solution is probably to move attribution expansion to `EditReaction`s: https://github.com/superlistapp/super_editor/issues/1296

As a temporary solution, I've added an attribution filter to the paragraph split request, which decides which attributions can extend from the end of one paragraph to the beginning of a new paragraph.

### CODE REVIEW

File: super_editor/test/super_editor/text_entry/links_test.dart [hunk 1]
```diff
@@ -311,5 +311,87 @@ void main() {
...
+    testWidgetsOnAllPlatforms('does not extend link to new paragraph', (tester) async {
+      await tester //
+          .createDocument()
+          .fromMarkdown("[www.google.com](www.google.com)")
+          .withInputSource(TextInputSource.ime)
+          .pump();
+
+      final doc = SuperEditorInspector.findDocument()!;
+
+      // Place the caret at "www.google.com|"
```
Comment (angelosilvestre) [inline super_editor/test/super_editor/text_entry/links_test.dart:324]: Just a reminder to end the comment with a `.`.

File: super_editor/test/super_editor/text_entry/links_test.dart [hunk 2]
```diff
@@ -311,5 +311,87 @@ void main() {
...
+          .withInputSource(TextInputSource.ime)
+          .pump();
+
+      final doc = SuperEditorInspector.findDocument()!;
+
+      // Ensure the Markdown correctly created a list item.
+      expect(doc.nodes.first, isA<ListItemNode>());
+
+      // Place the caret at "www.google.com|"
+      await tester.placeCaretInParagraph(doc.nodes.first.id, 14);
```
Comment (angelosilvestre) [inline super_editor/test/super_editor/text_entry/links_test.dart:366]: A reminder to end the comment with a `.`.

File: super_editor/test/super_editor/text_entry/links_test.dart [hunk 3]
```diff
@@ -311,5 +311,87 @@ void main() {
...
+
+      // Create a new list item.
+      await tester.pressEnter();
+
+      // We had an issue where link attributions were extended to the beginning of
+      // an empty paragraph, but were removed after the user started typing. So, first,
+      // ensure that no link markers were added to the empty paragraph.
```
Comment (angelosilvestre) [inline super_editor/test/super_editor/text_entry/links_test.dart:373]: paragraph -> list item

**Review by angelosilvestre — APPROVED** [review]
LGTM with a few comments.
