### PR TITLE
Moved tasks into Super Editor and fixed bug that prevented creating new tasks after texisting tasks (Resolves #923)

### LINKED ISSUE #923: [SuperEditor] - Task component doesn't create new task on ENTER
We've had a regression where a task item in the example app doesn't do anything when `enter` is pressed at the end of the line. 

Return this behavior to its previous state.

Also, add a test for this under a new file location: `test/super_editor/components/task_test.dart`

### PR DESCRIPTION
**Pull request by matthew-carroll**
Moved tasks into Super Editor and fixed bug that prevented creating new tasks after texisting tasks (Resolves #923)

At some point we lost the ability to press ENTER at the end of a task in the example app and create a new task. This PR fixes that. I'm not sure how it was ever working. We have code in the ENTER handler that rejects any text node that isn't a `ParagraphNode`. I added a new key handler that specifically handles this case.

This PR also moves tasks into Super Editor as a standard content type. I also added tests to ensure that `TaskNode`s and `TaskComponent`s do the right thing within a `SuperEditor`.

I tried adding tests for tapping the checkbox. Those tests work on desktop, but not on mobile. At least part of the problem on mobile is that the mobile gesture recognizer still sits on top of the document, instead of beneath the document, like desktop. I filed https://github.com/superlistapp/super_editor/issues/927 to solve that problem. When it's solved, the mobile tests that are skipped in this PR should be combined with the desktop tests.

I changed how the demo app deals with brightness. Instead of making the setting a local `bool`, I switched to `Brightness` and applied it with a `Theme` widget. This way, any given component can lookup the current brightness and base its appearance on the right value.

I also discovered that the `ProxyDocumentComponent` implementation didn't deal with the possibility that the inner component might not take up all the space of the proxy component. I added offset calculations to deal with that.

### CODE REVIEW

File: super_editor/example/lib/demos/example_editor/example_editor.dart [hunk 1]
```diff
@@ -353,23 +360,23 @@ class _ExampleEditorState extends State<ExampleEditor> {
...
-            if (!_isLight) ..._darkModeStyles,
+            if (!isLight) ..._darkModeStyles,
             taskStyles,
           ],
         ),
         componentBuilders: [
-          ...defaultComponentBuilders,
           TaskComponentBuilder(_docEditor),
+          ...defaultComponentBuilders,
         ],
```
Comment (angelosilvestre) [inline super_editor/example/lib/demos/example_editor/example_editor.dart:380]: As tasks were moved into Super Editor, shouldn't `TaskComponentBuilder` be moved into `defaultComponentBuilders` ?

**Review by angelosilvestre — COMMENTED** [review]
LGTM with a single comment.

File: super_editor/example/lib/demos/example_editor/example_editor.dart (hunk 1 above)
Comment (matthew-carroll) [reply super_editor/example/lib/demos/example_editor/example_editor.dart:380]: It should, but I haven't found a way to create it without passing it the `DocumentEditor`, which isn't available, statically...
