### PR TITLE
[SuperEditor] Fix performAction override for TextInputAction.newline (Resolves #1012)

### LINKED ISSUE #1012: [SuperEditor] [Android] Overriding performAction has no effect for newline
### Description
When providing an `imeConfiguration` setting newline as the `keyboardActionButton`, and also providing `imeOverrides` for `performAction`, such override will only be invoked if InputAction is not `newLine`.

### Expected behavior
I would expect to have the possibility to fully override the action being perform regardless of the keyboardActionButton that is provided.

### Minimal Example on demo_mobile_editing_android.dart

```
import 'package:flutter/material.dart';
import 'package:super_editor/super_editor.dart';

import 'keyboard_overlay_clipper.dart';

class _DeltaTextInputClientDecorator extends DeltaTextInputClientDecorator {
  @override
  void performAction(TextInputAction action) {
    print('performAction invoked');

    super.performAction(action);
  }
}

/// Mobile Android document editing demo.
///
/// This demo forces the editor into a mobile configuration,
/// no matter which platform or form factor you use.
class MobileEditingAndroidDemo extends StatefulWidget {
  @override
  _MobileEditingAndroidDemoState createState() =>
      _MobileEditingAndroidDemoState();
}

class _MobileEditingAndroidDemoState extends State<MobileEditingAndroidDemo> {
  final GlobalKey _docLayoutKey = GlobalKey();

  late Document _doc;
  late DocumentEditor _docEditor;
  late DocumentComposer _composer;
  late CommonEditorOperations _docOps;

  FocusNode? _editorFocusNode;

  @override
  void initState() {
    super.initState();
    _doc = _createInitialDocument();
    _docEditor = DocumentEditor(document: _doc as MutableDocument);
    _composer = DocumentComposer();
    _docOps = CommonEditorOperations(
      editor: _docEditor,
      composer: _composer,
      documentLayoutResolver: () =>
          _docLayoutKey.currentState as DocumentLayout,
    );
    _editorFocusNode = FocusNode();
  }

  @override
  void dispose() {
    _editorFocusNode!.dispose();
    _composer.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return SafeArea(
      child: Column(
        children: [
          Expanded(
            child: SuperEditor(
              focusNode: _editorFocusNode,
              documentLayoutKey: _docLayoutKey,
              editor: _docEditor,
              composer: _composer,
              imeOverrides: _DeltaTextInputClientDecorator(),
              imeConfiguration: SuperEditorImeConfiguration(
                keyboardActionButton: TextInputAction.newline,
              ),
              gestureMode: DocumentGestureMode.android,
              inputSource: TextInputSource.ime,
              androidToolbarBuilder: (_) => AndroidTextEditingFloatingToolbar(
                onCutPressed: () => _docOps.cut(),
                onCopyPressed: () => _docOps.copy(),
                onPastePressed: () => _docOps.paste(),
                onSelectAllPressed: () => _docOps.selectAll(),
              ),
              stylesheet: defaultStylesheet.copyWith(
                documentPadding: const EdgeInsets.all(16),
              ),
              createOverlayControlsClipper: (_) =>
                  const KeyboardToolbarClipper(),
            ),
          ),
          MultiListenableBuilder(
            listenables: <Listenable>{
              _doc,
              _composer.selectionNotifier,
            },
            builder: (_) => SizedBox.shrink(),
          ),
        ],
      ),
    );
  }

  MutableDocument _createInitialDocument() {
    return MutableDocument(
      nodes: [
        ParagraphNode(
          id: DocumentEditor.createNodeId(),
          text: AttributedText(
            text:
                'Etiam id lacus interdum, efficitur ex convallis, accumsan ipsum. Integer faucibus mollis mauris, a suscipit ante mollis vitae. Fusce justo metus, congue non lectus ac, luctus rhoncus tellus. Phasellus vitae fermentum orci, sit amet sodales orci. Fusce at ante iaculis nunc aliquet pharetra. Nam placerat, nisl in gravida lacinia, nisl nibh feugiat nunc, in sagittis nisl sapien nec arcu. Nunc gravida faucibus massa, sit amet accumsan dolor feugiat in. Mauris ut elementum leo.',
          ),
        ),
      ],
    );
  }
}

```

I would expect
` print('performAction invoked');`
to be invoked. However this only happens if I set something different as the keyboardAction

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor] Fix `performAction` override for `TextInputAction.newline`. Resolves #1012

When `SuperEditor` is configured to use `TextInputAction.newline`,  pressing the action button doesn't call `performAction` in the given `imeOverrides`. 

The cause is that, on Android, pressing an action button configured as `TextInputAction.newline` generates an insertion delta of `\n` instead of calling `performAction`. `TextDeltasDocumentEditor` translates the insertion into a `performAction` call. However, the call is handled inside `TextDeltasDocumentEditor` as it doesn't know about the overrides.

This PR changes `TextDeltasDocumentEditor` to accept a new property to override `performAction`.

### CODE REVIEW

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 1]
```diff
@@ -15,13 +15,17 @@ class TextDeltasDocumentEditor {
...
     required this.commonOps,
+    this.onPerformAction,
   });
 
   final DocumentEditor editor;
   final ValueNotifier<DocumentSelection?> selection;
   final ValueNotifier<DocumentRange?> composingRegion;
   final CommonEditorOperations commonOps;
 
+  /// Override the handling of a [TextInputAction]s.
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:26]: Please change the dart doc to the following:

```
/// Callback invoked when the client should handle a given [TextInputAction].
///
/// Typically, [TextInputAction]s are reported through a different part of Flutter's IME
/// API. However, some actions, on some platforms, are converted into text editing
/// deltas, rather than reported as explicit actions. For example, on Android, the `newline`
/// action is reported as a text insertion with a `\n` character. That change is intercepted
/// by this editor and reported as a [TextInputAction.newline] instead.
```

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 2]
```diff
@@ -278,4 +282,12 @@ class TextDeltasDocumentEditor {
         break;
     }
   }
+
+  void _dispatchTextInputAction(TextInputAction action) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:286]: Let's get rid of this method, and the existing `performAction()` implementation. Please move the existing newline action behavior such that it hooks into our general action handling system, instead of us maintaining a special implementation in this class just for that one action.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart [hunk 3]
```diff
@@ -131,12 +131,14 @@ class SuperEditorImeInteractorState extends State<SuperEditorImeInteractor> impl
   void initState() {
     super.initState();
     _focusNode = (widget.focusNode ?? FocusNode());
+    _imeClient = DeltaTextInputClientDecorator();
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart:134]: You should keep the `_configureImeClientDecorators()` with this line. Otherwise it begs the question, what are we decorating?

File: super_editor/test/src/default_editor/document_input_ime_test.dart [hunk 4]
```diff
@@ -126,6 +126,47 @@ void main() {
       expect(document.nodes.length, 1);
     });
 
+    testWidgetsOnAndroid('allows apps to handle performAction in their own way upon new line insertion',
```
Comment (matthew-carroll) [inline super_editor/test/src/default_editor/document_input_ime_test.dart:129]: This test name seems overly verbose: `allows app to handle newline action`

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:286]: `TextDeltasDocumentEditor` is the only place where we handle the actions in SuperEditor. `DocumentImeInputClient` just forwads the `performAction` call to this class.

File: super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/supereditor_ime_interactor.dart]: It seems we can move this line back to where it was.

**Comment by matthew-carroll** [comment]
Let's try this...

In the deltas document editor, change the existing `performAction()` method to be `insertNewline()` and only include the implementation for inserting a new line. Also, have the deltas document editor always call out to the `onPerformAction` callback that it's given. Make the `onPerformAction` callback required.

In the document ime client, change its implementation of `performAction()` to check for the newline action and then conditionally invoke `textDeltasDocumentEditor.insertNewline()`.

With these changes, we should see one of the following situations...

Normal:
```
IME -> _imeClient.performAction(action)
_imeClient.performAction -> TextDeltasDocumentEditor.insertNewline()
```

Normal with overrides:
```
IME -> _imeClient.performAction(action)
_imeClient.performAction -> MyOverrides.performAction()
```

Android "/n":
```
IME -> _imeClient.updateEditingValueWithDeltas()
_imeClient.updateEditingValueWithDeltas -> onPerformAction(action)
onPerformAction -> _imeClient.performAction(action)
_imeClient.performAction -> TextDeltasDocumentEditor.insertNewline()
```

Android "/n" with overrides:
```
IME -> _imeClient.updateEditingValueWithDeltas()
_imeClient.updateEditingValueWithDeltas -> onPerformAction(action)
onPerformAction -> _imeClient.performAction(action)
_imeClient.performAction -> MyOverrides.performAction()
```

With these changes we can always think of `performAction()` as handling IME actions. The only difference is how that method internally delegates to others.

**Comment by angelosilvestre** [comment]
@matthew-carroll Updated.

File: super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart [hunk 5]
```diff
@@ -278,7 +278,17 @@ class DocumentImeInputClient extends TextInputConnectionDecorator with TextInput
   @override
   void performAction(TextInputAction action) {
     editorImeLog.fine("IME says to perform action: $action");
-    textDeltasDocumentEditor.performAction(action);
+    switch (action) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart:281]: I don't think we need this switch statement. I think we can just use an if-statement, because that's all this client cares about.

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/document_ime_communication.dart]: Updated.

**Review by matthew-carroll — APPROVED** [review]
LGTM
