### PR TITLE
[SuperTextField] Fix ImeAttributedTextEditingController not removing inner controller listener (Resolves #1227)

### LINKED ISSUE #1227: [SuperTextField] ImeAttributedTextEditingController does not remove listener from the inner controller
`ImeAttributedTextEditingController` (let's call it the IME controller) takes a real controller (a.k.a. inner controller) and it attaches a listener to when it changes in the constructor.

In case the IME controller is disposed, but the real controller isn't, and then the real controller is passed to a new instance of the IME controller, then we get in a situation where the listener previously added to the real controller will try to notify the listeners of the disposed instance of the IME controller, which leads to the following exception:
```
flutter: exception: A _TextEditingController was used after being disposed.
Once you have called dispose() on a _TextEditingController, it can no longer be used.
stackTrace: #0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure> (package:flutter/src/foundation/change_notifier.dart:179:9)
#1      ChangeNotifier.debugAssertNotDisposed (package:flutter/src/foundation/change_notifier.dart:186:6)
#2      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:382:27)
#3      ImeAttributedTextEditingController._onInnerControllerChange (package:super_editor/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart:199:5)
#4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:403:24)
#5      AttributedTextEditingController.update (package:super_editor/src/infrastructure/super_textfield/infrastructure/attributed_text_editing_controller.dart:655:5)
#6      AttributedTextEditingController.insertAtCaret (package:super_editor/src/infrastructure/super_textfield/infrastructure/attributed_text_editing_controller.dart:219:5)
#7      ImeAttributedTextEditingController.insertAtCaret (package:super_editor/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart:465:21)
#8      ImeAttributedTextEditingController.updateEditingValueWithDeltas (package:super_editor/src/infrastructure/super_textfield/input_method_engine/_ime_text_editing_controller.dart:293:11)
#9      TextInput._handleTextInputInvocation (package:flutter/src/services/text_input.dart:1857:63)
#10     TextInput._loudlyHandleTextInputInvocation (package:flutter/src/services/text_input.dart:1746:20)
#11     MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:547:55)
#12     MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:540:34)
#13     _DefaultBinaryMessenger.setMessageHandler.<anonymous closure> (package:flutter/src/services/binding.dart:479:35)
...
```

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperTextField] Fix ImeAttributedTextEditingController not removing inner controller listener. Resolves #1227 

In `ImeAttributedTextEditingController` we are adding a listener to the inner controller, but we aren't removing it upon disposal. This causes a crash if the inner controller is reused in a new `ImeAttributedTextEditingController`.

This PR changes `ImeAttributedTextEditingController` to remove the listener when `dispose` is called.

I'm not sure if we need a test for this, but I added anyway.

### CODE REVIEW

File: super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart [hunk 1]
```diff
@@ -401,6 +401,63 @@ void main() {
...
+              },
+            ),
+          ),
+        ),
+      ),
+    );
+
+    // Rebuild the widget tree, attaching the inner controller to another IME controller
+    // and disposing the old one.
+    controllerB = ImeAttributedTextEditingController(
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart:447]: What's the purpose of creating another `controllerB` instance outside of the widget tree?

File: super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart [hunk 2]
```diff
@@ -401,6 +401,63 @@ void main() {
...
+      controller: innerController,
+      disposeClientController: false,
+    );
+    controllerA.dispose();
+    rebuildNotifier.value = false;
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart:452]: Why are we tracking rebuilds?

File: super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart [hunk 3]
```diff
@@ -401,6 +401,63 @@ void main() {
...
+    await tester.pump();
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart:453]: What's this pump supposed to do?

File: super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart [hunk 4]
```diff
@@ -401,6 +401,63 @@ void main() {
...
+
+    // Change the text of the inner controller to notify the listeners.
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart:455]: Reading through this test it feels like you're trying to write a generic test for a very specific issue. The test title is "allows reusing inner controller" which is very generic. But your test is specifically looking for a crash when notifying listeners after disposal. There's no need to be overly generic when there's something specific that you're verifying. In fact, being overly generic makes it very difficult for future developers to understand why you did what you did in this test.

File: super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart:447]: This is used to simulate the situation mentioned in the ticket, where the inner controller is attached to a new IME controller instance.

File: super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart:452]: This is just to force a rebuild and tell the builder we should use `controllerB` instead of `controllerA`. 

I renamed the variable.

File: super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart:453]: The pump doesn't seem to be needed. Removed.

File: super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart (hunk 4 above)
Comment (angelosilvestre) [reply super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart:454]: Is "allows reusing inner controller after disposal" specif enough?

We could also use a regular dart test instead of a widget test, as the issue doesn't depend on a widget tree.

Comment (matthew-carroll) [reply super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart:454]: That's still a generalization of the problem, and a generalization of what you're verifying with this test. You wrote this test to make sure that a listener isn't notified after disposal. Do we have any reason to believe that this test would ever verify anything other than that condition? The name implies that there might be any number of things that could go wrong when "re-using an inner controller" and this test makes sure that none of those bad things happen. But there's only one thing we know that this test will catch.

File: super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart [hunk 5]
```diff
@@ -401,6 +401,61 @@ void main() {
...
+      controller: innerController,
+      disposeClientController: false,
+    );
+    controllerA.dispose();
+    useControllerA.value = false;
+
+    // Change the text of the inner controller to notify the listeners.
+    innerController.text = AttributedText(text: 'New text');
+
+    // Reaching this point means that disposing the old controller didn't cause a crash.
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart:457]: This statement will be a surprise for the reader, because you haven't mentioned at any point what might crash. If this test ever becomes out of date and needs adjustment, what problem is the developer supposed to adjust for? We've lost the root problem that this test is meant to prevent.

File: super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart [hunk 6]
```diff
@@ -401,6 +401,61 @@ void main() {
...
+
+    await tester.pumpWidget(
+      MaterialApp(
+        home: Scaffold(
+          body: SizedBox(
+            width: 300,
+            child: ValueListenableBuilder(
+              valueListenable: useControllerA,
+              builder: (context, shouldUseTextFieldA, _) {
+                return shouldUseTextFieldA //
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart:429]: I think we can simplify this build in a couple ways. First, I don't think we need two controller variables. You can just re-assign a single `imeController` variable at the appropriate time.

Second, there's then no need for a ternary. Maybe you can use a `ValueNotifier<int>` to cause rebuilds:

```dart
ValueListenableBuilder(
  valueListenable: buildSignal,
  builder: (context, _, __) {
    return SuperTextField(
      textController: imeController,
      inputSource: TextInputSource.ime,
    );
  },
);
```

File: super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart [hunk 7]
```diff
@@ -401,6 +401,61 @@ void main() {
...
+                      );
+              },
+            ),
+          ),
+        ),
+      ),
+    );
+
+    // Rebuild the widget tree, attaching the inner controller to another IME controller
+    // and disposing the old one.
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/ime_attributed_text_editing_controller_test.dart:446]: I'm wondering if this requires a widget tree build at all? The problem is a listener firing when it shouldn't, right? Can't we test that with a lot less code without the widget tree?

**Comment by angelosilvestre** [comment]
@matthew-carroll Updated the test to avoid pumping a widget tree. We still need to use a widget test because, otherwise, the exception isn't thrown.

**Review by matthew-carroll — APPROVED** [review]
LGTM
