### PR TITLE
[SuperEditor] Fix selection shifting when moving between nodes (Resolves #1761)

### LINKED ISSUE #1761: [SuperEditor] Moving selection up/down between tasks shifts the offset
**Package Version**
`main` branch with commit hash https://github.com/superlistapp/super_editor/commit/fbddcaf3f7e6543514c8b05d0c710aaa7ca349a4.

**To Reproduce**
1. Go to "Animated task height" demo
2. Add more text to each task, like "Task 1 with some extra text", "Task 2 with some extra text", etc.
3. Place the selection at the end of the first task
4. Press down key 

**Actual behavior**
The caret moves vertically (to the node below), but moves 6 characters to the left.

**Expected behavior**
Since the length o the node below is the same, then the caret should just move vertically.

**Platform**
Desktop.

**Flutter version**
Flutter master commit e278279a48f0479386c249cf18f26b29c6f9018f.

**Screenshots**

https://github.com/superlistapp/super_editor/assets/31278849/0b810924-ba05-4a8f-91c1-9fca023baad6

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor] Fix selection shifting when moving between nodes. Resolves #1761

In the "Animated task height" demo, moving the caret between nodes using UP or DOWN arrow is shifting the selection horizontally:

https://github.com/superlistapp/super_editor/assets/31278849/0b810924-ba05-4a8f-91c1-9fca023baad6

This would happen to any component that mixes in `ProxyDocumentComponent`. 

To move the selection vertically between nodes we first get the current offset for the selected position and then compute 
 which position in the upstream/downstream node is closer to this offset.

The issue is that for `ProxyDocumentComponent`, `getOffsetForPosition` only considers the text inside the component, not the whole component. In the example of the task component, it ignores the checkbox that appears before the text.

For example, consider this layout:

```
[ ]  This is the task 1
[ ]  This is the task 2
```

If the caret sits in `This is the task 1|`, pressing DOWN should move the caret to `This is the task 2|`.

However, we are computing the original offset as if the layout was like the following:

```
This is the task 1
[ ]  This is the task 2
```

So the offset at `This is the task 1|` would move down to `This is the t|ask 2`.

This PR changes `ProxyDocumentComponent` to consider the offset inside the whole component layout.

### CODE REVIEW

**Comment by angelosilvestre** [comment]
@matthew-carroll I noticed a similar issue when moving the selection from a list item to a paragraph, and from a paragraph to a list item.

However, it should be a different issue, because `UnorderedListItemComponent` doesn't uses `ProxyDocumentComponent`. Should I take a look at this?

File: super_editor/lib/src/core/document_layout.dart [hunk 1]
```diff
@@ -347,7 +347,7 @@ mixin ProxyDocumentComponent<T extends StatefulWidget> implements DocumentCompon
 
   @override
   Offset getOffsetForPosition(NodePosition nodePosition) {
-    return _childDocumentComponent.getOffsetForPosition(nodePosition);
+    return _getOffsetFromChild(_childDocumentComponent.getOffsetForPosition(nodePosition));
```
Comment (matthew-carroll) [inline super_editor/lib/src/core/document_layout.dart:350]: Did you check all the uses of `getOffsetForPosition` to ensure that this change is inline with any related expectations?

Please add a comment that makes it clear why calling `_getOffsetFromChild()` here. Also, please put a comma and newline after `getOffsetForPosition()` so that we can clearly see that two calls are taking place.

File: super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart [hunk 2]
```diff
@@ -823,6 +824,392 @@ void main() {
         },
         variant: inputSourceVariant,
       );
+
+      group("jumps to downstream node with DOWN ARROW", () {
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart:828]: Shouldn't some combination of the group and test names mention that we're preserving the approximate x offset? That's what the issue ticket is about, right?

File: super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart [hunk 3]
```diff
@@ -823,6 +824,392 @@ void main() {
...
+          final document = MutableDocument(
+            nodes: [
+              TaskNode(id: '1', text: AttributedText('This is a task'), isComplete: false),
+              TaskNode(id: '2', text: AttributedText('This is another task'), isComplete: false),
+            ],
+          );
+          final composer = MutableDocumentComposer();
+          final editor = createDefaultDocumentEditor(document: document, composer: composer);
+
+          await tester.pumpWidget(
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart:1169]: I'm seeing a bunch of repetition in these tests, and the tests are pretty long. Can we simplify the unimportant details of these tests at all?

**Comment by matthew-carroll** [comment]
> I noticed a similar issue when moving the selection from a list item to a paragraph, and from a paragraph to a list item.

Let's solve both issues in this PR. The UX problem remains the same, regardless of whether the implementation details are different.

File: super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart:828]: Updated

File: super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart:1169]: Updated

File: super_editor/lib/src/core/document_layout.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/lib/src/core/document_layout.dart]: > Did you check all the uses of getOffsetForPosition to ensure that this change is inline with any related expectations?

Currently, `getOffsetForPosition` seems to be used only for moving the caret.

> Please add a comment that makes it clear why calling `_getOffsetFromChild()` here

I added a comment, but I could use some help to make it more clear.

File: super_editor/lib/src/default_editor/list_items.dart [hunk 4]
```diff
@@ -271,10 +273,9 @@ class ListItemComponentViewModel extends SingleColumnLayoutComponentViewModel wi
 /// Displays a un-ordered list item in a document.
 ///
 /// Supports various indentation levels, e.g., 1, 2, 3, ...
-class UnorderedListItemComponent extends StatelessWidget {
+class UnorderedListItemComponent extends StatefulWidget {
   const UnorderedListItemComponent({
     Key? key,
-    required this.textKey,
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/list_items.dart:277]: Can you explain why it's OK to remove this? Isn't the `textKey` passed from the component builder so that this widget shares the same key with other areas of the widget tree?

File: super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart [hunk 5]
```diff
@@ -146,7 +146,17 @@ class SuperEditorInspector {
   /// {@macro supereditor_finder}
   static AttributedText findTextInParagraph(String nodeId, [Finder? superEditorFinder]) {
     final documentLayout = findDocumentLayout(superEditorFinder);
-    return (documentLayout.getComponentByNodeId(nodeId) as TextComponentState).widget.text;
+    final component = documentLayout.getComponentByNodeId(nodeId);
```
Comment (matthew-carroll) [inline super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart:149]: This method no longer does what the name implies. We need to do something here. Are there current usages of this method (before this PR) that use it to find text in a non-paragraph `TextNode`?

File: super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart [hunk 6]
```diff
@@ -158,7 +168,7 @@ class SuperEditorInspector {
   static TextSpan findRichTextInParagraph(String nodeId, [Finder? superEditorFinder]) {
     final documentLayout = findDocumentLayout(superEditorFinder);
 
-    final textComponentState = documentLayout.getComponentByNodeId(nodeId) as TextComponentState;
+    final textComponentState = documentLayout.getComponentByNodeId(nodeId) as DocumentComponent;
```
Comment (matthew-carroll) [inline super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart:171]: Why did the type cast here change? The name of the variable suggests that its a `TextComponentState`.

File: super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart [hunk 7]
```diff
@@ -823,6 +824,680 @@ void main() {
         },
         variant: inputSourceVariant,
       );
+
+      group("jumps to downstream node preserving approximate x position with DOWN ARROW", () {
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_input_keyboard_actions_test.dart:828]: "x position" -> "x-position"

File: super_editor/lib/src/default_editor/list_items.dart (hunk 4 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/list_items.dart:277]: I modified the component build to pass the `componentKey` directly as the key for the `UnorderedListItemComponent`.

To be able to get the `RenderBox` for the whole component, not just the text inside of it, we need to use the `componentKey` as the key for the "main" component.

File: super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart (hunk 5 above)
Comment (angelosilvestre) [reply super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart:149]: We already use it to find the text of list items. For example, the test "pastes within a list item" uses it.

File: super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart (hunk 6 above)
Comment (angelosilvestre) [reply super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart:171]: Because now the component might be a `ProxyDocumentComponent`.

File: super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart (hunk 5 above)
Comment (matthew-carroll) [reply super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart:149]: If list items already use the existing method (without your changes) then it suggests that there's more to this story. List items are proxies, right? If so, how was this method working for them before your changes?

Comment (angelosilvestre) [reply super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart:149]: Before this PR, the component key was applied to the `TextComponent` inside the list item component, so it wasn't working like the proxy component, it was as if the list item was just the `TextComponent` inside of it.

Comment (matthew-carroll) [reply super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart:149]: And which aspect of this PR requires us to change that? Where do you now need a key that's bound to the proxy component?

Comment (angelosilvestre) [reply super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart:149]: Because we need to get the character `Offset` in the whole component space, not just the `Offset` in the `TextComponent` space. We need the `Offset` in the whole component coordinate space to move to the correctly x-offset.

Comment (matthew-carroll) [reply super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart:149]: Sure, I appreciate that we need to be able to get the delta between the component bounds and the content bounds. But isn't it the component, itself, that calculates this? In other words, doesn't the proxy component widget run that calculation? If so, the proxy component widget already has direct access to its render object, i.e., its own origin and bounds. Am I missing something? Is some other object trying to lookup the proxy component origin?

File: super_editor/lib/src/default_editor/list_items.dart [hunk 8]
```diff
@@ -305,10 +305,24 @@ class UnorderedListItemComponent extends StatelessWidget {
   final bool showComposingUnderline;
   final bool showDebugPaint;
 
+  @override
+  State<UnorderedListItemComponent> createState() => _UnorderedListItemComponentState();
+}
+
+class _UnorderedListItemComponentState extends State<UnorderedListItemComponent>
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/list_items.dart:312]: It seems unfortunate that we have to convert this to a stateful widget just to get the proxy component behavior. Is it possible to create a `StatelessProxyDocumentComponent` widget that would allow the list item component to do something like:

```dart
return Row(
  children: [
    // list item indicatory
    Expanded (
      child: StatelessProxyDocumentComponent(
        child: TextComponent(
          key: _textKey,
          // ...
        ),
      ),
    ],
  ),
);
```

File: super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart (hunk 6 above)
Comment (matthew-carroll) [reply super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart:171]: Please rename this one like the other one.

File: super_editor/lib/src/default_editor/list_items.dart (hunk 8 above)
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/list_items.dart:312]: To implement a component we need to make it a stateful widget. The `DocumentComponent` is a mixin on `State`, not on the widget.

We could make a `ProxyComponentWidget extends StatefulWidget` and then use it like you described.

Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/list_items.dart]: I implemented a `ProxyDocumentComponent`. Please take a look to see if you agree with the list component looks like now.

If you are happy with the implementation, I'll add the docs for the new component.

File: super_editor/lib/src/core/document_layout.dart [hunk 9]
```diff
@@ -443,6 +451,35 @@ mixin ProxyDocumentComponent<T extends StatefulWidget> implements DocumentCompon
   }
 }
 
+class ProxyTextComponent extends StatefulWidget {
```
Comment (matthew-carroll) [inline super_editor/lib/src/core/document_layout.dart:454]: Do we need this to be specific to text? It looks like the only abstract behavior in `ProxyDocumentComponent` is `GlobalKey get childDocumentComponentKey` - can't we define a stateful widget that implements that one property and avoid making it specific to any particular content type?

If so, perhaps we should rename `ProxyDocumentComponent` to `ProxyDocumentComponentStateMixin` and then create a new widget called `ProxyDocumentComponent` that takes the desired key, and the subtree, like the `Row` for the list items.

Comment (angelosilvestre) [reply super_editor/lib/src/core/document_layout.dart:454]: We can't. This component need to mix in `ProxyTextComposable`, otherwise things like double tap to select by word doesn't work. This mixin need to be mixed by `ProxyTextComponent` because the `ProxyTextComponent` is bound to the component key.

File: super_editor/lib/src/default_editor/list_items.dart [hunk 10]
```diff
@@ -305,6 +306,8 @@ class UnorderedListItemComponent extends StatelessWidget {
   final bool showComposingUnderline;
   final bool showDebugPaint;
 
+  final GlobalKey _textKey = GlobalKey();
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/list_items.dart:309]: Let's call this `_innerTextComponentKey`.

Let's add this Dart Doc:

```
/// A [GlobalKey] that connects a [ProxyTextDocumentComponent] to its
/// descendant [TextComponent].
///
/// The [ProxyTextDocumentComponent] doesn't know where the
/// [TextComponent] sits in its subtree, but the proxy needs access to the
/// [TextComponent] to provide access to text layout details.
///
/// This key doesn't need to be public because the given [componentKey]
/// provides clients with direct access to text layout queries, as well as
/// standard [DocumentComponent] queries.
```

File: super_editor/lib/src/default_editor/text.dart [hunk 11]
```diff
@@ -1011,6 +1011,35 @@ class TextComponentState extends State<TextComponent> with DocumentComponent imp
   }
 }
 
+class ProxyTextDocumentComponent extends StatefulWidget {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/text.dart:1014]: Dart Doc:

```
/// A [ProxyDocumentComponent] that adds [TextComposable] capabilities so
/// that simple text-based proxy components can meet their expected contract
/// without going through the work of defining a stateful widget that mixes in
/// the [ProxyDocumentComponent] methods.
///
/// Using a [ProxyTextDocumentComponent] is never technically necessary.
/// Custom [DocumentComponent]s can achieve a similar result by mixing in
/// [ProxyDocumentComponent] within a `State` object. This widget is provided
/// as a convenience so that some components can be defined as stateless
/// widgets while still providing access to component behaviors and text layout
/// queries.
```

Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/text.dart:1014]: BTW, the line length on all comments that I post on GitHub might be wrong. I space them to avoid new lines on GitHub - the actual lines should probably be longer.

File: super_editor/lib/src/default_editor/text.dart [hunk 12]
```diff
@@ -1011,6 +1011,35 @@ class TextComponentState extends State<TextComponent> with DocumentComponent imp
...
+  const ProxyTextDocumentComponent({
+    super.key,
+    required this.childDocumentComponentKey,
+    required this.child,
+  });
+
+  final GlobalKey<State<StatefulWidget>> childDocumentComponentKey;
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/text.dart:1021]: The type definition seems redundant. Can a `GlobalKey` ever bind to something other than a `State<StatefulWidget>`?

Also, let's call this `textComponentKey`.

File: super_editor/lib/src/default_editor/text.dart [hunk 13]
```diff
@@ -1011,6 +1011,35 @@ class TextComponentState extends State<TextComponent> with DocumentComponent imp
...
+
+  final Widget child;
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/text.dart:1023]:
```
/// The widget subtree, which must include a widget that implements 
/// `TextComposable`, and that `TextComposable` must be bound to
/// the given [textComponentKey].
```

File: super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart (hunk 5 above)
Comment (matthew-carroll) [reply super_editor/lib/src/test/super_editor_test/supereditor_inspector.dart:149]: Let's rename this to `findTextInComponent()`

**Comment by matthew-carroll** [comment]
@angelosilvestre there are merge conflicts

**Comment by angelosilvestre** [comment]
@matthew-carroll I rebased and fixed the conflicts.

**Review by matthew-carroll — APPROVED** [review]
LGTM
