### PR TITLE
[SuperEditor] Fix crash with selected color strategy in an empty paragraph (Resolves #2253)

### LINKED ISSUE #2253: [BUG] - Exception when triple clicking in empty paragraph while _selectedTextColorStrategy != null
**Package Version**
super_editor, GitHub, main branch

**User Info**
coneno, QuikFlow

**To Reproduce**
1. Open the example app
2. Go to the Selected Text Colors section
3. Delete all text
4. Triple click the empty paragraph
5. See exception

**Actual behavior**
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:attributed_text/src/span_range.dart': Failed assertion: line 20 pos 16: 'end >= -1': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
#2      new SpanRange (package:attributed_text/src/span_range.dart:20:16)
#3      SingleColumnLayoutSelectionStyler._applySelection (package:super_editor/src/default_editor/layout_single_column/_styler_user_selection.dart:145:21)
#4      SingleColumnLayoutSelectionStyler.style (package:super_editor/src/default_editor/layout_single_column/_styler_user_selection.dart:79:11)
#5      SingleColumnLayoutPresenter._createNewViewModel (package:super_editor/src/default_editor/layout_single_column/_presenter.dart:190:35)
#6      SingleColumnLayoutPresenter.updateViewModel (package:super_editor/src/default_editor/layout_single_column/_presenter.dart:148:18)
#7      _SingleColumnDocumentLayoutState._onPresenterMarkedDirty (package:super_editor/src/default_editor/layout_single_column/_layout.dart:115:22)
#8      SingleColumnLayoutPresenterChangeListener.onPresenterMarkedDirty (package:super_editor/src/default_editor/layout_single_column/_presenter.dart:339:30)
#9      SingleColumnLayoutPresenter._assemblePipeline.<anonymous closure> (package:super_editor/src/default_editor/layout_single_column/_presenter.dart:125:22)
#10     SingleColumnLayoutStylePhase.markDirty (package:super_editor/src/default_editor/layout_single_column/_presenter.dart:408:21)
#11     ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:433:24)
#12     ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:555:5)
#13     PausableValueNotifier.resumeNotifications (package:super_editor/src/infrastructure/pausable_value_notifier.dart:49:11)
#14     MutableDocumentComposer.onTransactionEnd (package:super_editor/src/core/document_composer.dart:155:24)
#15     Editor._onTransactionEnd (package:super_editor/src/core/editor.dart:331:16)
#16     Editor.endTransaction (package:super_editor/src/core/editor.dart:231:5)
#17     Editor.execute (package:super_editor/src/core/editor.dart:283:7)
#18     _DocumentMouseInteractorState._selectParagraphAt (package:super_editor/src/default_editor/document_gestures_mouse.dart:448:21)
#19     _DocumentMouseInteractorState._onTripleTapDown (package:super_editor/src/default_editor/document_gestures_mouse.dart:428:34)
#20     TapSequenceGestureRecognizer.addAllowedPointer.<anonymous closure> (package:super_editor/src/infrastructure/multi_tap_gesture.dart:105:71)
#21     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:344:24)
#22     TapSequenceGestureRecognizer.addAllowedPointer (package:super_editor/src/infrastructure/multi_tap_gesture.dart:105:9)
#23     GestureRecognizer.addPointer (package:flutter/src/gestures/recognizer.dart:246:7)
#24     RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:1514:18)
#25     RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:3059:29)
#26     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:475:22)
#27     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:425:11)
#28     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:420:7)
#29     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:383:5)
#30     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:330:7)
#31     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:299:9)
#32     _invoke1 (dart:ui/hooks.dart:328:13)
#33     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:442:7)
#34     _dispatchPointerDataPacket (dart:ui/hooks.dart:262:31)
```
**Expected behavior**
The cursor is placed in the empty paragraph and there is no exception.

**Platform**
macOS

**Flutter version**
Flutter 3.22.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b0850beeb2 (5 weeks ago) • 2024-07-16 21:43:41 -0700
Engine • revision 235db911ba
Tools • Dart 3.4.4 • DevTools 2.34.3

**Screenshots**
Screenshot 2024-08-18 at 18 14 03

**Additional Context**
Fixed it like this for now (added `!textSelection.isCollapsed` to condition):
https://github.com/coneno/super_editor/commit/dc9cd3fa8a0ba2fa5eace51eb02ae00ce8b0ba90

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor] Fix crash with selected color strategy in an empty paragraph (Resolves #2253)

When the editor has a `selectedTextColorStrategy` configured, triple tapping on an empty paragraph crashes the editor with the following exception:

```console
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: 'package:attributed_text/src/span_range.dart': Failed assertion: line 20 pos 16: 'end >= -1': is not true.
#0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:63:4)
#1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:45:5)
#2      new SpanRange (package:attributed_text/src/span_range.dart:20:16)
#3      SingleColumnLayoutSelectionStyler._applySelection (package:super_editor/src/default_editor/layout_single_column/_styler_user_selection.dart:147:17)
#4      SingleColumnLayoutSelectionStyler.style (package:super_editor/src/default_editor/layout_single_column/_styler_user_selection.dart:79:11)
#5      SingleColumnLayoutPresenter._createNewViewModel (package:super_editor/src/default_editor/layout_single_column/_presenter.dart:189:35)
#6      SingleColumnLayoutPresenter.updateViewModel (package:super_editor/src/default_editor/layout_single_column/_presenter.dart:148:18)
#7      _SingleColumnDocumentLayoutState._onPresenterMarkedDirty (package:super_editor/src/default_editor/layout_single_column/_layout.dart:115:22)
#8      SingleColumnLayoutPresenterChangeListener.onPresenterMarkedDirty (package:super_editor/src/default_editor/layout_single_column/_presenter.dart:338:30)
#9      SingleColumnLayoutPresenter._assemblePipeline.<anonymous closure> (package:super_editor/src/default_editor/layout_single_column/_presenter.dart:125:22)
#10     SingleColumnLayoutStylePhase.markDirty (package:super_editor/src/default_editor/layout_single_column/_presenter.dart:407:21)
#11     ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:439:24)
#12     ValueNotifier.value= (package:flutter/src/foundation/change_notifier.dart:564:5)
#13     PausableValueNotifier.resumeNotifications (package:super_editor/src/infrastructure/pausable_value_notifier.dart:49:11)
#14     MutableDocumentComposer.onTransactionEnd (package:super_editor/src/core/document_composer.dart:155:24)
#15     Editor._onTransactionEnd (package:super_editor/src/core/editor.dart:331:16)
#16     Editor.endTransaction (package:super_editor/src/core/editor.dart:231:5)
#17     Editor.execute (package:super_editor/src/core/editor.dart:283:7)
#18     _DocumentMouseInteractorState._selectParagraphAt (package:super_editor/src/default_editor/document_gestures_mouse.dart:499:21)
#19     _DocumentMouseInteractorState._onTripleTapDown (package:super_editor/src/default_editor/document_gestures_mouse.dart:479:34)
#20     TapSequenceGestureRecognizer.addAllowedPointer.<anonymous closure> (package:super_editor/src/infrastructure/multi_tap_gesture.dart:105:71)
#21     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:357:24)
#22     TapSequenceGestureRecognizer.addAllowedPointer (package:super_editor/src/infrastructure/multi_tap_gesture.dart:105:9)
#23     GestureRecognizer.addPointer (package:flutter/src/gestures/recognizer.dart:254:7)
#24     RawGestureDetectorState._handlePointerDown (package:flutter/src/widgets/gesture_detector.dart:1550:18)
#25     RenderPointerListener.handleEvent (package:flutter/src/rendering/proxy_box.dart:3095:44)
#26     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:499:22)
#27     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:460:11)
#28     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:437:7)
#29     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:394:5)
#30     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:341:7)
#31     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:308:9)
#32     _invoke1 (dart:ui/hooks.dart:332:13)
#33     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:451:7)
#34     _dispatchPointerDataPacket (dart:ui/hooks.dart:267:31)
```

This PR fixes this issue by checking if the selection is not collapsed before trying to apply the attributions.

### CODE REVIEW

File: super_editor/test/super_editor/supereditor_selection_test.dart [hunk 1]
```diff
@@ -84,6 +84,27 @@ void main() {
         expect(richText.getSpanForPosition(const TextPosition(offset: 5))!.style!.color, Colors.green);
         expect(richText.getSpanForPosition(const TextPosition(offset: 16))!.style!.color, Colors.green);
       });
+
+      testWidgetsOnAllPlatforms("does not crash when placing the selection on an empty paragraph", (tester) async {
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_selection_test.dart:88]: If triple tap is relevant, please mention that in the title. This test makes it sound like a single tap, or even dragging a handle might crash in an empty paragraph.

**Review by matthew-carroll — APPROVED** [review]
