### PR TITLE
[SuperEditor][web] Fix text input after a deletion (Resolves #1224)

### LINKED ISSUE #1224: Web text input works inconsistently
- Launch the Example Editor with Chrome. (`super_editor/example (branch stable) ❯ flutter run -d chrome`) 
- Type in the document for a bit
- Sometimes, the document updates in response to text input, then eventually stops responding to text input.
- Other times, the editor does not update in response to text input, then somehow starts updating in response to text input.
- May be related to spacebar or delete keys.

Flutter Doctor

```
Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.10.5, on macOS 13.4.1 22F82 darwin-arm64, locale en-US)
    ! The flutter binary is not on your path. Consider adding /Users/brian/lab/flutter/bin to your path.
    ! The dart binary is not on your path. Consider adding /Users/brian/lab/flutter/bin to your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 14.3.1)
[✓] Chrome - develop for the web
[!] Android Studio (not installed)
[✓] IntelliJ IDEA Community Edition (version 2023.1.3)
[✓] VS Code (version 1.79.2)
[✓] Connected device (3 available)
[✓] Network resources

! Doctor found issues in 2 categories.
```

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][web] Fix text input after a deletion. Resolves #1224

On web, if we quickly press backspace and type a character at the end of a paragraph we get the following exception and the text input crashes:

```
Couldn't map an IME position to a document position.
```

The issue is that we are handling the deletion twice on web. In IME mode, Flutter reports both the deletion delta and the backspace keypress.

This PR changes `defaultImeKeyboardActions` to include a different version of `deleteUpstreamContentWithBackspace`, which does nothing when running on web.

### CODE REVIEW

**Comment by angelosilvestre** [comment]
@brian-superlist Could you please try this PR?

File: super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart [hunk 1]
```diff
@@ -249,6 +249,27 @@ ExecutionInstruction deleteUpstreamContentWithBackspace({
   return didDelete ? ExecutionInstruction.haltExecution : ExecutionInstruction.continueExecution;
 }
 
+ExecutionInstruction deleteUpstreamContentWithBackspaceOnNonWeb({
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:252]: Rather than refer to `OnNonWeb`, I think it makes more sense to say `WithIME`, which then communicates why we're using it in the IME list.

Also, we're probably going to forget why we did this almost immediately, right? There should be a clear description as to why this handler exists.

File: super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart [hunk 2]
```diff
@@ -249,6 +249,27 @@ ExecutionInstruction deleteUpstreamContentWithBackspace({
...
+  required SuperEditorContext editContext,
+  required RawKeyEvent keyEvent,
+}) {
+  if (kIsWeb) {
+    return ExecutionInstruction.continueExecution;
+  }
+
+  if (keyEvent is! RawKeyDownEvent) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:260]: Is there any reason that you don't call the regular handler internally? Seems like we probably don't need to duplicate anything, do we?

File: super_editor/lib/src/default_editor/super_editor.dart [hunk 3]
```diff
@@ -903,7 +903,7 @@ final defaultImeKeyboardActions = <DocumentKeyboardAction>[
   deleteToStartOfLineWithCmdBackspaceOnMac,
   deleteWordUpstreamWithAltBackspaceOnMac,
   deleteWordUpstreamWithControlBackspaceOnWindowsAndLinux,
-  deleteUpstreamContentWithBackspace,
+  deleteUpstreamContentWithBackspaceOnNonWeb,
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/super_editor.dart:906]: Can you please add appropriate tests that replicate the web behavior of sending both to ensure the problem is solved?

**Comment by brian-superlist** [comment]
@angelosilvestre This one is working better, typing generally doesn't get stuck, but it looks like there are two issues:

**Issue 1: Cannot remove a node by pressing delete key**

_Reproduction Steps:_

  1. Create a new blank node
  2. Set selecetion at beginning of node
  3. Press the Backspace Key (Delete key on Mac)
 
_Expected:_ Node is deleted and selection returns to end of previous node
_Actual:_ Nothing happens

https://github.com/superlistapp/super_editor/assets/90610075/2cdd15d4-e3d8-4c5b-adc6-9cadddd4f9c5

**Issue 2: Selected Text + Deletion does not work correctly**

_Reproduction Steps:_
  1. Add some content to the editor
  2. Select that content
  3. Press the Backspace Key (Delete key on Mac)

_Expected:_ Selected Content is Deleted
_Actual:_ Wrong content is deleted

This also does not work if you type normal characters instead of pressing the backspace / delete key.

https://github.com/superlistapp/super_editor/assets/90610075/b8c6d350-4fc0-448d-940f-34617a625476

**Comment by angelosilvestre** [comment]
> Issue 2: Selected Text + Deletion does not work correctly

I was able to fix this issue. It's the same root cause as the first issue. We are changing the selection when we are handling the deltas and also on key events.

I applied the same solution. However, I've found a flutter web issue: even when we are expanding the selection upstream (shift + left arrow), the IME reports a downstream selection. This causes the caret to be display at the wrong position.

I filed https://github.com/flutter/flutter/issues/131906.

@matthew-carroll

**Comment by brian-superlist** [comment]
Thanks, @angelosilvestre. I found one problem with the current PR. Is it related to the Flutter issue you mentioned?

**Reproduction Steps**

  1. Select some text
  2. Replace with different content
  4. Create a new empty node
  5. Unable to delete it

https://github.com/superlistapp/super_editor/assets/90610075/375ca921-259d-4faa-8f31-89f7867a446a


**Logs**

```
══╡ EXCEPTION CAUGHT BY SERVICES LIBRARY ╞══════════════════════════════════════════════════════════
The following assertion was thrown during method call TextInputClient.updateEditingStateWithDeltas:
Assertion failed:
file:///Users/brian/lab/flutter/packages/flutter/lib/src/services/text_editing_delta.dart:135:14
_debugTextRangeIsValid(newSelection, oldText)
"The selection range: TextSelection(baseOffset: 69, extentOffset: 70, isDirectional: false) is not
within the bounds of text: ~ of length: 1"

When the exception was thrown, this was the stack:
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
packages/flutter/src/services/text_editing_delta.dart 135:58                      fromJSON
packages/flutter/src/services/text_input.dart 1860:59                             _handleTextInputInvocation
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/flutter/src/services/text_input.dart 1768:45                             [_handleTextInputInvocation]
packages/flutter/src/services/text_input.dart 1753:20                             _loudlyHandleTextInputInvocation
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/flutter/src/services/text_input.dart 1751:51                             [_loudlyHandleTextInputInvocation]
packages/flutter/src/services/platform_channel.dart 552:55                        _handleAsMethodCall
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/flutter/src/services/platform_channel.dart 549:40                        [_handleAsMethodCall]
packages/flutter/src/services/platform_channel.dart 545:34                        <fn>
packages/flutter/src/services/binding.dart 567:35                                 <fn>
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 84:54                runBody
dart-sdk/lib/_internal/js_dev_runtime/patch/async_patch.dart 127:5                _async
packages/flutter/src/services/binding.dart 564:98                                 <fn>
lib/_engine/engine/platform_dispatcher.dart 1335:13                               invoke2
lib/ui/channel_buffers.dart 25:12                                                 invoke
lib/ui/channel_buffers.dart 65:7                                                  push
lib/ui/channel_buffers.dart 131:16                                                push
lib/_engine/engine/platform_dispatcher.dart 438:25                                invokeOnPlatformMessage
lib/_engine/engine/text_editing/text_editing.dart 2182:39                         updateEditingStateWithDelta
lib/_engine/engine/text_editing/text_editing.dart 2289:19                         <fn>
lib/_engine/engine/text_editing/text_editing.dart 1378:7                          handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall

call:
  MethodCall(TextInputClient.updateEditingStateWithDeltas, [1, {deltas: [{oldText: ~, deltaText: ,
  deltaStart: -1, deltaEnd: -1, selectionBase: 69, selectionExtent: 70, composingBase: -1,
  composingExtent: -1}]}])
════════════════════════════════════════════════════════════════════════════════════════════════════
(6.190) ExampleApp > FINE: Showing text format toolbar
(6.208) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor change
(6.208) ExampleApp > FINE: Anchor is null. Building an empty box.
(6.228) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor change
(6.229) ExampleApp > FINE: Anchor is non-null: Offset(194.6, 299.8), child: ValueListenableBuilder<DocumentSelection?>
(6.229) ExampleApp > FINE: Building toolbar. Selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "ef55d572-e96f-4a42-8eaa-bcb3950ee6f5", position: (TextNodePosition(offset: 59, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "ef55d572-e96f-4a42-8eaa-bcb3950ee6f5", position: (TextNodePosition(offset: 70, affinity: TextAffinity.downstream)))
(8.442) ExampleApp > FINE: Showing text format toolbar
(8.457) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor change
(8.457) ExampleApp > FINE: Anchor is null. Building an empty box.
(8.474) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor change
(8.474) ExampleApp > FINE: Anchor is non-null: Offset(643.5, 274.8), child: ValueListenableBuilder<DocumentSelection?>
(8.475) ExampleApp > FINE: Building toolbar. Selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "ef55d572-e96f-4a42-8eaa-bcb3950ee6f5", position: (TextNodePosition(offset: 59, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "ef55d572-e96f-4a42-8eaa-bcb3950ee6f5", position: (TextNodePosition(offset: 62, affinity: TextAffinity.downstream)))
(8.548) ExampleApp > FINE: Showing text format toolbar
(8.549) ExampleApp > FINE: Building toolbar. Selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "ef55d572-e96f-4a42-8eaa-bcb3950ee6f5", position: (TextNodePosition(offset: 51, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "ef55d572-e96f-4a42-8eaa-bcb3950ee6f5", position: (TextNodePosition(offset: 62, affinity: TextAffinity.downstream)))
(8.559) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor change
(8.559) ExampleApp > FINE: Anchor is non-null: Offset(614.1, 274.8), child: ValueListenableBuilder<DocumentSelection?>
Error: Assertion failed: org-dartlang-sdk:///lib/ui/text.dart:547:16
start >= -1
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/ui/text.dart 547:26                                                           new
lib/_engine/engine/text_editing/text_editing.dart 573:48                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/ui/text.dart:547:16
start >= -1
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/ui/text.dart 547:26                                                           new
lib/_engine/engine/text_editing/text_editing.dart 573:48                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
```

**Comment by angelosilvestre** [comment]
@brian-superlist Thanks. I will investigate.

**Comment by angelosilvestre** [comment]
@brian-superlist This issue seems to be related to https://github.com/flutter/flutter/issues/131023

I pushed a commit in this PR related to the new line duplication.

**Comment by brian-superlist** [comment]
Great, text editing is feeling much better overall! The next problem I've found relates to multiple nodes.

**Problem 1**

  1. Create a new node
  2. Select the text in that node and some text from the node before
  3. Type in a character

_Expected_: Selected text is removed and replaced with the character I've typed
_Actual_: Nothing happens and the editor is broken


https://github.com/superlistapp/super_editor/assets/90610075/52511816-4aa9-42e5-aa34-5f10f8db6ff3

```
(5.229) ExampleApp > FINE: Showing text format toolbar
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
Initializing logger: ExampleApp
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
Initializing logger: ExampleApp
(17.323) ExampleApp > FINE: Showing text format toolbar
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
Error: Assertion failed: org-dartlang-sdk:///lib/_engine/engine/text_editing/text_editing.dart:480:10
replacedRange.start <= originalText.length && replacedRange.end <= originalText.length
is not true
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 294:49      throw_
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/errors.dart 35:3        assertFailed
lib/_engine/engine/text_editing/text_editing.dart 480:89                          _replace
lib/_engine/engine/text_editing/text_editing.dart 574:37                          inferDeltaState
lib/_engine/engine/text_editing/text_editing.dart 1372:56                         handleChange
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 574:37  _checkAndCall
dart-sdk/lib/_internal/js_dev_runtime/private/ddc_runtime/operations.dart 579:39  dcall
```

**Problem 2**

Selection across nodes does not work.

  1. Create a new node
  2. Add some text
  3. Use the keyboard to select all the text from the new node and try to select text from previous node

_Expected:_ Text is selected and can be modified
_Actual:_ Text selection is wrong


https://github.com/superlistapp/super_editor/assets/90610075/af42a71d-6d7e-47cd-b751-b25e44281015

```
The platformViewRegistry getter is deprecated and will be removed in a future release. Please import it from `dart:ui_web` instead.
Initializing logger: ExampleApp
(13.273) ExampleApp > FINE: Showing text format toolbar
(14.069) ExampleApp > FINE: Showing text format toolbar
(14.083) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor change
(14.084) ExampleApp > FINE: Anchor is null. Building an empty box.
(14.100) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor change
(14.100) ExampleApp > FINE: Anchor is non-null: Offset(255.6, 109.7), child: ValueListenableBuilder<DocumentSelection?>
(14.101) ExampleApp > FINE: Building toolbar. Selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 6, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 7, affinity: TextAffinity.downstream)))
(14.322) ExampleApp > FINE: Showing text format toolbar
(14.326) ExampleApp > FINE: Building toolbar. Selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 5, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 7, affinity: TextAffinity.downstream)))
(14.340) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor change
(14.340) ExampleApp > FINE: Anchor is non-null: Offset(250.7, 109.7), child: ValueListenableBuilder<DocumentSelection?>
(14.349) ExampleApp > FINE: Showing text format toolbar
(14.351) ExampleApp > FINE: Building toolbar. Selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 4, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 7, affinity: TextAffinity.downstream)))
(14.363) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor change
(14.363) ExampleApp > FINE: Anchor is non-null: Offset(248.5, 109.7), child: ValueListenableBuilder<DocumentSelection?>
(14.388) ExampleApp > FINE: Showing text format toolbar
(14.393) ExampleApp > FINE: Building toolbar. Selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 3, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 7, affinity: TextAffinity.downstream)))
(14.406) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor change
(14.406) ExampleApp > FINE: Anchor is non-null: Offset(245.5, 109.7), child: ValueListenableBuilder<DocumentSelection?>
(14.423) ExampleApp > FINE: Showing text format toolbar
(14.427) ExampleApp > FINE: Building toolbar. Selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 2, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 7, affinity: TextAffinity.downstream)))
(14.439) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor change
(14.439) ExampleApp > FINE: Anchor is non-null: Offset(240.9, 109.7), child: ValueListenableBuilder<DocumentSelection?>
(14.454) ExampleApp > FINE: Showing text format toolbar
(14.459) ExampleApp > FINE: Building toolbar. Selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 1, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 7, affinity: TextAffinity.downstream)))
(14.471) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor change
(14.471) ExampleApp > FINE: Anchor is non-null: Offset(236.1, 109.7), child: ValueListenableBuilder<DocumentSelection?>
(14.705) ExampleApp > FINE: Showing text format toolbar
(14.710) ExampleApp > FINE: Building toolbar. Selection: [DocumentSelection] - 
  base: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 0, affinity: TextAffinity.downstream))),
  extent: ([DocumentPosition] - node: "b465b12f-e724-457c-a318-d4b7da9bede4", position: (TextNodePosition(offset: 7, affinity: TextAffinity.downstream)))
(14.724) ExampleApp > FINE: (Re)Building _PositionedToolbar widget due to anchor change
(14.725) ExampleApp > FINE: Anchor is non-null: Offset(231.2, 109.7), child: ValueListenableBuilder<DocumentSelection?>
```

**Comment by angelosilvestre** [comment]
> Problem 1

This seems to be the same as https://github.com/flutter/flutter/issues/131023

> Problem 2

We do need a fix on our side, but we need to receive the selection affinity correctly in order to fix this (https://github.com/flutter/flutter/issues/131906)

**Comment by matthew-carroll** [comment]
@angelosilvestre @brian-superlist - Please let me know when you think this is ready for my final review to merge in.

**Comment by brian-superlist** [comment]
I don't know the internals of Super Editor well, but I'm a little curious if problem 2 is really related only to the Flutter affinity bug? For example, I can also create the problem starting from a node, moving the caret from left to right:

https://github.com/superlistapp/super_editor/assets/90610075/5273e9b7-a643-45cb-9a04-563a5b5f8068

If it definitely is, I'd say this one is good to go until we fix the underlying Flutter issues

**Comment by angelosilvestre** [comment]
@brian-superlist I have a fix for moving the caret left to right. I should push it today.

**Comment by brian-superlist** [comment]
Thanks @angelosilvestre! 

As some general feedback, I found many of these issues reported in this thread by doing very quick functional testing (< 3 minutes). To speed up PRs like this in the future and reduce these back-and-forth rounds of time-delayed feedback, I'd ask you to do more thorough functional testing on your side before asking for functional testing on our side.

Before we merge this one in, I'd recommend taking 5-10 minutes to run the example app on web, use the editor to write more content "like a normal user," and see if you run into any issues that I might have missed.

**Comment by angelosilvestre** [comment]
@brian-superlist Will do!

**Comment by brian-superlist** [comment]
@angelosilvestre Thanks 😄

**Comment by matthew-carroll** [comment]
> Before we merge this one in, I'd recommend taking 5-10 minutes to run the example app on web, use the editor to write more content "like a normal user," and see if you run into any issues that I might have missed.

This is really something that should be handled by tests. I don't really want any humans on any side spending a lot of time being test robots. Are we simply lacking appropriate tests? Or is this fundamentally a web issue, and therefore dependent on web integration tests?

**Comment by matthew-carroll** [comment]
@angelosilvestre can you check whether we're missing widget tests for this, or whether we need integration tests?

If the problem is that we need a web integration test, can you try writing a single integration test that covers one of these interactions and see if it works? I've run into major problems with web integration tests in the past, but perhaps they're usable now.

**Comment by angelosilvestre** [comment]
With the changes from this PR we will need to add some tests for web. However, there are some places where we check for `kIsWeb` and we aren't able to override this value.

We can introduce an overridable value instead of checking `kIsWeb` or we can use integration tests. But, even with integration tests, I'm not sure if we would get the assertion failures from some of the issues mentioned in this PR, because the input events would be totally generated by flutter itself.

**Comment by matthew-carroll** [comment]
> because the input events would be totally generated by flutter itself

Aren't we primarily dealing with selection changes? Wouldn't an integration test use the real IME to do that?

This PR accumulated a number of different issues. It's possible that some of those can't reasonably be tested, but the issues that can be tested, should be tested, because the alternative is to have people manually do these things over and over every time we release.

**Comment by angelosilvestre** [comment]
I think it's good now.

There are three remaining issues that are flutter issues:

- Place the caret at the end of a paragraph
- Press enter
- Type a single letter
- Press enter again
- The editor crashes

This is caused by https://github.com/flutter/flutter/issues/131023 and seems to be solved by https://github.com/flutter/engine/pull/44595.

- Place the caret at a paragraph
- Shift + left arrow until selection expands to a character from the previous node 
- Press backspace
- The editor crashes

I added this issue to the flutter ticket and it seems the fix is in progress: https://github.com/flutter/flutter/issues/131023#issuecomment-1674143311

- Place the caret at the middle of a word
- Press shift + left arrow to expand the selection upstream
- The selection expands, but the caret don't move

This is caused by https://github.com/flutter/flutter/issues/131906.

**Comment by matthew-carroll** [comment]
@angelosilvestre you enumerated the issues that this PR doesn't fix. Can you please enumerate what this PR does fix?

**Comment by angelosilvestre** [comment]
@matthew-carroll 

- Fix a crash after pressing backspace
- Fix expanding the selection upstream
- Fix new line duplication on enter
- Fix new line duplication on enter on task nodes

**Comment by angelosilvestre** [comment]
Solved conflicts.

File: super_editor/lib/src/infrastructure/text_input.dart [hunk 4]
```diff
@@ -1,5 +1,19 @@
...
+///
+/// This is intended to be used in tests.
+bool? debugIsWebOverride;
+
+/// Whether or not we are running on web.
+///
+/// By default this is the same as [kIsWeb].
+///
+/// This is intended to be overriden in tests by setting [debugIsWebOverride].
+bool get isWeb => debugIsWebOverride ?? kIsWeb;
```
Comment (matthew-carroll) [inline super_editor/lib/src/infrastructure/text_input.dart:19]: Please move this up above `debugIsWebOverride` - the reader is much more likely to be looking for this property than the other one.

File: super_editor/test/super_editor/document_test_tools.dart [hunk 5]
```diff
@@ -416,7 +416,7 @@ class TestSuperEditorConfigurator {
       imeOverrides: _config.imeOverrides,
       keyboardActions: [
         ..._config.prependedKeyboardActions,
-        ...defaultKeyboardActions,
+        ...(_config.inputSource == TextInputSource.ime ? defaultImeKeyboardActions : defaultKeyboardActions),
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/document_test_tools.dart:419]: Test tools should not be making `SuperEditor` policy decisions. We pass `_config.inputSource` into `SuperEditor`. If any such decision needs to be made, it should be made by `SuperEditor`. This configuration system only exists to let testers provide non-default values for `SuperEditor` properties.

File: super_editor/example/lib/demos/example_editor/example_editor.dart [hunk 6]
```diff
@@ -432,7 +432,6 @@ class _ExampleEditorState extends State<ExampleEditor> {
           ],
           gestureMode: _gestureMode,
           inputSource: _inputSource,
-          keyboardActions: _inputSource == TextInputSource.ime ? defaultImeKeyboardActions : defaultKeyboardActions,
```
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/example/lib/demos/example_editor/example_editor.dart:435]: We don't need it because the constructor already does the same.

File: super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart [hunk 7]
```diff
@@ -232,6 +233,18 @@ ExecutionInstruction anyCharacterOrDestructiveKeyToDeleteSelection({
   return ExecutionInstruction.haltExecution;
 }
 
+ExecutionInstruction deleteUpstreamContentWithBackspaceWithIme({
```
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:236]: We must ignore the key event only if we use IME as the input source. When using keyboard as the input source we still need to handle backspace.

Inside the key handler we don't know which input source is being used. We could add it to `SuperEditorContext`, then we would be able to just modify the existing handler.

File: super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart [hunk 8]
```diff
@@ -363,6 +376,140 @@ ExecutionInstruction moveUpDownLeftAndRightWithArrowKeys({
...
+  if (isWeb) {
+    // On web, pressing arrow keys reports both non-text deltas and key events.
+    // We handle the non-text delta to change the selection and ignore the key event.
+    return ExecutionInstruction.continueExecution;
+  }
+
+  return moveUpDownLeftAndRightWithArrowKeys(editContext: editContext, keyEvent: keyEvent);
+}
+
+ExecutionInstruction moveUpAndDownWithArrowKeysOnWeb({
```
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:392]: When using web with IME as the input source, left and right arrow keys generate non-text deltas which change the position. We need to handle only up and down arrow keys to move between lines and nodes.

File: super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart [hunk 9]
```diff
@@ -115,9 +115,9 @@ class TextDeltasDocumentEditor {
 
     if (delta.textInserted == "\n") {
       // On iOS, newlines are reported here and also to performAction().
-      // On Android and web, newlines are only reported here. So, on Android and web,
+      // On Android, newlines are only reported here. So, on Android,
       // we forward the newline action to performAction.
-      if (defaultTargetPlatform == TargetPlatform.android || kIsWeb) {
+      if (defaultTargetPlatform == TargetPlatform.android) {
```
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_ime/document_delta_editing.dart:120]: I think something has changed, but I would need to test with previous Flutter versions to confirm it.

File: super_editor/lib/src/default_editor/paragraph.dart [hunk 10]
```diff
@@ -750,6 +751,19 @@ ExecutionInstruction backspaceToClearParagraphBlockType({
   return didClearBlockType ? ExecutionInstruction.haltExecution : ExecutionInstruction.continueExecution;
 }
 
+ExecutionInstruction enterToInsertBlockNewlineWithIme({
```
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/paragraph.dart:754]: When we use IME as the input source we still need to handle this key events, even on web.

File: super_editor/lib/src/infrastructure/text_input.dart [hunk 11]
```diff
@@ -1,5 +1,19 @@
...
 /// The mode of user text input.
 enum TextInputSource {
   keyboard,
   ime,
 }
+
+/// Overrides the value of [isWeb].
+///
+/// This is intended to be used in tests.
+bool? debugIsWebOverride;
```
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/text_input.dart:12]: > Please add the appropriate annotation for test related APIs. And then you don't need to state that in the comments.

Do you mean `visibleForTesting`?

> Also, I'm not sure a bool is the right type for this. Shouldn't the developer be able to override this value in both directions? Either force it to "yes we're on web" or force it to "no we're not on web"? That would require a 3 value type.

As this is a nullable `bool`, this is already possible:

`null`: use `isWeb` value
`true`: we are on web
`false`: we are not on web

File: super_editor/test/super_editor/document_test_tools.dart (hunk 5 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/document_test_tools.dart:419]: `SuperEditor` already has this policy, but as we are always setting a value for `keyboardActions` we are overriding it and always using `defaultKeyboardActions`, even when using IME.

File: super_editor/test/test_tools.dart [hunk 12]
```diff
@@ -85,6 +84,46 @@ void testWidgetsOnDesktop(
   testWidgetsOnLinux("$description (on Linux)", test, skip: skip, variant: variant);
 }
 
+/// A widget test that runs a variant for every desktop platform, e.g.,
+/// Mac, Windows, Linux and for macOS Web.
```
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/test/test_tools.dart:88]: Modified to run on all platforms on web.

File: super_editor/lib/src/infrastructure/text_input.dart (hunk 11 above)
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/text_input.dart]: I added a dart doc, but if you think we should use an `enum` we can change it.

File: super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart (hunk 7 above)
[the remark this answers is not in the document]
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:236]: In that case, I think the way we've handled things like this in the past is to define keyboard handlers that block execution, rather than composing conditional handlers around other handlers. Those blocking handlers are probably easier to name accurately. I bet that approach will also prove easier for people to understand.

File: super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart (hunk 8 above)
[the remark this answers is not in the document]
Comment (matthew-carroll) [reply super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:392]: Does this mean that we've duplicated all the vertical arrow key behavior just because our original handler included both horizontal and vertical implementations?

If so, we should separate the original handler into two handlers. One for horizontal and one for vertical. Then we can leave the vertical one alone, and we can introduce a blocking handler for the horizontal case on web.

File: super_editor/lib/src/infrastructure/text_input.dart (hunk 11 above)
[the remark this answers is not in the document]
Comment (matthew-carroll) [reply super_editor/lib/src/infrastructure/text_input.dart]: Yeah. `visibleForTesting`.

In general, it's probably not a good idea to give significance to a `null` `bool`. That condition is likely to be overlooked. You can do a nullable `enum`, but a nullable `bool` is just begging for confusion.

File: super_editor/test/super_editor/document_test_tools.dart (hunk 5 above)
Comment (matthew-carroll) [reply super_editor/test/super_editor/document_test_tools.dart:419]: Are we doing this with any other configuration property? Or is this the first one that we've pulled out from `SuperEditor` into the configuration system?

**Comment by matthew-carroll** [comment]
FYI - there are merge conflicts, probably because I moved around a bunch of tests.

File: super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart (hunk 7 above)
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:236]: Understood. I'll use that approach.

File: super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart (hunk 8 above)
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:392]: Updated.

File: super_editor/lib/src/infrastructure/text_input.dart (hunk 11 above)
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/lib/src/infrastructure/text_input.dart]: Updated.

File: super_editor/test/super_editor/document_test_tools.dart (hunk 5 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/document_test_tools.dart:419]: It seems it's just for this property. We do a similar thing for the component builders, but as we have only one list of `defaultComponentBuilders` this isn't a problem.

File: super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart [hunk 13]
```diff
@@ -323,41 +322,171 @@ ExecutionInstruction moveUpDownLeftAndRightWithArrowKeys({
...
+  if (isWeb) {
+    // On web, pressing arrow keys reports both non-text deltas and key events.
+    // We handle the non-text delta to change the selection and ignore the key event.
+    return ExecutionInstruction.blocked;
+  }
+
+  return ExecutionInstruction.continueExecution;
+}
+
+ExecutionInstruction moveBetweenNodesWithLeftRightArrowKeysOnWeb({
```
Comment (matthew-carroll) [inline super_editor/lib/src/default_editor/document_hardware_keyboard/document_keyboard_actions.dart:412]: Let's try doing all the left/right web stuff in a single handler.

File: super_editor/test/super_editor/components/task_test.dart [hunk 14]
```diff
@@ -136,6 +136,58 @@ void main() {
       );
     });
 
+    testWidgetsOnWebDesktop("inserts new task on ENTER at end of existing task", (tester) async {
+      final document = MutableDocument(
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/components/task_test.dart:140]: Can you use our standard super editor configuration instead of doing all this manually?

File: super_editor/test/super_editor/supereditor_input_ime_test.dart [hunk 15]
```diff
@@ -745,6 +745,94 @@ Paragraph two
       });
     });
 
+    group('on web', () {
+      group('moves caret', () {
+        testWidgetsOnDesktopAndWeb('to end of previous node when LEFT_ARROW is pressed at the beginning of a paragraph',
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_input_ime_test.dart:750]: If this is in the "on web" group, why are we testing "OnDesktopAndWeb"?

File: super_editor/test/super_editor/supereditor_input_ime_test.dart [hunk 16]
```diff
@@ -745,6 +745,94 @@ Paragraph two
...
+            (tester) async {
+          await tester
+              .createDocument() //
+              .withLongDoc()
+              .withInputSource(TextInputSource.ime)
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/supereditor_input_ime_test.dart:755]: Should the input source be a variant so that we ensure this works for both input modes?

File: super_editor/test/test_tools.dart [hunk 17]
```diff
@@ -85,6 +84,113 @@ void testWidgetsOnDesktop(
...
+/// A widget test that runs a variant for every desktop platform as native and web, e.g.,
+/// Mac, Windows, Linux.
+@isTestGroup
+void testWidgetsOnDesktopAndWeb(
+  String description,
+  WidgetTesterCallback test, {
+  bool skip = false,
+  TestVariant<Object?> variant = const DefaultTestVariant(),
+}) {
+  testWidgetsOnMac("$description (on MAC)", test, skip: skip, variant: variant);
```
Comment (matthew-carroll) [inline super_editor/test/test_tools.dart:96]: Can this implementation be reduced to the following?

```dart
testWidgetsOnDesktop(...);
testWidgetsOnWebDesktop(...);
```

File: super_editor/test/super_editor/components/task_test.dart (hunk 14 above)
Comment (angelosilvestre) [reply super_editor/test/super_editor/components/task_test.dart:140]: The `TaskComponentBuilder` requires an `Editor` in the constructor, so we can't user our standard configuration right now.

File: super_editor/test/super_editor/supereditor_input_ime_test.dart (hunk 15 above)
Comment (matthew-carroll) [reply super_editor/test/super_editor/supereditor_input_ime_test.dart:751]: I see that "on web" was changed to "on desktop" - that just reverses the problem. We're specifying a group that's more narrow than what's in the group. It seems to me like that group name is pointless. It's not just desktop, it's not just web. You could say "on desktop and web" but we might as well let the test names clarify that. I believe each of these test names will add a suffix that specifies which platform, right?

Comment (angelosilvestre) [reply super_editor/test/super_editor/supereditor_input_ime_test.dart]: Updated.

**Review by matthew-carroll — APPROVED** [review]
LGTM

**Comment by angelosilvestre** [comment]
@matthew-carroll Rebased onto main to fix a compilation error due to the change in the `AttributedText` constructor.
