### PR TITLE
[SuperEditor][Android] Fix magnifier position inside an ancestor scrollable (Resolves #1810)

### LINKED ISSUE #1810: [SuperEditor] [Android] Magnifier position is broken when Editor in a CustomScrollView
**Package Version**
`main` branch with commit hash https://github.com/superlistapp/super_editor/commit/2cb93e23ba2442e911c1bfcaf107c247adc6d131

**To Reproduce**
1. Go to Sliver Editor demo
2. Scroll down a bit
3. Place the selection in the content
4. Start dragging the drag handle upwards

**Actual behavior**
Initially the magnifier is not visible and as the drag handle is moved towards the top of the editor, then we see the magnifier coming from the bottom and getting closer to the selection.

**Expected behavior**
The magnifier is visible above the selection.

**Platform**
Android.

**Flutter version**
Flutter master commit e278279a48f0479386c249cf18f26b29c6f9018f.

**Screenshots**

https://github.com/superlistapp/super_editor/assets/31278849/bba51f3a-6ca4-4f2a-b29c-91c31e6f00e1

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][Android] Fix magnifier position inside an ancestor scrollable. Resolves #1810

If the editor is inside a `CustomScrollView` with other widgets above the editor, the magnifier isn't positioned correctly when dragging the drag handle:

https://github.com/superlistapp/super_editor/assets/31278849/bba51f3a-6ca4-4f2a-b29c-91c31e6f00e1

I noticed we are positioning the drag handle leader using the mobile interactor coordinate space, and it seems the we need to position it using the global coordinate space.

Modifying the android interactor to position the leader using the global coordinates seems to solve the issue:

Inside a `CustomScrollView`: 

[android_with_scrollable.webm](https://github.com/superlistapp/super_editor/assets/7597082/dfd7587c-2c55-498c-af0d-634efcdc5fe4)

Without an ancestor `Scrollable`:

[android_without_scrollable.webm](https://github.com/superlistapp/super_editor/assets/7597082/18611cfe-09d0-4178-aaf4-4d74a9697ac0)

### CODE REVIEW

File: super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart [hunk 1]
```diff
@@ -211,6 +212,168 @@ void main() {
...
+        for (int i = 0; i < 5; i += 1) {
+          await gesture.moveBy(const Offset(24, 0));
+          await tester.pump();
+        }
+
+        // Ensure magnifier is visible and it's placed above the caret.
+        expect(SuperEditorInspector.isMobileMagnifierVisible(), isTrue);
+        expect(
+          tester.getBottomLeft(SuperEditorInspector.findMobileMagnifier()).dy,
+          lessThan(tester.getTopLeft(SuperEditorInspector.findMobileCaret()).dy),
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart:270]: Can you add a comment about why this condition satisfies the goal of the test? I'm guessing this is because you expect the content above the editor to push the magnifier down if we're in the wrong coordinate space. If so, we should spell that out very clearly for future readers.

Comment (angelosilvestre) [reply super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart:272]: Updated.

File: super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart [hunk 2]
```diff
@@ -211,6 +212,172 @@ void main() {
...
+
+        // Press and drag the caret somewhere else in the paragraph.
+        final gesture = await tester.pressDownOnCollapsedMobileHandle();
+        for (int i = 0; i < 5; i += 1) {
+          await gesture.moveBy(const Offset(24, 0));
+          await tester.pump();
+        }
+
+        // Ensure magnifier is visible and it's placed above the caret.
+        // If the wrong coordinate space is used, the content above the editor
```
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart:367]: > you're checking that the magnifier overlaps the caret?

Nope, the bottom left of the magnifier being less than the top left of the caret means that the magnifier  "ends" before the caret "starts", since a lower y means it's above it on the screen.

[the remark this answers is not in the document]
Comment (matthew-carroll) [reply super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart:367]: Ok. Before we take a look at the comment, should we add a bound in the other direction? For example, this test might fail if the magnifier is pushed down towards the bottom of the screen, but this test wouldn't fail if the magnifier sits at the top of the screen, right? Should we add a reasonable upper limit to make sure the magnifier is roughly in the right place?

[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart]: Updated.

File: super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart [hunk 3]
```diff
@@ -211,6 +212,188 @@ void main() {
...
+        await tester.tapInParagraph("1", 440);
+
+        // Press and drag the caret somewhere else in the paragraph.
+        final gesture = await tester.pressDownOnCollapsedMobileHandle();
+        for (int i = 0; i < 5; i += 1) {
+          await gesture.moveBy(const Offset(24, 0));
+          await tester.pump();
+        }
+
+        // Ensure magnifier is visible, it's placed above the caret and not
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart:266]: Now that you've updated the conditions, let's update the comment:

```
// Ensure that the magnifier appears above the caret. To check this, we make
// sure the bottom of the magnifier is above the top of the caret, and we make
// sure that the bottom of the magnifier is not unreasonable far above the
// caret.
```

Let's also change the code so that both conditions check the bottom of the magnifier. It seems strange to change from checking the bottom of the magnifier to checking the top of it.

Comment (angelosilvestre) [reply super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart]: Updated.

File: super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart [hunk 4]
```diff
@@ -211,6 +212,189 @@ void main() {
...
+        // sure that the bottom of the magnifier is not unreasonable far above the caret.
+        expect(SuperEditorInspector.isMobileMagnifierVisible(), isTrue);
+        expect(
+          tester.getBottomLeft(SuperEditorInspector.findMobileMagnifier()).dy,
+          lessThan(tester.getTopLeft(SuperEditorInspector.findMobileCaret()).dy),
+        );
+        expect(
+          tester.getTopLeft(SuperEditorInspector.findMobileCaret()).dy -
+              tester.getBottomLeft(SuperEditorInspector.findMobileMagnifier()).dy,
+          lessThan(70.0),
```
Comment (matthew-carroll) [inline super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart:324]: Is `70` still a reasonable number now that we're checking the distance between the bottom of hte magnifier and the top of the caret? That seems very large.

Comment (angelosilvestre) [reply super_editor/test/super_editor/mobile/super_editor_android_overlay_controls_test.dart]: In the tests the reported distance is  ~ `12.8`. I modified the maximum distance to be `20`.

**Review by matthew-carroll — COMMENTED** [review]
LGTM
