### PR TITLE
[SuperEditor][SuperTextField] Workaround a character height issue (Resolves #2323)

### LINKED ISSUE #2323: [BUG] - [SuperEditor/SuperTextField] Caret heigh changes when inserting a space at the end of the text
**Package Version**
main branch (36376a5a9cc8569a0c89211c255773f96668e7db)

**User Info**
Superlist

**To Reproduce**
1. Go to `SuperEditor` demo
2. Place the selection at the end of a text node
3. Insert a space

The same happens in the `SuperTextField` demo

**Actual behavior**
Space is added and caret height changes (gets smaller)

**Expected behavior**
Space is added and caret height remains the same

**Platform**
Seems to be in all platforms

**Flutter version**
master

**Screenshots**

https://github.com/user-attachments/assets/a59e847b-c86b-4753-9968-348004083eca

### PR DESCRIPTION
**Pull request by angelosilvestre**
[SuperEditor][SuperTextField] Workaround a character height issue. Resolves #2323

Inserting a space at the end of a node causes the caret to have a smaller caret:

https://github.com/user-attachments/assets/a59e847b-c86b-4753-9968-348004083eca

This looks to be a Flutter bug, which is reported in https://github.com/flutter/flutter/issues/155330

This PR adds a temporary workaround. When the selection sits at the end of a text node which ends with a space, we use the caret height of the space (the last character) instead of the caret height reported for the end of the text (after the space).

https://github.com/user-attachments/assets/f824be01-f27c-4141-8738-ce56706bd710

### CODE REVIEW

**Comment by angelosilvestre** [comment]
@matthew-carroll Unfortunately we might need to release a new version of `super_text_layout`, because I needed to include another parameter to a public constructor.

**Comment by miguelcmedeiros** [comment]
@angelosilvestre I tested this PR and I'm still getting the issue on android (tested using an emulator), but only in SuperEditor.

**Comment by angelosilvestre** [comment]
Thanks for testing this @miguelcmedeiros. It seems I missed that.

I'll take a look as soon as I can.

**Comment by angelosilvestre** [comment]
@miguelcmedeiros Would you mind testing this again?

**Comment by miguelcmedeiros** [comment]
@angelosilvestre tested it on Android and it works as expected.

File: super_text_layout/lib/src/caret_layer.dart [hunk 1]
```diff
@@ -97,10 +104,33 @@ class TextLayoutCaretState extends State<TextLayoutCaret> with TickerProviderSta
...
+    if (widget.text != null &&
+        widget.text!.text.isNotEmpty && //
+        widget.position!.offset == widget.text!.length &&
+        widget.text!.text[widget.text!.text.length - 1] == ' ') {
+      // The selection sits at the end the text and the last character is a space. Use the upstream
+      // character caret height instead of the one computed for the selection extent (which is smaller than
+      // it should be, due to the bug). Since the selection sits after the last character, the upstream
+      // character is the space itself.
+      final upstreamPosition = TextPosition(offset: widget.text!.length - 1);
+      return widget.textLayout.getHeightForCaret(upstreamPosition) ??
```
Comment (matthew-carroll) [inline super_text_layout/lib/src/caret_layer.dart:127]: Can we implement this hack inside of `getHeightForCaret()` and/or `getLineHeightAtPosition()` and remove all the other code in the PR?

Comment (angelosilvestre) [reply super_text_layout/lib/src/caret_layer.dart]: Updated.

**Review by matthew-carroll — APPROVED** [review]
LGTM
