### PR TITLE
Fix: Can now convert paragraph to task and begin with task completed (Resolves #2109)

### LINKED ISSUE #2109: [Bug][SuperEditor][SuperReader] - Tasks can't begin as completed
Due to a hard-coded value in the `ConvertParagraphToTaskCommand` we can't convert a paragraph to a task and immediately check it.

Replace the hard-coded value by passing the variable that's already made available in that command.

### PR DESCRIPTION
**Pull request by matthew-carroll**
Fix: Can now convert paragraph to task and begin with task completed (Resolves #2109)

The bug was simply that we weren't passing a variable forward - instead we hardcoded `false`.

I also cleaned up the corresponding test suite by using the pump scaffold method in all tests.

### CODE REVIEW

File: super_editor/test/super_editor/components/task_test.dart [hunk 1]
```diff
@@ -591,6 +411,42 @@ void main() {
...
+          nodes: [
+            ParagraphNode(id: "1", text: AttributedText("This is a task")),
+          ],
+        );
+        final editor = await _pumpScaffold(tester, document: document);
+
+        // Convert the paragraph to a task.
+        editor.execute([
+          const ConvertParagraphToTaskRequest(nodeId: "1", isComplete: true),
+        ]);
```
Comment (angelosilvestre) [inline super_editor/test/super_editor/components/task_test.dart:444]: I think it should be "complete task". Both tests have the same description.

**Review by angelosilvestre — APPROVED** [review]
LGTM with a single comment.
