### PR TITLE
[SuperTextField] [SuperDesktopTextField] Adds Page-Up/Down, Home/End selectors and handlers to SuperDesktopTextField (Resolves #1438)

### LINKED ISSUE #1438: [SuperTextField] Parent scroll view with SuperTextField does not scroll when Page Up/Down keys are pressed
Steps to reproduce:
* Place a `SuperTextField` (or several) on a scrollable widget (e.g. `CustomScrollView`)
* The view should have enough content to make it scrollable
* Place the focus on the text field
* Press Page Down

**Expected:** the scrollable view should scroll down
**Actual:** nothing happens

This used to work on a scrollable page with multiple text fields, which would scroll when Page Up/Down were pressed.

### PR DESCRIPTION
**Pull request by rutvik110**
[SuperTextField] [SuperDesktopTextField] Adds Page-Up/Down, Home/End selectors and handlers to SuperDesktopTextField (Resolves #1438)

## **Issue:** 

Steps to reproduce: 
1. Wrap a `SuperTextField` within a `Scrollable`, for e.g. `CustomScrollView`.
2. Tap on `SuperTextField` to make it focused.
3. Press Page Up/Down.

This actions no longer trigger the scroll on the ancestor `Scrollable`. Intended behaviour is to have the ancestor `Scrollable` to scroll up/down depending on the key press. 

## **Solution:**

This seems to have been working before we updated how we handle shortcuts [here](https://github.com/superlistapp/super_editor/pull/1339). This change now propogates the OS level shortcuts to the IME instead of handling them through defined key handlers, which was causing some issue as discussed in that PR. 

This PR introduces new selectors and key handlers at `SuperDesktopTextField` level to handle Page Up/Down, Home/End shortcuts to scroll the ancestor `Scrollable` if any present.

https://github.com/superlistapp/super_editor/assets/65209850/4ac5b96f-79e7-4796-a745-f60f6a8f8b36

## **Changes:**

* Adds 4 new keyboard handlers to `defaultTextFieldKeyboardHandlers` and `defaultTextFieldImeKeyboardHandlers` for `SuperDesktopTextField`, <br>
     * `scrollOnPageUpKeyPress`
     * `scrollOnPageDownKeyPress`
     * `scrollOnCtrlOrCmdAndHomeKeyPress`
     * `scrollOnCtrlOrCmdAndEndKeyPress`
 
* Adds 4 new selectors to `defaultTextFieldSelectorHandlers` for `SuperDesktopTextField`,  <br>

    * `_scrollPageUp`
    * `_scrollPageDown`
    * `_scrollToBeginningOfDocument`
    * `_scrollToEndOfDocument`
       
* `TextFieldKeyboardHandler` updated with an additional `Scrollable?` parameter.
* `SuperTextFieldSelectorHandler` updated with an additional `Scrollable?` parameter.
* Added `_findAncestorScrollable` which looks for the ancestor `Scrollable` and returns it if one is present to be later used for performing scroll actions on the `Scrollable` through newly added scroll selectors and handlers.

### CODE REVIEW

**Comment by rutvik110** [comment]
@angelosilvestre Let me know if this is the right direction that we wanna move in with this issue. If yes, then I'll get started on one additional thing @matthew-carroll mentioned in the issue and some docs and tests for this changes.

> Some clarification on this, if a text field has enough content to scroll, page up/down should apply to the text field. If the text field doesn't have any scrollable content, then the text field should let the page up/down keys bubble up.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 1]
```diff
@@ -399,13 +416,15 @@ class SuperDesktopTextFieldState extends State<SuperDesktopTextField> implements
...
   }) {
+    final ancestorScrollable = _findAncestorScrollable(context)?.position;
     return Actions(
       actions: defaultTargetPlatform == TargetPlatform.macOS ? disabledMacIntents : {},
       child: SuperTextFieldKeyboardInteractor(
         focusNode: _focusNode,
         textController: _controller,
         textKey: _textKey,
         keyboardActions: widget.keyboardHandlers,
+        ancestorScrollable: ancestorScrollable,
```
Comment (angelosilvestre) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: IMO, we could query the ancestor scrollable in `SuperTextFieldKeyboardInteractor` and `SuperTextFieldImeInteractor` instead of passing via constructor.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 2]
```diff
@@ -966,6 +990,7 @@ class _SuperTextFieldKeyboardInteractorState extends State<SuperTextFieldKeyboar
         controller: widget.textController,
         textLayout: widget.textKey.currentState!.textLayout,
         keyEvent: keyEvent,
+        scrollable: widget.ancestorScrollable,
```
Comment (angelosilvestre) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:993]: It doesn't seem right to be passing the scrollable directly as an argument to the handlers. Maybe would could introduce a `SuperTextFieldContext`, like we have in `SuperEditor`.

We should get Matt's opinion on this.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 3]
```diff
@@ -2189,6 +2244,138 @@ class DefaultSuperTextFieldKeyboardHandlers {
...
+      return TextFieldKeyboardHandlerResult.notHandled;
+    }
+
+    if (keyEvent.logicalKey.keyId != LogicalKeyboardKey.pageUp.keyId) {
+      return TextFieldKeyboardHandlerResult.notHandled;
+    }
+
+    if (scrollable == null) {
+      return TextFieldKeyboardHandlerResult.handled;
+    }
```
Comment (angelosilvestre) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2263]: Why are we returning `handled` if the scrollable is `null`.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 4]
```diff
@@ -2189,6 +2244,138 @@ class DefaultSuperTextFieldKeyboardHandlers {
...
+      return TextFieldKeyboardHandlerResult.notHandled;
+    }
+
+    if (keyEvent.logicalKey.keyId != LogicalKeyboardKey.pageDown.keyId) {
+      return TextFieldKeyboardHandlerResult.notHandled;
+    }
+
+    if (scrollable == null) {
+      return TextFieldKeyboardHandlerResult.handled;
+    }
```
Comment (angelosilvestre) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2290]: Same here.

**Review by angelosilvestre — COMMENTED** [review]
Sorry be the delayed review. I left some comments.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 5]
```diff
@@ -1735,6 +1772,10 @@ const defaultTextFieldKeyboardHandlers = <TextFieldKeyboardHandler>[
 /// );
 /// ```
 const defaultTextFieldImeKeyboardHandlers = <TextFieldKeyboardHandler>[
+  DefaultSuperTextFieldKeyboardHandlers.scrollOnPageUpKeyPress,
+  DefaultSuperTextFieldKeyboardHandlers.scrollOnPageDownKeyPress,
+  DefaultSuperTextFieldKeyboardHandlers.scrollOnCtrlOrCmdAndHomeKeyPress,
+  DefaultSuperTextFieldKeyboardHandlers.scrollOnCtrlOrCmdAndEndKeyPress,
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1778]: Hmm, I'll check if that's the case in the scenario you mentioned and likely move those below `sendKeyEventToMacOs` once that's clear.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 1 above)
Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: Won't that duplicate `_findAncestorScrollable` method?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 2 above)
Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:993]: That would be much better. 

@matthew-carroll Wdyt?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 3 above)
Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2263]: yes, that should be `.notHandled`. Will update it.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 2 above)
Comment (matthew-carroll) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:993]: It seems like this question might be moot based on the answer to the question above this one, right? Or are both questions equally relevant?

**Comment by matthew-carroll** [comment]
@rutvik110 @angelosilvestre before I take a deeper look at this, can you two determine which of the open issues are considered resolved? If you have issues that aren't resolved, but don't necessarily require my input, can you work through those, too?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 3 above)
Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2263]: I noticed there is another situation mentioned by Matt in the ticket:

> Some clarification on this, if a text field has enough content to scroll, page up/down should apply to the text field. If the text field doesn't have any scrollable content, then the text field should let the page up/down keys bubble up.

If the textfield's content is scrollable, we need to apply the page up/down to it.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 2 above)
Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:993]: I think both are equally relevant. What @angelosilvestre may be questioning is whether other selectors/handlers should be aware of the scrollable directly as opposed to it being used through a  `SuperTextFieldContext`. 
Passing the `SuperTextFieldContext` to later access scrollable if needed seems more appropriate but whether to introduce it for a scrollable alone is debatable.

**Comment by rutvik110** [comment]
Yah, most of the open issues won't require you tagging in but just the one related to addition of `SuperTextFieldContext` [here](https://github.com/superlistapp/super_editor/pull/1463#discussion_r1335043919).

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 1 above)
Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: Yes, we will some duplication, but IMO this is acceptable. Passing an `ancestorScrollable` to `SuperTextFieldKeyboardInteractor` seems worse to me, as `SuperTextFieldKeyboardInteractor` can query itself for an ancestor scrollable.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 2 above)
Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:993]: @rutvik110 I think you should go ahead and introduce a `SuperTextFieldContext`. If at a later point we need to access another resource on the keyboard handlers we don't want to change the method signature again.

**Review by angelosilvestre — COMMENTED** [review]
I left some comments.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 1 above)
Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: Now that we've decided to introduce `SuperTextFieldContext`, do you think it would best to now just pass that context to `SuperTextFieldKeyboardInteractor` and to any widget that may've to deal with ancestor scrollable or the scroll controller of the `SuperTextField`?

Comment (matthew-carroll) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: We haven't decided this yet. Is that the only open question on this PR at this point? Is that blocking all other PR updates?

Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: Its blocking only this issue and the issue being discussed below this one directly. The decision here will affect how we provide access of the ancestor scrollable and the `SuperTextField` scroll controller to the methods that handle scroll actions on shortcuts.

Comment (matthew-carroll) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: Ok, I'm looking deeper into this now. One thing I'll mention is that as for the question of passing the `ancestorScrollable` vs querying for it within the interactor widget, the answer to a question like that is almost always to query for the thing you want from within the widget that wants it. We don't have any control over Flutter's build pipeline, nor do we even have great visibility into what Flutter does, so it's inherently dangerous to try to pass `State` or `RenderObject` or `Layer` objects around.

Comment (matthew-carroll) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: I've looked up our `SuperEditor` handles and I've checked the `SuperEditorContext` we pass them. It's worth noting that I think there's also a different signature for `SuperReader` which passes a `SuperReaderContext` or something like that. The point there being, these contexts are specific to the widget that creates them, so we can't use the concept of a context within code that's intended to be generic across widgets.

In the case of key handlers, I think it's fair to say that there's not much that's generic about them. Pretty much by definition, they apply to a rather specific widget UX. This is why I thought it was OK to pass a `SuperEditorContext` and a `SuperReaderContext`.

I think that logic makes sense for `SuperTextField` as well.

As for this particular issue, are we trying to pass our own `SuperTextField` scrolling system to the key handlers, or are we trying to pass an ancestor scrollable that may or may not exist?

If we're looking up the ancestor scrollable just for the purpose of passing it to the key handlers, then it makes me wonder if we should pass the `BuildContext` instead? Who knows what ancestor widgets a key handler might want to lookup. This time it just happens to be a scrollable.

However, if what we want to pass to the key handlers is our own `SuperTextField` scrolling system, then I think it probably makes sense to pass that explicitly within the `SuperTextFieldContext`.

Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: > As for this particular issue, are we trying to pass our own SuperTextField scrolling system to the key handlers, or are we trying to pass an ancestor scrollable that may or may not exist?

Key handlers that react to scroll operations need to be aware of both of them. They'll first try to scroll within the `SuperDesktopTextField` using the scroll controller created within it, and once we exceed the scrolling content within `SuperDesktopTextField`, the scroll actions will affect the scrolling of the ancestor scrollable if one's present.

Comment (matthew-carroll) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: Sounds like we should pass both the `BuildContext` of the `SuperTextField`, as well as the internal scrollable.

Does `SuperTextField` have an interface for its scrolling system the way that `SuperEditor` does?

Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: Not yet.

Comment (matthew-carroll) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: Is it clear to you what such a scrolling API should look like? Are you comfortable introducing that? Or would you prefer that I do it?

Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: I've a vague idea abt it. Do we want to introduce an api like `AutoScroller` that will expose certain scrolling info and actions, so that we've a single source from where scrolling actions can be performed and affect the scrolling of the `SuperTextField`?
If yes, what kind of things should this scrolling api expose? and what parts of the existing scrolling system defined for each individual `SuperDesktopTextField`, `SuperAndroidTextField` and `SuperIOSTextField` should it replace? 

If I can get a little bit idea of it, then I can start on it.

Comment (matthew-carroll) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:427]: Sounds like I should take care of that. For the moment, go ahead and expose the existing scrolling artifact to implement this and then file an issue to introduce a scrolling API for `SuperTextField`.

**Comment by rutvik110** [comment]
@angelosilvestre Want to hear your thoughts on this one particular edge case here,

**Scenario:** `SuperDesktopField` and ancestor scrollable both has scrollable content within them. On initial End key press, we scrolled to the bottom of the `SuperDesktopField`, and on next Page-Down or End key press, we scrolled towards ancestor scrollable's bottom.
Now, upon pressing the Page-Up or Home key....

**Actual behaviour:** Currently, we first try to scroll within the `SuperDesktopField` and once its scroll content is consumed, we scroll the ancestor scrollable. This presents a ux issue as seen in the below demo, where we are not able to scroll the ancestor scrollable unless the scrollable action can't be performed within `SuperDesktopField`, 
for e.g. once we reach to the top of the `SuperDesktopField`, then only Page-Up/Home key press affects the ancestor scrollable.

https://github.com/superlistapp/super_editor/assets/65209850/e532d02e-35de-4169-a9bb-fd68af234f35



**Expected behaviour:** Need to be decided.

**Comment by matthew-carroll** [comment]
@rutvik110 what behavior do you get when you do something similar in a web browser, where your text field scrolls and the window scrolls?

**Comment by rutvik110** [comment]
Tested it on github, it consumes the textfield content first before it scrolls the page. I think that's the natural behaviour across web for this scenario.

https://github.com/superlistapp/super_editor/assets/65209850/d3dc71e8-8da9-46f5-bfcd-d034e2e59603

**Comment by matthew-carroll** [comment]
@rutvik110 that video looks like it mixes directions. It doesn't seem to be testing exactly the same thing you showed in thep revious demo. Can you try testing the exact same thing in both cases to make sure we don't miss anything?

**Comment by rutvik110** [comment]
Sure! Here it's, the behaviour remains the same in both directions.

https://github.com/superlistapp/super_editor/assets/65209850/53a89435-2250-43dd-bd23-e0272ff21ed8

**Comment by angelosilvestre** [comment]
@rutvik110 If I understood it correctly, the problem is that the ancestor scrollable is scrolled all the way to the bottom, and the textfield is scrolling its own content up instead of the scrollable. Is that correct? If so, one thing we could do it to scroll the ancestor scrollable in PAGE UP/DOWN if the textfield isn't visible on the viewport. Once it's visible, we should use the regular behavior of scrolling the content first and then the ancestor scrollable.

**Comment by rutvik110** [comment]
Hmm, but the natural behaviour for this case as seen across web is that textfields content is being scrolled first as demonstrated in my previous comment.

Shouldn't we follow that for keeping consistency with what a user may expect in this scenario?

**Comment by angelosilvestre** [comment]
@matthew-carroll What's your thoughts on this? Should we aim to be consistent with how textfields work on browsers? Should we try to improve the UX?

**Comment by rutvik110** [comment]
@angelosilvestre Currently, within textfield, the `scrollOnHomeKeyPress` and `scrollOnEndKeyPress` handlers are conflicting with the existing `moveToLineStartWithHome` and `moveToLineEndWithEnd` that also need to respond to the `HOME` and `END` key press. 

Should we update the scroll key handlers to may be this particular combination of keys for desktop, `scrollOnCtrlOrCmdAndHomeKeyPress` and `scrollOnCtrlOrCmdAndEndKeyPress`. This is how we earlier dealt with this particular issue in context of `SuperEditor` scrolling.

**Comment by angelosilvestre** [comment]
@rutvik110 I think `moveToLineStartWithHome` and `moveToLineEndWithEnd` run only for Windows and Linux. Also, scrolling with HOME and END seems to be a mac only shortcut.

I think we probably want to transmit this information in the method name, like `moveToLineStartWithHomeOnWindowsAndLinux`, `scrollOnHomeKeyPressOnMac` and so on.

**Comment by rutvik110** [comment]
yah, that's right. Those two handlers run only for `Windows` and `Linux`. 

> Also, scrolling with HOME and END seems to be a mac only shortcut.

Yes but this keys may also scroll the document/page on other platforms but that would vary from app to app basis or whether they're pressed in an browser. Normally HOME and END would scroll to start/end of the document or move the cursor to the start/end of the line.

What we've done in case of `SuperEditor` was to attach this two scroll actions to ctrl/cmd+home/end shortcuts to get around this. Should we be following similar approach here? Seems only right as otherwise we may've conflict with existing handlers that may need to home/end keys.

**Comment by angelosilvestre** [comment]
If I understood it correctly, I think we should use separate key handlers. For example:

`scrollOnHomeOnMacOrWeb`,
`scrollOnCtrlHome`, (for both command on mac and ctrl on windows and linux)
`moveToLineStartWithHomeOnWindowsAndLinux`,
...

Does that make sense?

**Comment by rutvik110** [comment]
> scrollOnCtrlHome, (for both command on mac and ctrl on windows and linux)

Didn't got what you're trying to say here? For mac and web, won't the `scrollOnHomeOnMacOrWeb` you mentioned above it would suffice?

**Comment by angelosilvestre** [comment]
Yeah, if command + home doesn't have any special behavior on Mac then we'll only need scrollOnCtrlHomeOnWindowsAndLinux

**Comment by rutvik110** [comment]
Ok, lets' go ahead with addition of following handlers to delegate scrolling of textfield on different platforms, 

`scrollOnCtrlHomeOnWindowsAndLinux` & `scrollOnCtrlEndOnWindowsAndLinux` - scrolls textfield on ctrl+home/end on `windows` & `linux`
`scrollOnHomeOnMac` & `scrollOnEndOnMac` - scrolls textfield on home/end on `mac`.

**Comment by rutvik110** [comment]
@angelosilvestre Pushed the updates based on latest addition from #1507. 

Overview, updates to following handlers, 

  `DefaultSuperTextFieldKeyboardHandlers.scrollOnPageUpKeyPress`,
  `DefaultSuperTextFieldKeyboardHandlers.scrollOnPageDownKeyPress`,
  `DefaultSuperTextFieldKeyboardHandlers.scrollOnCtrlOrCmdAndHomeKeyPress`,
  `DefaultSuperTextFieldKeyboardHandlers.scrollOnCtrlOrCmdAndEndKeyPress`.

We've moved to responding on ctrl/cmd + home/end press to scroll textfield/ancestor scrollable to the beginning/end of the content instead of only relying on home/end key press, which was conflicting with existing handlers that moved caret to start/end of line on home/end key press.

And `ancestorScrollable` is now fetched within this and other mac scroll selectors as needed using passed `BuildContext` through `TextFieldScroller`, instead of passing it down through constructors.

**Comment by rutvik110** [comment]
@angelosilvestre I also noticed that for `TextInputSource.ime`, the usual ctrl+a/e doesn't move the caret along the start/end of the line? Isn't that the expected behaviour on mac?  

This seems to be happening due to the `moveCaretToStartOrEnd` handler is placed below `sendKeyEventToMacOs` within `defaultTextFieldImeKeyboardHandlers`, and thus never gets chance to respond to this shortcuts on mac. 

Is that intentded? If not, I can update it within this PR or should I file a separate issue for it?

**Comment by angelosilvestre** [comment]
@rutvik110 Command + a should generate a selector on Mac. That's why the method is placed below `sendKeyEventToMacOs`.

Maybe I missed the implementation for that selection. Could you please confirm that `onPerformSelector` is being called when command + a is pressed?

**Comment by rutvik110** [comment]
> Could you please confirm that onPerformSelector is being called when command + a is pressed?
It doesn't. It results in the complete selection of the content within textfield which is the general behaviour for that shortcut on mac. 

Actually, the `Cmd` + Right/Left arrow moves the caret along the start/end of the line.

https://github.com/superlistapp/super_editor/assets/65209850/db410976-a58c-4b14-9cc3-7bffea2bed2d

I think this behaviour is correct. I mistakenly associated the `Ctrl` + A/E shortcut to moving caret along star/end of the line which isn't true. Though we may wanna add the missing `moveToBeginningOfParagraph` and `moveToEndOfParagraph` selectors for `SuperTextField`. I'll file an issue for it later today.

**Comment by matthew-carroll** [comment]
I haven't reviewed all the new discussion here, but FYI, there's a merge conflict

**Comment by rutvik110** [comment]
@angelosilvestre Could you take a look at the recent additions? If it's all good then I can move into adding tests for this new additions.

**Comment by matthew-carroll** [comment]
@rutvik110 I don't see any tests for this behavior in the PR. Please ensure that we have tests for all varieties of page scrolling, for example, without an ancestor scrollable, with an ancestor scrollable under various visibility conditions, like placing a text field near the top of the content and then scrolling all the way down and then all the way back up, and placing a text field near the bottom and then scrolling all the way down and then all the way back up, and the same thing with a text field in the center of the content.

We want to ensure that scroll behavior switches between the text field and the ancestor at expected times and produces expected results. If the user ever sees an undesirable scroll behavior, we should have a test that fails.

This is also true for any other key handler adjustments you may have made in this PR. If you were able to change how some key handlers work, without breaking any tests, then we were missing tests for those behaviors.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 6]
```diff
@@ -1765,6 +1772,12 @@ const defaultTextFieldImeKeyboardHandlers = <TextFieldKeyboardHandler>[
   // handlers, passing the key combo to the OS on Mac. Place all custom Mac key
   // combos above this handler.
   DefaultSuperTextFieldKeyboardHandlers.sendKeyEventToMacOs,
+  DefaultSuperTextFieldKeyboardHandlers.scrollOnPageUpKeyPress,
+  DefaultSuperTextFieldKeyboardHandlers.scrollOnPageDownKeyPress,
+  DefaultSuperTextFieldKeyboardHandlers.scrollOnCtrlOrCmdAndHomeKeyPress,
+  DefaultSuperTextFieldKeyboardHandlers.scrollOnCtrlOrCmdAndEndKeyPress,
```
Comment (angelosilvestre) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:1778]: I think we can omit the `KeyPress` at the end of the handlers.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 7]
```diff
@@ -2202,6 +2215,331 @@ class DefaultSuperTextFieldKeyboardHandlers {
...
+    final ScrollPosition? ancestorScrollable =
+        _findAncestorScrollable(textFieldContext.textFieldBuildContext)?.position;
+
+    if (keyEvent is! RawKeyDownEvent) {
+      return TextFieldKeyboardHandlerResult.notHandled;
+    }
+
+    if (keyEvent.logicalKey.keyId != LogicalKeyboardKey.pageUp.keyId) {
+      return TextFieldKeyboardHandlerResult.notHandled;
+    }
```
Comment (angelosilvestre) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2232]: Please move this to the top of this method. We don't need to lookup the `ancestorScrollable` if either of these conditions are false.

Also, is there a reason why you are comparing the `keyId` instead of directly the `logicalKey`?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 8]
```diff
@@ -2202,6 +2215,331 @@ class DefaultSuperTextFieldKeyboardHandlers {
...
+
+    if (ancestorScrollable == null && textFieldScroller.maxScrollExtent == 0) {
+      return TextFieldKeyboardHandlerResult.handled;
+    }
```
Comment (angelosilvestre) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2236]: Please add a comment inside this if branch explaining what `ancestorScrollable == null && textFieldScroller.maxScrollExtent == 0` means for us.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 9]
```diff
@@ -2202,6 +2215,331 @@ class DefaultSuperTextFieldKeyboardHandlers {
...
+        ),
+        duration: const Duration(milliseconds: 150),
+        curve: Curves.decelerate,
+      );
+      return TextFieldKeyboardHandlerResult.handled;
+    }
+
+    if (ancestorScrollable == null) {
+      return TextFieldKeyboardHandlerResult.handled;
+    }
```
Comment (angelosilvestre) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2252]: Please add a comment explaining why we return `handled` here.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 10]
```diff
@@ -2202,6 +2215,331 @@ class DefaultSuperTextFieldKeyboardHandlers {
...
+    final ScrollPosition? ancestorScrollable =
+        _findAncestorScrollable(textFieldContext.textFieldBuildContext)?.position;
+
+    if (keyEvent is! RawKeyDownEvent) {
+      return TextFieldKeyboardHandlerResult.notHandled;
+    }
+
+    if (keyEvent.logicalKey.keyId != LogicalKeyboardKey.pageDown.keyId) {
+      return TextFieldKeyboardHandlerResult.notHandled;
+    }
```
Comment (angelosilvestre) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2278]: Same comment of the previous handler here about moving the if statement up. Please adjust all of the handlers.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 11]
```diff
@@ -2202,6 +2215,331 @@ class DefaultSuperTextFieldKeyboardHandlers {
...
+    ancestorScrollable.animateTo(
+      min(ancestorScrollable.pixels + ancestorScrollable.viewportDimension, ancestorScrollable.maxScrollExtent),
+      duration: const Duration(milliseconds: 150),
+      curve: Curves.decelerate,
+    );
+
+    return TextFieldKeyboardHandlerResult.handled;
+  }
+
+  static TextFieldKeyboardHandlerResult scrollOnCtrlOrCmdAndHomeKeyPress({
```
Comment (angelosilvestre) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2309]: In this method we scroll all the way to the top, right?

We should communicate this information on the method name or, at least, in a dart doc, so we don't need to look at the implementation to figure this out.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 12]
```diff
@@ -2202,6 +2215,331 @@ class DefaultSuperTextFieldKeyboardHandlers {
...
+      return TextFieldKeyboardHandlerResult.notHandled;
+    }
+
+    if (keyEvent.logicalKey != LogicalKeyboardKey.home) {
+      return TextFieldKeyboardHandlerResult.notHandled;
+    }
+
+    if (defaultTargetPlatform != TargetPlatform.macOS && !kIsWeb) {
+      return TextFieldKeyboardHandlerResult.notHandled;
+    }
```
Comment (angelosilvestre) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2439]: We have an `isWeb` getter that we can override in tests. Please use that getter instead of `kIsWeb`.

**Review by angelosilvestre — COMMENTED** [review]
I left a few comments. Some comments are applicable to all handlers.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 7 above)
Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2232]: > Also, is there a reason why you are comparing the keyId instead of directly the logicalKey?
Nothing particular. I'll update it.

**Comment by rutvik110** [comment]
> @rutvik110 I don't see any tests for this behavior in the PR. Please ensure that we have tests for all varieties of page scrolling, for example, without an ancestor scrollable, with an ancestor scrollable under various visibility conditions, like placing a text field near the top of the content and then scrolling all the way down and then all the way back up, and placing a text field near the bottom and then scrolling all the way down and then all the way back up, and the same thing with a text field in the center of the content.
> 
> We want to ensure that scroll behavior switches between the text field and the ancestor at expected times and produces expected results. If the user ever sees an undesirable scroll behavior, we should have a test that fails.
> 
> This is also true for any other key handler adjustments you may have made in this PR. If you were able to change how some key handlers work, without breaking any tests, then we were missing tests for those behaviors.

Yup! I'm getting started with them now.

**Comment by rutvik110** [comment]
@angelosilvestre Overview on recent updates,

1. Tests added for `SuperTextField` scrolling behaviour without any ancestor scrollable. 
2. Tests for textfield scrolling in presence of ancestor scrollable. Here we are testing whether scrolling past textfields content does scrolls ancestor scrollable and does so when textfield is placed at either top/bottom/center of the ancestor scrollable.
3. Tests for scrolling to the top and end of the document, also test the mac and web platforms with both `Ctrl + Home/End` and `Home/End` shortcuts.

File: super_editor/test/super_textfield/super_textfield_scroll_test.dart [hunk 13]
```diff
@@ -192,9 +195,732 @@ void main() {
...
+                equals(scrollState.position.maxScrollExtent),
+              );
+            } else {
+              // Ensure we scrolled to the bottom of the page viewport.
+              expect(
+                ancestorScrollState.position.pixels,
+                equals(ancestorScrollState.position.maxScrollExtent),
+              );
+            }
+          }
```
Comment (angelosilvestre) [inline super_editor/test/super_textfield/super_textfield_scroll_test.dart:535]: IMO, the for-loop makes it more difficult to read. We could write:

```dart
// Comment explaining what we are doing.
await _scrollToEnd(useHomeOnMacOrWeb, tester);
expect(
  scrollState.position.pixels,
  equals(scrollState.position.maxScrollExtent),
);

// Comment explaining what we are doing.
await _scrollToEnd(useHomeOnMacOrWeb, tester);
expect(
  ancestorScrollState.position.pixels,
  ancestorScrollState.position.maxScrollExtent),
);
```

@matthew-carroll What's your thought on this?

File: super_editor/test/super_textfield/super_textfield_scroll_test.dart [hunk 14]
```diff
@@ -192,9 +195,732 @@ void main() {
...
 }
 
+/// Sends a scrollToEnd event using platform appropriate shortcuts.
+///
+/// On macOS and web, (CMD + END) and END shortcuts are performed. On all other platforms,
+/// (CTRL + END) is used.
+///
+/// [useHomeOnMacOrWeb] is used to toggle between using (CMD + END) and END on macOS
+/// and web.
+Future<void> _scrollToEnd(bool useHomeOnMacOrWeb, WidgetTester tester) async {
```
Comment (angelosilvestre) [inline super_editor/test/super_textfield/super_textfield_scroll_test.dart:737]: What about naming this method like `_pressScrollToEndCombo` or something like this? I'm saying this because this method itself doesn't perform the scrolling. It presses a key combination that, hopefully, will cause the shortcut system to perform the scrolling.

File: super_editor/test/super_textfield/super_textfield_scroll_test.dart [hunk 15]
```diff
@@ -192,9 +195,732 @@ void main() {
...
+          await tester.tapAt(tester.getTopLeft(find.byType(SuperTextField)));
+          await tester.pump();
+
+          // Find textfield scrollable.
+          final scrollState = tester.state<ScrollableState>(find.descendant(
+            of: find.byType(SuperTextField),
+            matching: find.byType(Scrollable),
+          ));
+
+          await tester.sendKeyEvent(LogicalKeyboardKey.pageDown);
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/test/super_textfield/super_textfield_scroll_test.dart:221]: yah, rn there aren't any for page up and down.

File: super_editor/test/super_textfield/super_textfield_scroll_test.dart (hunk 13 above)
Comment (rutvik110) [reply super_editor/test/super_textfield/super_textfield_scroll_test.dart:535]: ah yah, that's actually better. Idk why I went with for loop earlier.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 16]
```diff
@@ -2202,6 +2215,345 @@ class DefaultSuperTextFieldKeyboardHandlers {
...
+
+    final TextFieldScroller textFieldScroller = textFieldContext.scroller;
+    final ScrollPosition? ancestorScrollable =
+        _findAncestorScrollable(textFieldContext.textFieldBuildContext)?.position;
+
+    // No scrollable content within `SuperDesktopField` and ancestor scrollable
+    // is absent, but we technically handled the task.
+    if (textFieldScroller.maxScrollExtent == 0 && ancestorScrollable == null) {
+      return TextFieldKeyboardHandlerResult.handled;
+    }
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2238]: > Also, are you sure we should return handled even if we do nothing?

I believe yes. If we are recognising the key event here, then it's technically handled by this key handler. And so far, we don't expect two handlers to handle the same key event, right?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 17]
```diff
@@ -2546,3 +2904,164 @@ void _deleteToEndOfLine({
...
+  ancestorScrollable.animateTo(
+    ancestorScrollable.maxScrollExtent,
+    duration: const Duration(milliseconds: 150),
+    curve: Curves.decelerate,
+  );
+}
+
+void _scrollPageUp({
+  required SuperTextFieldContext textFieldContext,
+}) {
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2795]: Yah that's good idea. 

Not sure why `_scrollPageUp` should return bool here. Within our keyboard/ime handlers, if we're recognising the key event, then technically we handled the event there. Whether it scrolls/not depending on its content, doesn't count towards recognising the key event as handled I believe. 

Wdyt?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 16 above)
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart]: > And so far, we don't expect two handlers to handle the same key event, right?

I'm not so sure about that. The app can install its own key handler to handle, for example, SHIFT + PAGE UP, OPTION + PAGE UP, and so on. By returning `handled`, we are preventing other shortcuts.

My guess is that if we are doing nothing, we should give a chance to other handlers to handle the key.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 17 above)
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2795]: This is related to this comment: https://github.com/superlistapp/super_editor/pull/1463#discussion_r1373893149

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 16 above)
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart]: ok this makes it more clear now. Will update em.

**Comment by rutvik110** [comment]
@angelosilvestre Made the suggested updates. Let me know if there's anything else.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 18]
```diff
@@ -2546,3 +2716,204 @@ void _deleteToEndOfLine({
...
+      curve: Curves.decelerate,
+    );
+
+    return true;
+  }
+
+  // Ancestor scrollable is absent, but we technically handled the task.
+  if (ancestorScrollable == null) {
+    return false;
+  }
```
Comment (angelosilvestre) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2753]: I think this comment is out of date, as we are returning `false` here. Also, please place the comment inside the if branch.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 19]
```diff
@@ -2546,3 +2716,204 @@ void _deleteToEndOfLine({
...
+  required SuperTextFieldContext textFieldContext,
+}) {
+  final TextFieldScroller textFieldScroller = textFieldContext.scroller;
+  final ScrollPosition? ancestorScrollable = _findAncestorScrollable(textFieldContext.textFieldBuildContext)?.position;
+
+  // No scrollable content within `SuperDesktopField` and ancestor scrollable
+  // is absent, but we technically handled the task.
+  if (textFieldScroller.maxScrollExtent == 0 && ancestorScrollable == null) {
+    return false;
+  }
```
Comment (angelosilvestre) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2782]: Same here about the comment being outdated and comment position inside the if branch. The same applies for the other handlers.

**Review by angelosilvestre — COMMENTED** [review]
I left a couple minor comments. After that, you can ask Matt for its review.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 19 above)
Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2782]: Done! Updated.

**Comment by rutvik110** [comment]
@matthew-carroll Could you please take a final look at the PR? 

Overview:

1. Adds 4 new macOS selectors for handling OS recognized scroll event :   
     * `_scrollToBeginningOfDocument`
     * `_scrollToEndOfDocument`
     * `_scrollPageUp`
     * `_scrollPageDown`
2. Adds following keyboard and IME handlers:
     * `scrollOnPageUp`
     * `scrollOnPageDown`
     * `scrollToBeginningOfDocumentOnCtrlOrCmdAndHome`
     * `scrollToEndOfDocumentOnCtrlOrCmdAndEnd`

All of this handlers/selectors first try to scroll the textfield, and if there's no scrollable content within textfield then tries to scroll ancestor scrollable if one's present. 

Above handlers/selectors apply to all the platforms. In addition to those, for macOS and web we also added `scrollToBeginningOfDocumentOnHomeOnMacOrWeb` and `scrollToEndOfDocumentOnEndOnMacOrWeb` handlers. On both of this platforms, `HOME` and `END` is supposed to scroll to the top/end of the document respectively.

File: super_editor/example/lib/demos/supertextfield/_textfield_within_scrollable_demo.dart [hunk 20]
```diff
@@ -0,0 +1,58 @@
...
+                  color: Colors.black,
+                );
+              },
+            ),
+          ),
+        ),
+        SliverPadding(
+          padding: EdgeInsets.all(10),
+        ),
+        SliverList.builder(
```
Comment (matthew-carroll) [inline super_editor/example/lib/demos/supertextfield/_textfield_within_scrollable_demo.dart:48]: Does this demo really need an infinite list after the text field?

Based on the demos of GitHub that you showed in the PR, I would think that this demo setup should come down to some empty space that takes up most of the window, then a text field, and then more space that takes up about another window worth of space. Doesn't that more closely approximate the examples you referenced when implementing this PR?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 21]
```diff
@@ -2546,3 +2716,204 @@ void _deleteToEndOfLine({
...
+/// Returns `true` if the scroll was performed, `false` otherwise to give other
+/// key handlers opportunity to handle the key event if we didn't took
+/// any action.
+bool _scrollToBeginningOfDocument({
+  required SuperTextFieldContext textFieldContext,
+}) {
+  final TextFieldScroller textFieldScroller = textFieldContext.scroller;
+  final ScrollPosition? ancestorScrollable = _findAncestorScrollable(textFieldContext.textFieldBuildContext)?.position;
+
+  // No scrollable content within `SuperDesktopField` and ancestor scrollable
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2734]: This comment looks like it's referring to the condition inside of the if-statement, not the condition when reaching the if-statement. Please make sure that when a comment says something about the state of execution, that the comment appears in a place where that statement is true. For example, at the moment the reader actually reads this comment, the statement "No scrollable content..." isn't true, yet.

Let's replace this comment with a comment inside the if-statement:

```
// The textfield doesn't have any scrollable content. There is no ancestor
// scrollable to scroll. Fizzle.
```

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 22]
```diff
@@ -2546,3 +2716,204 @@ void _deleteToEndOfLine({
...
+  // is absent, but we technically handled the task.
+  if (textFieldScroller.maxScrollExtent == 0 && ancestorScrollable == null) {
+    return false;
+  }
+
+  if (textFieldScroller.scrollOffset > 0) {
+    textFieldScroller.animateTo(
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2741]: Let's make it clear why we're doing this:

```
// The text field has more content than can fit, and the text field is partially
// scrolled downward. Scroll back to the top of the text field.
```

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 23]
```diff
@@ -2546,3 +2716,204 @@ void _deleteToEndOfLine({
...
+      textFieldScroller.minScrollExtent,
+      duration: const Duration(milliseconds: 150),
+      curve: Curves.decelerate,
+    );
+
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2746]: Where's the interacting with the ancestor scrollable? It looks like we're only attempting to scroll the text field...

If this method is missing the ancestor logic, and we don't have any failing tests, then this means we're missing at least one test. Please add a failing test, first, and then get it to pass by adding what's missing.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 24]
```diff
@@ -2546,3 +2716,204 @@ void _deleteToEndOfLine({
...
+/// Returns `true` if the scroll was performed, `false` otherwise to give other
+/// key handlers opportunity to handle the key event if we didn't took
+/// any action.
+bool _scrollToEndOfDocument({
+  required SuperTextFieldContext textFieldContext,
+}) {
+  final TextFieldScroller textFieldScroller = textFieldContext.scroller;
+  final ScrollPosition? ancestorScrollable = _findAncestorScrollable(textFieldContext.textFieldBuildContext)?.position;
+
+  // No scrollable content within `SuperDesktopField` and ancestor scrollable
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2778]: Please apply my same comment from the `_scrollToBeginningOfDocument()`

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 25]
```diff
@@ -2546,3 +2716,204 @@ void _deleteToEndOfLine({
...
+  // is absent, but we technically handled the task.
+  if (textFieldScroller.maxScrollExtent == 0 && ancestorScrollable == null) {
+    return false;
+  }
+
+  if (textFieldScroller.scrollOffset < textFieldScroller.maxScrollExtent) {
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2784]: Please add the same comment I mentioned in `_scrollToBeginningOfDocument()`

Also, to avoid repeating this, please apply those comments in general, as needed.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 26]
```diff
@@ -2546,3 +2716,204 @@ void _deleteToEndOfLine({
...
+    textFieldScroller.animateTo(
+      textFieldScroller.maxScrollExtent,
+      duration: const Duration(milliseconds: 150),
+      curve: Curves.decelerate,
+    );
+
+    return true;
+  }
+
+  // Ancestor scrollable is absent, but we technically handled the task.
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2794]: This comment is unnecessarily wandering. Let's replace this comment with one inside the if-statement, as follows:

```
// There is no ancestor scrollable to scroll. Fizzle.
```

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 27]
```diff
@@ -2546,3 +2716,204 @@ void _deleteToEndOfLine({
...
+  if (ancestorScrollable == null) {
+    return false;
+  }
+
+  if (!ancestorScrollable.maxScrollExtent.isFinite) {
+    // Can't scroll to infinity, but we technically handled the task.
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2800]: Let's get rid of all of these "but we technically handled the task" comments. If you want to make it clear in a given comment that we intend to return immediately, you can simply say "Return."

```
// We want to scroll to the end of the ancestor scrollable, but it's infinitely long,
// so we can't. Return.
```

Although this is case where you want to do something, but there's nothing that you can reasonably do, where the term "fizzle" is probably more appropriate:

```
// We want to scroll to the end of the ancestor scrollable, but it's infinitely long,
// so we can't. Fizzle.
```

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 28]
```diff
@@ -2546,3 +2716,204 @@ void _deleteToEndOfLine({
...
+    return false;
+  }
+
+  ancestorScrollable.animateTo(
```
Comment (matthew-carroll) [inline super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2804]: To match the frequency of comments elsewhere, let's comment this line:

```
// Scroll to the end of the ancestor scrollable.
```

**Review by matthew-carroll — COMMENTED** [review]
I did a partial review. I think the comments that I left might apply to some of the other areas that I haven't reviewed yet, so I'm committing these to avoid repeating the same comments.

File: super_editor/example/lib/demos/supertextfield/_textfield_within_scrollable_demo.dart [hunk 29]
```diff
@@ -0,0 +1,58 @@
...
+  @override
+  State<TextFieldWithinScrollableDemo> createState() => _TextFieldWithinScrollableDemoState();
+}
+
+class _TextFieldWithinScrollableDemoState extends State<TextFieldWithinScrollableDemo> {
+  @override
+  Widget build(BuildContext context) {
+    return CustomScrollView(
+      slivers: [
+        SliverPadding(
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/example/lib/demos/supertextfield/_textfield_within_scrollable_demo.dart:16]: It doesn't. Updated.

File: super_editor/example/lib/demos/supertextfield/_textfield_within_scrollable_demo.dart [hunk 30]
```diff
@@ -0,0 +1,58 @@
...
+                      color: Colors.grey.shade300,
+                      width: 1,
+                    ),
+                  ),
+                  child: child,
+                );
+              },
+              textStyleBuilder: (attributions) {
+                return TextStyle(
+                  color: Colors.black,
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/example/lib/demos/supertextfield/_textfield_within_scrollable_demo.dart:39]: Currently the text rendered by `SuperTextField` or `SuperDesktopTextField` has white color. I'ven't looked into why that's the case, but for that reason, we're setting the text color to black where needed.

File: super_editor/example/lib/demos/supertextfield/_textfield_within_scrollable_demo.dart (hunk 20 above)
Comment (rutvik110) [reply super_editor/example/lib/demos/supertextfield/_textfield_within_scrollable_demo.dart:48]: > Does this demo really need an infinite list after the text field?

I don't think it does. Will update it.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 23 above)
Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2746]: It's right below it? Not sure I understand the question here.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 31]
```diff
@@ -0,0 +1,910 @@
...
+///
+/// On macOS and web, (CMD + HOME) and HOME shortcuts are performed. On all other platforms,
+/// (CTRL + HOME) is used.
+///
+/// [useHomeOnMacOrWeb] is used to toggle between using (CMD + HOME) and HOME on macOS
+/// and web.
+Future<void> _pressScrollToTopCombo(bool useHomeOnMacOrWeb, WidgetTester tester) async {
+  if (useHomeOnMacOrWeb && (defaultTargetPlatform == TargetPlatform.macOS || isWeb)) {
+    await tester.sendKeyEvent(LogicalKeyboardKey.home);
+    await tester.pumpAndSettle();
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:558]: Why are you pumping and settling for one and not the other two? Also, why are you using a simulated Flutter event for one, but delegating the others to their own methods?

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 32]
```diff
@@ -0,0 +1,910 @@
...
+      await _pressCmdEnd(tester);
+    } else {
+      await _pressCtrlEnd(tester);
+    }
+  }
+}
+
+/// Sends a scrollToHome event using platform appropriate shortcuts.
+///
+/// On macOS and web, (CMD + HOME) and HOME shortcuts are performed. On all other platforms,
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:550]: What do you mean "(CMD + HOME) and HOME shortcuts are performed" - which one is it? That's two.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 33]
```diff
@@ -0,0 +1,910 @@
...
+/// (CTRL + HOME) is used.
+///
+/// [useHomeOnMacOrWeb] is used to toggle between using (CMD + HOME) and HOME on macOS
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:553]: Please notice the passive nature of this comment "...is used to toggle between..." - you're describing a behavior as if it's happening in the background or something. This a property that we expect the developer to set, so statements in Dart Docs should actively instruct the developer what to do, or at least actively describe the impact of possible values:

```
/// When running on Mac or Web, when `useHomeOnMacOrWeb` is `true`, the
/// HOME key is pressed by itself, otherwise CMD + HOME are pressed together.
```

However, all of that said, my initial reaction is that I'm not a fan of this boolean being here to begin with. The fact that it's a non-named parameter means we're gonna have this method called with `(true)` and `(false)` in a bunch of place without any idea what we're toggling. Also, this property is only ever applied when running on Mac and Web - it's generally not a good idea to have properties that only effect a function some of the time. 

All in all, I get the sense that this method is making too many decisions as it is right now. The tests that are currently using this method should more directly decide what they want to do.

File: super_editor/example/lib/demos/supertextfield/textfield_inside_single_child_scroll_view_demo.dart [hunk 34]
```diff
@@ -0,0 +1,61 @@
...
+}
+
+class _TextFieldInsideSingleChildScrollViewDemoState extends State<TextFieldInsideSingleChildScrollViewDemo> {
+  @override
+  Widget build(BuildContext context) {
+    return SingleChildScrollView(
+      child: Column(
+        children: [
+          SizedBox(
+            height: MediaQuery.of(context).size.height * 0.8,
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/example/lib/demos/supertextfield/textfield_inside_single_child_scroll_view_demo.dart:19]: That's to only avoid pushing textfield off the screen and to provide a clear visual on where textfield is.

File: super_editor/example/lib/demos/supertextfield/textfield_inside_single_child_scroll_view_demo.dart [hunk 35]
```diff
@@ -0,0 +1,61 @@
...
+            width: double.maxFinite,
+            child: Placeholder(
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/example/lib/demos/supertextfield/textfield_inside_single_child_scroll_view_demo.dart:21]: Just to give indication that the empty space represents some content. Used only for visual aid, and nothing else.

File: super_editor/example/lib/demos/supertextfield/textfield_inside_single_child_scroll_view_demo.dart [hunk 36]
```diff
@@ -0,0 +1,61 @@
...
+              child: Center(
+                child: Text("Content"),
+              ),
+            ),
+          ),
+          Padding(
+            padding: const EdgeInsets.all(8.0),
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/example/lib/demos/supertextfield/textfield_inside_single_child_scroll_view_demo.dart:28]: That's for spacing from the screen edges.

File: super_editor/example/lib/demos/supertextfield/textfield_inside_single_child_scroll_view_demo.dart [hunk 37]
```diff
@@ -0,0 +1,61 @@
...
+                      width: 1,
+                    ),
+                  ),
+                  child: child,
+                );
+              },
+            ),
+          ),
+          SizedBox(
+            height: MediaQuery.of(context).size.height * 2,
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/example/lib/demos/supertextfield/textfield_inside_single_child_scroll_view_demo.dart:49]: Clarified here,
https://github.com/superlistapp/super_editor/pull/1463#discussion_r1382346608

File: super_editor/example/lib/demos/supertextfield/textfield_inside_single_child_scroll_view_demo.dart [hunk 38]
```diff
@@ -0,0 +1,61 @@
...
+            width: double.maxFinite,
+            child: Placeholder(
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/example/lib/demos/supertextfield/textfield_inside_single_child_scroll_view_demo.dart:51]: Same reason as this,

> Just to give indication that the empty space represents some content. Used only for visual aid, and nothing else.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 39]
```diff
@@ -0,0 +1,910 @@
...
+
+/// Defines the placement of [SuperDesktopTextField] within ancestor
+/// scrollable.
+enum _TextFieldPlacementWithinScrollable {
+  top,
+  center,
+  bottom;
+}
+
+Future<void> _pressCmdHome(WidgetTester tester) async {
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:880]: Already merged in. Will use those here.

https://github.com/Flutter-Bounty-Hunters/flutter_test_robots/pull/11

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart (hunk 31 above)
Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:558]: > Why are you pumping and settling for one and not the other two?

That's because I was using the Flutter simulated event here, as for the other two we perform that that within those methods. Updated to use shortcut methods from test robots.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 40]
```diff
@@ -0,0 +1,910 @@
...
+        ),
+      ),
+    ),
+  );
+
+  // The first frame might have a zero viewport height. Pump a second frame to account for the final viewport size.
+  await tester.pump();
+}
+
+/// Key used by [SuperDesktopTextField]'s ancestor scrollable.
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:840]: This was used earlier to identify the ancestor scrollable in tests in presence of multiple scrollables. But this was related to an earlier version of the widget tree that we were testing against but isn't useful anymore. 

I've removed this key usage to find ancestor scrollable as it's no longer necessary and a simple `find.byType` would suffice anywhere in the tests where we need to access ancestor scrollable.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 41]
```diff
@@ -0,0 +1,910 @@
...
+    if (defaultTargetPlatform == TargetPlatform.macOS) {
+      await _pressCmdHome(tester);
+    } else {
+      await _pressCtrlHome(tester);
+    }
+  }
+}
+
+/// Variant for an [SuperDesktopTextField] experience with/without ancestor scrollable.
+final _scrollingVariant = ValueVariant<_SuperDesktopTextFieldScrollSetup>({
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:559]: It does introduces a little bit complexity but given that the number of different scenarios we're testing against, if we'd to use `group`s for that then it would only result in a lot of duplicated tests where most of them would only be different in a place or two but share the same execution steps.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart (hunk 33 above)
Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:544]: I think then it'll better to handle whatever this method is doing within the tests itself. Initially I had this extracted away as this was being repeated across a lot of places, but some duplication with more clarify should be fine I guess.

Will update tests to handle this within themselves instead of delegating this to an external method like here.

File: super_editor/example/lib/demos/supertextfield/textfield_inside_single_child_scroll_view_demo.dart (hunk 34 above)
[the remark this answers is not in the document]
Comment (matthew-carroll) [reply super_editor/example/lib/demos/supertextfield/textfield_inside_single_child_scroll_view_demo.dart:20]: Ok, please include a comment for any such sizing so that the reader knows why you did it, and also so the reader can keep that behavior working in the case that other details change.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart (hunk 41 above)
[the remark this answers is not in the document]
Comment (matthew-carroll) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:638]: It's generally preferable, especially in tests, to have short, duplicated, and directly evident code, rather than build a little execution framework to avoid a little bit of duplication. It's far more disruptive overall to introduce a completely different test execution paradigm for this one file to avoid those few lines of duplication. If using the standard approach truly turns out to be onerous then we can revisit, but I'd like to see how bad it is using our standard approach before considering alternatives.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 42]
```diff
@@ -0,0 +1,959 @@
...
+          final currentVariant = _scrollingVariant.currentValue;
+
+          // Pump the widget tree with a SuperDesktopTextField which is four lines tall.
+          await currentVariant!.pumpEditor(
+            tester,
+            _scrollingVariant.currentValue!.textInputSource,
+          );
+
+          // Tap on the text field to focus it.
+          await tester.tap(find.byType(SuperDesktopTextField));
```
Comment (angelosilvestre) [inline super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:59]: Please use `tester.placeCaretInSuperTextField` if possible.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 43]
```diff
@@ -0,0 +1,959 @@
...
```
Comment (angelosilvestre) [inline super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:96]: Please use `tester.placeCaretInSuperTextField` if possible.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 44]
```diff
@@ -0,0 +1,959 @@
...
```
Comment (angelosilvestre) [inline super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:134]: Please use `tester.placeCaretInSuperTextField` if possible.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 45]
```diff
@@ -0,0 +1,959 @@
...
+          // Scroll to viewport's top.
+          if (useHomeOrEndOnMacAndWeb && (defaultTargetPlatform == TargetPlatform.macOS || isWeb)) {
+            await tester.pressHome();
+          } else {
+            if (defaultTargetPlatform == TargetPlatform.macOS) {
+              await tester.pressCmdHome(tester);
+            } else {
+              await tester.pressCtrlHome(tester);
+            }
+          }
```
Comment (angelosilvestre) [inline super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:193]: @matthew-carroll I'm not sure if placing these if statements in all places we want to press the "scroll to top" shortcut is the ideal approach.

Would it make sense to write different tests for mac on web, mac desktop and other desktop platforms?

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 46]
```diff
@@ -0,0 +1,959 @@
...
+      testWidgetsOnDesktopAndWeb(
+        'PAGE DOWN scrolls down by the viewport height',
+        (tester) async {
+          final currentVariant = _scrollingVariant.currentValue;
+
+          // Pump the widget tree with a SuperDesktopTextField which is four lines tall.
+          await currentVariant!.pumpEditor(
+            tester,
+            _scrollingVariant.currentValue!.textInputSource,
+          );
```
Comment (angelosilvestre) [inline super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:22]: Would it make sense to move this comment to the `pumpEditor` dart doc?

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 47]
```diff
@@ -2546,3 +2746,215 @@ void _deleteToEndOfLine({
...
+
+/// Scrolls to the top of the textfield.
+///
+/// In absence of scrollable content within textfield, tries to scroll the ancestor
+/// scrollable to its top.
+///
+/// Returns `true` if the scroll was performed, `false` otherwise to give other
+/// key handlers opportunity to handle the key event if we didn't took
+/// any action.
+bool _scrollToBeginningOfDocument({
```
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2758]: I think we could move this within the scroll handlers that make use of this method and decide the handling of key event.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart (hunk 44 above)
Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:134]: Can't use it here as it looks up for `SuperTextField` and we're using `SuperDesktopTextField` in the tree. 

I've added an new helper `placeCaretInSuperDesktopTextField` within `SuperTextFieldRobot` for tapping within `SuperDesktopTextField`. Feel free to suggest any updates there or if we wanna keep it or not?

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart (hunk 46 above)
Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:23]: I think its helpful here to give idea to the reader what kind of widget is being pumped. Without this comment, it's a bit ambiguous.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart (hunk 45 above)
Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart]: I've separated this in two different tests. 

One now explicitly tests cmd/ctrl + home/end combo to scroll across all desktop platforms. 

And to test for scroll using home/end across mac, and web desktop, I've introduced a new test group, that only runs the given test across mac desktop, and web desktop across all platforms.

```dart
void _testWidgetsOnMacAndWebDesktop(
  String description,
  WidgetTesterCallback test, {
  bool skip = false,
  TestVariant<Object?> variant = const DefaultTestVariant(),
}) {
  testWidgetsOnMac(description, test, skip: skip, variant: variant);

  testWidgetsOnWebDesktop(description, test, skip: skip, variant: variant);
}
```

Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart]: This new test group is used for tests which are identical on mac desktop, and web desktop testing.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart (hunk 41 above)
[the remark this answers is not in the document]
Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:933]: @matthew-carroll In latest updates,  some of this unnecessary variants are cleared out now in favour of using `group`, and separate `test`s. Let me know what you think of the latest updates and additions.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart (hunk 44 above)
Comment (angelosilvestre) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart]: Can we just use the `SuperTextField` , as it will use `SuperDesktopTextField` internally for desktop?

Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart]: We could but won't someone be using `SuperDesktopField` directly if he's on desktop? And here we want to test this updates specifically for  `SuperDesktopTextField` coze that's where we support them and for mobile platforms this updates are not yet supported.

If we had to use `SuperTextField`, then that begs the question why don't we have tests for android or ios. I think in terms of what we're testing for, using `SuperDesktopField` here clarifies that more clearly. 

Wdyt?

Comment (angelosilvestre) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart]: I think we can use `SuperTextField` and force the configuration to be desktop. That way, the test robots methods will work and we are sure we are using an internal `SuperDesktopTextField`.

Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart]: Done. Replaced the `SuperDesktopTextField` we were using in the widget tree with `SuperTextField` and removed the added method in the `SuperTextFieldRobot`.

Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart]: There are references to `SuperDesktopTextField` in the tests. Do you want me to change those to `SuperTextField` with this change? Though we're primarily testing `SuperDesktopTextField` behaviours here so I think those are fine. But wdyt?

Comment (angelosilvestre) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart]: IMO, if possible, we should try to use `SuperTextfield` whenever possible. Not sure if Matt has the same opinion on that.

Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart]: ok, I'll update `SuperDesktopTextField` to `SuperTextField` where needed in tests execution, other than that few references directly to `SuperDesktopTextField`  in the docs should be fine I believe to convey that we're dealing with `SuperDesktopTextField`.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart [hunk 48]
```diff
@@ -2546,3 +2746,215 @@ void _deleteToEndOfLine({
...
+
+  final direction = ancestorScrollable.axisDirection;
+  // If the direction is horizontal, then we are inside a widget like a TabBar
+  // or a horizontal ListView, so we can't use the ancestor scrollable
+  if (direction == AxisDirection.left || direction == AxisDirection.right) {
+    return null;
+  }
+
+  return ancestorScrollable;
+}
```
[the remark this answers is not in the document]
Comment (matthew-carroll) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2964]: @rutvik110 @angelosilvestre it looks like the only thing this method does beyond the regular `Scrollable.of()` is filter out horizontal scrollables. Is that right?

If so, @rutvik110  the name of this method should reflect that. Developers shouldn't have to read the implementation ot discover surprises like that.

As for sharing the implementation I think we can define an extension method within our flutter extensions directory where we define other generic Flutter capabilities that aren't specific to editors, readers, or text fields.

File: super_editor/test/super_textfield/super_textfield_ime_test.dart [hunk 49]
```diff
@@ -6,6 +6,7 @@ import 'package:flutter_test_runners/flutter_test_runners.dart';
 import 'package:super_editor/src/infrastructure/platforms/mac/mac_ime.dart';
 import 'package:super_editor/super_editor.dart';
 import 'package:super_editor/super_editor_test.dart';
+import 'package:super_text_layout/super_text_layout.dart';
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_textfield_ime_test.dart:9]: Why is this here?

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 50]
```diff
@@ -0,0 +1,1174 @@
+import 'package:flutter/foundation.dart';
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:1]: A couple things on the name of this file:

First, I think we say "scrolling" in other test file names in this project, don't we? If so, let's stay consist with terminology instead of saying "scroll".

Second, this file name mentions nothing about key presses. Do you intend for htis file to include all scrolling tests of all types? Or only key presses? If it should hold all such tests, have you verified that no other scrolling tests exist elsewhere?

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 51]
```diff
@@ -0,0 +1,1174 @@
...
+import 'package:flutter_test_robots/flutter_test_robots.dart';
+import 'package:flutter_test_runners/flutter_test_runners.dart';
+import 'package:meta/meta.dart';
+import 'package:super_editor/super_editor.dart';
+
+import '../test_runners.dart';
+import 'super_textfield_robot.dart';
+
+void main() {
+  group("SuperDesktopTextField", () {
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:14]: Is there a reason that we're defining these in terms of `SuperDesktopTextField`?

I know that we implemented htis behavior there, but isn't `SuperTextField` supposed to pass all of these tests? What if `SuperTextField` failed all these tests - wouldn't that be a problem?

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 52]
```diff
@@ -0,0 +1,1174 @@
...
+    group("text field scrolling", () {
+      testWidgetsOnDesktopAndWeb(
+        'PAGE DOWN scrolls down by the viewport height',
+        (tester) async {
+          final currentVariant = _scrollingVariant.currentValue;
+
+          // Pump the widget tree with a SuperDesktopTextField which is four lines tall.
+          await currentVariant!.pumpEditor(
+            tester,
+            textInputSource: currentVariant.textInputSource,
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:24]: Why are we passing variant properties into the variant's method? Doesn't the variant know what the variant wants?

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart [hunk 53]
```diff
@@ -0,0 +1,1174 @@
...
+  _TextFieldPlacementWithinScrollable placement,
+});
+
+/// Defines the placement of [SuperDesktopTextField] within ancestor
+/// scrollable.
+///
+/// Testing against different layouts helps verify that the text field's scrolling
+/// through scroll shortcuts remains same irrespective of the text field's placement
+/// within ancestor scrollable.
+enum _TextFieldPlacementWithinScrollable {
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:1157]: Let's refer to this as "vertical alignment" instead of "placement" - nobody will know what placement means without jumping here to read it.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart (hunk 41 above)
[the remark this answers is not in the document]
Comment (matthew-carroll) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:933]: I still don't see any meaningful benefit for these variants as they exist. There's still quite a bit of extra stuff defined in this test suite without providing commensurate complexity savings elsewhere.

It seems that you only need two variants: input source and vertical alignment.

You can create a variant for each one, or perhaps even create a variant that includes their permutations. 

You don't need to move the standard `pump` method into a variant, that's just confusing as compared to all other tests. If the `pump` method needs optional parameters, then declare it with optional parameters and pass them in based on the variant.

You shouldn't need to customize the description for every variant. Flutter already be appending variant names to every test. So if you have a variant for input source and vertical alignment, those test descriptions should automatically include them.

By using simple variants for values, you can get rid of most of the special stuff you have defined in this test suite, which will keep more within the reader expectations of all other test suites.

File: super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart (hunk 48 above)
[the remark this answers is not in the document]
Comment (angelosilvestre) [reply super_editor/lib/src/super_textfield/desktop/desktop_textfield.dart:2964]: > it looks like the only thing this method does beyond the regular Scrollable.of() is filter out horizontal scrollables. Is that right?

That is correct.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart (hunk 52 above)
Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:24]: yes, this was a poor design choice from my side for the variant class. Will have it updated wrt to this [comment](https://github.com/superlistapp/super_editor/pull/1463#discussion_r1391731175),

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart (hunk 51 above)
Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:14]: > Is there a reason that we're defining these in terms of SuperDesktopTextField?

Nothing in particular. As this changes were related most directly to the `SuperDesktopTextField`, it's been referred in the tests so far.

> I know that we implemented htis behavior there, but isn't SuperTextField supposed to pass all of these tests? What if SuperTextField failed all these tests - wouldn't that be a problem?

So `SuperTextField` does pass all tests as well. I'll update references to `SuperDesktopTextField` with `SuperTextField` where needed.

File: super_editor/test/super_textfield/super_textfield_ime_test.dart (hunk 49 above)
Comment (rutvik110) [reply super_editor/test/super_textfield/super_textfield_ime_test.dart:9]: Seems to have been added by mistake from my side. I'll revert this change.

File: super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart (hunk 50 above)
Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:1]: > Second, this file name mentions nothing about key presses. Do you intend for htis file to include all scrolling tests of all types? Or only key presses? 

I think the current tests are mostly tied to scrolling through key presses, and that's we what we wanna include here. I'll update the file name wrt that.

> If it should hold all such tests, have you verified that no other scrolling tests exist elsewhere?

There's `super_textfield_scroll_test.dart` which includes text field scrolling tests but this tests for cases of scrolling  introduced by user selection. For the changes in this PR, we want to test scrolling behaviour through key presses that not only affects text field but also ancestor scrollable in some cases, so I think keeping these in separate file is best.

Comment (matthew-carroll) [reply super_editor/test/super_textfield/super_desktop_textfield_scroll_test.dart:1]: If we're going to have files that specify something like keyboard scrolling, then please update the other test files to indicate that they're gesture scrolling so that we can discern the difference without opening the files.

**Comment by rutvik110** [comment]
Failing tests are related to the issue #1593.

**Comment by rutvik110** [comment]
@matthew-carroll Updated scroll handlers wrt to `KeyEvent` migration changes from #1593.

File: super_editor/test/super_textfield/super_desktop_textfield_keyboard_shortcuts_scrolling_test.dart [hunk 54]
```diff
@@ -0,0 +1,1592 @@
+import 'package:flutter/foundation.dart';
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_desktop_textfield_keyboard_shortcuts_scrolling_test.dart:1]: Looks like this test should be renamed to from `super_desktop_textfield` to `super_textfield`

File: super_editor/test/super_textfield/super_desktop_textfield_keyboard_shortcuts_scrolling_test.dart [hunk 55]
```diff
@@ -0,0 +1,1592 @@
...
+import 'package:flutter_test_runners/flutter_test_runners.dart';
+import 'package:meta/meta.dart';
+import 'package:super_editor/super_editor.dart';
+
+import '../test_runners.dart';
+import 'super_textfield_robot.dart';
+
+void main() {
+  group("SuperTextField", () {
+    group("text field scrolling", () {
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_desktop_textfield_keyboard_shortcuts_scrolling_test.dart:15]: You don't need to repeat "text field" - you've already stated that this is a `SuperTextField` test.

File: super_editor/test/super_textfield/super_desktop_textfield_keyboard_shortcuts_scrolling_test.dart [hunk 56]
```diff
@@ -0,0 +1,1592 @@
...
+
+            // Ensure we scrolled to ancestor scrollable's top.
+            expect(
+              ancestorScrollState.position.pixels,
+              equals(ancestorScrollState.position.minScrollExtent),
+            );
+          },
+          variant: _textFieldInputSourceVariant,
+        );
+        _testWidgetsOnMacAndWebDesktop(
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_desktop_textfield_keyboard_shortcuts_scrolling_test.dart:1007]: Please make sure you have blank lines between tests.

File: super_editor/test/super_textfield/super_desktop_textfield_keyboard_shortcuts_scrolling_test.dart [hunk 57]
```diff
@@ -0,0 +1,1592 @@
...
+            expect(
+              ancestorScrollState.position.pixels,
+              equals(ancestorScrollState.position.minScrollExtent),
+            );
+          },
+          variant: _textFieldInputSourceVariant,
+        );
+      });
+
+      group('''when placed at bottom of page, scrolls all the way from top of the text field to
```
Comment (matthew-carroll) [inline super_editor/test/super_textfield/super_desktop_textfield_keyboard_shortcuts_scrolling_test.dart:1073]: Please don't use a multi-line quote in test names

Comment (rutvik110) [reply super_editor/test/super_textfield/super_desktop_textfield_keyboard_shortcuts_scrolling_test.dart]: Updated descriptions accordingly.

**Review by matthew-carroll — APPROVED** [review]
LGTM
